import { createHash } from "node:crypto";
import { readFile, writeFile } from "node:fs/promises";
import { resolve } from "node:path";
import { createCatalogMigrationValidationReport, type CatalogSeedBundle, type CatalogSeedProgram, type CatalogSeedProgramIntake } from "../src/server/catalog/seed-contract.ts";
import { createPostgresPool } from "../src/server/db/postgres-client.ts";
import { localDatabaseUrl } from "./lib/local-development.ts";

const root=process.cwd(),batch="bsu-school-undergraduate-cleanup",prefix=`catalog.${batch}`,schoolSlug="beijing-sport-university";
const manifestPath=resolve(root,"work/catalog-official/bsu-complete-batch-01/manifest.json"),parsedPath=resolve(root,"work/catalog-official/bsu-complete-batch-01/parsed-programs.json"),dependencyPath=resolve(root,"seeds/catalog.cscalite-online-20260910.published.json"),statePath=resolve(root,".cuac-local/runtime.json");
const paths={candidate:resolve(root,`seeds/${prefix}.draft.json`),validation:resolve(root,`seeds/${prefix}.validation.json`),review:resolve(root,`seeds/${prefix}.review.json`)};
const sha=(value:string|Buffer)=>createHash("sha256").update(value).digest("hex"),writeJson=(path:string,value:unknown)=>writeFile(path,`${JSON.stringify(value,null,2)}\n`,"utf8");
const [manifest,parsed,dependency,state]=await Promise.all([manifestPath,parsedPath,dependencyPath,statePath].map(path=>readFile(path,"utf8").then(JSON.parse)));
const evidence=new Map<string,any>((manifest.sources??[]).map((source:any)=>[source.id,source]));
const expected={"bsu-international-admission-2026":"205f0d5e7615133fa201d100f81539d64ce24056f4c116fdf82e9a281fc02056","bsu-international-program-catalog-2026":"7e7ba4b40bf09d4e77ee58b7bb70f7c9f062a414fa207fa3d088d39be93c10ef"} as Record<string,string>;
for(const [id,hash] of Object.entries(expected)){const source=evidence.get(id);if(!source||source.sha256!==hash||source.status!==200||source.finalUrl!==source.url)throw new Error(`BSU evidence changed: ${id}`);if(sha(await readFile(resolve(manifestPath,"..",source.artifactPath)))!==hash)throw new Error(`BSU artifact mismatch: ${id}`);}
const city=dependency.cities.find((row:any)=>row.slug==="beijing"),oldSchool=dependency.schools.find((row:any)=>row.slug===schoolSlug),guide=evidence.get("bsu-international-admission-2026"),catalog=evidence.get("bsu-international-program-catalog-2026");
if(!city||!oldSchool||parsed.programCount!==106)throw new Error("BSU dependency or parsed scope changed.");
const school={slug:schoolSlug,nameEn:"Beijing Sport University",nameZh:"北京体育大学",citySlug:"beijing",schoolType:"Public",region:"Beijing, North China",applicationLevel:"Undergraduate, Master, Doctoral and Non-degree",languageOfInstruction:"Chinese",hskRequirement:"Degree routes are Chinese-taught; graduate scholarship applicants need HSK Level 5 or above, subject to the published prior Chinese-medium degree exemption.",deadlineSummary:"The 2026 general application and document-review period ran from December 2025 through June 2026; individual scholarship deadlines may be earlier.",tuitionSummary:"Undergraduate CNY 25,000-28,000/year; Master CNY 30,000-34,000/year; Doctoral CNY 40,000-45,000/year.",cscaRequired:true,cscaRequirement:"Undergraduate applicants follow the CSCA subject combinations printed for each major in the official 2026 program catalog.",subjectTags:["Physical Education","Sports Science","Sports Management","Sports Medicine","Journalism and Communication","Psychology"],languageTags:["Chinese-taught"],status:"draft" as const,sourceUrl:guide.finalUrl,sourceLabel:guide.label,sourceSha256:guide.sha256,capturedAt:guide.fetchedAt,sourceFieldLineage:{nameEn:"official page title and prospectus",nameZh:"official page title and prospectus",citySlug:"official university identity",applicationLevel:"program section",languageOfInstruction:"program section",hskRequirement:"graduate scholarship eligibility section",deadlineSummary:"admissions procedure",tuitionSummary:"fees section",cscaRequired:"undergraduate admission requirements and official program catalog",cscaRequirement:"program catalog CSCA column"}};
const slugByName=new Map<string,string>((dependency.programs??[]).filter((row:any)=>row.schoolSlug===schoolSlug).map((row:any)=>[row.nameEn,row.slug]));
const rows=parsed.programs.filter((row:any)=>row.degreeLevel==="Undergraduate"&&slugByName.has(row.nameEn));
if(rows.length!==10)throw new Error(`Expected 10 conflicting undergraduate rows, found ${rows.length}`);
const programs:CatalogSeedProgram[]=rows.map((row:any)=>({slug:slugByName.get(row.nameEn)!,schoolSlug,citySlug:"beijing",nameEn:row.nameEn,degreeLevel:"Undergraduate",durationYears:4,fieldCategory:row.schoolEn,subjectArea:row.nameEn,teachingLanguage:"Chinese",cscaRequirement:"CSCA is required; use the subject combination published for this major in the official 2026 program catalog.",tuitionAmount:row.tuitionCnyPerYear,tuitionCurrency:"CNY",tuitionPeriod:"year",tuitionText:`CNY ${Number(row.tuitionCnyPerYear).toLocaleString("en-US")}/year`,scholarshipText:"Eligible applicants may separately apply for BSU's published scholarship routes; funding is not guaranteed.",applicationUrl:"https://ims.bsu.edu.cn/EEdepot.aspx",applicationNote:"2026 international undergraduate route; applications are reviewed online and may include a video interview.",hasScholarship:true,badgeText:"2026 official route",displaySubjects:[row.nameEn],displayGroup:"bsu-bachelor",displayGroupLabel:"BSU 2026 Undergraduate routes",status:"draft",sourceUrl:catalog.finalUrl,sourceLabel:catalog.label,sourceSha256:catalog.sha256,capturedAt:catalog.fetchedAt,sourceFieldLineage:{nameEn:row.sourceLocator,degreeLevel:`${row.sourceLocator}; catalog section`,durationYears:"bsu-international-admission-2026 program-duration section",fieldCategory:`${row.sourceLocator}; school/college column`,teachingLanguage:"bsu-international-admission-2026 program section",tuitionAmount:`${row.sourceLocator}; tuition column`,applicationUrl:"bsu-international-admission-2026 online-application section"}}));
const programIntakes:CatalogSeedProgramIntake[]=programs.map(program=>({programSlug:program.slug,intakeTerm:"Fall",intakeYear:2026,deadlineLabel:"Application and document review period: December 2025 through June 2026",applicationRound:"2026 international degree intake",status:"closed",sourceUrl:guide.finalUrl,sourceLabel:guide.label,sourceSha256:guide.sha256,capturedAt:guide.fetchedAt,sourceFieldLineage:{intakeYear:"admissions procedure",deadlineLabel:"admissions procedure",status:"derived: published application period has ended"}}));
const candidate:CatalogSeedBundle={version:1,generatedAt:manifest.generatedAt,cities:[city],schools:[school],programs,programIntakes,scholarships:[]},candidateText=`${JSON.stringify(candidate,null,2)}\n`,validation=createCatalogMigrationValidationReport(candidate);
if(!validation.ok)throw new Error(`BSU cleanup validation failed: ${validation.errors.join(" ")}`);
const pool=createPostgresPool({databaseUrl:localDatabaseUrl(state),max:1,applicationName:"cuac:bsu-cleanup-review"});
try{
 const schoolDb=await pool.query("select s.id,s.status,s.verification_status,to_jsonb(s)-'created_at'-'updated_at' snapshot from schools s where s.slug=$1",[schoolSlug]);
 const targetPrograms=await pool.query("select slug,status,verification_status,to_jsonb(p)-'created_at'-'updated_at' snapshot from programs p where p.school_id=$1 and slug=any($2::text[]) order by slug",[schoolDb.rows[0]?.id,programs.map(row=>row.slug)]);
 const protectedPrograms=await pool.query("select count(*)::int total,count(*) filter(where verification_status='verified')::int verified from programs where school_id=$1 and not(slug=any($2::text[])) and status='active'",[schoolDb.rows[0]?.id,programs.map(row=>row.slug)]);
 const scholarships=await pool.query("select count(*)::int total,count(*) filter(where verification_status='verified')::int verified from scholarships where school_id=$1 and status='active'",[schoolDb.rows[0]?.id]);
 if(schoolDb.rows.length!==1||schoolDb.rows[0].status!=="active"||schoolDb.rows[0].verification_status==="verified"||targetPrograms.rows.length!==10||targetPrograms.rows.some((row:any)=>row.status!=="active"||row.verification_status==="verified")||protectedPrograms.rows[0]?.total!==96||protectedPrograms.rows[0]?.verified!==96||scholarships.rows[0]?.total!==1||scholarships.rows[0]?.verified!==1)throw new Error("BSU cleanup database baseline changed.");
 const reviewBase={version:1,status:"awaiting_exact_user_approval",generatedAt:manifest.generatedAt,scope:{schoolSlug,schoolOverwriteCount:1,programOverwriteCount:10,programIntakeUpsertCount:10,archiveCount:0,protectedProgramCount:96,protectedScholarshipCount:1},candidateSha256:sha(candidateText),candidateBundleSha256:validation.bundleSha256,operationPlanSha256:validation.operationPlanSha256,manifestSha256:sha(await readFile(manifestPath)),parsedProgramsSha256:sha(await readFile(parsedPath)),evidence:[guide,catalog].map((source:any)=>({sourceId:source.id,sourceUrl:source.finalUrl,sourceLabel:source.label,sha256:source.sha256,fetchedAt:source.fetchedAt,contentType:source.contentType,byteLength:source.byteLength})),reconciliation:{destructiveDeletion:false,overwrites:[{entity:"school",slug:schoolSlug,count:1},{entity:"program",slugs:programs.map(row=>row.slug),count:10},{entity:"programIntake",programSlugs:programs.map(row=>row.slug),count:10}],archives:[],protected:{verifiedPrograms:96,verifiedScholarships:1},databaseBaseline:{schoolId:schoolDb.rows[0].id,schoolSnapshot:schoolDb.rows[0].snapshot,programSnapshots:targetPrograms.rows.map((row:any)=>row.snapshot)}},sourceReview:{result:"pass",note:"The official BSU 2026 admissions prospectus and 12-page program catalog are hash-bound. The 10 target rows map one-to-one to the existing undergraduate records."},coverageLimitations:["The PDF Chinese font map is damaged; official English major names are used without invented translations.","CSCA is recorded as required, but subject combinations are not guessed where machine-readable extraction is unavailable.","No applicant, account, payment, bank or personal-contact data is included."],sensitiveDataCheck:{result:"pass",scope:"one school, 10 undergraduate programs and 10 intake records",note:"Public institutional catalog and admissions-policy data only."}};
 const reviewHash=sha(JSON.stringify(reviewBase)),review={...reviewBase,reviewHash,requiredApprovalText:`批准发布北京体育大学学校与本科旧记录官方更新（审核哈希 ${reviewHash}）`};
 await Promise.all([writeJson(paths.candidate,candidate),writeJson(paths.validation,validation),writeJson(paths.review,review)]);
 console.log(JSON.stringify({ok:true,batch,reviewHash,requiredApprovalText:review.requiredApprovalText,summary:validation.summary,protected:{programs:96,scholarships:1},paths},null,2));
}finally{await pool.end();}
