import { createHash } from "node:crypto";
import { readFile, writeFile } from "node:fs/promises";
import { resolve } from "node:path";
import { createCatalogMigrationValidationReport, type CatalogSeedBundle } from "../src/server/catalog/seed-contract.ts";
import { createPostgresPool } from "../src/server/db/postgres-client.ts";
import { localDatabaseUrl } from "./lib/local-development.ts";

const root = process.cwd(), batch = "nankai-safe-new-batch-01", paths = { complete: resolve(root, "seeds/catalog.nankai-complete-batch-01.draft.json"), freshManifest: resolve(root, "work/catalog-official/nankai-refresh-20260914/manifest.json"), oldManifests: [resolve(root, "work/catalog-official/nankai-complete-batch-01/manifest.json"), resolve(root, "work/catalog-official/nankai-complete-batch-01-master/manifest.json")], completeReview: resolve(root, "seeds/catalog.nankai-complete-batch-01.review.json"), candidate: resolve(root, `seeds/catalog.${batch}.draft.json`), validation: resolve(root, `seeds/catalog.${batch}.validation.json`), review: resolve(root, `seeds/catalog.${batch}.review.json`), state: resolve(root, ".cuac-local/runtime.json") };
const sha = (value: string | Buffer) => createHash("sha256").update(value).digest("hex"), parse = async (path: string) => JSON.parse(await readFile(path, "utf8"));
const [complete, freshManifest, completeReview, state, ...oldManifests] = await Promise.all([parse(paths.complete), parse(paths.freshManifest), parse(paths.completeReview), parse(paths.state), ...paths.oldManifests.map(parse)]) as [CatalogSeedBundle, any, any, any, ...any[]];
const schoolSlug = "nankai-university"; if (complete.cities?.length !== 1 || complete.schools?.length !== 1 || complete.schools[0].slug !== schoolSlug || complete.programs?.length !== 339 || complete.programIntakes?.length !== 339 || complete.scholarships?.length !== 2 || freshManifest.sources?.length !== 9 || completeReview.visualReview?.result !== "pass" || completeReview.sensitiveDataCheck?.result !== "pass") throw new Error("Nankai candidate or review scope changed.");
const oldSources = new Map(oldManifests.flatMap((manifest: any) => manifest.sources ?? []).map((row: any) => [row.id, row])); for (const source of freshManifest.sources) { const old: any = oldSources.get(source.id); if (!old || old.sha256 !== source.sha256 || old.finalUrl !== source.finalUrl || old.contentType !== source.contentType) throw new Error(`Nankai source changed: ${source.id}`); }
const programSlugs = complete.programs.map((row) => row.slug), scholarshipSlugs = complete.scholarships.map((row) => row.slug);
const pool = createPostgresPool({ databaseUrl: localDatabaseUrl(state), max: 1, applicationName: "cuac:nankai-safe-new-review" }); let baseline: any;
try {
  const school = await pool.query("select id,slug,status,verification_status from schools where slug=$1", [schoolSlug]), city = await pool.query("select id,slug,status,verification_status from cities where slug='tianjin'"), activePrograms = await pool.query("select id,slug,status,verification_status from programs where school_id=$1 and status='active' order by slug", [school.rows[0]?.id]), conflicts = await pool.query("select id,slug,status,verification_status from programs where slug=any($1::text[]) order by slug", [programSlugs]), scholarshipConflicts = await pool.query("select id,slug,status,verification_status,last_verified_at from scholarships where slug=any($1::text[]) order by slug", [scholarshipSlugs]), activeScholarships = await pool.query("select id,slug,status,verification_status from scholarships where school_id=$1 and status='active' order by slug", [school.rows[0]?.id]), intakes = await pool.query("select count(*)::int count from program_intakes pi join programs p on p.id=pi.program_id where p.school_id=$1", [school.rows[0]?.id]);
  baseline = { school: school.rows, city: city.rows, activePrograms: activePrograms.rows, conflicts: conflicts.rows, scholarshipConflicts: scholarshipConflicts.rows, activeScholarships: activeScholarships.rows, intakeCount: intakes.rows[0]?.count ?? 0 };
  if (school.rows.length !== 1 || school.rows[0].status !== "active" || school.rows[0].verification_status !== "unverified" || city.rows.length !== 1 || city.rows[0].status !== "active" || activePrograms.rows.length !== 10 || conflicts.rows.length !== 0 || activePrograms.rows.some((row: any) => row.verification_status !== "unverified")) throw new Error("Nankai dependency/program baseline changed.");
  if (scholarshipConflicts.rows.length !== 1 || scholarshipConflicts.rows[0].slug !== "official-2026-nankai-silk-road-scholarship" || scholarshipConflicts.rows[0].status !== "active" || scholarshipConflicts.rows[0].verification_status !== "verified" || activeScholarships.rows.length !== 2) throw new Error("Nankai scholarship baseline changed.");
} finally { await pool.end(); }
const conflictingScholarships = new Set(baseline.scholarshipConflicts.map((row: any) => row.slug)), scholarships = complete.scholarships.filter((row) => !conflictingScholarships.has(row.slug)); if (scholarships.length !== 1 || scholarships[0].slug !== "official-2026-nankai-cgs-type-b") throw new Error("Nankai safe scholarship split changed.");
const freshHashes = new Set(freshManifest.sources.map((row: any) => row.sha256)); if ([...complete.programs, ...complete.programIntakes, ...scholarships].some((row: any) => !freshHashes.has(row.sourceSha256))) throw new Error("Nankai safe record lacks freshly confirmed evidence.");
const candidate: CatalogSeedBundle = { version: 1, generatedAt: freshManifest.generatedAt, cities: complete.cities, schools: complete.schools, programs: complete.programs, programIntakes: complete.programIntakes, scholarships }, candidateText = `${JSON.stringify(candidate, null, 2)}\n`, validation = createCatalogMigrationValidationReport(candidate); if (!validation.ok) throw new Error(`Nankai safe-new validation failed: ${validation.errors.join(" ")}`);
const reviewBase = { version: 1, status: "standing_user_approval", generatedAt: candidate.generatedAt, scope: { schoolSlug, dependencyCityReplayCount: 1, dependencySchoolReplayCount: 1, newProgramRouteCount: 339, newProgramIntakeCount: 339, newScholarshipCount: 1, overwriteCount: 0, archiveCount: 0 }, candidateSha256: sha(candidateText), candidateBundleSha256: validation.bundleSha256, operationPlanSha256: validation.operationPlanSha256, freshManifestSha256: sha(await readFile(paths.freshManifest, "utf8")), evidence: freshManifest.sources.map((row: any) => ({ sourceId: row.id, sourceUrl: row.finalUrl, sourceLabel: row.label, sha256: row.sha256, fetchedAt: row.fetchedAt, contentType: row.contentType })), standingAuthorization: { reference: "user-chat-2026-09-13-default-publication", instruction: "发布默认允许", appliesBecause: "This batch inserts only 339 new official program routes, 339 intakes and one new rich scholarship. Tianjin city and Nankai University are read-only dependencies; no record is overwritten or archived." }, sourceReview: { result: "pass", note: "All nine registered Nankai 2026 sources were refreshed on 2026-09-14 and are byte-for-byte unchanged from the interpreted review set." }, visualReview: completeReview.visualReview, reconciliation: { destructiveDeletion: false, overwrites: [], archives: [], deferredLegacyProgramSlugs: baseline.activePrograms.map((row: any) => row.slug), deferredStableScholarshipSlugs: baseline.scholarshipConflicts.map((row: any) => row.slug), deferredLegacyScholarshipSlugs: baseline.activeScholarships.filter((row: any) => !conflictingScholarships.has(row.slug)).map((row: any) => row.slug), databaseBaseline: { schoolId: baseline.school[0].id, cityId: baseline.city[0].id, activeProgramCount: baseline.activePrograms.length, activeScholarshipCount: baseline.activeScholarships.length, intakeCount: baseline.intakeCount } }, coverageLimitations: ["The school profile, shared Tianjin city, one stable scholarship update, ten legacy program aliases and one merged scholarship remain unchanged pending explicit cleanup approval."], sensitiveDataCheck: { result: "pass", scope: "safe-new publication candidate", note: "Only public institutional, program, admissions and scholarship-policy fields are included. Applicant, account, payment, bank, staff-name and personal-contact data are excluded." } };
const reviewHash = sha(JSON.stringify(reviewBase)), publicationReference = `standing-authorized-${batch}-${reviewHash}`; await Promise.all([writeFile(paths.candidate, candidateText, "utf8"), writeFile(paths.validation, `${JSON.stringify(validation, null, 2)}\n`, "utf8"), writeFile(paths.review, `${JSON.stringify({ ...reviewBase, reviewHash, publicationReference }, null, 2)}\n`, "utf8")]); console.log(JSON.stringify({ ok: true, batch, reviewHash, publicationReference, scope: reviewBase.scope, paths }, null, 2));
