import { createHash } from "node:crypto";
import { readFile, writeFile } from "node:fs/promises";
import { resolve } from "node:path";
import { CatalogSeedWriter } from "../src/server/catalog/seed-writer.ts";
import { createCatalogMigrationValidationReport, type CatalogSeedBundle } from "../src/server/catalog/seed-contract.ts";
import { assertLocalCatalogPublishTarget, LOCAL_CATALOG_PUBLISH_CONFIRMATION } from "../src/server/catalog/local-publish-safety.ts";
import { createPostgresPool, createTransactionalSqlClient } from "../src/server/db/postgres-client.ts";

const root=process.cwd(),paths={candidate:resolve(root,"seeds/catalog.ustc-safe-new-batch-01.draft.json"),validation:resolve(root,"seeds/catalog.ustc-safe-new-batch-01.validation.json"),review:resolve(root,"seeds/catalog.ustc-safe-new-batch-01.review.json"),output:resolve(root,"seeds/catalog.ustc-safe-new-batch-01.approved.local.json"),approval:resolve(root,"seeds/catalog.ustc-safe-new-batch-01.approval.json"),state:resolve(root,".cuac-local/runtime.json")},parse=async(path:string)=>JSON.parse(await readFile(path,"utf8")),sha=(value:string)=>createHash("sha256").update(value).digest("hex");
const candidateText=await readFile(paths.candidate,"utf8"),candidate=JSON.parse(candidateText) as CatalogSeedBundle,[validation,review,state]=await Promise.all([parse(paths.validation),parse(paths.review),parse(paths.state)]),{publicationReference,...withoutPublication}=review,{reviewHash,...reviewBase}=withoutPublication;
if(sha(JSON.stringify(reviewBase))!==reviewHash||publicationReference!=="standing-user-default-publication"||review.status!=="standing_user_approval"||review.scope?.newProgramRouteCount!==287||review.scope?.newScholarshipCount!==5||review.scope?.overwriteCount!==0||review.scope?.archiveCount!==0||review.reconciliation?.destructiveDeletion!==false||review.sensitiveDataCheck?.result!=="pass")throw new Error("USTC standing review is invalid.");
const fresh=createCatalogMigrationValidationReport(candidate);if(!fresh.ok||!validation.ok||sha(candidateText)!==review.candidateSha256||fresh.bundleSha256!==review.candidateBundleSha256||fresh.bundleSha256!==validation.bundleSha256||fresh.operationPlanSha256!==review.operationPlanSha256||fresh.operationPlanSha256!==validation.operationPlanSha256)throw new Error("USTC candidate changed after review.");
const approvedAt=new Date().toISOString(),programSlugs=candidate.programs!.map((row)=>row.slug),scholarshipSlugs=candidate.scholarships!.map((row)=>row.slug),reviewReference=`standing-user-default-publication-ustc-safe-new-${reviewHash}`,sourceSchemaSha256=sha(JSON.stringify({cityFields:[...new Set(candidate.cities!.flatMap((row)=>Object.keys(row)))].sort(),schoolFields:[...new Set(candidate.schools!.flatMap((row)=>Object.keys(row)))].sort(),programFields:[...new Set(candidate.programs!.flatMap((row)=>Object.keys(row)))].sort(),intakeFields:[...new Set(candidate.programIntakes!.flatMap((row)=>Object.keys(row)))].sort(),scholarshipFields:[...new Set(candidate.scholarships!.flatMap((row)=>Object.keys(row)))].sort()}));
const publication:CatalogSeedBundle={version:2,generatedAt:approvedAt,handoff:{sourceSystem:"CUAC reviewed official USTC 2026 admissions, program catalogs and scholarship sources",cleanedExportName:"catalog.ustc-safe-new-batch-01.draft.json",cleanedExportSha256:fresh.bundleSha256,sourceSchemaSha256,reviewReference,prohibitedDataReviewReference:reviewReference,approvalRecordedAt:approvedAt,sourceReadOnly:true,prohibitedDataConfirmedExcluded:true},cities:candidate.cities,schools:candidate.schools,programs:candidate.programs!.map((row)=>({...row,status:"active" as const,verificationStatus:"verified" as const,lastVerifiedAt:approvedAt})),programIntakes:candidate.programIntakes,scholarships:candidate.scholarships!.map((row)=>({...row,status:"active" as const,verificationStatus:"verified" as const,lastVerifiedAt:approvedAt}))};
const report=createCatalogMigrationValidationReport(publication);if(!report.ok||report.summary.programs!==287||report.summary.programIntakes!==287||report.summary.scholarships!==5)throw new Error(`Invalid USTC publication: ${report.errors.join(" ")}`);
const approval={version:1,approvedAt,approvalMode:"standing-product-owner-authorization",reviewReference,approvedReviewSha256:reviewHash,approvedCandidateBundleSha256:fresh.bundleSha256,publicationBundle:"seeds/catalog.ustc-safe-new-batch-01.approved.local.json",publicationBundleSha256:report.bundleSha256,schoolSlug:"university-of-science-and-technology-of-china",programSlugs,scholarshipSlugs,archivedAliases:[],prohibitedDataConfirmedExcluded:true};async function writeOrVerify(path:string,value:unknown){const body=`${JSON.stringify(value,null,2)}\n`;try{await writeFile(path,body,{encoding:"utf8",flag:"wx"});}catch(error:any){if(error?.code!=="EEXIST")throw error;if(await readFile(path,"utf8")!==body)throw new Error(`Existing artifact differs: ${path}`);}}await writeOrVerify(paths.output,publication);await writeOrVerify(paths.approval,approval);
const target=assertLocalCatalogPublishTarget(state,publication,LOCAL_CATALOG_PUBLISH_CONFIRMATION,reviewReference),pool=createPostgresPool({databaseUrl:target.databaseUrl,max:1,applicationName:"cuac:ustc-safe-new-publish"});try{const client=createTransactionalSqlClient(pool);const result=await client.transaction(async(tx)=>{
 const identity=await tx.query<{database_name:string;database_user:string}>("select current_database() database_name,current_user database_user",[]);if(identity[0]?.database_name!==target.publicTarget.databaseName||identity[0]?.database_user!==target.publicTarget.databaseUser)throw new Error("Database identity mismatch.");
 const school=await tx.query<{id:string;status:string;verification_status:string}>("select id,status,verification_status from schools where slug='university-of-science-and-technology-of-china'",[]);if(school.length!==1||school[0].id!==review.reconciliation.databaseBaseline.schoolId||school[0].status!=="active"||school[0].verification_status!=="unverified")throw new Error("USTC dependency school changed.");
 const legacy=await tx.query<{id:string;slug:string;status:string;verification_status:string}>("select id,slug,status,verification_status from scholarships where id=any($1::uuid[]) order by id",[review.reconciliation.legacyScholarshipsDeferred.map((row:any)=>row.id)]);if(legacy.length!==3||legacy.some((row)=>row.status!=="active"||row.verification_status!=="unverified"))throw new Error("USTC legacy scholarships changed.");
 const beforePrograms=await tx.query<{slug:string;status:string;verification_status:string;last_verified_at:Date|null}>("select slug,status,verification_status,last_verified_at from programs where slug=any($1::text[])",[programSlugs]),beforeScholarships=await tx.query<{slug:string;status:string;verification_status:string;last_verified_at:Date|null}>("select slug,status,verification_status,last_verified_at from scholarships where slug=any($1::text[])",[scholarshipSlugs]);const preState=beforePrograms.length===0&&beforeScholarships.length===0,postState=beforePrograms.length===287&&beforeScholarships.length===5&&[...beforePrograms,...beforeScholarships].every((row)=>row.status==="active"&&row.verification_status==="verified"&&row.last_verified_at?.toISOString()===approvedAt);if(!preState&&!postState)throw new Error("USTC candidate rows no longer match pre-state or this publication.");
 const written=await new CatalogSeedWriter(tx).writeBundle(publication);if(!written.ok)throw new Error(`Catalog write failed: ${written.errors.join(" ")}`);
 const totals=await tx.query<{programs:string;verified_programs:string;intakes:string;scholarships:string;verified_scholarships:string}>("select (select count(*) from programs where school_id=$1 and status='active')::text programs,(select count(*) from programs where school_id=$1 and status='active' and verification_status='verified')::text verified_programs,(select count(*) from program_intakes pi join programs p on p.id=pi.program_id where p.school_id=$1 and pi.status='closed')::text intakes,(select count(*) from scholarships where school_id=$1 and status='active')::text scholarships,(select count(*) from scholarships where school_id=$1 and status='active' and verification_status='verified')::text verified_scholarships",[school[0].id]);if(totals[0]?.programs!=="287"||totals[0]?.verified_programs!=="287"||totals[0]?.intakes!=="287"||totals[0]?.scholarships!=="8"||totals[0]?.verified_scholarships!=="5")throw new Error(`USTC post-publication totals invalid: ${JSON.stringify(totals[0])}`);return{written,...totals[0]};});console.log(JSON.stringify({ok:true,target:target.publicTarget,reviewHash,publicationBundleSha256:report.bundleSha256,approvalPath:paths.approval,outputPath:paths.output,...result},null,2));}finally{await pool.end();}
