import { createHash } from "node:crypto";
import { readFile, writeFile } from "node:fs/promises";
import { resolve } from "node:path";
import { createCatalogMigrationValidationReport, type CatalogSeedBundle, type CatalogSeedProgram, type CatalogSeedScholarship } from "../src/server/catalog/seed-contract.ts";

const root = process.cwd();
const schoolSlug = "xiamen-university";
const paths = {
  parsed: resolve(root, "work/catalog-official/xmu-complete-batch-01/parsed-programs.json"),
  manifest: resolve(root, process.env.CUAC_XMU_MANIFEST ?? "work/catalog-official/xmu-complete-batch-01/manifest.json"),
  draft: resolve(root, "seeds/catalog.xmu-complete-batch-01.draft.json"),
  validation: resolve(root, "seeds/catalog.xmu-complete-batch-01.validation.json"),
  review: resolve(root, "seeds/catalog.xmu-complete-batch-01.review.json"),
};
const sha = (value: string | Buffer) => createHash("sha256").update(value).digest("hex");
const parsedText = await readFile(paths.parsed, "utf8");
if (sha(parsedText) !== "5432c7d39476696caaf4bcbc74ad07ac8f1df01bee4bf5a9f68e2feeca16b6d6") throw new Error("Parsed XMU artifact changed after review.");
const parsed = JSON.parse(parsedText);
if (parsed.programCount !== 535 || JSON.stringify(parsed.counts) !== JSON.stringify({ Undergraduate: 88, Master: 215, Doctoral: 232 })) throw new Error("XMU parsed counts mismatch.");
const expected: Record<string, string> = {
  "xmu-chinese-government-university-program-2026": "2ad0f86dfa05793bdb60f88b4b39245ded7d8357f88750be15a17206c58ea2fa",
  "xmu-undergraduate-admissions-2026": "700a45c5f482eec8f2ebde02a86bd208d709f29e0f97e641fe0e095fbaf9b569",
  "xmu-master-admissions-2026": "751f4548404c9a93f22d3566fd7b2c2e243793cd22240037447459e09c216b6e",
  "xmu-doctoral-admissions-2026": "ff4fb7dd0ac06b0cb0870528f7f65f01482ee642edb5f09e2092c0a9aabf9dcb",
  "xmu-chinese-undergraduate-programs-2026": "460bafb8fc4a16173b958de2def81f0d967b3d28614b31f062e3c16ba79b9d6d",
  "xmu-english-undergraduate-programs-2026": "710947de8e00979e19add79f318564b65b2d970ad07a03ed04ece1cdedd025b3",
  "xmu-chinese-master-programs-2026": "67c5067c11a2e5c5dd53d8ae90dc7395234de34989e8def87313b1c8de355e8b",
  "xmu-english-master-programs-2026": "947b8d3b16a9db9d941bb990bbab97c471d4123623ed62b1b65fe6c2d7f04121",
  "xmu-chinese-doctoral-programs-2026": "260b730aa5927c5c4ac4b20871b5d0429ded2bc10590a10d441819adc3b82b10",
  "xmu-english-doctoral-programs-2026": "52079e0cb96cc84b1b82f62353b9463fac7b265af92298167aeaca2bdfa7b1b1",
  "xmu-fujian-government-scholarship-2026": "1b4090d32344866908ba6fbd07b67fd3063611e8c7468d5e30cf53097364f46c",
  "xmu-new-international-student-scholarship-2026": "3c9b8fd1fdb28345c6e3eea6e33d9de3d4d69ea96bb5b40e177edf62a215f94d",
  "xmu-sustainable-coastal-development-scholarship-2026": "95902b148cb40dc5f01017285975976fc191aced5b1fc1c722ec626268b60f3d",
};
const manifest = JSON.parse(await readFile(paths.manifest, "utf8"));
const evidence = new Map<string, any>();
for (const row of manifest.sources ?? []) if (expected[row.id] === row.sha256 && row.status === 200) evidence.set(row.id, row);
const missing = Object.keys(expected).filter((id) => !evidence.has(id));
if (missing.length) throw new Error(`Missing locked XMU evidence: ${missing.join(", ")}`);
const slugify = (value: string) => value.toLowerCase().replace(/&/g, " and ").replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");
const admissionsByDegree: Record<string, any> = { Undergraduate: evidence.get("xmu-undergraduate-admissions-2026"), Master: evidence.get("xmu-master-admissions-2026"), Doctoral: evidence.get("xmu-doctoral-admissions-2026") };
function tuition(row: any): string {
  if (row.degreeLevel === "Undergraduate") {
    if (row.teachingLanguage === "English") return row.name.includes("MBBS") ? "RMB 38,000/year" : "RMB 90,000/year";
    return "RMB 24,000 or 26,000/year according to discipline category";
  }
  if (row.degreeLevel === "Master") {
    if (row.programCode === "045300") return "RMB 30,000/year";
    return row.teachingLanguage === "English" ? "RMB 39,000 or 45,000/year according to discipline category" : "RMB 26,000 or 30,000/year according to discipline category";
  }
  return row.teachingLanguage === "English" ? "RMB 42,000 or 55,000/year according to discipline category" : "RMB 30,000 or 34,000/year according to discipline category";
}
const programs: CatalogSeedProgram[] = parsed.programs.map((row: any) => {
  const source = evidence.get(row.sourceId); const guide = admissionsByDegree[row.degreeLevel]; const displayTuition = tuition(row); const code = row.programCode || `table-${row.catalogId}`;
  const language = row.teachingLanguage === "English" ? { englishRequirement: "TOEFL iBT 80, IELTS Academic 6.0, an accepted English-medium certificate or another XMU-recognized equivalent; applicants from countries where English is official are exempt." } : { hskRequirement: "Humanities, economics, management, law and arts generally require HSK 5 score 210; science, engineering, medicine and physical education generally require HSK 4 score 210; stated Chinese-medium exemptions apply." };
  const csca = row.degreeLevel === "Undergraduate" ? (row.teachingLanguage === "Chinese" ? ["Professional Chinese", "Mathematics", "Physics and/or Chemistry for science, engineering, agriculture and medicine"] : ["Mathematics", "Physics and/or Chemistry for science, engineering, agriculture and medicine"]) : undefined;
  return { slug: `${schoolSlug}-${row.degreeLevel.toLowerCase()}-${slugify(row.name)}-${slugify(row.teachingLanguage)}-${slugify(code)}-${row.catalogId}`, schoolSlug, citySlug: "xiamen", nameEn: row.name, degreeLevel: row.degreeLevel, durationYears: row.durationYears, fieldCategory: row.school, subjectArea: row.department, teachingLanguage: row.teachingLanguage, ...language, ...(csca ? { cscaSubjects: csca, displaySubjects: csca, cscaRequirement: "2026 undergraduate applicants submit CSCA results: Mathematics is compulsory; Professional Chinese is compulsory for Chinese-medium routes except the stated Chinese-language exemption; Physics and/or Chemistry apply to science, engineering, agriculture and medicine. Test language follows the program medium." } : { cscaRequirement: "No CSCA requirement is published for this graduate route." }), tuitionText: displayTuition, displayTuition, scholarshipText: "XMU's verified 2026 government, university and sustainable-coastal scholarship routes are reviewed separately.", applicationUrl: "https://application.xmu.edu.cn", applicationNote: `${row.campus}; ${row.school}; ${row.department}; ${row.studyMode}${row.programCode ? `; official program code ${row.programCode}` : ""}; ${row.sourceLocator}. Tuition is published by medium and discipline category in the corresponding 2026 admission guide.`, hasScholarship: true, badgeText: `Official ${row.degreeLevel.toLowerCase()} route`, displayGroup: row.degreeLevel, displayGroupLabel: `${row.degreeLevel} programs`, status: "draft", sourceUrl: source.url, sourceLabel: source.label, sourceSha256: source.sha256, capturedAt: source.fetchedAt, sourceFieldLineage: { nameEn: `${row.sourceLocator}, Programs/Majors column`, degreeLevel: "official catalog title", fieldCategory: `${row.sourceLocator}, Colleges/Schools column`, subjectArea: `${row.sourceLocator}, Departments column`, teachingLanguage: "official catalog title", durationYears: `${row.sourceLocator}, Duration column`, applicationNote: `${row.sourceLocator}, location, school, department, code and mode columns`, tuitionText: `${guide.label}, Study Costs section`, ...(csca ? { cscaSubjects: "2026 undergraduate admission guide, CSCA subject matrix" } : {}) } };
});
if (programs.length !== 535 || new Set(programs.map((row) => row.slug)).size !== 535) throw new Error("XMU program routes/slugs mismatch.");
const info = (label: string, value?: string) => ({ label, ...(value ? { value } : {}) }); const benefit = (label: string) => ({ label, included: true });
const commonMaterials = [info("Passport information page"), info("Highest diploma or expected-graduation proof"), info("Academic transcripts"), info("Language proficiency evidence"), info("Personal statement or study/research plan"), info("Physical examination record"), info("Financial support guarantee"), info("No-criminal-record report")];
function scholarship(sourceId: string, value: Partial<CatalogSeedScholarship> & Pick<CatalogSeedScholarship, "slug" | "title" | "fundingLevel" | "coverage" | "applicableDegree" | "amountText">): CatalogSeedScholarship { const source = evidence.get(sourceId); return { schoolSlug, status: "draft", sourceUrl: source.url, sourceLabel: source.label, sourceSha256: source.sha256, capturedAt: source.fetchedAt, providerLocation: "China", targetCountries: [], targetRegions: [], actionLinks: [{ label: source.label, url: source.url, kind: "official-source" }, { label: "XMU international application system", url: "https://application.xmu.edu.cn", kind: "official-application" }], sourceFieldLineage: { title: "official notice title", fundingLevel: "official coverage section", coverage: "official coverage section", amountText: "official coverage section", applicableDegree: "official eligibility/program section", applicableProgram: "official academic-program section", eligibilityItems: "official eligibility section", applicationMaterials: "official application procedure and degree admission guides", applicationSteps: "official application procedure section", deadlineDate: "official application-period section" }, ...value }; }
const scholarships: CatalogSeedScholarship[] = [
  scholarship("xmu-chinese-government-university-program-2026", { slug: "official-2026-xmu-chinese-government-university-scholarship", title: "Xiamen University 2026 Chinese Government Scholarship - University Program", nameZh: "厦门大学2026年中国政府奖学金高校项目", type: "government", typeLabel: "Chinese Government Scholarship Type B", providerName: "中华人民共和国教育部 / 国家留学基金管理委员会", providerNameEn: "Ministry of Education of the PRC / China Scholarship Council", fundingLevel: "Full", coverage: "Tuition, university dormitory or accommodation subsidy, monthly stipend and comprehensive medical insurance", applicableDegree: "Bachelor, Master, Doctoral", applicableProgram: "CSC-approved XMU 2026 degree programs; approval and final scope remain subject to CSC", amountText: "CNY 2,500/month for undergraduates, CNY 3,000/month for master's students and CNY 3,500/month for doctoral students; CNY 800/year medical insurance plus tuition and accommodation support.", deadlineDate: "2026-02-15", deadlineLabel: "December 1, 2025-February 15, 2026", applicationRound: "2026 Chinese Government Scholarship University Program", benefitItems: [benefit("Tuition"), benefit("University dormitory or accommodation subsidy"), benefit("CNY 2,500/month undergraduate stipend"), benefit("CNY 3,000/month master's stipend"), benefit("CNY 3,500/month doctoral stipend"), benefit("CNY 800/year comprehensive medical insurance")], eligibilityItems: [info("Bachelor", "High-school diploma and under 25"), info("Master", "Bachelor's degree and under 35"), info("Doctoral", "Master's degree and under 40"), info("Concurrent funding", "May not hold another Chinese-government or XMU scholarship concurrently")], applicationMaterials: [...commonMaterials, info("Signed CSC application form"), info("Pre-acceptance letter for postgraduate applicants")], applicationSteps: [info("Step 1", "Apply in CSC as Type B using XMU agency number 10384"), info("Step 2", "Apply in the XMU system and upload the CSC form"), info("Step 3", "Complete XMU review and await CSC final approval")], summary: "XMU's 2026 full Chinese Government Scholarship Type B route for CSC-approved degree programs.", sortOrder: 10 }),
  scholarship("xmu-fujian-government-scholarship-2026", { slug: "official-2026-xmu-fujian-government-scholarship", title: "Xiamen University 2026 Fujian Provincial Government Scholarship", nameZh: "厦门大学2026年福建省政府外国留学生奖学金", type: "government", typeLabel: "Fujian Provincial Government Scholarship", providerName: "福建省人民政府", providerNameEn: "Fujian Provincial Government", fundingLevel: "Partial", coverage: "One-year fixed award by degree level; renewal requires fresh selection and provincial approval", applicableDegree: "Bachelor, Master, Doctoral", applicableProgram: "Eligible XMU 2026 degree programs", amountText: "CNY 30,000/year for bachelor's programs, CNY 40,000/year for master's programs and CNY 50,000/year for doctoral programs.", deadlineDate: "2026-04-10", deadlineLabel: "December 1, 2025-April 10, 2026", applicationRound: "2026 Fujian Provincial Government Scholarship", benefitItems: [benefit("CNY 30,000 undergraduate annual award"), benefit("CNY 40,000 master's annual award"), benefit("CNY 50,000 doctoral annual award")], eligibilityItems: [info("Nationality", "Non-Chinese citizen in good health"), info("Bachelor", "High-school diploma or above and under 30"), info("Master", "Bachelor's degree or above and under 35"), info("Doctoral", "Master's degree or above and under 40"), info("Chinese", "Chinese level equivalent to HSK 3 or above")], applicationMaterials: [...commonMaterials, info("Signed Fujian Provincial Government Scholarship form")], applicationSteps: [info("Step 1", "Obtain or qualify for XMU admission"), info("Step 2", "Apply in the XMU system and upload the scholarship form"), info("Step 3", "Await XMU nomination and Fujian provincial final approval")], summary: "A one-year 2026 Fujian government award with degree-specific fixed amounts and annual reselection.", sortOrder: 20 }),
  scholarship("xmu-new-international-student-scholarship-2026", { slug: "official-2026-xmu-new-international-student-scholarship", title: "Xiamen University New International Students Scholarships for 2026", nameZh: "厦门大学2026年国际学生新生奖学金", type: "university", typeLabel: "Xiamen University New International Students Scholarship", providerName: "厦门大学", providerNameEn: "Xiamen University", fundingLevel: "Full or partial", coverage: "Bachelor second-class covers tuition; master and doctoral first-class cover tuition plus stipend; second-class covers tuition", applicableDegree: "Bachelor, Master, Doctoral", applicableProgram: "Published XMU degree programs, excluding English-medium bachelor's routes from the scholarship page's program list", amountText: "Bachelor second-class: tuition only (5 awards). Master first-class: tuition plus CNY 3,000/month (3); second-class: tuition only (8). Doctoral first-class: tuition plus CNY 3,500/month (3); second-class: tuition only (5).", deadlineDate: "2026-04-10", deadlineLabel: "December 1, 2025-April 10, 2026", applicationRound: "2026 XMU New International Students Scholarship", benefitItems: [benefit("Tuition for all published award classes"), benefit("CNY 3,000/month for master's first-class"), benefit("CNY 3,500/month for doctoral first-class")], eligibilityItems: [info("Admission", "Must meet the corresponding XMU degree-program requirements"), info("Bachelor", "High-school diploma and under 25"), info("Master", "Bachelor's degree and under 40"), info("Doctoral", "Master's degree and under 45"), info("Renewal", "Subject to annual assessment")], applicationMaterials: [...commonMaterials, info("XMU scholarship application form")], applicationSteps: [info("Step 1", "Apply for admission and scholarship in the XMU system"), info("Step 2", "Upload the signed scholarship form"), info("Step 3", "Await comprehensive review and university final approval")], summary: "XMU's competitive 2026 new-student award with tuition-only and tuition-plus-stipend classes.", sortOrder: 30 }),
  scholarship("xmu-sustainable-coastal-development-scholarship-2026", { slug: "official-2026-xmu-sustainable-coastal-development-scholarship", title: "Xiamen University 2026 Sustainable Coastal Development Scholarship", nameZh: "厦门大学2026年海岸带可持续发展奖学金", type: "university", typeLabel: "Sustainable Coastal Development Scholarship", providerName: "厦门大学海岸带可持续发展能力建设项目", providerNameEn: "XMU Sustainable Coastal Development Program", fundingLevel: "Full", coverage: "Tuition, on-campus accommodation, monthly stipend and comprehensive medical insurance", applicableDegree: "Master, Doctoral", applicableProgram: "Published ocean-related Chinese- and English-medium postgraduate programs in law of the sea, ocean science, environment/ecology, marine affairs and marine engineering", amountText: "CNY 3,000/month for master's students and CNY 3,500/month for doctoral students, plus tuition, on-campus accommodation and comprehensive medical insurance.", deadlineDate: "2026-04-10", deadlineLabel: "December 1, 2025-April 10, 2026", applicationRound: "2026 Sustainable Coastal Development Scholarship", targetCountries: ["Brunei", "Cambodia", "Indonesia", "Laos", "Malaysia", "Myanmar", "Philippines", "Singapore", "Thailand", "Vietnam"], targetRegions: ["ASEAN"], benefitItems: [benefit("Tuition"), benefit("On-campus accommodation"), benefit("CNY 3,000/month master's stipend"), benefit("CNY 3,500/month doctoral stipend"), benefit("Comprehensive medical insurance")], eligibilityItems: [info("Nationality", "Non-Chinese citizen from an ASEAN country"), info("Master", "Bachelor's degree or above and under 40"), info("Doctoral", "Master's degree or above and under 45"), info("Field", "Published ocean/coastal-related program")], applicationMaterials: [...commonMaterials, info("Sustainable Coastal Development Scholarship application form")], applicationSteps: [info("Step 1", "Qualify for XMU master's or doctoral admission"), info("Step 2", "Apply in the XMU system and submit the SCD form and required documents"), info("Step 3", "Await SCD Program comprehensive review")], summary: "A full 2026 ocean and coastal postgraduate scholarship for ASEAN applicants, with one doctoral and three master's places subject to confirmation.", sortOrder: 40 }),
];
const schoolSource = evidence.get("xmu-undergraduate-admissions-2026");
const candidate: CatalogSeedBundle = { version: 1, generatedAt: manifest.generatedAt,
  cities: [{ slug: "xiamen", nameEn: "Xiamen", nameZh: "厦门", region: "East China", status: "draft", sourceUrl: schoolSource.url, sourceLabel: schoolSource.label, sourceSha256: schoolSource.sha256, capturedAt: schoolSource.fetchedAt, sourceFieldLineage: { nameEn: "official XMU admissions address", nameZh: "normalized Chinese city name", region: "normalized geographic region from the official Fujian address" } }],
  schools: [{ slug: schoolSlug, nameEn: "Xiamen University", nameZh: "厦门大学", citySlug: "xiamen", schoolType: "public", region: "Xiamen, Fujian, East China", applicationLevel: "Undergraduate, Master, Doctoral", languageOfInstruction: "Chinese and English depending on route", languageRequirement: "Chinese routes use discipline-specific HSK thresholds; English routes accept TOEFL, IELTS, prior English-medium study or other XMU-recognized evidence.", hskRequirement: "Humanities, economics, management, law and arts: HSK 5 score 210; science, engineering, medicine and physical education: HSK 4 score 210; stated exemptions and Chinese-language route rules apply.", englishRequirement: "TOEFL iBT 80 or IELTS Academic 6.0, accepted prior English-medium instruction or another XMU-recognized equivalent; applicants from English-official countries are exempt.", deadlineSummary: "2026 applications open December 1, 2025. Chinese Government Scholarship deadline: February 15; other reviewed scholarships: April 10; self-funded: May 10.", tuitionSummary: "2026 annual tuition ranges from RMB 24,000 to RMB 90,000 depending on degree, language and discipline; doctoral tuition is waived in the fourth academic year under the published guide.", applicationFee: "RMB 400", websiteUrl: "https://www.xmu.edu.cn/", admissionsUrl: "https://admissions.xmu.edu.cn/", cscaRequired: true, cscaRequirement: "All undergraduate applicants submit CSCA scores. Mathematics is compulsory; Professional Chinese applies to Chinese-medium routes except the stated Chinese-language exemption; Physics and/or Chemistry apply to science, engineering, agriculture and medicine. Test language matches the program medium.", cscaSubjects: ["Professional Chinese where applicable", "Mathematics", "Physics and/or Chemistry for applicable categories"], subjectTags: [...new Set(programs.map((row) => row.fieldCategory).filter(Boolean))] as string[], languageTags: ["Chinese", "English"], tuitionBandLabel: "RMB 24,000-90,000/year", campusHighlights: ["535 official 2026 international degree routes", "88 undergraduate, 215 master's and 232 doctoral routes", "64 English-medium routes", "Siming, Xiang'an and Zhangzhou campuses", "Four independently verified 2026 scholarship records"], status: "draft", sourceUrl: schoolSource.url, sourceLabel: schoolSource.label, sourceSha256: schoolSource.sha256, capturedAt: schoolSource.fetchedAt, sourceFieldLineage: { nameEn: "official 2026 admission guide title", citySlug: "official admissions address", applicationLevel: "three official degree guides", languageRequirement: "official eligibility sections", deadlineSummary: "official application timelines", tuitionSummary: "official study-cost sections", applicationFee: "official study-cost sections", cscaRequirement: "official undergraduate admission guide" } }],
  programs,
  programIntakes: programs.map((program) => { const source = admissionsByDegree[program.degreeLevel!]; return { programSlug: program.slug, intakeTerm: "Fall", intakeYear: 2026, deadlineDate: "2026-05-10T00:00:00.000Z", deadlineLabel: "Self-funded application deadline: May 10, 2026; scholarship deadlines are earlier", applicationRound: "2026 international degree intake", status: "closed" as const, sourceUrl: source.url, sourceLabel: source.label, sourceSha256: source.sha256, capturedAt: source.fetchedAt, sourceFieldLineage: { deadlineDate: "official 2026 degree guide application timeline; date-only value normalized to ISO UTC" } }; }),
  scholarships,
};
const candidateText = `${JSON.stringify(candidate, null, 2)}\n`; const validation = createCatalogMigrationValidationReport(JSON.parse(candidateText)); if (!validation.ok) throw new Error(`XMU candidate validation failed:\n${validation.errors.join("\n")}`); const candidateSha256 = sha(candidateText);
const legacyProgramSlugs = ["xiamen-university-accounting", "xiamen-university-biological-science", "xiamen-university-chemistry", "xiamen-university-clinical-medicine-mbbs-english", "xiamen-university-digital-media-art-english", "xiamen-university-ecology", "xiamen-university-economics", "xiamen-university-education", "xiamen-university-environmental-design-english", "xiamen-university-finance", "xiamen-university-international-economics-and-trade", "xiamen-university-marine-science", "xiamen-university-statistics", "xiamen-university-visual-communication-design-english"];
const legacyScholarshipSlugs = ["xiamen-university", "xiamen-university-67", "xiamen-university-68"];
const reviewBase: any = { version: 1, status: "awaiting_user_approval", generatedAt: candidate.generatedAt, scope: { schoolSlug, cityOverwriteCount: 1, schoolOverwriteCount: 1, programRouteCount: 535, undergraduateRouteCount: 88, masterRouteCount: 215, doctoralRouteCount: 232, programIntakeCount: 535, scholarshipCount: 4, newScholarshipCount: 3, stableScholarshipUpdateCount: 1, archiveProgramAliasCount: 14, archiveScholarshipAliasCount: 3 }, candidateSha256, candidateBundleSha256: validation.bundleSha256, operationPlanSha256: validation.operationPlanSha256, evidence: [...evidence.values()].sort((a,b) => a.id.localeCompare(b.id)).map(row => ({ sourceId: row.id, sourceUrl: row.url, sourceLabel: row.label, sha256: row.sha256, fetchedAt: row.fetchedAt, contentType: row.contentType })), sourceReview: { result: "pass", htmlProgramRowsReviewed: 535, sourceTableCount: 6, note: "All six official program tables were parsed without contact columns; official row sequences, required fields, row counts, durations and full-time modes were checked." }, reconciliation: { destructiveDeletion: false, cityOverwrite: { slug: "xiamen", previousSource: "unverified third-party source", replacementSource: "verified XMU official source" }, schoolOverwrite: { slug: schoolSlug, previousSource: "unverified third-party source", replacementSource: "verified XMU official source" }, stableScholarshipUpdateSlugs: ["official-2026-xmu-chinese-government-university-scholarship"], legacyProgramAliasesToArchive: legacyProgramSlugs, legacyScholarshipAliasesToArchive: legacyScholarshipSlugs }, publicationDecisions: [{ field: "Xiamen Tan Kah Kee Scholarship", officialStatus: "SUSPEND in the 2026 degree admission guides", decision: "Archive the unverified legacy record and do not create an active 2026 scholarship." }, { field: "Program contact columns", decision: "Exclude coordinator names, direct telephone numbers and personal/role email addresses from the candidate bundle." }, { field: "Tuition", decision: "Retain official language/discipline ranges where the program table does not assign a discipline fee category; do not guess a single amount." }], sensitiveDataCheck: { result: "pass", scope: "candidate bundle only", note: "Only public institutional, program, admissions and scholarship information is included. Coordinator/contact columns were intentionally excluded; applicant records, private files, accounts and payment data are absent." }, reviewNotes: ["The 14 legacy programs and three legacy scholarships are proposed for archival, not deletion.", "The existing verified Chinese Government Scholarship slug is updated in place with current rich fields.", "The batch replaces unverified third-party Xiamen city and XMU school source metadata.", "Standing default publication does not cover these reconciliations; exact approval is required."] };
const reviewHash = sha(JSON.stringify(reviewBase)); const review = { ...reviewBase, reviewHash, publicationReference: `product-owner-approved-xmu-complete-batch-01-${reviewHash}` };
await Promise.all([writeFile(paths.draft, candidateText, "utf8"), writeFile(paths.validation, `${JSON.stringify(validation, null, 2)}\n`, "utf8"), writeFile(paths.review, `${JSON.stringify(review, null, 2)}\n`, "utf8")]);
console.log(JSON.stringify({ ok: true, counts: reviewBase.scope, candidateSha256, candidateBundleSha256: validation.bundleSha256, reviewHash, publicationReference: review.publicationReference, paths }, null, 2));
