import { createHash } from "node:crypto";
import { readFile, writeFile } from "node:fs/promises";
import { resolve } from "node:path";
import { CatalogSeedWriter } from "../src/server/catalog/seed-writer.ts";
import { createCatalogMigrationValidationReport, type CatalogSeedBundle } from "../src/server/catalog/seed-contract.ts";
import { assertLocalCatalogPublishTarget, LOCAL_CATALOG_PUBLISH_CONFIRMATION } from "../src/server/catalog/local-publish-safety.ts";
import { createPostgresPool, createTransactionalSqlClient } from "../src/server/db/postgres-client.ts";

const root = process.cwd(), batch = "scut-school-scholarships-batch-01", prefix = `catalog.${batch}`;
const paths = { candidate: resolve(root, `seeds/${prefix}.draft.json`), validation: resolve(root, `seeds/${prefix}.validation.json`), review: resolve(root, `seeds/${prefix}.review.json`), output: resolve(root, `seeds/${prefix}.approved.local.json`), approval: resolve(root, `seeds/${prefix}.approval.json`), state: resolve(root, ".cuac-local/runtime.json") };
const parse = async (path: string) => JSON.parse(await readFile(path, "utf8")), sha = (value: string) => createHash("sha256").update(value).digest("hex");
const candidateText = await readFile(paths.candidate, "utf8"), candidate = JSON.parse(candidateText) as CatalogSeedBundle;
const [validation, review, state, oldApproval] = await Promise.all([parse(paths.validation), parse(paths.review), parse(paths.state), parse(paths.approval).catch(() => null)]), { reviewHash, publicationReference, ...reviewBase } = review;
if (sha(JSON.stringify(reviewBase)) !== reviewHash || publicationReference !== `standing-authorized-${batch}-${reviewHash}`) throw new Error("SCUT review mismatch.");
const fresh = createCatalogMigrationValidationReport(candidate);
if (!fresh.ok || !validation.ok || sha(candidateText) !== review.candidateSha256 || fresh.bundleSha256 !== review.candidateBundleSha256 || fresh.bundleSha256 !== validation.bundleSha256 || fresh.operationPlanSha256 !== review.operationPlanSha256 || fresh.operationPlanSha256 !== validation.operationPlanSha256) throw new Error("SCUT candidate changed after review.");
if (review.status !== "standing_user_approval" || review.standingAuthorization?.instruction !== "发布默认允许" || review.sourceReview?.result !== "pass" || review.sensitiveDataCheck?.result !== "pass" || review.reconciliation?.destructiveDeletion !== false || review.scope?.newSchoolCount !== 1 || review.scope?.newScholarshipCount !== 8 || review.scope?.newProgramRouteCount !== 0 || review.scope?.overwriteCount !== 0 || review.scope?.archiveCount !== 0) throw new Error("SCUT batch is not standing-authorized.");
if (candidate.cities?.length !== 1 || candidate.schools?.length !== 1 || candidate.programs?.length !== 0 || candidate.programIntakes?.length !== 0 || candidate.scholarships?.length !== 8 || candidate.scholarships.some((row: any) => !row.benefitItems?.length || !row.eligibilityItems?.length || !row.applicationMaterials?.length || !row.applicationSteps?.length || !row.actionLinks?.length)) throw new Error("SCUT candidate scope or rich scholarship fields changed.");
const approvedAt = oldApproval?.approvedAt ?? new Date().toISOString(), sourceSchemaSha256 = sha(JSON.stringify({ cityFields: [...new Set(candidate.cities.flatMap(Object.keys))].sort(), schoolFields: [...new Set(candidate.schools.flatMap(Object.keys))].sort(), scholarshipFields: [...new Set(candidate.scholarships.flatMap(Object.keys))].sort() }));
const publication: CatalogSeedBundle = { version: 2, generatedAt: approvedAt, handoff: { sourceSystem: "CUAC reviewed official South China University of Technology sources", cleanedExportName: `${prefix}.draft.json`, cleanedExportSha256: fresh.bundleSha256, sourceSchemaSha256, reviewReference: publicationReference, prohibitedDataReviewReference: publicationReference, approvalRecordedAt: approvedAt, sourceReadOnly: true, prohibitedDataConfirmedExcluded: true }, cities: candidate.cities, schools: candidate.schools.map((row) => ({ ...row, status: "active" as const, verificationStatus: "verified" as const, lastVerifiedAt: approvedAt })), programs: [], programIntakes: [], scholarships: candidate.scholarships.map((row) => ({ ...row, status: "active" as const, verificationStatus: "verified" as const, lastVerifiedAt: approvedAt })) };
const report = createCatalogMigrationValidationReport(publication); if (!report.ok || report.summary.schools !== 1 || report.summary.programs !== 0 || report.summary.scholarships !== 8) throw new Error(`Invalid SCUT publication: ${report.errors.join(" ")}`);
const approval = { version: 1, approvedAt, approvalMode: "standing-user-default-publication", reviewReference: publicationReference, approvedReviewSha256: reviewHash, approvedCandidateFileSha256: sha(candidateText), approvedCandidateBundleSha256: fresh.bundleSha256, publicationBundle: `seeds/${prefix}.approved.local.json`, publicationBundleSha256: report.bundleSha256, schoolSlug: review.scope.schoolSlug, programSlugs: [], scholarshipSlugs: publication.scholarships!.map((row) => row.slug), archivedProgramAliases: [], archivedScholarshipAliases: [], prohibitedDataConfirmedExcluded: true };
async function writeOrVerify(path: string, value: unknown) { const body = `${JSON.stringify(value, null, 2)}\n`; try { await writeFile(path, body, { encoding: "utf8", flag: "wx" }); } catch (error: any) { if (error?.code !== "EEXIST") throw error; if (await readFile(path, "utf8") !== body) throw new Error(`Existing artifact differs: ${path}`); } }
await writeOrVerify(paths.output, publication); await writeOrVerify(paths.approval, approval);
const target = assertLocalCatalogPublishTarget(state, publication, LOCAL_CATALOG_PUBLISH_CONFIRMATION, publicationReference), pool = createPostgresPool({ databaseUrl: target.databaseUrl, max: 1, applicationName: "cuac:scut-school-scholarships-publish" });
try {
  const client = createTransactionalSqlClient(pool);
  const result = await client.transaction(async (tx) => {
    const cityBefore = await tx.query<any>("select to_jsonb(c)-'created_at'-'updated_at' snapshot from cities c where slug='guangzhou'", []); if (cityBefore.length !== 1 || cityBefore[0].snapshot.id !== review.reconciliation.databaseBaseline.cityId) throw new Error("SCUT Guangzhou dependency changed.");
    const schoolBefore = await tx.query<any>("select id,status,verification_status,last_verified_at from schools where slug='south-china-university-of-technology'", []), scholarshipSlugs = publication.scholarships!.map((row) => row.slug), scholarshipsBefore = await tx.query<any>("select slug,status,verification_status,last_verified_at from scholarships where slug=any($1::text[])", [scholarshipSlugs]);
    const pre = schoolBefore.length === 0 && scholarshipsBefore.length === 0, post = schoolBefore.length === 1 && scholarshipsBefore.length === 8 && schoolBefore[0].status === "active" && schoolBefore[0].verification_status === "verified" && schoolBefore[0].last_verified_at?.toISOString() === approvedAt && scholarshipsBefore.every((row) => row.status === "active" && row.verification_status === "verified" && row.last_verified_at?.toISOString() === approvedAt); if (!pre && !post) throw new Error("SCUT safe-new records partially conflict.");
    const written = await new CatalogSeedWriter(tx).writeBundle(publication, { preserveExistingCitySlugs: ["guangzhou"] }); if (!written.ok) throw new Error(`SCUT write failed: ${written.errors.join(" ")}`);
    const cityAfter = await tx.query<any>("select to_jsonb(c)-'created_at'-'updated_at' snapshot from cities c where slug='guangzhou'", []); if (JSON.stringify(cityAfter[0]?.snapshot) !== JSON.stringify(cityBefore[0].snapshot)) throw new Error("SCUT publication changed Guangzhou dependency.");
    const totals = await tx.query<any>("select s.id,(select count(*) from programs p where p.school_id=s.id and p.status='active')::int programs,(select count(*) from scholarships h where h.school_id=s.id and h.status='active')::int scholarships,(select count(*) from scholarships h where h.school_id=s.id and h.status='active' and h.verification_status='verified' and jsonb_array_length(h.benefit_items)>0 and jsonb_array_length(h.eligibility_items)>0 and jsonb_array_length(h.application_materials)>0 and jsonb_array_length(h.application_steps)>0 and jsonb_array_length(h.action_links)>0)::int rich_verified_scholarships from schools s where s.slug='south-china-university-of-technology' and s.status='active' and s.verification_status='verified'", []);
    const expected = { programs: 0, scholarships: 8, rich_verified_scholarships: 8 }; if (totals.length !== 1 || Object.entries(expected).some(([key, value]) => totals[0]?.[key] !== value)) throw new Error(`SCUT post-check failed: ${JSON.stringify({ expected, actual: totals[0] })}`);
    return { written: written.summary, totals: totals[0] };
  });
  console.log(JSON.stringify({ ok: true, batch, target: target.publicTarget, approvedReviewSha256: reviewHash, publicationBundleSha256: report.bundleSha256, approvalPath: paths.approval, outputPath: paths.output, ...result }, null, 2));
} finally { await pool.end(); }
