import { createHash } from "node:crypto";
import { readFile, writeFile } from "node:fs/promises";
import { resolve } from "node:path";
import { createCatalogMigrationValidationReport, type CatalogSeedBundle, type CatalogSeedScholarship } from "../src/server/catalog/seed-contract.ts";

const root = process.cwd();
const manifestPath = resolve(root, "work/catalog-official/ustb-complete-batch-01/manifest.json");
const manifestText = await readFile(manifestPath, "utf8");
const manifest = JSON.parse(manifestText);
const sources = new Map(manifest.sources.map((row: any) => [row.id, row]));
const requiredSourceIds = [
  "ustb-international-admission-guide-2026", "ustb-undergraduate-application-2026", "ustb-graduate-application-2026",
  "ustb-undergraduate-program-catalog-2026", "ustb-master-program-catalog-2026", "ustb-doctoral-program-catalog-2026",
  "ustb-english-taught-programs-2026", "ustb-international-economics-1-plus-3-2026", "ustb-undergraduate-admission-guide-2026",
  "ustb-csca-guide-2026", "ustb-chinese-government-scholarship-2026", "ustb-dingxin-scholarship-2026",
  "ustb-silk-road-scholarship-2026", "ustb-beijing-government-scholarship-2026-2027",
];
for (const id of requiredSourceIds) {
  const source: any = sources.get(id);
  if (!source || source.status !== 200 || !/^[a-f0-9]{64}$/.test(source.sha256)) throw new Error(`Missing valid source: ${id}`);
}
const meta = (id: string) => {
  const source: any = sources.get(id);
  return { sourceUrl: source.finalUrl, sourceLabel: source.label, sourceSha256: source.sha256, capturedAt: source.fetchedAt };
};
const slugify = (value: string) => value.toLowerCase().normalize("NFKD").replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");
const schoolSlug = "university-of-science-and-technology-beijing";
const applicationUrl = "https://onlineapply.ustb.edu.cn/";
type Major = [nameZh: string, nameEn: string, school: string];

const undergraduate: Major[] = [
  ["安全工程", "Safety Engineering", "School of Resources and Safety Engineering"], ["采矿工程", "Mining Engineering", "School of Resources and Safety Engineering"],
  ["矿物加工工程", "Mineral Processing Engineering", "School of Resources and Safety Engineering"], ["工程力学", "Engineering Mechanics", "School of Resources and Safety Engineering"],
  ["职业卫生工程", "Occupational Health Engineering", "School of Resources and Safety Engineering"], ["智能采矿工程", "Intelligent Mining Engineering", "School of Resources and Safety Engineering"],
  ["智能建造", "Intelligent Construction", "School of Future Urban Engineering"], ["土木工程", "Civil Engineering", "School of Future Urban Engineering"],
  ["建筑环境与能源应用工程", "Building Environment and Energy Application Engineering", "School of Future Urban Engineering"], ["工程管理", "Engineering Management", "School of Future Urban Engineering"],
  ["冶金工程", "Metallurgical Engineering", "School of Metallurgical and Ecological Engineering"], ["储能科学与工程", "Energy Storage Science and Engineering", "School of Metallurgical and Ecological Engineering"],
  ["材料科学与工程", "Materials Science and Engineering", "School of Materials Science and Engineering"],
  ["机械工程", "Mechanical Engineering", "School of Mechanical Engineering"], ["机器人工程", "Robotics Engineering", "School of Mechanical Engineering"],
  ["车辆工程", "Vehicle Engineering", "School of Mechanical Engineering"], ["物流工程", "Logistics Engineering", "School of Mechanical Engineering"],
  ["工业设计", "Industrial Design", "School of Mechanical Engineering"], ["视觉传达设计", "Visual Communication Design", "School of Mechanical Engineering"],
  ["能源与动力工程", "Energy and Power Engineering", "School of Energy and Environmental Engineering"], ["新能源科学与工程", "New Energy Science and Engineering", "School of Energy and Environmental Engineering"],
  ["环境工程", "Environmental Engineering", "School of Energy and Environmental Engineering"], ["环境科学", "Environmental Science", "School of Energy and Environmental Engineering"],
  ["自动化", "Automation", "School of Automation and Electrical Engineering"], ["测控技术与仪器", "Measurement and Control Technology and Instruments", "School of Automation and Electrical Engineering"],
  ["智能感知工程", "Intelligent Sensing Engineering", "School of Automation and Electrical Engineering"], ["人工智能", "Artificial Intelligence", "School of Intelligence Science and Technology"],
  ["计算机科学与技术", "Computer Science and Technology", "School of Computer and Communication Engineering"], ["信息安全", "Information Security", "School of Computer and Communication Engineering"],
  ["物联网工程", "Internet of Things Engineering", "School of Computer and Communication Engineering"], ["通信工程", "Communication Engineering", "School of Computer and Communication Engineering"],
  ["数学与应用数学", "Mathematics and Applied Mathematics", "School of Mathematics and Physics"], ["信息与计算科学", "Information and Computing Science", "School of Mathematics and Physics"],
  ["应用物理学", "Applied Physics", "School of Mathematics and Physics"], ["统计学", "Statistics", "School of Mathematics and Physics"],
  ["应用化学", "Applied Chemistry", "School of Chemistry and Biological Engineering"], ["生物技术", "Biotechnology", "School of Chemistry and Biological Engineering"],
  ["工商管理（人工智能双学位）", "Business Administration (Artificial Intelligence Dual Degree)", "School of Economics and Management"], ["会计学", "Accounting", "School of Economics and Management"],
  ["国际经济与贸易", "International Economics and Trade", "School of Economics and Management"], ["金融工程", "Financial Engineering", "School of Economics and Management"],
  ["大数据管理与应用", "Big Data Management and Application", "School of Economics and Management"], ["信息管理与信息系统", "Information Management and Information Systems", "School of Economics and Management"],
  ["行政管理", "Public Administration", "School of Humanities and Social Sciences"], ["社会工作", "Social Work", "School of Humanities and Social Sciences"],
  ["法学", "Law", "School of Humanities and Social Sciences"], ["英语", "English", "School of Foreign Studies"], ["日语", "Japanese", "School of Foreign Studies"], ["德语", "German", "School of Foreign Studies"],
];
const masters: Major[] = [
  ["采矿工程", "Mining Engineering", "School of Resources and Safety Engineering"], ["地质学", "Geology", "School of Resources and Safety Engineering"],
  ["安全科学与工程", "Safety Science and Engineering", "School of Resources and Safety Engineering"], ["矿物加工工程", "Mineral Processing Engineering", "School of Resources and Safety Engineering"],
  ["力学（工学）", "Mechanics (Engineering)", "School of Resources and Safety Engineering"], ["土木工程", "Civil Engineering", "School of Future Urban Engineering"],
  ["供热供燃气通风及空调工程", "Heating, Gas Supply, Ventilation and Air Conditioning Engineering", "School of Future Urban Engineering"],
  ["环境科学与工程", "Environmental Science and Engineering", "School of Energy and Environmental Engineering"], ["动力工程及工程热物理", "Power Engineering and Engineering Thermophysics", "School of Energy and Environmental Engineering"],
  ["冶金工程", "Metallurgical Engineering", "School of Metallurgical and Ecological Engineering"], ["材料科学与工程", "Materials Science and Engineering", "School of Materials Science and Engineering"],
  ["机械工程", "Mechanical Engineering", "School of Mechanical Engineering"], ["设计学", "Design", "School of Mechanical Engineering"], ["物流工程", "Logistics Engineering", "School of Mechanical Engineering"],
  ["控制科学与工程", "Control Science and Engineering", "School of Automation and Electrical Engineering"], ["仪器科学与技术", "Instrument Science and Technology", "School of Automation and Electrical Engineering"],
  ["人工智能科学与工程", "Artificial Intelligence Science and Engineering", "School of Intelligence Science and Technology"], ["信息与通信工程", "Information and Communication Engineering", "School of Computer and Communication Engineering"],
  ["计算机科学与技术", "Computer Science and Technology", "School of Computer and Communication Engineering"], ["数学", "Mathematics", "School of Mathematics and Physics"],
  ["物理学", "Physics", "School of Mathematics and Physics"], ["统计学", "Statistics", "School of Mathematics and Physics"], ["力学（理学）", "Mechanics (Science)", "School of Mathematics and Physics"],
  ["生物学", "Biology", "School of Chemistry and Biological Engineering"], ["化学", "Chemistry", "School of Chemistry and Biological Engineering"],
  ["化学工程与技术", "Chemical Engineering and Technology", "School of Chemistry and Biological Engineering"], ["生物技术与工程", "Biotechnology and Engineering", "School of Chemistry and Biological Engineering"],
  ["企业管理", "Business Management", "School of Economics and Management"], ["金融学", "Finance", "School of Economics and Management"], ["产业经济学", "Industrial Economics", "School of Economics and Management"],
  ["国际贸易学", "International Trade", "School of Economics and Management"], ["技术经济及管理", "Technical Economics and Management", "School of Economics and Management"],
  ["管理科学与工程", "Management Science and Engineering", "School of Economics and Management"], ["会计学", "Accounting", "School of Economics and Management"],
  ["公共管理学（行政管理方向）", "Public Administration (Administrative Management)", "School of Humanities and Social Sciences"],
  ["公共管理学（教育经济与管理方向）", "Public Administration (Education Economics and Management)", "School of Humanities and Social Sciences"],
  ["社会学", "Sociology", "School of Humanities and Social Sciences"], ["法学", "Law", "School of Humanities and Social Sciences"],
  ["外国语言文学（英语语言文学方向）", "Foreign Languages and Literatures (English Language and Literature)", "School of Foreign Studies"],
  ["外国语言文学（外国语言学及应用语言学方向）", "Foreign Languages and Literatures (Foreign Linguistics and Applied Linguistics)", "School of Foreign Studies"],
  ["马克思主义理论", "Marxist Theory", "School of Marxism"], ["科学技术哲学", "Philosophy of Science and Technology", "School of Marxism"],
  ["科学技术史", "History of Science and Technology", "Institute for Cultural Heritage and History of Science and Technology"], ["作物学", "Crop Science", "School of Advanced Agriculture"],
];
const doctorals: Major[] = [
  ["安全科学与工程", "Safety Science and Engineering", "School of Resources and Safety Engineering"], ["矿业工程", "Mining Engineering", "School of Resources and Safety Engineering"],
  ["力学（工学）", "Mechanics (Engineering)", "School of Resources and Safety Engineering"], ["土木工程", "Civil Engineering", "School of Future Urban Engineering"],
  ["环境科学与工程", "Environmental Science and Engineering", "School of Energy and Environmental Engineering"], ["动力工程及工程热物理", "Power Engineering and Engineering Thermophysics", "School of Energy and Environmental Engineering"],
  ["冶金工程", "Metallurgical Engineering", "School of Metallurgical and Ecological Engineering"], ["储能化学与物理", "Energy Storage Chemistry and Physics", "School of Metallurgical and Ecological Engineering"],
  ["材料科学与工程", "Materials Science and Engineering", "School of Materials Science and Engineering"], ["机械工程", "Mechanical Engineering", "School of Mechanical Engineering"],
  ["物流工程", "Logistics Engineering", "School of Mechanical Engineering"], ["控制科学与工程", "Control Science and Engineering", "School of Automation and Electrical Engineering"],
  ["仪器科学与技术", "Instrument Science and Technology", "School of Automation and Electrical Engineering"], ["人工智能科学与工程", "Artificial Intelligence Science and Engineering", "School of Intelligence Science and Technology"],
  ["计算机科学与技术", "Computer Science and Technology", "School of Computer and Communication Engineering"], ["信息与通信工程", "Information and Communication Engineering", "School of Computer and Communication Engineering"],
  ["物理学", "Physics", "School of Mathematics and Physics"], ["应用数学与工程科学", "Applied Mathematics and Engineering Science", "School of Mathematics and Physics"],
  ["力学（理学）", "Mechanics (Science)", "School of Mathematics and Physics"], ["化学", "Chemistry", "School of Chemistry and Biological Engineering"],
  ["工商管理", "Business Administration", "School of Economics and Management"], ["管理科学与工程", "Management Science and Engineering", "School of Economics and Management"],
  ["外国语言文学", "Foreign Languages and Literatures", "School of Foreign Studies"], ["马克思主义理论", "Marxist Theory", "School of Marxism"],
  ["科学技术史", "History of Science and Technology", "Institute for Cultural Heritage and History of Science and Technology"],
];

const englishMasters = new Set(["Metallurgical Engineering", "Safety Science and Engineering", "Environmental Science and Engineering", "Information and Communication Engineering", "Business Management", "Management Science and Engineering", "International Trade", "Public Administration (Education Economics and Management)", "Sociology"]);
const common = (sourceId: string, nameZh: string, nameEn: string, school: string, degreeLevel: "Bachelor" | "Master" | "Doctoral", teachingLanguage: "Chinese" | "English", slug: string) => ({
  slug, schoolSlug, citySlug: "beijing", nameEn, nameZh, degreeLevel,
  durationYears: degreeLevel === "Bachelor" ? 4 : degreeLevel === "Master" ? (nameEn === "Business Management" || nameEn.includes("Public Administration") || nameEn === "Sociology" || nameEn === "International Trade" || nameEn === "Management Science and Engineering" ? 2 : 3) : 4,
  fieldCategory: school, subjectArea: nameEn, teachingLanguage,
  hskRequirement: teachingLanguage === "Chinese" ? (degreeLevel === "Bachelor" ? "HSK 4" : degreeLevel === "Master" ? "HSK 5" : "HSK 6") : "No HSK threshold is published for this English-taught route.",
  englishRequirement: teachingLanguage === "English" ? (degreeLevel === "Bachelor" ? "IELTS 5.5, TOEFL 70, or another official English-proficiency certificate when English is not an official language." : "IELTS 6, TOEFL 80, or another official English-proficiency certificate when English is not an official language.") : "Not applicable to the published Chinese-taught route.",
  cscaRequirement: degreeLevel === "Bachelor" ? "CSCA transcript required; all majors require Mathematics, while science/engineering/agriculture majors also require Physics or Chemistry and the published Chinese subject rule applies to Chinese-taught routes." : "No CSCA requirement is published for graduate routes.",
  tuitionAmount: degreeLevel === "Bachelor" ? 23300 : degreeLevel === "Master" ? (teachingLanguage === "English" ? 37600 : 31600) : (teachingLanguage === "English" ? 47600 : 41600),
  tuitionCurrency: "CNY", tuitionPeriod: "year",
  tuitionText: `CNY ${degreeLevel === "Bachelor" ? "23,300" : degreeLevel === "Master" ? (teachingLanguage === "English" ? "37,600" : "31,600") : (teachingLanguage === "English" ? "47,600" : "41,600")}/year`,
  displayTuition: `CNY ${degreeLevel === "Bachelor" ? "23,300" : degreeLevel === "Master" ? (teachingLanguage === "English" ? "37,600" : "31,600") : (teachingLanguage === "English" ? "47,600" : "41,600")}/year`,
  scholarshipText: "Eligible applicants may apply for the Chinese Government Scholarship, Dingxin Scholarship, or another currently published USTB funding route, subject to each award's rules.",
  applicationUrl, applicationNote: `Official 2026 ${teachingLanguage.toLowerCase()}-taught ${degreeLevel.toLowerCase()} route.`, hasScholarship: true,
  badgeText: "Official 2026 route", displayGroup: degreeLevel, displayGroupLabel: `${teachingLanguage}-taught ${degreeLevel.toLowerCase()} programs`, status: "draft" as const,
  ...meta(sourceId), sourceFieldLineage: { nameZh: "official 2026 program table", nameEn: "CUAC normalized English translation of the official Chinese major title", fieldCategory: "official school/college column", degreeLevel: "official catalog heading", teachingLanguage: teachingLanguage === "English" ? "official English-taught program page" : "official degree catalog and language policy", durationYears: "official 2026 admission guide", tuitionText: "official 2026 admission guide fee table", hskRequirement: "official 2026 application requirements", englishRequirement: "official 2026 application requirements", cscaRequirement: "official 2026 CSCA instructions" },
});

const programs: any[] = [];
for (const [nameZh, nameEn, school] of undergraduate) programs.push(common("ustb-undergraduate-program-catalog-2026", nameZh, nameEn, school, "Bachelor", "Chinese", `${schoolSlug}-${slugify(nameEn)}`));
for (const nameEn of ["Materials Science and Engineering", "Environmental Engineering"]) {
  const [nameZh, , school] = undergraduate.find((row) => row[1] === nameEn)!;
  programs.push(common("ustb-english-taught-programs-2026", nameZh, `${nameEn} (English)`, school, "Bachelor", "English", `${schoolSlug}-${slugify(nameEn)}-english`));
}
programs.push({ ...common("ustb-international-economics-1-plus-3-2026", "国际经济与贸易（1+3）", "International Economics and Trade (1+3)", "School of Economics and Management", "Bachelor", "Chinese", `${schoolSlug}-international-economics-and-trade-1-plus-3`), hskRequirement: "No HSK 4 certificate is required at entry; the route requires HSK 5 by graduation.", applicationNote: "Year 1 combines Chinese and foundation study; years 2–4 cover the degree curriculum." });
for (const [nameZh, nameEn, school] of masters) {
  programs.push(common("ustb-master-program-catalog-2026", nameZh, nameEn, school, "Master", "Chinese", `${schoolSlug}-master-${slugify(nameEn)}`));
  if (englishMasters.has(nameEn)) programs.push(common("ustb-english-taught-programs-2026", nameZh, `${nameEn} (English)`, school, "Master", "English", `${schoolSlug}-master-${slugify(nameEn)}-english`));
}
programs.push(common("ustb-english-taught-programs-2026", "工商管理硕士（MBA）", "Master of Business Administration (MBA)", "School of Economics and Management", "Master", "English", `${schoolSlug}-master-business-administration-mba-english`));
for (const [nameZh, nameEn, school] of doctorals) {
  programs.push(common("ustb-doctoral-program-catalog-2026", nameZh, nameEn, school, "Doctoral", "Chinese", `${schoolSlug}-doctoral-${slugify(nameEn)}`));
  programs.push(common("ustb-international-admission-guide-2026", nameZh, `${nameEn} (English)`, school, "Doctoral", "English", `${schoolSlug}-doctoral-${slugify(nameEn)}-english`));
}

const programIntakes = programs.map((program) => ({
  programSlug: program.slug, intakeTerm: "Fall", intakeYear: 2026, openDate: "2025-11-01T00:00:00Z", deadlineDate: "2026-06-15T00:00:00Z",
  deadlineLabel: "Applications: November 1, 2025–June 15, 2026; scholarship deadlines differ by award.", applicationRound: "2026 international degree admission", status: "closed" as const,
  ...meta(program.degreeLevel === "Bachelor" ? "ustb-undergraduate-application-2026" : "ustb-graduate-application-2026"),
  sourceFieldLineage: { openDate: "official application period; normalized to ISO UTC", deadlineDate: "official application period; normalized to ISO UTC", deadlineLabel: "official application period" },
}));

const scholarship = (sourceId: string, value: Omit<CatalogSeedScholarship, "sourceUrl" | "sourceLabel" | "sourceSha256" | "capturedAt" | "schoolSlug" | "status">): CatalogSeedScholarship => ({
  schoolSlug, status: "draft", providerLocation: "Beijing, China", targetCountries: [], targetRegions: [], ...meta(sourceId),
  actionLinks: [{ label: "Official scholarship notice", url: meta(sourceId).sourceUrl, kind: "official-source" }, { label: "USTB application portal", url: applicationUrl, kind: "official-application" }],
  sourceFieldLineage: { title: "official notice title", fundingLevel: "scholarship coverage section", coverage: "scholarship coverage section", applicableDegree: "published degree scope", applicableProgram: "published program scope", eligibilityItems: "eligibility section", applicationMaterials: "application-materials section", applicationSteps: "application process section", deadlineLabel: "published application deadline" },
  ...value,
});
const scholarships: CatalogSeedScholarship[] = [
  scholarship("ustb-chinese-government-scholarship-2026", { slug: "official-2026-ustb-cgs-type-a-bilateral", title: "USTB 2026 Chinese Government Scholarship — Type A Bilateral Program", nameZh: "北京科技大学2026年中国政府奖学金国别奖 Type A", type: "government", typeLabel: "Chinese Government Scholarship Type A", providerName: "Ministry of Education of the PRC / China Scholarship Council", providerNameEn: "Ministry of Education of the PRC / China Scholarship Council", fundingLevel: "Full or Partial", coverage: "The official USTB notice describes Chinese Government Scholarship awards as full or partial; award details follow the dispatching authority and CSC decision.", applicableDegree: "Bachelor, Master, Doctoral", applicableProgram: "USTB degree programs accepted under the applicant's dispatching authority route", amountText: "Award package determined by CSC and the dispatching authority", deadlineLabel: "Generally November to March; exact deadline differs by country", applicationRound: "2026 Type A bilateral route", benefitItems: [{ label: "Funding package", included: true, note: "Full or partial award as determined by CSC" }], eligibilityItems: [{ label: "Citizenship", value: "Non-Chinese citizen in good health" }, { label: "Application channel", value: "Apply through the home-country dispatching authority or Chinese embassy/consulate" }], applicationMaterials: [{ label: "CSC application materials", value: "Follow the dispatching authority's current requirements." }], applicationSteps: [{ label: "Step 1", value: "Contact the dispatching authority or Chinese embassy/consulate" }, { label: "Step 2", value: "Complete the CSC application" }, { label: "Step 3", value: "After award, complete USTB online registration" }], summary: "USTB's officially published 2026 Type A Chinese Government Scholarship route.", sortOrder: 10 }),
  scholarship("ustb-chinese-government-scholarship-2026", { slug: "official-2026-ustb-cgs-high-level-postgraduate", title: "USTB 2026 Chinese Government Scholarship — High-Level Postgraduate Program", nameZh: "北京科技大学2026年中国政府奖学金高水平研究生项目", type: "government", typeLabel: "Chinese Government Scholarship Type B", providerName: "Ministry of Education of the PRC / China Scholarship Council", providerNameEn: "Ministry of Education of the PRC / China Scholarship Council", fundingLevel: "Full", coverage: "Tuition, accommodation, comprehensive medical insurance and monthly stipend.", applicableDegree: "Master, Doctoral", applicableProgram: "Published USTB master and doctoral programs", amountText: "Monthly stipend: CNY 3,000 master; CNY 3,500 doctoral", deadlineDate: "2026-03-15", deadlineLabel: "March 15, 2026", applicationRound: "2026 High-Level Postgraduate Program", benefitItems: [{ label: "Tuition", included: true }, { label: "Accommodation", included: true }, { label: "Medical insurance", included: true }, { label: "Monthly stipend", included: true, note: "CNY 3,000 master; CNY 3,500 doctoral" }], eligibilityItems: [{ label: "Master", value: "Bachelor's degree; under age 35" }, { label: "Doctoral", value: "Master's degree; under age 40" }, { label: "Chinese route", value: "At least HSK 4; HSK 5 required to enter the major after any approved language year" }, { label: "English route", value: "IELTS 6, TOEFL 80, or another official English certificate when English is not an official language" }], applicationMaterials: [{ label: "Degree certificates and transcripts" }, { label: "Study/research plan" }, { label: "Two professor or associate-professor recommendations" }, { label: "Language proof" }, { label: "Passport" }, { label: "Physical examination" }, { label: "No-criminal-record certificate" }], applicationSteps: [{ label: "Step 1", value: "Apply in the CSC Type B system with USTB agency code 10008" }, { label: "Step 2", value: "Apply in the USTB international application system and pay the application fee" }, { label: "Step 3", value: "If selected, upload USTB's pre-admission document to CSC" }], summary: "Full USTB 2026 CGS Type B route for high-level postgraduate applicants.", sortOrder: 20 }),
  scholarship("ustb-silk-road-scholarship-2026", { slug: "official-2026-ustb-cgs-silk-road", title: "USTB 2026 Chinese Government Scholarship — Silk Road Program", nameZh: "北京科技大学2026年中国政府奖学金“丝绸之路”项目", type: "government", typeLabel: "Chinese Government Scholarship — Silk Road", providerName: "Ministry of Education of the PRC / China Scholarship Council", providerNameEn: "Ministry of Education of the PRC / China Scholarship Council", fundingLevel: "Full", coverage: "Tuition, accommodation, living stipend and comprehensive medical insurance.", applicableDegree: "Bachelor, Master, Doctoral", applicableProgram: "Metallurgical Engineering; Materials Science and Engineering; Computer Science and Technology; Environmental Science and Engineering; Safety Science and Engineering, by the published degree/language matrix", amountText: "Full scholarship package; stipend amount not separately stated in this notice", deadlineDate: "2026-05-15", deadlineLabel: "May 15, 2026", applicationRound: "2026 Silk Road Program", targetCountries: ["Pakistan", "Mongolia", "Cambodia", "Indonesia", "Vietnam", "Laos", "Bangladesh", "Malaysia", "Thailand", "Myanmar"], benefitItems: [{ label: "Tuition", included: true }, { label: "Accommodation", included: true }, { label: "Living stipend", included: true }, { label: "Medical insurance", included: true }], eligibilityItems: [{ label: "Nationality", value: "Citizen of one of the ten published eligible countries" }, { label: "Bachelor", value: "High-school qualification; under age 25" }, { label: "Master", value: "Bachelor's degree; under age 35" }, { label: "Doctoral", value: "Master's degree; under age 40" }, { label: "Language", value: "HSK 4 for Chinese study, or IELTS 6 / TOEFL 80 / equivalent for English study" }], applicationMaterials: [{ label: "CSC Type B application form" }, { label: "Passport" }, { label: "Highest degree certificate and transcripts" }, { label: "Language proof" }, { label: "Study plan of at least 1,000 words" }, { label: "Two recommendation letters" }, { label: "Physical examination" }, { label: "No-criminal-record certificate" }], applicationSteps: [{ label: "Step 1", value: "Apply in CSC Type B with agency code 10008" }, { label: "Step 2", value: "Apply in USTB's system and pay the application fee" }, { label: "Step 3", value: "Await USTB review by official email" }], summary: "Full 2026 Silk Road award for specified USTB disciplines and ten eligible countries.", sortOrder: 30 }),
  scholarship("ustb-dingxin-scholarship-2026", { slug: "official-2026-ustb-dingxin-scholarship", title: "USTB 2026 Dingxin Scholarship for International Students", nameZh: "北京科技大学2026年国际学生鼎新奖学金", type: "university", typeLabel: "Dingxin Scholarship", providerName: "University of Science and Technology Beijing", providerNameEn: "University of Science and Technology Beijing", fundingLevel: "Full or Partial", coverage: "Full award: tuition, on-campus accommodation, living stipend and comprehensive medical insurance; partial award: one or more of these components.", applicableDegree: "Bachelor, Master, Doctoral", applicableProgram: "USTB international degree programs", amountText: "Full or partial package; component amounts are not separately published", deadlineDate: "2026-04-30", deadlineLabel: "April 30, 2026", applicationRound: "2026 Dingxin Scholarship", benefitItems: [{ label: "Tuition", included: true }, { label: "On-campus accommodation", included: true }, { label: "Living stipend", included: true }, { label: "Medical insurance", included: true }], eligibilityItems: [{ label: "Citizenship", value: "Non-Chinese citizen in good health" }, { label: "Bachelor", value: "High-school diploma; under age 30" }, { label: "Master", value: "Bachelor's degree; under age 40" }, { label: "Doctoral", value: "Master's degree; under age 45" }, { label: "Renewal", value: "Annual review is required to continue funding" }], applicationMaterials: [{ label: "Admission materials", value: "Use the materials published for the relevant USTB degree application." }], applicationSteps: [{ label: "Step 1", value: "Log in to USTB's application system" }, { label: "Step 2", value: "Select Dingxin Scholarship, upload materials and pay the application fee" }, { label: "Step 3", value: "Submit and await the official admission decision" }], bodySections: [{ title: "Duration", body: "Bachelor: four years; master: two to three years; doctoral: four years. Funding is normally not extended beyond the duration set at admission." }], summary: "USTB's 2026 university-funded full or partial award across all degree levels.", sortOrder: 40 }),
  scholarship("ustb-beijing-government-scholarship-2026-2027", { slug: "official-2026-2027-ustb-beijing-government-scholarship", title: "USTB 2026–2027 Beijing Government Scholarship for International Students", nameZh: "北京科技大学2026—2027学年北京来华留学生政府奖学金", type: "government", typeLabel: "Beijing Government Scholarship", providerName: "Beijing Municipal Government / University of Science and Technology Beijing", providerNameEn: "Beijing Municipal Government / University of Science and Technology Beijing", fundingLevel: "Partial", coverage: "Category A, B or C support including tuition and/or accommodation according to the award tier.", applicableDegree: "Foundation, Bachelor, Master, Doctoral", applicableProgram: "Eligible self-funded international students at USTB, including 2026 entrants and continuing students", amountText: "Category A/B/C support; exact tier amount is not stated in the notice", deadlineDate: "2026-09-19", deadlineLabel: "September 19, 2026", applicationRound: "2026–2027 academic year", benefitItems: [{ label: "Tuition support", included: true, note: "Varies by A/B/C tier" }, { label: "Accommodation support", included: true, note: "Varies by A/B/C tier" }], eligibilityItems: [{ label: "Status", value: "Self-funded international foundation, bachelor, master or doctoral student" }, { label: "No concurrent award", value: "Must not concurrently hold another Chinese government, social-organization or university scholarship, excluding one-time prizes" }, { label: "New entrant merit", value: "Published GPA/ranking thresholds differ for A versus B/C categories" }], applicationMaterials: [{ label: "Beijing Government Scholarship application form" }, { label: "Highest qualification and transcript", value: "For 2026 entrants" }, { label: "Language proof", value: "For 2026 entrants" }, { label: "Research or award evidence", value: "If applicable" }, { label: "Insurance payment proof" }], applicationSteps: [{ label: "Step 1", value: "Prepare the application form and evidence" }, { label: "Step 2", value: "Submit to the class adviser by September 19" }, { label: "Step 3", value: "USTB reviews and publishes the result" }], summary: "Current 2026–2027 Beijing municipal award administered by USTB for eligible self-funded students.", sortOrder: 50 }),
];

const schoolSource = meta("ustb-international-admission-guide-2026");
const bundle: CatalogSeedBundle = {
  version: 1, generatedAt: manifest.generatedAt,
  cities: [{ slug: "beijing", nameEn: "Beijing", nameZh: "北京", region: "North China", province: "Beijing", status: "active", ...schoolSource, sourceFieldLineage: { nameEn: "official USTB address", nameZh: "official USTB address", region: "CUAC normalized geographic region", province: "official USTB address" } }],
  schools: [{ slug: schoolSlug, nameEn: "University of Science and Technology Beijing", nameZh: "北京科技大学", citySlug: "beijing", schoolType: "Public", region: "Beijing, North China", applicationLevel: "Bachelor, Master, Doctoral", languageOfInstruction: "Chinese and English", languageRequirement: "Bachelor Chinese routes require HSK 4; graduate Chinese routes require HSK 5 for master and HSK 6 for doctoral admission. English routes require the published IELTS/TOEFL or equivalent proof.", hskRequirement: "Bachelor HSK 4; Master HSK 5; Doctoral HSK 6 for Chinese-taught admission routes.", englishRequirement: "Bachelor English routes: IELTS 5.5 or TOEFL 70; postgraduate English routes: IELTS 6 or TOEFL 80, or another official English certificate when applicable.", deadlineSummary: "2026 degree applications were open November 1, 2025–June 15, 2026; scholarship deadlines vary by award.", tuitionSummary: "Bachelor CNY 23,300/year; master CNY 31,600 Chinese or 37,600 English; doctoral CNY 41,600 Chinese or 47,600 English.", websiteUrl: "https://www.ustb.edu.cn/", admissionsUrl: applicationUrl, cscaRequirement: "All undergraduate applicants submit CSCA Mathematics; science/engineering/agriculture routes additionally require Physics or Chemistry, with the published Chinese-subject rule for Chinese-taught routes.", subjectTags: ["Materials Science and Engineering", "Metallurgical Engineering", "Mining Engineering", "Safety Science and Engineering", "Computer Science and Technology", "Environmental Science and Engineering", "Artificial Intelligence", "Management Science and Engineering"], languageTags: ["Chinese-taught", "English-taught"], tuitionBandLabel: "CNY 23,300–47,600/year", campusHighlights: ["Double First-Class university", "Materials science", "Metallurgy", "Mining engineering", "Beijing location"], status: "draft", ...schoolSource, sourceFieldLineage: { nameEn: "official university identity", nameZh: "official university identity", citySlug: "official address", schoolType: "official institutional profile", applicationLevel: "official 2026 program catalog", languageOfInstruction: "official 2026 English-taught program page and admission guide", deadlineSummary: "official 2026 application period", tuitionSummary: "official 2026 fee table", cscaRequirement: "official 2026 CSCA guide" } }],
  programs, programIntakes, scholarships,
};
const report = createCatalogMigrationValidationReport(bundle);
const degreeCounts = Object.fromEntries(["Bachelor", "Master", "Doctoral"].map((degree) => [degree, programs.filter((row) => row.degreeLevel === degree).length]));
const languageCounts = Object.fromEntries(["Chinese", "English"].map((language) => [language, programs.filter((row) => row.teachingLanguage === language).length]));
const lockedCounts = { undergraduateCatalogMajors: undergraduate.length, masterCatalogMajors: masters.length, doctoralCatalogMajors: doctorals.length, degreeCounts, languageCounts, totalPrograms: programs.length, intakes: programIntakes.length, scholarships: scholarships.length };
if (!report.ok || undergraduate.length !== 49 || masters.length !== 44 || doctorals.length !== 25 || programs.length !== 156 || programIntakes.length !== 156 || scholarships.length !== 5 || new Set(programs.map((row) => row.slug)).size !== programs.length) throw new Error(`Invalid USTB candidate: ${JSON.stringify({ errors: report.errors, lockedCounts })}`);
const candidatePath = resolve(root, "seeds/catalog.ustb-complete-batch-01.draft.json");
const validationPath = resolve(root, "seeds/catalog.ustb-complete-batch-01.validation.json");
const body = `${JSON.stringify(bundle, null, 2)}\n`;
await writeFile(candidatePath, body);
await writeFile(validationPath, `${JSON.stringify({ ...report, candidateSha256: createHash("sha256").update(body).digest("hex"), manifestSha256: createHash("sha256").update(manifestText).digest("hex"), lockedCounts }, null, 2)}\n`);
console.log(JSON.stringify({ ok: true, candidatePath, validationPath, counts: report.summary, lockedCounts, bundleSha256: report.bundleSha256, operationPlanSha256: report.operationPlanSha256 }, null, 2));
