import { createHash } from "node:crypto";
import { readFile, writeFile } from "node:fs/promises";
import { resolve } from "node:path";
import { createCatalogMigrationValidationReport, type CatalogSeedBundle } from "../src/server/catalog/seed-contract.ts";
import { createPostgresPool } from "../src/server/db/postgres-client.ts";
import { localDatabaseUrl } from "./lib/local-development.ts";

const root = process.cwd(), paths = { complete: resolve(root, "seeds/catalog.ouc-international-batch-01.draft.json"), completeReview: resolve(root, "seeds/catalog.ouc-international-batch-01.review.json"), safeApproval: resolve(root, "seeds/catalog.ouc-safe-new-batch-01.approval.json"), safePublication: resolve(root, "seeds/catalog.ouc-safe-new-batch-01.approved.local.json"), freshManifest: resolve(root, "work/catalog-official/ouc-refresh-without-two-large-pdfs-20260914/manifest.json"), candidate: resolve(root, "seeds/catalog.ouc-cleanup.draft.json"), validation: resolve(root, "seeds/catalog.ouc-cleanup.validation.json"), review: resolve(root, "seeds/catalog.ouc-cleanup.review.json"), state: resolve(root, ".cuac-local/runtime.json") };
const sha = (value: string | Buffer) => createHash("sha256").update(value).digest("hex"), read = async (path: string) => { const text = await readFile(path, "utf8"); return { text, value: JSON.parse(text) }; };
const [completeFile, completeReviewFile, safeApprovalFile, safePublicationFile, freshManifestFile, stateFile] = await Promise.all([paths.complete, paths.completeReview, paths.safeApproval, paths.safePublication, paths.freshManifest, paths.state].map(read));
const complete = completeFile.value as CatalogSeedBundle, completeReview = completeReviewFile.value, safeApproval = safeApprovalFile.value, safePublication = safePublicationFile.value as CatalogSeedBundle, freshManifest = freshManifestFile.value, state = stateFile.value, schoolSlug = "ocean-university-of-china";
if (complete.cities?.length !== 1 || complete.schools?.length !== 1 || complete.schools[0].slug !== schoolSlug || safeApproval.programSlugs?.length !== 8 || safeApproval.scholarshipSlugs?.length !== 3 || safePublication.programs?.length !== 8 || freshManifest.sources?.length !== 15) throw new Error("OUC cleanup dependencies changed.");
const safeSet = new Set(safeApproval.programSlugs), stablePrograms = complete.programs?.filter((row) => !safeSet.has(row.slug)) ?? [], stableSet = new Set(stablePrograms.map((row) => row.slug)), stableIntakes = complete.programIntakes?.filter((row) => stableSet.has(row.programSlug)) ?? [];
if (stablePrograms.length !== 2 || stableIntakes.length !== 2) throw new Error("OUC cleanup stable route count changed.");
const plannedProgramArchive = completeReview.reconciliation?.archives?.find((row: any) => row.entityType === "program"), plannedScholarshipArchive = completeReview.reconciliation?.archives?.find((row: any) => row.entityType === "scholarship"); if (!plannedProgramArchive || !plannedScholarshipArchive) throw new Error("OUC archive plan is unavailable.");
const pool = createPostgresPool({ databaseUrl: localDatabaseUrl(state), max: 1, applicationName: "cuac:ouc-cleanup-review" }); let baseline: any;
try {
  const school = await pool.query("select id,slug,status,verification_status from schools where slug=$1", [schoolSlug]), city = await pool.query("select id,slug,status,verification_status from cities where slug='qingdao'"), stable = await pool.query("select id,slug,status,verification_status from programs where slug=any($1::text[]) order by slug", [[...stableSet]]), safePrograms = await pool.query("select slug,status,verification_status,last_verified_at from programs where slug=any($1::text[]) order by slug", [safeApproval.programSlugs]), safeScholarships = await pool.query("select slug,status,verification_status,last_verified_at from scholarships where slug=any($1::text[]) order by slug", [safeApproval.scholarshipSlugs]), activePrograms = await pool.query("select id,slug,status,verification_status from programs where school_id=$1 and status='active' order by slug", [school.rows[0]?.id]), activeScholarships = await pool.query("select id,slug,status,verification_status from scholarships where school_id=$1 and status='active' order by slug", [school.rows[0]?.id]);
  baseline = { school: school.rows, city: city.rows, stable: stable.rows, safePrograms: safePrograms.rows, safeScholarships: safeScholarships.rows, activePrograms: activePrograms.rows, activeScholarships: activeScholarships.rows };
  if (school.rows.length !== 1 || school.rows[0].status !== "active" || school.rows[0].verification_status !== "unverified" || city.rows.length !== 1 || city.rows[0].status !== "active" || stable.rows.length !== 2 || stable.rows.some((row: any) => row.verification_status !== "unverified")) throw new Error("OUC school/stable baseline changed.");
  if (safePrograms.rows.length !== 8 || safeScholarships.rows.length !== 3 || [...safePrograms.rows, ...safeScholarships.rows].some((row: any) => row.status !== "active" || row.verification_status !== "verified" || row.last_verified_at?.toISOString() !== safeApproval.approvedAt) || activePrograms.rows.length !== 21 || activeScholarships.rows.length !== 4) throw new Error("OUC safe publication changed.");
} finally { await pool.end(); }
const programAlias = baseline.activePrograms.find((row: any) => row.id === plannedProgramArchive.id && row.slug === plannedProgramArchive.slug), scholarshipAlias = baseline.activeScholarships.find((row: any) => row.id === plannedScholarshipArchive.id && row.slug === plannedScholarshipArchive.slug); if (!programAlias || !scholarshipAlias || programAlias.verification_status !== "unverified" || scholarshipAlias.verification_status !== "unverified") throw new Error("OUC legacy aliases changed.");
const retainedLegacyPrograms = baseline.activePrograms.filter((row: any) => !safeSet.has(row.slug) && !stableSet.has(row.slug) && row.id !== programAlias.id); if (retainedLegacyPrograms.length !== 10) throw new Error("OUC retained legacy program set changed.");
const candidate: CatalogSeedBundle = { version: 1, generatedAt: freshManifest.generatedAt, cities: complete.cities, schools: complete.schools, programs: stablePrograms, programIntakes: stableIntakes, scholarships: [] }, candidateText = `${JSON.stringify(candidate, null, 2)}\n`, validation = createCatalogMigrationValidationReport(candidate); if (!validation.ok) throw new Error(`OUC cleanup validation failed: ${validation.errors.join(" ")}`);
const reviewBase = { version: 1, status: "requires_explicit_approval", generatedAt: candidate.generatedAt, scope: { schoolSlug, cityDependencyReplayCount: 1, schoolOverwriteCount: 1, stableProgramOverwriteCount: 2, programIntakeUpsertCount: 2, archiveProgramAliasCount: 1, archiveScholarshipAliasCount: 1, retainedLegacyProgramCount: 10, verifiedSafeProgramMutationCount: 0, verifiedSafeScholarshipMutationCount: 0 }, candidateSha256: sha(candidateText), candidateBundleSha256: validation.bundleSha256, operationPlanSha256: validation.operationPlanSha256, evidence: { freshManifestSha256: sha(freshManifestFile.text), freshOfficialSourceCount: 15, completeReviewSha256: sha(completeReviewFile.text), safeApprovalSha256: sha(safeApprovalFile.text), safePublicationSha256: sha(safePublicationFile.text) }, reconciliation: { destructiveDeletion: false, overwrite: [{ entityType: "school", id: baseline.school[0].id, slug: schoolSlug }, ...baseline.stable.map((row: any) => ({ entityType: "program", id: row.id, slug: row.slug }))], archives: [{ entityType: "program", id: programAlias.id, slug: programAlias.slug }, { entityType: "scholarship", id: scholarshipAlias.id, slug: scholarshipAlias.slug }], retainedLegacyProgramSlugs: retainedLegacyPrograms.map((row: any) => row.slug), protectedSafeProgramSlugs: safeApproval.programSlugs, protectedSafeScholarshipSlugs: safeApproval.scholarshipSlugs, databaseBaseline: { schoolId: baseline.school[0].id, cityId: baseline.city[0].id, stableProgramIds: baseline.stable.map((row: any) => row.id) } }, sourceReview: { result: "pass", note: "Fifteen official OUC sources were refreshed unchanged; every school and stable-route field in this cleanup remains bound to reviewed official evidence." }, visualReview: completeReview.visualReview, sensitiveDataCheck: { result: "pass", scope: "school profile, two stable programs and two archive status changes", note: "Only public catalog data is present. Applicant, account, payment, bank, staff-name and personal-contact data are excluded." }, reviewNotes: ["Eight verified programs and three rich scholarships are protected and will not be rewritten.", "Ten unrelated legacy Chinese-taught programs remain active and unmodified pending a later official-language catalog batch.", "The shared Qingdao city dependency is resolved without an update.", "The two aliases are status-archived, not deleted."] };
const reviewHash = sha(JSON.stringify(reviewBase)), requiredApproval = `批准完成中国海洋大学英文国际项目第一批清理（审核哈希 ${reviewHash}），覆盖学校及 2 条同名旧项目，并归档 1 条错误项目别名及 1 条旧奖学金合并概览`;
await Promise.all([writeFile(paths.candidate, candidateText, "utf8"), writeFile(paths.validation, `${JSON.stringify(validation, null, 2)}\n`, "utf8"), writeFile(paths.review, `${JSON.stringify({ ...reviewBase, reviewHash, requiredApproval }, null, 2)}\n`, "utf8")]); console.log(JSON.stringify({ ok: true, reviewHash, requiredApproval, scope: reviewBase.scope, paths }, null, 2));
