import { createHash } from "node:crypto";
import { readFile, writeFile } from "node:fs/promises";
import { resolve } from "node:path";
import { createPostgresPool, createTransactionalSqlClient } from "../src/server/db/postgres-client.ts";
import { localDatabaseUrl } from "./lib/local-development.ts";

const options=new Map(process.argv.slice(2).map((arg)=>{const at=arg.indexOf("=");if(!arg.startsWith("--")||at<0)throw new Error(`Option requires value: ${arg}`);return[arg.slice(2,at),arg.slice(at+1)];}));
const required=(name:string)=>{const value=options.get(name)?.trim();if(!value)throw new Error(`Missing --${name}=...`);return value;};
const approvedHash=required("review-hash"),reviewReference=required("review"),approvedAt=required("approved-at");if(!/^[a-f0-9]{64}$/.test(approvedHash)||Number.isNaN(Date.parse(approvedAt)))throw new Error("Invalid approval parameters.");
const root=process.cwd(),paths={review:resolve(root,"seeds/catalog.beihang-scholarships-legacy-archive.review.json"),audit:resolve(root,"seeds/catalog.beihang-scholarships-legacy-archive.approval.json"),state:resolve(root,".cuac-local/runtime.json")},sha=(value:string)=>createHash("sha256").update(value).digest("hex");
const [reviewText,stateText]=await Promise.all([readFile(paths.review,"utf8"),readFile(paths.state,"utf8")]),review=JSON.parse(reviewText),state=JSON.parse(stateText),{reviewHash,requiredApproval,...reviewBase}=review;
if(reviewHash!==approvedHash||sha(JSON.stringify(reviewBase))!==approvedHash||requiredApproval!==reviewReference||review.status!=="requires_explicit_approval"||review.scope?.archiveScholarshipAliasCount!==1||review.scope?.insertCount!==0||review.scope?.overwriteCount!==0||review.reconciliation?.destructiveDeletion!==false)throw new Error("Approved archive review does not match the stored operation.");
const pool=createPostgresPool({databaseUrl:localDatabaseUrl(state),max:1,applicationName:"cuac:beihang-scholarships-legacy-archive-publish"});let result:any;
try{const client=createTransactionalSqlClient(pool);result=await client.transaction(async(tx)=>{
 const school=await tx.query<{id:string}>("select id from schools where slug='beihang-university' and status='active' and verification_status='verified'",[]);if(school.length!==1||school[0].id!==review.reconciliation.databaseBaseline.schoolId)throw new Error("Beihang school identity changed.");
 const legacy=await tx.query<{id:string;status:string;verification_status:string}>("select id,status,verification_status from scholarships where slug='beihang-university'",[]);if(legacy.length!==1||legacy[0].id!==review.reconciliation.databaseBaseline.legacyScholarshipId||![["active","unverified"],["archived","unverified"]].some(([status,verification])=>legacy[0].status===status&&legacy[0].verification_status===verification))throw new Error("Legacy scholarship no longer matches reviewed state.");
 if(legacy[0].status==="active")await tx.query("update scholarships set status='archived',updated_at=now() where id=$1 and status='active'",[legacy[0].id]);
 const totals=await tx.query<{active_count:string;verified_count:string;archived_legacy:string}>("select count(*) filter(where status='active')::text active_count,count(*) filter(where status='active' and verification_status='verified')::text verified_count,count(*) filter(where id=$2 and status='archived')::text archived_legacy from scholarships where school_id=$1",[school[0].id,legacy[0].id]);if(totals[0]?.active_count!=="11"||totals[0]?.verified_count!=="11"||totals[0]?.archived_legacy!=="1")throw new Error(`Beihang archive post-check failed: ${JSON.stringify(totals[0])}`);return totals[0];});}finally{await pool.end();}
const audit={version:1,approvedAt,reviewReference,approvedReviewSha256:approvedHash,operation:"archive-scholarship-alias",schoolSlug:"beihang-university",archivedSlug:"beihang-university",physicalDeletion:false,result};const body=`${JSON.stringify(audit,null,2)}\n`;try{await writeFile(paths.audit,body,{encoding:"utf8",flag:"wx"});}catch(error:any){if(error?.code!=="EEXIST")throw error;if(await readFile(paths.audit,"utf8")!==body)throw new Error("Existing archive audit differs.");}console.log(JSON.stringify({ok:true,auditPath:paths.audit,...result},null,2));
