import { createHash } from "node:crypto";
import { readFile, writeFile } from "node:fs/promises";
import { resolve } from "node:path";
import { createCatalogMigrationValidationReport, type CatalogSeedBundle } from "../src/server/catalog/seed-contract.ts";
import { createPostgresPool } from "../src/server/db/postgres-client.ts";
import { localDatabaseUrl } from "./lib/local-development.ts";

const root=process.cwd(),paths={complete:resolve(root,"seeds/catalog.ustc-complete-batch-01.draft.json"),base:resolve(root,"seeds/catalog.cscalite-online-20260910.published.json"),manifest:resolve(root,"work/catalog-official/ustc-complete-batch-01/manifest.json"),candidate:resolve(root,"seeds/catalog.ustc-safe-new-batch-01.draft.json"),validation:resolve(root,"seeds/catalog.ustc-safe-new-batch-01.validation.json"),review:resolve(root,"seeds/catalog.ustc-safe-new-batch-01.review.json"),state:resolve(root,".cuac-local/runtime.json")};
const sha=(value:string|Buffer)=>createHash("sha256").update(value).digest("hex");
const [completeText,baseText,manifestText,stateText]=await Promise.all([readFile(paths.complete,"utf8"),readFile(paths.base,"utf8"),readFile(paths.manifest,"utf8"),readFile(paths.state,"utf8")]);
const complete=JSON.parse(completeText) as CatalogSeedBundle,base=JSON.parse(baseText) as CatalogSeedBundle,manifest=JSON.parse(manifestText),state=JSON.parse(stateText),schoolSlug="university-of-science-and-technology-of-china";
const dependencySchool=(base.schools??[]).find((row)=>row.slug===schoolSlug),dependencyCity=(base.cities??[]).find((row)=>row.slug==="hefei");
if(!dependencySchool||!dependencyCity)throw new Error("Original USTC dependency rows are unavailable.");
if(complete.programs?.length!==287||complete.programIntakes?.length!==287||complete.scholarships?.length!==5)throw new Error("Complete USTC candidate scope changed.");
if(manifest.sources?.length!==14||manifest.sources.some((row:any)=>row.status!==200||!/^[a-f0-9]{64}$/.test(row.sha256)))throw new Error("USTC evidence manifest changed.");
const candidateRaw:CatalogSeedBundle={version:1,generatedAt:complete.generatedAt,cities:[dependencyCity],schools:[dependencySchool],programs:complete.programs,programIntakes:complete.programIntakes,scholarships:complete.scholarships};
const candidateText=`${JSON.stringify(candidateRaw,null,2)}\n`,candidate=JSON.parse(candidateText) as CatalogSeedBundle,validation=createCatalogMigrationValidationReport(candidate);
if(!validation.ok)throw new Error(`Invalid USTC safe-new candidate: ${validation.errors.join(" ")}`);
const programSlugs=candidate.programs!.map((row)=>row.slug),scholarshipSlugs=candidate.scholarships!.map((row)=>row.slug),pool=createPostgresPool({databaseUrl:localDatabaseUrl(state),max:1,applicationName:"cuac:ustc-safe-new-review"});let baseline:any;
try{
 const school=await pool.query("select id,status,verification_status,source_url from schools where slug=$1",[schoolSlug]),city=await pool.query("select id,status,verification_status,source_url from cities where slug='hefei'"),programs=await pool.query("select id,slug from programs where school_id=$1 and status='active'",[school.rows[0]?.id]),scholarships=await pool.query("select id,slug,status,verification_status,source_url from scholarships where school_id=$1 order by slug",[school.rows[0]?.id]),programConflicts=await pool.query("select slug from programs where slug=any($1::text[])",[programSlugs]),scholarshipConflicts=await pool.query("select slug from scholarships where slug=any($1::text[])",[scholarshipSlugs]);
 baseline={school:school.rows,city:city.rows,programs:programs.rows,scholarships:scholarships.rows,programConflicts:programConflicts.rows,scholarshipConflicts:scholarshipConflicts.rows};
 if(school.rows.length!==1||school.rows[0].status!=="active"||school.rows[0].verification_status!=="unverified"||city.rows.length!==1||programs.rows.length!==0||scholarships.rows.length!==3||programConflicts.rows.length!==0||scholarshipConflicts.rows.length!==0)throw new Error(`USTC safe-new baseline changed: ${JSON.stringify(baseline)}`);
 if(scholarships.rows.some((row:any)=>row.status!=="active"||row.verification_status!=="unverified"))throw new Error("USTC legacy scholarships changed.");
}finally{await pool.end();}
const reviewBase={version:1,status:"standing_user_approval",generatedAt:candidate.generatedAt,scope:{schoolSlug,dependencyCityReplayCount:1,dependencySchoolReplayCount:1,newProgramRouteCount:287,newProgramIntakeCount:287,newScholarshipCount:5,overwriteCount:0,archiveCount:0},candidateSha256:sha(candidateText),candidateBundleSha256:validation.bundleSha256,operationPlanSha256:validation.operationPlanSha256,manifestSha256:sha(manifestText),evidence:manifest.sources.map((row:any)=>({sourceId:row.id,sourceUrl:row.finalUrl,sourceLabel:row.label,sha256:row.sha256,fetchedAt:row.fetchedAt,contentType:row.contentType})),standingAuthorization:{reference:"user-chat-2026-09-13-default-publication",instruction:"发布默认允许",appliesBecause:"The batch inserts 287 new non-conflicting official program routes, 287 intakes and five new rich scholarships. It does not overwrite, archive or delete catalog content; the original Hefei and USTC dependency rows are replayed from their published seed."},reconciliation:{destructiveDeletion:false,overwrites:[],archives:[],programSlugConflicts:0,scholarshipSlugConflicts:0,legacyScholarshipsDeferred:baseline.scholarships.map((row:any)=>({id:row.id,slug:row.slug})),databaseBaseline:{schoolId:baseline.school[0].id,cityId:baseline.city[0].id}},sourceReview:{result:"pass",note:"Fourteen exact registered USTC official sources and their stored hashes back the program, admissions and scholarship fields. Eleven image-based postgraduate catalog pages were previously rendered and reviewed."},coverageLimitations:["This safe-new batch does not replace the unverified school profile and does not archive the three legacy scholarship summaries.","The official undergraduate detail page enumerates 35 programs although the overview says 38; only the 35 named programs are published.","The 287 records are degree/language application routes; language variants are intentionally distinct."],sensitiveDataCheck:{result:"pass",scope:"publication candidate",note:"Public institutional, program, admissions and scholarship data only. Applicant, payment, account and personal-contact data are excluded."}};
const reviewHash=sha(JSON.stringify(reviewBase));
await Promise.all([writeFile(paths.candidate,candidateText,"utf8"),writeFile(paths.validation,`${JSON.stringify(validation,null,2)}\n`,"utf8"),writeFile(paths.review,`${JSON.stringify({...reviewBase,reviewHash,publicationReference:"standing-user-default-publication"},null,2)}\n`,"utf8")]);
console.log(JSON.stringify({ok:true,reviewHash,scope:reviewBase.scope,paths},null,2));
