import { createHash } from "node:crypto";
import { readFile, writeFile } from "node:fs/promises";
import { resolve } from "node:path";
import { createCatalogMigrationValidationReport, type CatalogSeedBundle, type CatalogSeedScholarship } from "../src/server/catalog/seed-contract.ts";

const root = process.cwd();
const manifestPaths = [
  resolve(root, "work/catalog-official/heu-complete-batch-01/manifest.json"),
  resolve(root, "work/catalog-official/heu-pdf-batch-01/manifest.json"),
];
const manifestTexts = await Promise.all(manifestPaths.map((path) => readFile(path, "utf8")));
const manifests = manifestTexts.map((text) => JSON.parse(text));
const sources = new Map(manifests.flatMap((manifest) => manifest.sources).map((row: any) => [row.id, row]));
const requiredSourceIds = [
  "heu-international-home", "heu-undergraduate-guide-2026", "heu-graduate-guide-2026", "heu-admission-handbook-page-2026",
  "heu-cgs-bilateral-current", "heu-cgs-high-level-graduate-current", "heu-marine-scholarship-current",
  "heu-eurasian-countries-scholarship-2026", "heu-university-scholarship-current", "heu-corporate-scholarship-current",
  "heu-international-chinese-language-teachers-scholarship-2025", "heu-atomic-energy-scholarship-2026",
  "heu-silk-road-scholarship-page-2026-2027", "heu-admission-handbook-pdf-2026",
  "heu-silk-road-scholarship-pdf-2026-2027", "heu-atomic-energy-scholarship-pdf-2026",
  "heu-international-chinese-language-teachers-scholarship-pdf-2025",
];
for (const id of requiredSourceIds) {
  const source: any = sources.get(id);
  if (!source || source.status !== 200 || !/^[a-f0-9]{64}$/.test(source.sha256)) throw new Error(`Missing valid source: ${id}`);
}
const meta = (id: string) => {
  const source: any = sources.get(id);
  return { sourceUrl: source.finalUrl, sourceLabel: source.label, sourceSha256: source.sha256, capturedAt: source.fetchedAt };
};
const slugify = (value: string) => value.toLowerCase().normalize("NFKD").replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");
const schoolSlug = "harbin-engineering-university";
const applicationUrl = "https://hrbeu.at0086.cn/student";
type Major = [college: string, name: string];
const undergraduates: Major[] = [
  ["College of Shipbuilding Engineering", "Naval Architecture and Ocean Engineering"],
  ["College of Aerospace and Civil Engineering", "Civil Engineering"],
  ["College of Power and Energy Engineering", "Energy and Power Engineering"], ["College of Power and Energy Engineering", "Marine Engineering"],
  ["College of Intelligent Systems Science and Engineering", "Artificial Intelligence"], ["College of Intelligent Systems Science and Engineering", "Electrical Engineering and Automation"], ["College of Intelligent Systems Science and Engineering", "Measurement Control Technology and Instruments"], ["College of Intelligent Systems Science and Engineering", "Automation"], ["College of Intelligent Systems Science and Engineering", "Robotics Engineering"],
  ["College of Underwater Acoustic Engineering", "Underwater Acoustics Engineering"], ["College of Underwater Acoustic Engineering", "Electronic Information Engineering (Underwater Acoustics)"], ["College of Underwater Acoustic Engineering", "Marine Information Engineering"],
  ["College of Computer Science and Technology", "Computer Science and Technology"], ["College of Computer Science and Technology", "Information Security"], ["College of Computer Science and Technology", "Software Engineering"],
  ["College of Mechanical and Electrical Engineering", "Mechanical Design & Manufacturing and Their Automation"], ["College of Mechanical and Electrical Engineering", "Industrial Design"], ["College of Mechanical and Electrical Engineering", "Intelligent Manufacturing Engineering"],
  ["College of Information and Communication Engineering", "Electronic Information Engineering"], ["College of Information and Communication Engineering", "Communications Engineering"],
  ["School of Economics and Management", "Business Administration"], ["School of Economics and Management", "Big Data Management and Application"],
  ["College of Materials Science and Chemical Engineering", "Materials Science and Engineering"], ["College of Materials Science and Chemical Engineering", "Chemical Engineering and Technology"], ["College of Materials Science and Chemical Engineering", "New Energy Materials and Devices"],
  ["College of Mathematical Sciences", "Mathematics and Applied Mathematics"], ["College of Physics and Optoelectronic Engineering", "Applied Physics"], ["College of Physics and Optoelectronic Engineering", "Opto-Electronics Information Science and Technology"],
  ["School of Foreign Studies", "English"], ["College of Humanities and Social Sciences", "Law"], ["College of Humanities and Social Sciences", "Sociology"],
  ["College of International Cooperative Education", "Chinese Language and Literature"], ["College of Nuclear Science and Technology", "Nuclear Energy Engineering and Technology"], ["College of Nuclear Science and Technology", "Nuclear Chemical and Fuel Engineering"], ["College of Marxism", "Ideological and Political Education"],
];
const undergraduateEnglish = new Set(["Civil Engineering", "Artificial Intelligence", "Robotics Engineering", "Computer Science and Technology", "Electronic Information Engineering"]);
type Graduate = [college: string, name: string, language: "Chinese" | "English", master: boolean, doctoral: boolean];
const graduates: Graduate[] = [
  ["College of Shipbuilding Engineering", "Design and Construction of Naval Architecture and Ocean Structure", "English", true, true], ["College of Shipbuilding Engineering", "Mechanics", "English", true, true],
  ["College of Aerospace and Civil Engineering", "Civil Engineering", "English", true, false], ["College of Aerospace and Civil Engineering", "Mechanics", "English", true, true],
  ["College of Power and Energy Engineering", "Power Engineering and Engineering Thermophysics", "English", true, true], ["College of Power and Energy Engineering", "Marine Engine Engineering", "English", true, true],
  ["College of Intelligent Systems Science and Engineering", "Control Science and Engineering", "English", true, true], ["College of Intelligent Systems Science and Engineering", "Intelligent Science and Technology", "English", true, true], ["College of Intelligent Systems Science and Engineering", "Electrical Engineering", "Chinese", true, false],
  ["College of Underwater Acoustic Engineering", "Underwater Acoustics Engineering", "English", true, true], ["College of Underwater Acoustic Engineering", "Information and Communication Engineering", "English", true, true],
  ["College of Computer Science and Technology", "Computer Science and Technology", "Chinese", true, false], ["College of Computer Science and Technology", "Computer Science and Technology", "English", false, true],
  ["College of Mechanical and Electrical Engineering", "Mechanical Engineering", "English", true, true], ["College of Mechanical and Electrical Engineering", "Design Science", "Chinese", true, false],
  ["College of Information and Communication Engineering", "Information and Communication Engineering", "English", true, true], ["College of Information and Communication Engineering", "Electronic Science and Technology", "Chinese", true, false],
  ["School of Economics and Management", "Management Science and Engineering", "Chinese", true, true], ["School of Economics and Management", "Applied Economics", "Chinese", true, false], ["School of Economics and Management", "Business Administration", "Chinese", true, false],
  ["College of Materials Science and Chemical Engineering", "Chemical Engineering and Technology", "English", true, false], ["College of Materials Science and Chemical Engineering", "Materials Science and Engineering", "English", true, true],
  ["College of Mathematical Sciences", "Mathematics", "English", true, true], ["College of Physics and Optoelectronic Engineering", "Physics", "Chinese", true, false], ["College of Physics and Optoelectronic Engineering", "Optical Engineering", "English", true, true],
  ["School of Foreign Studies", "Foreign Language and Literature", "Chinese", true, false], ["School of Foreign Studies", "English Translation", "Chinese", true, false],
  ["College of Humanities and Social Sciences", "Law", "Chinese", true, false], ["College of Humanities and Social Sciences", "Sociology", "Chinese", true, false], ["College of Humanities and Social Sciences", "Applied Psychology", "Chinese", true, false],
  ["College of International Cooperative Education", "International Chinese Education", "Chinese", true, false], ["College of Nuclear Science and Technology", "Energy and Power (Nuclear Energy Engineering)", "English", true, false], ["College of Nuclear Science and Technology", "Nuclear Science and Technology", "English", false, true],
  ["College of Marxism", "Marxist Theory", "Chinese", true, true], ["Department of Physical Education", "Physical Education and Training", "Chinese", true, false],
];
type Degree = "Bachelor" | "Master" | "Doctoral";
type Language = "Chinese" | "English";
const routes: Array<{ college: string; name: string; degree: Degree; language: Language; sourceId: string }> = [];
for (const [college, name] of undergraduates) {
  routes.push({ college, name, degree: "Bachelor", language: "Chinese", sourceId: "heu-undergraduate-guide-2026" });
  if (undergraduateEnglish.has(name)) routes.push({ college, name, degree: "Bachelor", language: "English", sourceId: "heu-undergraduate-guide-2026" });
}
for (const [college, name, language, master, doctoral] of graduates) {
  if (master) routes.push({ college, name, degree: "Master", language, sourceId: "heu-graduate-guide-2026" });
  if (doctoral) routes.push({ college, name, degree: "Doctoral", language, sourceId: "heu-graduate-guide-2026" });
}
const seenSlugs = new Set<string>();
const programs = routes.map((route) => {
  const degreePart = route.degree === "Bachelor" ? "" : `${route.degree.toLowerCase()}-`;
  const languagePart = route.language === "English" ? "-english" : "";
  let slug = `${schoolSlug}-${degreePart}${slugify(route.name)}${languagePart}`;
  if (seenSlugs.has(slug)) slug = `${slug}-${slugify(route.college)}`;
  if (seenSlugs.has(slug)) throw new Error(`Duplicate HEU route slug: ${slug}`);
  seenSlugs.add(slug);
  const tuitionAmount = route.degree === "Bachelor"
    ? route.language === "Chinese" ? (route.name === "Chinese Language and Literature" ? 16000 : 17000) : route.name === "Civil Engineering" ? 45000 : route.name === "Artificial Intelligence" ? 22000 : undefined
    : route.language === "Chinese" ? (route.degree === "Master" ? 27000 : 35000) : route.degree === "Master" ? 33000 : 42000;
  const tuitionText = tuitionAmount ? `CNY ${tuitionAmount.toLocaleString("en-US")}/year` : "The official 2026 handbook does not publish a separate tuition amount for this English-taught bachelor route.";
  return {
    slug, schoolSlug, citySlug: "harbin", nameEn: route.language === "English" ? `${route.name} (English)` : route.name, nameZh: route.name,
    degreeLevel: route.degree, durationYears: route.degree === "Bachelor" ? 4 : route.degree === "Master" ? 3 : 4,
    fieldCategory: route.college, subjectArea: route.name, teachingLanguage: route.language,
    hskRequirement: route.language === "Chinese" ? (route.degree === "Bachelor" ? "HSK 4; Chinese Language Program applicants may use HSK 3 as published." : "HSK 5.") : "Not required for this published English-taught route.",
    englishRequirement: route.language === "English" ? "TOEFL 90 or IELTS 6.0 or above; the official guide also recognizes qualifying prior English-medium education." : "Not applicable to this published Chinese-taught route.",
    cscaRequirement: route.degree === "Bachelor" ? (route.college.includes("Economics") || route.college.includes("Humanities") || route.college.includes("Foreign") || route.college.includes("Marxism") || route.name === "Chinese Language and Literature" ? "2026 CSCA: Professional Chinese (Humanities) and Mathematics for arts/management routes." : "2026 CSCA: Mathematics and Physics for science and engineering routes.") : "No CSCA requirement is published for this graduate route.",
    ...(tuitionAmount ? { tuitionAmount, tuitionCurrency: "CNY", tuitionPeriod: "year" } : {}), tuitionText, displayTuition: tuitionText,
    scholarshipText: "HEU publishes Chinese Government, HEU, provincial, corporate and language-teacher scholarship routes; eligibility differs by award.",
    applicationUrl, applicationNote: `Official 2026 ${route.language.toLowerCase()}-taught ${route.degree.toLowerCase()} route.`, hasScholarship: true,
    badgeText: "Official 2026 route", displayGroup: route.degree, displayGroupLabel: `${route.language}-taught ${route.degree.toLowerCase()} programs`, status: "draft" as const,
    ...meta(route.sourceId), sourceFieldLineage: { nameEn: "official 2026 program table", nameZh: "official source publishes an English title; retained without inventing a translation", fieldCategory: "official college column", degreeLevel: "official degree column", teachingLanguage: "official language marker", durationYears: "official 2026 handbook", tuitionText: "official 2026 fees table", hskRequirement: "official application requirements", englishRequirement: "official application requirements", cscaRequirement: route.degree === "Bachelor" ? "official 2026 CSCA table" : "official graduate guide" },
  };
});
const programIntakes = programs.map((program) => ({
  programSlug: program.slug, intakeTerm: "Fall", intakeYear: 2026,
  deadlineDate: program.degreeLevel === "Bachelor" ? "2026-05-15T00:00:00Z" : "2026-04-30T00:00:00Z",
  deadlineLabel: program.degreeLevel === "Bachelor" ? "Final published bachelor round: May 15, 2026." : "Final published graduate round: April 30, 2026.",
  applicationRound: "2026 international degree admission", status: "closed" as const,
  ...meta(program.degreeLevel === "Bachelor" ? "heu-undergraduate-guide-2026" : "heu-graduate-guide-2026"), sourceFieldLineage: { deadlineDate: "official final application batch; normalized to ISO UTC", deadlineLabel: "official 2026 guide" },
}));

const scholarship = (sourceId: string, value: Omit<CatalogSeedScholarship, "sourceUrl" | "sourceLabel" | "sourceSha256" | "capturedAt" | "schoolSlug" | "status">): CatalogSeedScholarship => ({
  schoolSlug, status: "draft", providerLocation: "Harbin, Heilongjiang, China", targetCountries: [], targetRegions: [], ...meta(sourceId),
  actionLinks: [{ label: "Official scholarship source", url: meta(sourceId).sourceUrl, kind: "official-source" }, { label: "HEU application portal", url: applicationUrl, kind: "official-application" }],
  sourceFieldLineage: { title: "official notice title", fundingLevel: "official funding description", coverage: "official benefits section", applicableDegree: "official applicant categories", applicableProgram: "official program scope", eligibilityItems: "official eligibility section", applicationMaterials: "official application section or linked HEU handbook", applicationSteps: "official application procedure", deadlineLabel: "official deadline statement" }, ...value,
});
const standardMaterials = [{ label: "Passport photo page" }, { label: "Highest degree certificate and transcripts" }, { label: "Language proficiency certificate" }, { label: "Study plan" }, { label: "Physical examination record" }, { label: "No-criminal-record certificate" }];
const scholarships: CatalogSeedScholarship[] = [
  scholarship("heu-cgs-bilateral-current", { slug: "official-heu-cgs-type-a-bilateral", title: "Harbin Engineering University Chinese Government Scholarship — Type A Bilateral Program", nameZh: "哈尔滨工程大学中国政府奖学金国别双边项目（Type A）", type: "government", typeLabel: "Chinese Government Scholarship Type A", providerName: "Ministry of Education of the PRC / China Scholarship Council", providerNameEn: "Ministry of Education of the PRC / China Scholarship Council", fundingLevel: "Full or Partial", coverage: "Coverage is determined by the applicant's bilateral program and dispatching authority; HEU accepts sponsored degree and visiting categories.", applicableDegree: "Bachelor, Master, Doctoral and Visiting", applicableProgram: "Programs available under the applicant's home-country bilateral arrangement", amountText: "Award level and amount are determined by the bilateral arrangement.", deadlineLabel: "Dispatching-authority deadline is generally January to early April; HEU pre-admission request window is December 1 to February 28.", applicationRound: "Current Type A bilateral route", benefitItems: [{label:"Tuition and other support",included:true,note:"Full or partial award as determined by the bilateral arrangement"}], eligibilityItems: [{label:"Application channel",value:"Apply through the home-country dispatching authority; HEU does not directly accept the Type A scholarship application"},{label:"HEU admission eligibility",value:"Meet HEU international-student admission requirements"}], applicationMaterials: standardMaterials, applicationSteps: [{label:"Step 1",value:"Apply to the home-country dispatching authority and choose HEU"},{label:"Step 2",value:"If needed, request HEU pre-admission through the HEU Type A route"},{label:"Step 3",value:"Receive official admission documents through the dispatching authority"}], summary: "Official HEU Type A bilateral route; award scope varies by bilateral agreement.", sortOrder: 10 }),
  scholarship("heu-cgs-high-level-graduate-current", { slug: "official-heu-cgs-high-level-graduate", title: "Harbin Engineering University Chinese Government Scholarship — High-Level Graduate Program", nameZh: "哈尔滨工程大学中国政府奖学金高水平研究生项目", type: "government", typeLabel: "Chinese Government Scholarship", providerName: "Ministry of Education of the PRC / China Scholarship Council", providerNameEn: "Ministry of Education of the PRC / China Scholarship Council", fundingLevel: "Full", coverage: "Tuition, on-campus accommodation, comprehensive medical insurance and monthly living allowance.", applicableDegree: "Master and Doctoral", applicableProgram: "Published HEU graduate programs", amountText: "CNY 3,000/month master; CNY 3,500/month doctoral; insurance CNY 800/year", deadlineLabel: "Official maintained page states December 15 to January 31 of the following year; the page does not identify a specific cycle.", applicationRound: "Current maintained high-level graduate route", benefitItems: [{label:"Tuition",included:true},{label:"On-campus accommodation",included:true},{label:"Medical insurance",included:true,note:"CNY 800/year"},{label:"Monthly allowance",included:true,note:"CNY 3,000 master; CNY 3,500 doctoral"}], eligibilityItems: [{label:"Citizenship and health",value:"Non-Chinese national in good health"},{label:"Degree and age",value:"Master applicant with bachelor degree under 35; doctoral applicant with master degree under 40"},{label:"Academic performance",value:"At least 75/100 and good research ability"},{label:"No other scholarship",value:"Applicant should not apply for another scholarship"}], applicationMaterials: standardMaterials, applicationSteps: [{label:"Step 1",value:"Apply directly to HEU during the published window"},{label:"Step 2",value:"Submit complete materials as required by the official page"},{label:"Step 3",value:"Await university and CSC review"}], summary: "Full graduate Chinese Government Scholarship route on HEU's maintained official page.", sortOrder: 20 }),
  scholarship("heu-marine-scholarship-current", { slug: "official-heu-marine-scholarship-of-china", title: "Harbin Engineering University Marine Scholarship of China", nameZh: "哈尔滨工程大学中国政府海洋奖学金", type: "government", typeLabel: "Marine Scholarship of China", providerName: "State Oceanic Administration / Ministry of Education / China Scholarship Council", providerNameEn: "State Oceanic Administration / Ministry of Education / China Scholarship Council", fundingLevel: "Full", coverage: "Tuition, on-campus accommodation, living allowance and comprehensive medical insurance.", applicableDegree: "Master and Doctoral", applicableProgram: "Naval Architecture and Ocean Engineering and related specialties", amountText: "CNY 3,000/month master; CNY 3,500/month doctoral", deadlineLabel: "No application deadline is published on the maintained official page.", applicationRound: "Current maintained Marine Scholarship route", targetRegions: ["South China Sea coastal/island countries", "Indian Ocean coastal/island countries", "Pacific coastal/island countries", "African developing countries"], benefitItems: [{label:"Tuition",included:true},{label:"On-campus accommodation",included:true},{label:"Living allowance",included:true,note:"CNY 3,000 master; CNY 3,500 doctoral"},{label:"Medical insurance",included:true}], eligibilityItems: [{label:"Nationality scope",value:"Eligible coastal/island countries and African developing countries as published"},{label:"Degree and age",value:"Master applicant with bachelor degree usually under 35; doctoral applicant with master degree usually under 40"},{label:"Program fit",value:"Apply to NAOE or a related specialty; relevant-sector applicants receive priority"}], applicationMaterials: standardMaterials, applicationSteps: [{label:"Step 1",value:"Choose an eligible HEU NAOE-related graduate route"},{label:"Step 2",value:"Submit the scholarship and HEU application materials"},{label:"Step 3",value:"Await HEU and CSC review"}], summary: "Full marine-focused graduate scholarship for eligible coastal, island and African applicants.", sortOrder: 30 }),
  scholarship("heu-eurasian-countries-scholarship-2026", { slug: "official-2026-heilongjiang-eurasian-countries-scholarship-heu", title: "2026 Heilongjiang Scholarship Program for International Students from Eurasian Countries — HEU Route", nameZh: "2026年黑龙江省欧亚国家留学生奖学金（哈尔滨工程大学通道）", type: "government", typeLabel: "Heilongjiang Provincial Scholarship", providerName: "Ministry of Education of the PRC / Heilongjiang Province", providerNameEn: "Ministry of Education of the PRC / Heilongjiang Province", fundingLevel: "Full", coverage: "Tuition, accommodation, living expenses and comprehensive medical insurance.", applicableDegree: "Bachelor, Master and Doctoral", applicableProgram: "Programs offered by participating Heilongjiang institutions including HEU", amountText: "Full published fee coverage; the overview does not publish institution-specific cash amounts.", deadlineLabel: "The 2026 overview does not publish an HEU-specific application deadline.", applicationRound: "2026 Eurasian Countries Scholarship", targetCountries: ["Russia","Belarus","Ukraine","Georgia","Armenia","Kyrgyzstan","Uzbekistan","Tajikistan","Kazakhstan","Turkmenistan","Moldova","Azerbaijan","Mongolia"], benefitItems: [{label:"Tuition",included:true},{label:"Accommodation",included:true},{label:"Living expenses",included:true},{label:"Medical insurance",included:true}], eligibilityItems: [{label:"Nationality",value:"Citizen of one of the 13 Eurasian countries listed in the official 2026 overview"},{label:"Institution",value:"Apply through a participating Heilongjiang institution such as HEU"}], applicationMaterials: [{label:"See the participating institution's annual application requirements; the provincial overview does not enumerate HEU-specific materials"}], applicationSteps: [{label:"Step 1",value:"Confirm the annual HEU application route"},{label:"Step 2",value:"Submit HEU and scholarship materials under the institution's notice"}], summary: "Provincial full scholarship overview for 13 Eurasian countries; institution-specific quotas and procedure are not separately published on this page.", sortOrder: 40 }),
  scholarship("heu-university-scholarship-current", { slug: "official-heu-excellent-student-scholarship", title: "Harbin Engineering University Excellent Student Scholarship", nameZh: "哈尔滨工程大学优秀留学生奖学金", type: "university", typeLabel: "HEU Scholarship", providerName: "Harbin Engineering University", providerNameEn: "Harbin Engineering University", fundingLevel: "Full or Partial", coverage: "First class: full tuition plus living allowance; second class: full tuition; third class: 50% tuition. Visiting awards cover tuition for up to 12 months.", applicableDegree: "Bachelor, Master, Doctoral and Visiting", applicableProgram: "Published HEU degree and visiting programs", amountText: "First-class allowance: CNY 1,500/month bachelor; CNY 2,000/month master; CNY 3,000/month doctoral", deadlineLabel: "Detailed annual deadline is subject to HEU's annual application guideline.", applicationRound: "Current maintained HEU scholarship policy", benefitItems: [{label:"First class",included:true,note:"Full tuition plus monthly allowance by degree"},{label:"Second class",included:true,note:"Full tuition"},{label:"Third class",included:true,note:"50% tuition"},{label:"Visiting award",included:true,note:"Full tuition for up to 12 months"}], eligibilityItems: [{label:"Academic and conduct",value:"Good character, health, academic performance and communication skills"},{label:"Degree age limits",value:"Bachelor normally 25 or under; master 35 or under; doctoral 40 or under"},{label:"Research potential",value:"Postgraduate applicants must demonstrate academic and research potential"}], applicationMaterials: standardMaterials, applicationSteps: [{label:"Step 1",value:"Apply to an eligible HEU program"},{label:"Step 2",value:"Follow the annual HEU scholarship guideline"},{label:"Step 3",value:"Await HEU scholarship assessment"}], summary: "HEU's tiered tuition and stipend scholarship for degree and visiting students.", sortOrder: 50 }),
  scholarship("heu-university-scholarship-current", { slug: "official-heu-talent-based-scholarship", title: "Harbin Engineering University Talent-Based Scholarship", nameZh: "哈尔滨工程大学优秀人才奖学金", type: "university", typeLabel: "HEU Talent-Based Scholarship", providerName: "Harbin Engineering University", providerNameEn: "Harbin Engineering University", fundingLevel: "One-time Award", coverage: "One-time merit award for eligible first-year bachelor candidates.", applicableDegree: "Bachelor", applicableProgram: "HEU bachelor programs", amountText: "One-time CNY 5,000", deadlineLabel: "No separate application is required; assessment follows HEU admission and scholarship policy.", applicationRound: "Current maintained HEU talent scholarship policy", benefitItems: [{label:"One-time award",included:true,note:"CNY 5,000"}], eligibilityItems: [{label:"Talent",value:"High Chinese proficiency or outstanding cultural/sports achievements and strong overall competence"},{label:"No other award",value:"Must not hold a Chinese government, enterprise or other institutional scholarship"}], applicationMaterials: [{label:"No separate scholarship application; HEU assesses eligible first-year bachelor candidates"}], applicationSteps: [{label:"Step 1",value:"Apply for first-year HEU bachelor admission"},{label:"Step 2",value:"HEU assesses qualifying talent evidence"}], summary: "Non-application one-time talent award for eligible first-year bachelor candidates.", sortOrder: 60 }),
  scholarship("heu-corporate-scholarship-current", { slug: "official-2025-buminusa-heu-masters-scholarship", title: "2025 Buminusa–HEU Master's Scholarship", nameZh: "2025年 Buminusa—哈尔滨工程大学硕士奖学金", type: "enterprise", typeLabel: "Corporate Scholarship", providerName: "Bumi Nusantara Group / Harbin Engineering University", providerNameEn: "Bumi Nusantara Group / Harbin Engineering University", fundingLevel: "Full", coverage: "Tuition, on-campus accommodation, living allowance, transportation, X-visa fee, medical insurance and residence-permit fee.", applicableDegree: "Master", applicableProgram: "Published English-taught HEU STEM master's programs", amountText: "Approximate total value CNY 216,500 (about USD 30,310)", deadlineDate: "2025-05-15", deadlineLabel: "Application closed May 15, 2025; no 2026 replacement was published on the captured page.", applicationRound: "2025 corporate scholarship", targetCountries: ["Indonesia"], benefitItems: [{label:"Tuition",included:true},{label:"On-campus accommodation",included:true},{label:"Living allowance",included:true},{label:"Transport and immigration fees",included:true},{label:"Medical insurance",included:true}], eligibilityItems: [{label:"Nationality",value:"Indonesian citizen"},{label:"Academic and work background",value:"STEM bachelor degree and at least two years relevant work experience"},{label:"English",value:"IELTS 5.5 or TOEFL 79 minimum"},{label:"Age",value:"Under 35"}], applicationMaterials: standardMaterials, applicationSteps: [{label:"Step 1",value:"Complete the HEU online application"},{label:"Step 2",value:"Upload the seven published supporting documents"},{label:"Step 3",value:"Participate in screening and interview"}], summary: "Historical 2025 full corporate scholarship; retained with an explicit closed deadline because no newer official cycle was captured.", sortOrder: 70 }),
  scholarship("heu-international-chinese-language-teachers-scholarship-pdf-2025", { slug: "official-2025-heu-international-chinese-language-teachers-scholarship", title: "2025 Harbin Engineering University International Chinese Language Teachers Scholarship", nameZh: "2025年哈尔滨工程大学国际中文教师奖学金", type: "foundation", typeLabel: "International Chinese Language Teachers Scholarship", providerName: "Center for Language Education and Cooperation / Harbin Engineering University", providerNameEn: "Center for Language Education and Cooperation / Harbin Engineering University", fundingLevel: "Full", coverage: "Tuition, on-campus accommodation, living allowance except the four-week category, and comprehensive medical insurance.", applicableDegree: "Bachelor, Master and Non-degree Chinese study", applicableProgram: "International Chinese Language Education and the Chinese-language/culture categories published in the guide", amountText: "CNY 2,500/month bachelor, one-year and one-semester; CNY 3,000/month master", deadlineDate: "2025-10-31", deadlineLabel: "2025 deadlines: April 15, May 15, September 15 and October 31 by intake; all are closed.", applicationRound: "2025 language-teacher scholarship", benefitItems: [{label:"Tuition",included:true},{label:"On-campus accommodation",included:true},{label:"Living allowance",included:true,note:"Not included for four-week category; CNY 2,500 or 3,000 by category"},{label:"Medical insurance",included:true}], eligibilityItems: [{label:"Citizenship and age",value:"Non-Chinese citizen; generally age 16–35, with published exceptions"},{label:"Commitment",value:"Interested in Chinese-language teaching and related work"},{label:"Language",value:"Meet the category-specific HSK and HSKK thresholds"}], applicationMaterials: [{label:"Passport"},{label:"HSK/HSKK score reports"},{label:"Highest diploma and transcripts"},{label:"Recommending-institution reference"},{label:"Additional degree-category references where applicable"}], applicationSteps: [{label:"Step 1",value:"Confirm a recommending institution"},{label:"Step 2",value:"Apply in both HEU and the official scholarship systems"},{label:"Step 3",value:"Attend the online interview and monitor results"}], summary: "Complete 2025 HEU host-institution guide; displayed as a closed historical cycle until a newer official notice is captured.", sortOrder: 80 }),
  scholarship("heu-atomic-energy-scholarship-pdf-2026", { slug: "official-2026-heu-atomic-energy-scholarship", title: "Harbin Engineering University 2026–2027 Atomic Energy Scholarship Program of China", nameZh: "哈尔滨工程大学2026—2027学年中国政府原子能奖学金", type: "government", typeLabel: "Atomic Energy Scholarship of China", providerName: "China Atomic Energy Authority / Ministry of Education / China Scholarship Council", providerNameEn: "China Atomic Energy Authority / Ministry of Education / China Scholarship Council", fundingLevel: "Full", coverage: "Tuition, on-campus accommodation or published off-campus allowance, medical insurance and monthly living allowance.", applicableDegree: "Master and Doctoral", applicableProgram: "Energy and Power (Nuclear Energy Engineering) master's; Nuclear Science and Technology doctoral", amountText: "Master: CNY 3,000/month plus CNY 700 off-campus allowance where applicable; doctoral: CNY 3,500/month plus CNY 1,000 off-campus allowance where applicable", deadlineDate: "2026-03-31", deadlineLabel: "November 15, 2025 to March 31, 2026; closed.", applicationRound: "2026–2027 Atomic Energy Scholarship", benefitItems: [{label:"Tuition",included:true},{label:"Accommodation",included:true,note:"On campus covered; off-campus allowance CNY 700 master or CNY 1,000 doctoral per month"},{label:"Medical insurance",included:true,note:"CNY 800/person/year"},{label:"Living allowance",included:true,note:"CNY 3,000 master; CNY 3,500 doctoral"}], eligibilityItems: [{label:"Nationality",value:"Non-Chinese citizen from an emerging nuclear-power country"},{label:"Academic route",value:"Apply to the published nuclear-engineering master or doctoral route"},{label:"Degree and age",value:"Master applicant under 35 with bachelor degree; doctoral applicant under 40 with master degree"},{label:"English",value:"Written and spoken English proficiency; TOEFL 90 or IELTS 6.0 required when English is not the native language"}], applicationMaterials: standardMaterials, applicationSteps: [{label:"Step 1",value:"Apply in CSC Type B using HEU agency number 10217"},{label:"Step 2",value:"Apply in the HEU online system"},{label:"Step 3",value:"Complete qualification review and interview"},{label:"Step 4",value:"Monitor official HEU results by July 31, 2026"}], summary: "Fully documented 2026–2027 English-taught nuclear graduate scholarship.", sortOrder: 90 }),
  scholarship("heu-silk-road-scholarship-pdf-2026-2027", { slug: "official-2026-2027-heu-silk-road-scholarship", title: "Harbin Engineering University 2026–2027 Chinese Government Scholarship — Silk Road Program", nameZh: "哈尔滨工程大学2026—2027学年丝绸之路中国政府奖学金项目", type: "government", typeLabel: "Chinese Government Scholarship — Silk Road", providerName: "Ministry of Education of the PRC / China Scholarship Council", providerNameEn: "Ministry of Education of the PRC / China Scholarship Council", fundingLevel: "Full", coverage: "Tuition, on-campus accommodation, comprehensive medical insurance and monthly living allowance.", applicableDegree: "Master and Doctoral", applicableProgram: "Design and Construction of Naval Architecture and Ocean Structure; Power Engineering and Engineering Thermophysics; Control Science and Engineering; Information and Communication Engineering; Mechanics", amountText: "CNY 3,000/month master; CNY 3,500/month doctoral; insurance CNY 800/year", deadlineDate: "2026-05-20", deadlineLabel: "May 20, 2026; closed.", applicationRound: "2026–2027 Silk Road Scholarship", targetCountries: ["Russia","Pakistan","Thailand","Malaysia","Indonesia","Bangladesh","Nepal","Myanmar","Cambodia","Egypt","Algeria","Canada","Peru"], benefitItems: [{label:"Tuition",included:true},{label:"On-campus accommodation",included:true},{label:"Medical insurance",included:true,note:"CNY 800/year"},{label:"Living allowance",included:true,note:"CNY 3,000 master; CNY 3,500 doctoral"}], eligibilityItems: [{label:"Citizenship and health",value:"Non-Chinese citizen in good health"},{label:"Degree and age",value:"Master applicant with bachelor degree under 35; doctoral applicant with master degree under 40"},{label:"Language",value:"HSK 4 for Chinese-taught routes or IELTS 6.0 / TOEFL 90 for English-taught routes"},{label:"Academic result",value:"Average at least 75/100"},{label:"No other scholarship",value:"Applicant must not apply for another scholarship"}], applicationMaterials: [{label:"CSC and HEU online forms"},...standardMaterials,{label:"Two professor/associate-professor recommendation letters"},{label:"Guardian document if under 18"}], applicationSteps: [{label:"Step 1",value:"Apply in CSC Type B using HEU agency code 10217"},{label:"Step 2",value:"Complete the HEU online application"},{label:"Step 3",value:"Submit all materials before May 20, 2026"},{label:"Step 4",value:"Await HEU notification by July 31, 2026"}], summary: "Full 2026–2027 Silk Road graduate scholarship with five published majors and 13 target countries.", sortOrder: 100 }),
];

const schoolSource = meta("heu-admission-handbook-pdf-2026");
const bundle: CatalogSeedBundle = {
  version: 1, generatedAt: manifests[0].generatedAt,
  cities: [{ slug: "harbin", nameEn: "Harbin", nameZh: "哈尔滨", region: "Northeast China", province: "Heilongjiang", status: "active", ...schoolSource, sourceFieldLineage: { nameEn: "official HEU address", nameZh: "official HEU address", region: "CUAC normalized geographic region", province: "official HEU address" } }],
  schools: [{ slug: schoolSlug, nameEn: "Harbin Engineering University", nameZh: "哈尔滨工程大学", citySlug: "harbin", schoolType: "Public", region: "Harbin, Heilongjiang, Northeast China", applicationLevel: "Bachelor, Master, Doctoral", languageOfInstruction: "Chinese and English", languageRequirement: "Bachelor Chinese routes require HSK 4 (Chinese Language Program HSK 3); graduate Chinese routes require HSK 5. English routes require TOEFL 90 or IELTS 6.0 or qualifying English-medium education.", hskRequirement: "Bachelor HSK 4, with HSK 3 for the Chinese Language Program; graduate HSK 5.", englishRequirement: "TOEFL 90 or IELTS 6.0 or above, with published prior English-medium exemptions.", deadlineSummary: "Final 2026 bachelor round closed May 15; final graduate round closed April 30. Scholarship deadlines vary by award.", tuitionSummary: "Chinese bachelor CNY 16,000–17,000/year; published English bachelor amounts CNY 22,000 or 45,000; master CNY 27,000 Chinese or 33,000 English; doctoral CNY 35,000 Chinese or 42,000 English.", websiteUrl: "https://www.hrbeu.edu.cn/", admissionsUrl: applicationUrl, cscaRequirement: "2026 bachelor applicants submit CSCA: Mathematics and Physics for science/engineering; Professional Chinese (Humanities) and Mathematics for arts/management.", subjectTags: ["Naval Architecture","Ocean Engineering","Nuclear Science","Control Science","Underwater Acoustics","Power Engineering","Computer Science"], languageTags: ["Chinese-taught","English-taught"], tuitionBandLabel: "CNY 16,000–45,000/year where published", campusHighlights: ["Project 211 university","Double First-Class university","Shipbuilding and ocean engineering","Nuclear science and technology","Harbin Ice City location"], status: "draft", ...schoolSource, sourceFieldLineage: { nameEn: "official handbook identity", nameZh: "official handbook identity", citySlug: "official address", schoolType: "official institutional profile", applicationLevel: "official 2026 program tables", languageOfInstruction: "official program language columns", deadlineSummary: "official 2026 timelines", tuitionSummary: "official 2026 fees table", cscaRequirement: "official 2026 CSCA table" } }],
  programs, programIntakes, scholarships,
};
const report = createCatalogMigrationValidationReport(bundle);
const degreeCounts = Object.fromEntries(["Bachelor","Master","Doctoral"].map((degree) => [degree, programs.filter((row) => row.degreeLevel === degree).length]));
const languageCounts = Object.fromEntries(["Chinese","English"].map((language) => [language, programs.filter((row) => row.teachingLanguage === language).length]));
const lockedCounts = { undergraduateMajors: undergraduates.length, bachelorRoutes: degreeCounts.Bachelor, masterRoutes: degreeCounts.Master, doctoralRoutes: degreeCounts.Doctoral, chineseRoutes: languageCounts.Chinese, englishRoutes: languageCounts.English, totalPrograms: programs.length, intakes: programIntakes.length, scholarships: scholarships.length };
if (!report.ok || programs.length !== 91 || programIntakes.length !== 91 || scholarships.length !== 10 || seenSlugs.size !== programs.length) throw new Error(`Invalid HEU candidate: ${JSON.stringify({ errors: report.errors, lockedCounts })}`);
const candidatePath = resolve(root, "seeds/catalog.heu-complete-batch-01.draft.json");
const validationPath = resolve(root, "seeds/catalog.heu-complete-batch-01.validation.json");
const body = `${JSON.stringify(bundle, null, 2)}\n`;
await writeFile(candidatePath, body);
await writeFile(validationPath, `${JSON.stringify({ ...report, candidateSha256: createHash("sha256").update(body).digest("hex"), manifestSha256: createHash("sha256").update(manifestTexts.join("\n")).digest("hex"), lockedCounts }, null, 2)}\n`);
console.log(JSON.stringify({ ok: true, candidatePath, validationPath, counts: report.summary, lockedCounts, bundleSha256: report.bundleSha256, operationPlanSha256: report.operationPlanSha256 }, null, 2));
