import { createHash } from "node:crypto";
import { readFile, writeFile } from "node:fs/promises";
import { resolve } from "node:path";
import { CatalogSeedWriter } from "../src/server/catalog/seed-writer.ts";
import { createCatalogMigrationValidationReport, type CatalogSeedBundle } from "../src/server/catalog/seed-contract.ts";
import { assertLocalCatalogPublishTarget, LOCAL_CATALOG_PUBLISH_CONFIRMATION } from "../src/server/catalog/local-publish-safety.ts";
import { createPostgresPool, createTransactionalSqlClient } from "../src/server/db/postgres-client.ts";

const options = new Map(process.argv.slice(2).map(arg => { const at = arg.indexOf("="); if (!arg.startsWith("--") || at < 0) throw new Error(`Option requires a value: ${arg}`); return [arg.slice(2, at), arg.slice(at + 1)]; }));
const required = (name: string) => { const value = options.get(name)?.trim(); if (!value) throw new Error(`Missing --${name}=...`); return value; };
if ([...options.keys()].some(key => !new Set(["review-hash", "review", "approved-at", "confirm"]).has(key))) throw new Error("Unknown publication option.");
const approvedReviewHash = required("review-hash"); const reviewReference = required("review"); const approvedAt = required("approved-at"); const confirmation = required("confirm");
if (!/^[a-f0-9]{64}$/.test(approvedReviewHash) || !/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(?:\.\d{3})?Z$/.test(approvedAt) || Number.isNaN(Date.parse(approvedAt))) throw new Error("Invalid review hash or approval timestamp.");
if (confirmation !== LOCAL_CATALOG_PUBLISH_CONFIRMATION) throw new Error("Incorrect local catalog publication confirmation token.");
const root = process.cwd(); const paths = { candidate: resolve(root, "seeds/catalog.nankai-complete-batch-01.draft.json"), validation: resolve(root, "seeds/catalog.nankai-complete-batch-01.validation.json"), review: resolve(root, "seeds/catalog.nankai-complete-batch-01.review.json"), output: resolve(root, "seeds/catalog.nankai-complete-batch-01.approved.local.json"), approval: resolve(root, "seeds/catalog.nankai-complete-batch-01.approval.json"), state: resolve(root, ".cuac-local/runtime.json") };
const parse = async (path: string) => JSON.parse(await readFile(path, "utf8")); const hash = (value: string) => createHash("sha256").update(value).digest("hex");
const candidateText = await readFile(paths.candidate, "utf8"); const candidate = JSON.parse(candidateText) as CatalogSeedBundle; const validation = await parse(paths.validation); const review = await parse(paths.review); const state = await parse(paths.state);
const { reviewHash: storedHash, publicationReference: storedReference, ...reviewBase } = review;
if (storedHash !== approvedReviewHash || hash(JSON.stringify(reviewBase)) !== approvedReviewHash || storedReference !== reviewReference) throw new Error("Approved Nankai review hash/reference does not match the stored review.");
const candidateSha256 = hash(candidateText); const fresh = createCatalogMigrationValidationReport(candidate);
if (candidateSha256 !== review.candidateSha256 || !fresh.ok || !validation.ok || fresh.bundleSha256 !== review.candidateBundleSha256 || fresh.bundleSha256 !== validation.bundleSha256 || fresh.operationPlanSha256 !== review.operationPlanSha256 || fresh.operationPlanSha256 !== validation.operationPlanSha256) throw new Error("Nankai candidate or validation changed after review.");
if (review.status !== "awaiting_user_approval" || review.sensitiveDataCheck?.result !== "pass" || review.visualReview?.result !== "pass") throw new Error("Nankai candidate has not passed completed review.");
if (review.scope?.programRouteCount !== 339 || review.scope?.programIntakeCount !== 339 || review.scope?.scholarshipCount !== 2 || review.scope?.archiveProgramAliasCount !== 10 || review.scope?.archiveScholarshipAliasCount !== 1) throw new Error("Nankai review scope mismatch.");
const legacyPrograms: string[] = review.reconciliation?.legacyProgramAliasesToArchive; const legacyScholarships: string[] = review.reconciliation?.legacyScholarshipAliasesToArchive; const stableScholarships: string[] = review.reconciliation?.stableScholarshipUpdateSlugs;
if (legacyPrograms?.length !== 10 || legacyScholarships?.length !== 1 || legacyScholarships[0] !== "nankai-university" || stableScholarships?.length !== 1 || stableScholarships[0] !== "official-2026-nankai-silk-road-scholarship" || review.reconciliation?.destructiveDeletion !== false) throw new Error("Nankai reconciliation plan mismatch.");
const sourceSchemaSha256 = hash(JSON.stringify({ cityFields: [...new Set((candidate.cities ?? []).flatMap(row => Object.keys(row)))].sort(), schoolFields: [...new Set((candidate.schools ?? []).flatMap(row => Object.keys(row)))].sort(), programFields: [...new Set((candidate.programs ?? []).flatMap(row => Object.keys(row)))].sort(), intakeFields: [...new Set((candidate.programIntakes ?? []).flatMap(row => Object.keys(row)))].sort(), scholarshipFields: [...new Set((candidate.scholarships ?? []).flatMap(row => Object.keys(row)))].sort() }));
const publication: CatalogSeedBundle = { version: 2, generatedAt: approvedAt, handoff: { sourceSystem: "CUAC reviewed official Nankai University 2026 admissions, program and scholarship sources", cleanedExportName: "catalog.nankai-complete-batch-01.draft.json", cleanedExportSha256: fresh.bundleSha256, sourceSchemaSha256, reviewReference, prohibitedDataReviewReference: reviewReference, approvalRecordedAt: approvedAt, sourceReadOnly: true, prohibitedDataConfirmedExcluded: true }, cities: (candidate.cities ?? []).map(row => ({ ...row, status: "active" as const })), schools: (candidate.schools ?? []).map(row => ({ ...row, status: "active" as const, verificationStatus: "verified" as const, lastVerifiedAt: approvedAt })), programs: (candidate.programs ?? []).map(row => ({ ...row, status: "active" as const, verificationStatus: "verified" as const, lastVerifiedAt: approvedAt })), programIntakes: (candidate.programIntakes ?? []).map(row => ({ ...row, status: "closed" as const })), scholarships: (candidate.scholarships ?? []).map(row => ({ ...row, status: "active" as const, verificationStatus: "verified" as const, lastVerifiedAt: approvedAt })) };
const report = createCatalogMigrationValidationReport(publication); if (!report.ok || report.summary.cities !== 1 || report.summary.schools !== 1 || report.summary.programs !== 339 || report.summary.programIntakes !== 339 || report.summary.scholarships !== 2) throw new Error(`Invalid Nankai publication bundle: ${report.errors.join(" ")}`);
const approval = { version: 1, approvedAt, approvalMode: "explicit-product-owner-approval", reviewReference, approvedReviewSha256: approvedReviewHash, approvedCandidateFileSha256: candidateSha256, approvedCandidateBundleSha256: fresh.bundleSha256, publicationBundle: "seeds/catalog.nankai-complete-batch-01.approved.local.json", publicationBundleSha256: report.bundleSha256, schoolSlug: "nankai-university", programSlugs: publication.programs!.map(row => row.slug), scholarshipSlugs: publication.scholarships!.map(row => row.slug), archivedProgramAliases: legacyPrograms, archivedScholarshipAliases: legacyScholarships, updatedStableScholarships: stableScholarships, prohibitedDataConfirmedExcluded: true };
async function writeOrVerify(path: string, value: unknown) { const body = `${JSON.stringify(value, null, 2)}\n`; try { await writeFile(path, body, { encoding: "utf8", flag: "wx" }); } catch (error: any) { if (error?.code !== "EEXIST") throw error; if (await readFile(path, "utf8") !== body) throw new Error(`Existing artifact differs: ${path}`); } }
await writeOrVerify(paths.output, publication); await writeOrVerify(paths.approval, approval);
const target = assertLocalCatalogPublishTarget(state, publication, confirmation, reviewReference); const pool = createPostgresPool({ databaseUrl: target.databaseUrl, max: 1, applicationName: "cuac:nankai-complete-publish" });
try { const client = createTransactionalSqlClient(pool); const result = await client.transaction(async tx => {
  const identity = await tx.query<{ database_name: string; database_user: string }>("select current_database() database_name,current_user database_user", []); if (identity[0]?.database_name !== target.publicTarget.databaseName || identity[0]?.database_user !== target.publicTarget.databaseUser) throw new Error("Database identity mismatch.");
  const school = await tx.query<{ id: string; status: string; verification_status: string; source_url: string }>("select id,status,verification_status,source_url from schools where slug=$1", ["nankai-university"]); const city = await tx.query<{ id: string; status: string; source_url: string }>("select id,status,source_url from cities where slug=$1", ["tianjin"]); if (school.length !== 1 || school[0].id !== "c7ba4d24-a420-42aa-a37f-93bfd978cb18" || city.length !== 1 || city[0].id !== "530fec99-7fa2-4f49-8d29-ed730cefe175") throw new Error("Nankai/Tianjin identity mismatch.");
  const newProgramSlugs = publication.programs!.map(row => row.slug); const newScholarshipSlugs = publication.scholarships!.map(row => row.slug);
  const oldPrograms = await tx.query<{ slug: string; status: string; verification_status: string }>("select slug,status,verification_status from programs where slug=any($1::text[]) order by slug", [legacyPrograms]); const candidatePrograms = await tx.query<{ slug: string; status: string; verification_status: string; last_verified_at: Date | null }>("select slug,status,verification_status,last_verified_at from programs where slug=any($1::text[]) order by slug", [newProgramSlugs]); const oldScholarships = await tx.query<{ slug: string; status: string; verification_status: string; source_url: string; last_verified_at: Date | null }>("select slug,status,verification_status,source_url,last_verified_at from scholarships where slug=any($1::text[]) order by slug", [[...legacyScholarships, ...newScholarshipSlugs]]);
  const baseline = await tx.query<{ active_programs: string; active_intakes: string; active_scholarships: string }>("select (select count(*) from programs where school_id=$1 and status='active')::text active_programs,(select count(*) from program_intakes pi join programs p on p.id=pi.program_id where p.school_id=$1 and p.status='active')::text active_intakes,(select count(*) from scholarships where school_id=$1 and status='active')::text active_scholarships", [school[0].id]);
  const isPre = school[0].verification_status === "unverified" && school[0].source_url === "https://www.cscapilot.com/zh/schools" && city[0].source_url === "https://www.cscapilot.com/zh/study-china/cities/tianjin" && baseline[0]?.active_programs === "10" && baseline[0]?.active_intakes === "5" && baseline[0]?.active_scholarships === "2" && oldPrograms.length === 10 && oldPrograms.every(row => row.status === "active" && row.verification_status === "unverified") && candidatePrograms.length === 0 && oldScholarships.length === 2 && oldScholarships.some(row => row.slug === "nankai-university" && row.status === "active" && row.verification_status === "unverified") && oldScholarships.some(row => row.slug === "official-2026-nankai-silk-road-scholarship" && row.status === "active" && row.verification_status === "verified");
  const isPost = school[0].verification_status === "verified" && school[0].source_url === publication.schools![0].sourceUrl && city[0].source_url === publication.cities![0].sourceUrl && baseline[0]?.active_programs === "339" && baseline[0]?.active_intakes === "339" && baseline[0]?.active_scholarships === "2" && oldPrograms.length === 10 && oldPrograms.every(row => row.status === "archived") && candidatePrograms.length === 339 && candidatePrograms.every(row => row.status === "active" && row.verification_status === "verified" && row.last_verified_at?.toISOString() === approvedAt) && oldScholarships.some(row => row.slug === "nankai-university" && row.status === "archived") && oldScholarships.some(row => row.slug === "official-2026-nankai-silk-road-scholarship" && row.status === "active" && row.verification_status === "verified" && row.last_verified_at?.toISOString() === approvedAt);
  if (!isPre && !isPost) throw new Error(`Nankai database no longer matches reviewed pre-state or approved post-state: ${JSON.stringify({ school, city, baseline: baseline[0], oldPrograms: oldPrograms.length, candidatePrograms: candidatePrograms.length, oldScholarships })}`);
  const written = await new CatalogSeedWriter(tx).writeBundle(publication); if (!written.ok) throw new Error(`Catalog write failed: ${written.errors.join(" ")}`);
  await tx.query("update programs set status='archived',updated_at=now() where slug=any($1::text[]) and status='active'", [legacyPrograms]); await tx.query("update scholarships set status='archived',updated_at=now() where slug=any($1::text[]) and status='active'", [legacyScholarships]);
  const counts = await tx.query<{ undergraduate: string; master: string; doctoral: string; intakes: string; scholarships: string }>("select (select count(*) from programs where school_id=$1 and status='active' and degree_level='Undergraduate')::text undergraduate,(select count(*) from programs where school_id=$1 and status='active' and degree_level='Master')::text master,(select count(*) from programs where school_id=$1 and status='active' and degree_level='Doctoral')::text doctoral,(select count(*) from program_intakes pi join programs p on p.id=pi.program_id where p.school_id=$1 and p.status='active')::text intakes,(select count(*) from scholarships where school_id=$1 and status='active' and verification_status='verified')::text scholarships", [school[0].id]); if (counts[0]?.undergraduate !== "41" || counts[0]?.master !== "171" || counts[0]?.doctoral !== "127" || counts[0]?.intakes !== "339" || counts[0]?.scholarships !== "2") throw new Error(`Nankai post-publication counts mismatch: ${JSON.stringify(counts[0])}`);
  const archives = await tx.query<{ programs: string; scholarships: string }>("select (select count(*) from programs where slug=any($1::text[]) and status='archived')::text programs,(select count(*) from scholarships where slug=any($2::text[]) and status='archived')::text scholarships", [legacyPrograms, legacyScholarships]); if (archives[0]?.programs !== "10" || archives[0]?.scholarships !== "1") throw new Error("Nankai archive verification failed."); return { written, schoolId: school[0].id, counts: counts[0], archived: archives[0] };
}); console.log(JSON.stringify({ ok: true, target: target.publicTarget, approvedReviewSha256: approvedReviewHash, publicationBundleSha256: report.bundleSha256, approvalPath: paths.approval, outputPath: paths.output, ...result }, null, 2)); } finally { await pool.end(); }
