import { createHash } from "node:crypto";
import { readFile, writeFile } from "node:fs/promises";
import { resolve } from "node:path";
import { CatalogSeedWriter } from "../src/server/catalog/seed-writer.ts";
import { createCatalogMigrationValidationReport, type CatalogSeedBundle } from "../src/server/catalog/seed-contract.ts";
import { assertLocalCatalogPublishTarget, LOCAL_CATALOG_PUBLISH_CONFIRMATION } from "../src/server/catalog/local-publish-safety.ts";
import { createPostgresPool, createTransactionalSqlClient } from "../src/server/db/postgres-client.ts";

const options=new Map(process.argv.slice(2).map(arg=>{const at=arg.indexOf("=");if(!arg.startsWith("--")||at<0)throw new Error(`Option requires value: ${arg}`);return[arg.slice(2,at),arg.slice(at+1)];}));
const required=(name:string)=>{const value=options.get(name)?.trim();if(!value)throw new Error(`Missing --${name}=...`);return value;};
const approvedHash=required("review-hash"),reviewReference=required("review"),approvedAt=required("approved-at");
if(!/^[a-f0-9]{64}$/.test(approvedHash)||Number.isNaN(Date.parse(approvedAt)))throw new Error("Invalid approval parameters.");

const root=process.cwd(),schoolSlug="donghua-university",prefix="catalog.dhu-cleanup-batch-01";
const paths={candidate:resolve(root,`seeds/${prefix}.draft.json`),validation:resolve(root,`seeds/${prefix}.validation.json`),review:resolve(root,`seeds/${prefix}.review.json`),safeApproval:resolve(root,"seeds/catalog.dhu-safe-new-batch-01.approval.json"),output:resolve(root,`seeds/${prefix}.approved.local.json`),approval:resolve(root,`seeds/${prefix}.approval.json`),state:resolve(root,".cuac-local/runtime.json")};
const parse=async(path:string)=>JSON.parse(await readFile(path,"utf8")),sha=(value:string|Buffer)=>createHash("sha256").update(value).digest("hex");
const [candidateText,validation,review,safeApproval,state]=await Promise.all([readFile(paths.candidate,"utf8"),parse(paths.validation),parse(paths.review),parse(paths.safeApproval),parse(paths.state)]),candidate=JSON.parse(candidateText) as CatalogSeedBundle,{reviewHash,requiredApproval,...reviewBase}=review;
if(reviewHash!==approvedHash||sha(JSON.stringify(reviewBase))!==approvedHash||requiredApproval!==reviewReference||review.status!=="requires_explicit_approval")throw new Error("Approved DHU cleanup review does not match the stored operation.");
const fresh=createCatalogMigrationValidationReport(candidate);if(!fresh.ok||!validation.ok||sha(candidateText)!==review.candidateSha256||fresh.bundleSha256!==review.candidateBundleSha256||fresh.bundleSha256!==validation.bundleSha256||fresh.operationPlanSha256!==review.operationPlanSha256||fresh.operationPlanSha256!==validation.operationPlanSha256)throw new Error("DHU cleanup candidate changed after review.");
if(review.scope?.schoolOverwriteCount!==1||review.scope?.programOverwriteCount!==12||review.scope?.intakeOverwriteCount!==5||review.scope?.intakeInsertCount!==7||review.scope?.archiveCount!==0||review.scope?.deleteCount!==0||review.reconciliation?.destructiveDeletion!==false||review.sourceReview?.result!=="pass"||review.sensitiveDataCheck?.result!=="pass")throw new Error("DHU cleanup scope is invalid.");
if(candidate.schools?.length!==1||candidate.programs?.length!==12||candidate.programIntakes?.length!==7||candidate.scholarships?.length!==0||safeApproval.programSlugs?.length!==119||safeApproval.scholarshipSlugs?.length!==4)throw new Error("DHU cleanup or protected publication scope changed.");

const sourceSchemaSha256=sha(JSON.stringify({cityFields:[...new Set(candidate.cities!.flatMap(Object.keys))].sort(),schoolFields:[...new Set(candidate.schools!.flatMap(Object.keys))].sort(),programFields:[...new Set(candidate.programs!.flatMap(Object.keys))].sort(),intakeFields:[...new Set(candidate.programIntakes!.flatMap(Object.keys))].sort()}));
const publication:CatalogSeedBundle={version:2,generatedAt:approvedAt,handoff:{sourceSystem:"CUAC reviewed Donghua University official 2026 program PDFs and admissions pages",cleanedExportName:`${prefix}.draft.json`,cleanedExportSha256:fresh.bundleSha256,sourceSchemaSha256,reviewReference,prohibitedDataReviewReference:reviewReference,approvalRecordedAt:approvedAt,sourceReadOnly:true,prohibitedDataConfirmedExcluded:true},cities:candidate.cities!.map(row=>({...row,status:"active" as const})),schools:candidate.schools!.map(row=>({...row,status:"active" as const,verificationStatus:"verified" as const,lastVerifiedAt:approvedAt})),programs:candidate.programs!.map(row=>({...row,status:"active" as const,verificationStatus:"verified" as const,lastVerifiedAt:approvedAt})),programIntakes:candidate.programIntakes,scholarships:[]};
const report=createCatalogMigrationValidationReport(publication);if(!report.ok||report.summary.schools!==1||report.summary.programs!==12||report.summary.programIntakes!==7)throw new Error(`Invalid DHU cleanup publication: ${report.errors.join(" ")}`);
const programSlugs=publication.programs!.map(row=>row.slug),newIntakeProgramSlugs=publication.programIntakes!.map(row=>row.programSlug),legacyIds=new Map(review.reconciliation.overwrites.programs.map((row:any)=>[row.slug,row.id])),legacyIntakeIds=review.reconciliation.overwrites.intakes.map((row:any)=>row.id),safeProgramSlugs=safeApproval.programSlugs as string[],safeScholarshipSlugs=safeApproval.scholarshipSlugs as string[];
const approval={version:1,approvedAt,approvalMode:"explicit-user-approval",reviewReference,approvedReviewSha256:approvedHash,approvedCandidateFileSha256:sha(candidateText),approvedCandidateBundleSha256:fresh.bundleSha256,publicationBundle:`seeds/${prefix}.approved.local.json`,publicationBundleSha256:report.bundleSha256,schoolSlug,schoolId:review.reconciliation.databaseBaseline.school.id,updatedProgramSlugs:programSlugs,updatedIntakeIds:legacyIntakeIds,insertedIntakeProgramSlugs:newIntakeProgramSlugs,preservedIds:true,archivedAliases:[],physicalDeletion:false,prohibitedDataConfirmedExcluded:true};
async function writeOrVerify(path:string,value:unknown){const body=`${JSON.stringify(value,null,2)}\n`;try{await writeFile(path,body,{encoding:"utf8",flag:"wx"});}catch(error:any){if(error?.code!=="EEXIST")throw error;if(await readFile(path,"utf8")!==body)throw new Error(`Existing artifact differs: ${path}`);}}
await writeOrVerify(paths.output,publication);await writeOrVerify(paths.approval,approval);

const target=assertLocalCatalogPublishTarget(state,publication,LOCAL_CATALOG_PUBLISH_CONFIRMATION,reviewReference),pool=createPostgresPool({databaseUrl:target.databaseUrl,max:1,applicationName:"cuac:dhu-cleanup-publish"});
try{const client=createTransactionalSqlClient(pool);const result=await client.transaction(async tx=>{
  const schoolBefore=await tx.query<any>("select id,status,verification_status from schools where slug=$1",[schoolSlug]);if(schoolBefore.length!==1||schoolBefore[0].id!==review.reconciliation.databaseBaseline.school.id)throw new Error("DHU school identity changed.");
  const legacyBefore=await tx.query<any>("select id,slug,status,verification_status from programs where slug=any($1::text[]) order by slug",[programSlugs]);if(legacyBefore.length!==12||legacyBefore.some(row=>row.id!==legacyIds.get(row.slug)||row.status!=="active"||!["unverified","verified"].includes(row.verification_status)))throw new Error("DHU legacy program identities changed.");
  const oldIntakesBefore=await tx.query<any>("select id,program_id,intake_term,intake_year,status from program_intakes where id=any($1::uuid[]) order by id",[legacyIntakeIds]);if(oldIntakesBefore.length!==5)throw new Error("DHU legacy intake identities changed.");
  const safeProgramsBefore=await tx.query<any>("select jsonb_agg(to_jsonb(p)-'created_at'-'updated_at' order by p.slug) snapshot from programs p where p.slug=any($1::text[])",[safeProgramSlugs]);const safeIntakesBefore=await tx.query<any>("select jsonb_agg(to_jsonb(pi)-'created_at'-'updated_at' order by pi.id) snapshot from program_intakes pi join programs p on p.id=pi.program_id where p.slug=any($1::text[])",[safeProgramSlugs]);const safeScholarshipsBefore=await tx.query<any>("select jsonb_agg(to_jsonb(h)-'created_at'-'updated_at' order by h.slug) snapshot from scholarships h where h.slug=any($1::text[])",[safeScholarshipSlugs]);if(safeProgramsBefore[0]?.snapshot?.length!==119||safeIntakesBefore[0]?.snapshot?.length!==119||safeScholarshipsBefore[0]?.snapshot?.length!==4)throw new Error("DHU protected safe-new records changed.");
  const existingNewIntakes=await tx.query<any>("select p.slug,pi.id,pi.status from program_intakes pi join programs p on p.id=pi.program_id where p.slug=any($1::text[]) and pi.intake_term='Fall' and pi.intake_year=2026",[newIntakeProgramSlugs]);if(existingNewIntakes.length!==0&&existingNewIntakes.length!==7)throw new Error("DHU missing-intake insertion is partially applied.");
  const written=await new CatalogSeedWriter(tx).writeBundle(publication,{preserveExistingCitySlugs:["shanghai"]});if(!written.ok)throw new Error(`DHU cleanup write failed: ${written.errors.join(" ")}`);
  await tx.query("update program_intakes set deadline_date='2026-05-31T00:00:00.000Z'::timestamptz,deadline_label='May 31, 2026 (self-funded); April 15, 2026 for entrance-scholarship consideration',application_round='September 2026 undergraduate intake',status='closed',updated_at=now() where id=any($1::uuid[])",[legacyIntakeIds]);
  const schoolAfter=await tx.query<any>("select id,status,verification_status,last_verified_at,source_url from schools where slug=$1",[schoolSlug]);const legacyAfter=await tx.query<any>("select id,slug,status,verification_status,last_verified_at,source_url from programs where slug=any($1::text[]) order by slug",[programSlugs]);const oldIntakesAfter=await tx.query<any>("select id,deadline_date,deadline_label,application_round,status from program_intakes where id=any($1::uuid[]) order by id",[legacyIntakeIds]);const newIntakesAfter=await tx.query<any>("select p.slug,pi.id,pi.status,pi.deadline_date from program_intakes pi join programs p on p.id=pi.program_id where p.slug=any($1::text[]) and pi.intake_term='Fall' and pi.intake_year=2026 order by p.slug",[newIntakeProgramSlugs]);
  if(schoolAfter.length!==1||schoolAfter[0].id!==schoolBefore[0].id||schoolAfter[0].verification_status!=="verified"||schoolAfter[0].last_verified_at?.toISOString()!==approvedAt||!/^https:\/\/english\.dhu\.edu\.cn\//.test(schoolAfter[0].source_url))throw new Error("DHU school post-check failed.");
  if(legacyAfter.length!==12||legacyAfter.some(row=>row.id!==legacyIds.get(row.slug)||row.status!=="active"||row.verification_status!=="verified"||row.last_verified_at?.toISOString()!==approvedAt||!/^https:\/\/english\.dhu\.edu\.cn\//.test(row.source_url)))throw new Error("DHU legacy program post-check failed.");
  if(oldIntakesAfter.length!==5||oldIntakesAfter.some(row=>row.status!=="closed"||row.deadline_date?.toISOString()!=="2026-05-31T00:00:00.000Z"||row.application_round!=="September 2026 undergraduate intake")||newIntakesAfter.length!==7||newIntakesAfter.some(row=>row.status!=="closed"||row.deadline_date?.toISOString()!=="2026-05-31T00:00:00.000Z"))throw new Error("DHU intake post-check failed.");
  const safeProgramsAfter=await tx.query<any>("select jsonb_agg(to_jsonb(p)-'created_at'-'updated_at' order by p.slug) snapshot from programs p where p.slug=any($1::text[])",[safeProgramSlugs]);const safeIntakesAfter=await tx.query<any>("select jsonb_agg(to_jsonb(pi)-'created_at'-'updated_at' order by pi.id) snapshot from program_intakes pi join programs p on p.id=pi.program_id where p.slug=any($1::text[])",[safeProgramSlugs]);const safeScholarshipsAfter=await tx.query<any>("select jsonb_agg(to_jsonb(h)-'created_at'-'updated_at' order by h.slug) snapshot from scholarships h where h.slug=any($1::text[])",[safeScholarshipSlugs]);if(JSON.stringify(safeProgramsAfter[0]?.snapshot)!==JSON.stringify(safeProgramsBefore[0]?.snapshot)||JSON.stringify(safeIntakesAfter[0]?.snapshot)!==JSON.stringify(safeIntakesBefore[0]?.snapshot)||JSON.stringify(safeScholarshipsAfter[0]?.snapshot)!==JSON.stringify(safeScholarshipsBefore[0]?.snapshot))throw new Error("DHU cleanup changed protected safe-new records.");
  const totals=await tx.query<any>(`select s.id,s.verification_status,(select count(*) from programs p where p.school_id=s.id and p.status='active')::int programs,(select count(*) from programs p where p.school_id=s.id and p.status='active' and p.verification_status='verified')::int verified_programs,(select count(*) from program_intakes pi join programs p on p.id=pi.program_id where p.school_id=s.id and p.status='active')::int intakes,(select count(*) from scholarships h where h.school_id=s.id and h.status='active')::int scholarships,(select count(*) from scholarships h where h.school_id=s.id and h.status='active' and h.verification_status='verified')::int verified_scholarships from schools s where s.slug=$1`,[schoolSlug]);if(totals.length!==1||totals[0].verification_status!=="verified"||totals[0].programs!==131||totals[0].verified_programs!==131||totals[0].intakes!==131||totals[0].scholarships!==4||totals[0].verified_scholarships!==4)throw new Error(`DHU cleanup totals failed: ${JSON.stringify(totals[0])}`);
  return{written:written.summary,preserved:{schoolId:schoolAfter[0].id,programIds:legacyAfter.map(row=>({slug:row.slug,id:row.id})),updatedIntakeIds:oldIntakesAfter.map(row=>row.id)},totals:totals[0]};
});console.log(JSON.stringify({ok:true,target:target.publicTarget,approvedReviewSha256:approvedHash,publicationBundleSha256:report.bundleSha256,approvalPath:paths.approval,outputPath:paths.output,...result},null,2));}finally{await pool.end();}
