import { createHash } from "node:crypto";
import { readFile, writeFile } from "node:fs/promises";
import { resolve } from "node:path";
import { createCatalogMigrationValidationReport, type CatalogSeedBundle } from "../src/server/catalog/seed-contract.ts";
import { createPostgresPool } from "../src/server/db/postgres-client.ts";
import { localDatabaseUrl } from "./lib/local-development.ts";

const root = process.cwd(), paths = { complete: resolve(root, "seeds/catalog.nankai-complete-batch-01.draft.json"), completeReview: resolve(root, "seeds/catalog.nankai-complete-batch-01.review.json"), safeApproval: resolve(root, "seeds/catalog.nankai-safe-new-batch-01.approval.json"), safePublication: resolve(root, "seeds/catalog.nankai-safe-new-batch-01.approved.local.json"), freshManifest: resolve(root, "work/catalog-official/nankai-refresh-20260914/manifest.json"), candidate: resolve(root, "seeds/catalog.nankai-cleanup.draft.json"), validation: resolve(root, "seeds/catalog.nankai-cleanup.validation.json"), review: resolve(root, "seeds/catalog.nankai-cleanup.review.json"), state: resolve(root, ".cuac-local/runtime.json") };
const sha = (value: string | Buffer) => createHash("sha256").update(value).digest("hex"), read = async (path: string) => { const text = await readFile(path, "utf8"); return { text, value: JSON.parse(text) }; };
const [completeFile, completeReviewFile, safeApprovalFile, safePublicationFile, freshManifestFile, stateFile] = await Promise.all([paths.complete, paths.completeReview, paths.safeApproval, paths.safePublication, paths.freshManifest, paths.state].map(read));
const complete = completeFile.value as CatalogSeedBundle, completeReview = completeReviewFile.value, safeApproval = safeApprovalFile.value, safePublication = safePublicationFile.value as CatalogSeedBundle, freshManifest = freshManifestFile.value, state = stateFile.value, schoolSlug = "nankai-university", stableScholarshipSlug = "official-2026-nankai-silk-road-scholarship";
if (complete.cities?.length !== 1 || complete.schools?.length !== 1 || complete.schools[0].slug !== schoolSlug || safeApproval.programSlugs?.length !== 339 || safeApproval.scholarshipSlugs?.length !== 1 || safePublication.programs?.length !== 339 || freshManifest.sources?.length !== 9 || completeReview.visualReview?.result !== "pass") throw new Error("Nankai cleanup dependencies changed.");
const stableScholarships = complete.scholarships?.filter((row) => row.slug === stableScholarshipSlug) ?? []; if (stableScholarships.length !== 1) throw new Error("Nankai stable scholarship changed.");
const plannedProgramAliases: string[] = completeReview.reconciliation?.legacyProgramAliasesToArchive ?? [], plannedScholarshipAliases: string[] = completeReview.reconciliation?.legacyScholarshipAliasesToArchive ?? []; if (plannedProgramAliases.length !== 10 || plannedScholarshipAliases.length !== 1) throw new Error("Nankai archive plan changed.");
const pool = createPostgresPool({ databaseUrl: localDatabaseUrl(state), max: 1, applicationName: "cuac:nankai-cleanup-review" }); let baseline: any;
try {
  const school = await pool.query("select id,slug,status,verification_status from schools where slug=$1", [schoolSlug]), city = await pool.query("select id,slug,status,verification_status from cities where slug='tianjin'"), safePrograms = await pool.query("select slug,status,verification_status,last_verified_at from programs where slug=any($1::text[]) order by slug", [safeApproval.programSlugs]), safeScholarships = await pool.query("select slug,status,verification_status,last_verified_at from scholarships where slug=any($1::text[]) order by slug", [safeApproval.scholarshipSlugs]), stableScholarship = await pool.query("select id,slug,status,verification_status from scholarships where slug=$1", [stableScholarshipSlug]), programAliases = await pool.query("select id,slug,status,verification_status from programs where slug=any($1::text[]) order by slug", [plannedProgramAliases]), scholarshipAliases = await pool.query("select id,slug,status,verification_status from scholarships where slug=any($1::text[]) order by slug", [plannedScholarshipAliases]), totals = await pool.query("select (select count(*) from programs where school_id=$1 and status='active')::int programs,(select count(*) from scholarships where school_id=$1 and status='active')::int scholarships", [school.rows[0]?.id]);
  baseline = { school: school.rows, city: city.rows, safePrograms: safePrograms.rows, safeScholarships: safeScholarships.rows, stableScholarship: stableScholarship.rows, programAliases: programAliases.rows, scholarshipAliases: scholarshipAliases.rows, totals: totals.rows[0] };
  if (school.rows.length !== 1 || school.rows[0].status !== "active" || school.rows[0].verification_status !== "unverified" || city.rows.length !== 1 || city.rows[0].status !== "active") throw new Error("Nankai school/city baseline changed.");
  if (safePrograms.rows.length !== 339 || safeScholarships.rows.length !== 1 || [...safePrograms.rows, ...safeScholarships.rows].some((row: any) => row.status !== "active" || row.verification_status !== "verified" || row.last_verified_at?.toISOString() !== safeApproval.approvedAt)) throw new Error("Nankai safe publication changed.");
  if (stableScholarship.rows.length !== 1 || stableScholarship.rows[0].status !== "active" || stableScholarship.rows[0].verification_status !== "verified" || programAliases.rows.length !== 10 || scholarshipAliases.rows.length !== 1 || [...programAliases.rows, ...scholarshipAliases.rows].some((row: any) => row.status !== "active" || row.verification_status !== "unverified") || totals.rows[0]?.programs !== 349 || totals.rows[0]?.scholarships !== 3) throw new Error("Nankai stable/legacy baseline changed.");
} finally { await pool.end(); }
const candidate: CatalogSeedBundle = { version: 1, generatedAt: freshManifest.generatedAt, cities: complete.cities, schools: complete.schools, programs: [], programIntakes: [], scholarships: stableScholarships }, candidateText = `${JSON.stringify(candidate, null, 2)}\n`, validation = createCatalogMigrationValidationReport(candidate); if (!validation.ok) throw new Error(`Nankai cleanup validation failed: ${validation.errors.join(" ")}`);
const reviewBase = { version: 1, status: "requires_explicit_approval", generatedAt: candidate.generatedAt, scope: { schoolSlug, cityDependencyReplayCount: 1, schoolOverwriteCount: 1, scholarshipOverwriteCount: 1, archiveProgramAliasCount: 10, archiveScholarshipAliasCount: 1, verifiedSafeProgramMutationCount: 0, verifiedSafeScholarshipMutationCount: 0 }, candidateSha256: sha(candidateText), candidateBundleSha256: validation.bundleSha256, operationPlanSha256: validation.operationPlanSha256, evidence: { freshManifestSha256: sha(freshManifestFile.text), freshOfficialSourceCount: 9, completeReviewSha256: sha(completeReviewFile.text), safeApprovalSha256: sha(safeApprovalFile.text), safePublicationSha256: sha(safePublicationFile.text) }, reconciliation: { destructiveDeletion: false, overwrite: [{ entityType: "school", id: baseline.school[0].id, slug: schoolSlug }, { entityType: "scholarship", id: baseline.stableScholarship[0].id, slug: stableScholarshipSlug }], archives: [...baseline.programAliases.map((row: any) => ({ entityType: "program", id: row.id, slug: row.slug })), ...baseline.scholarshipAliases.map((row: any) => ({ entityType: "scholarship", id: row.id, slug: row.slug }))], protectedSafeProgramSlugs: safeApproval.programSlugs, protectedSafeScholarshipSlugs: safeApproval.scholarshipSlugs, databaseBaseline: { schoolId: baseline.school[0].id, cityId: baseline.city[0].id, stableScholarshipId: baseline.stableScholarship[0].id } }, sourceReview: { result: "pass", note: "All nine official Nankai 2026 sources were refreshed byte-for-byte unchanged; the school and Silk Road scholarship updates remain bound to reviewed evidence." }, visualReview: completeReview.visualReview, sensitiveDataCheck: { result: "pass", scope: "school profile, one scholarship update and eleven archive status changes", note: "Only public catalog fields and record identifiers are present. Applicant, account, payment, bank, staff-name and personal-contact data are excluded." }, reviewNotes: ["The 339 verified programs and newly published Type B scholarship are protected and will not be rewritten.", "Ten program aliases and one merged scholarship are status-archived, not deleted.", "The shared Tianjin city dependency is resolved without an update."] };
const reviewHash = sha(JSON.stringify(reviewBase)), requiredApproval = `批准完成南开大学学校与旧数据清理（审核哈希 ${reviewHash}），覆盖学校及 1 条既有丝路奖学金，并归档 10 条旧项目别名及 1 条旧奖学金合并概览`;
await Promise.all([writeFile(paths.candidate, candidateText, "utf8"), writeFile(paths.validation, `${JSON.stringify(validation, null, 2)}\n`, "utf8"), writeFile(paths.review, `${JSON.stringify({ ...reviewBase, reviewHash, requiredApproval }, null, 2)}\n`, "utf8")]); console.log(JSON.stringify({ ok: true, reviewHash, requiredApproval, scope: reviewBase.scope, paths }, null, 2));
