import { createHash } from "node:crypto";
import { readFile, writeFile } from "node:fs/promises";
import { resolve } from "node:path";
import { createCatalogMigrationValidationReport, type CatalogSeedBundle, type CatalogSeedSchool } from "../src/server/catalog/seed-contract.ts";
import { createPostgresPool } from "../src/server/db/postgres-client.ts";
import { localDatabaseUrl } from "./lib/local-development.ts";

const root=process.cwd(),paths={safe:resolve(root,"seeds/catalog.ecnu-safe-new-batch-01.approved.local.json"),approval:resolve(root,"seeds/catalog.ecnu-safe-new-batch-01.approval.json"),manifest:resolve(root,"work/catalog-official/ecnu-complete-batch-01/manifest.json"),candidate:resolve(root,"seeds/catalog.ecnu-cleanup.draft.json"),validation:resolve(root,"seeds/catalog.ecnu-cleanup.validation.json"),review:resolve(root,"seeds/catalog.ecnu-cleanup.review.json"),state:resolve(root,".cuac-local/runtime.json")},sha=(value:string|Buffer)=>createHash("sha256").update(value).digest("hex");
const [safeText,approvalText,manifestText,stateText]=await Promise.all([readFile(paths.safe,"utf8"),readFile(paths.approval,"utf8"),readFile(paths.manifest,"utf8"),readFile(paths.state,"utf8")]),safe=JSON.parse(safeText) as CatalogSeedBundle,approval=JSON.parse(approvalText),manifest=JSON.parse(manifestText),state=JSON.parse(stateText),schoolSlug="east-china-normal-university";
if(approval.programSlugs?.length!==280||approval.scholarshipSlugs?.length!==8||safe.programs?.length!==280||safe.scholarships?.length!==8)throw new Error("ECNU safe publication dependencies changed.");
const source=manifest.sources.find((row:any)=>row.id==="ecnu-undergraduate-admissions-2026");if(!source||source.status!==200||source.sha256!=="19d1e0a1a5e3e324f27885618bb066598151e9dacdcc3dc5610d2061407cfbad")throw new Error("ECNU official school source changed.");
const tuition=safe.programs.map((row:any)=>row.tuitionAmount).filter((value:any)=>typeof value==="number"),subjects=[...new Set(safe.programs.flatMap((row:any)=>row.cscaSubjects??[]))].sort(),languages=[...new Set(safe.programs.map((row:any)=>row.teachingLanguage).filter(Boolean))].sort(),degrees=[...new Set(safe.programs.map((row:any)=>row.degreeLevel).filter(Boolean))].sort();
const school:CatalogSeedSchool={slug:schoolSlug,nameEn:"East China Normal University",nameZh:"华东师范大学",citySlug:"shanghai",schoolType:"Public",region:"Shanghai, East China",applicationLevel:degrees.join(", "),languageOfInstruction:languages.join(", "),cscaRequired:subjects.length>0,cscaRequirement:"CSCA subject requirements are published per undergraduate route; consult the selected program record.",cscaSubjects:subjects,deadlineSummary:"2026 deadlines are route-specific and published with each reviewed intake.",tuitionSummary:`CNY ${Math.min(...tuition).toLocaleString("en-US")}–${Math.max(...tuition).toLocaleString("en-US")}/year across reviewed 2026 routes`,websiteUrl:"https://www.ecnu.edu.cn/",admissionsUrl:"https://lxs.ecnu.edu.cn/",subjectTags:[...new Set(safe.programs.map((row:any)=>row.subjectArea).filter(Boolean))].slice(0,20),languageTags:languages,status:"draft",sourceUrl:source.finalUrl,sourceLabel:source.label,sourceSha256:source.sha256,capturedAt:source.fetchedAt,sourceFieldLineage:{nameEn:"official admissions site identity",nameZh:"official institution identity",citySlug:"official university identity and Shanghai campus context",applicationLevel:"reviewed 2026 official undergraduate/master/doctoral catalogs",languageOfInstruction:"reviewed 2026 official program language columns",cscaSubjects:"reviewed official undergraduate catalog CSCA columns",deadlineSummary:"reviewed route intake records",tuitionSummary:"reviewed official program tuition columns",admissionsUrl:"official admissions source host"}};
const candidateRaw:CatalogSeedBundle={version:1,generatedAt:new Date().toISOString(),cities:safe.cities,schools:[school],programs:[],programIntakes:[],scholarships:[]},candidateText=`${JSON.stringify(candidateRaw,null,2)}\n`,candidate=JSON.parse(candidateText) as CatalogSeedBundle,validation=createCatalogMigrationValidationReport(candidate);if(!validation.ok)throw new Error(`Invalid ECNU cleanup candidate: ${validation.errors.join(" ")}`);
const pool=createPostgresPool({databaseUrl:localDatabaseUrl(state),max:1,applicationName:"cuac:ecnu-cleanup-review"});let baseline:any;
try{const schoolRows=await pool.query("select id,status,verification_status,source_url from schools where slug=$1",[schoolSlug]),programs=await pool.query("select id,slug,status,verification_status from programs where school_id=$1 and status='active' order by slug",[schoolRows.rows[0]?.id]),scholarships=await pool.query("select id,slug,status,verification_status from scholarships where school_id=$1 and status='active' order by slug",[schoolRows.rows[0]?.id]);const officialPrograms=programs.rows.filter((row:any)=>approval.programSlugs.includes(row.slug)),legacyPrograms=programs.rows.filter((row:any)=>!approval.programSlugs.includes(row.slug)),protectedScholarships=new Set([...approval.scholarshipSlugs,"official-2026-ecnu-shanghai-government-scholarship"]),officialScholarships=scholarships.rows.filter((row:any)=>protectedScholarships.has(row.slug)),legacyScholarships=scholarships.rows.filter((row:any)=>!protectedScholarships.has(row.slug));baseline={school:schoolRows.rows,officialPrograms,legacyPrograms,officialScholarships,legacyScholarships};if(schoolRows.rows.length!==1||schoolRows.rows[0].status!=="active"||schoolRows.rows[0].verification_status!=="unverified"||officialPrograms.length!==280||officialPrograms.some((row:any)=>row.verification_status!=="verified")||legacyPrograms.length!==12||legacyPrograms.some((row:any)=>row.verification_status!=="unverified")||officialScholarships.length!==9||officialScholarships.some((row:any)=>row.verification_status!=="verified")||legacyScholarships.length!==10||legacyScholarships.some((row:any)=>row.verification_status!=="unverified"))throw new Error(`ECNU cleanup baseline changed: ${JSON.stringify({school:schoolRows.rows,programs:programs.rows.length,officialPrograms:officialPrograms.length,legacyPrograms:legacyPrograms.length,scholarships:scholarships.rows.length,officialScholarships:officialScholarships.length,legacyScholarships:legacyScholarships.length})}`);}finally{await pool.end();}
const reviewBase={version:1,status:"requires_explicit_approval",generatedAt:candidate.generatedAt,scope:{schoolSlug,schoolOverwriteCount:1,archiveProgramAliasCount:12,archiveScholarshipAliasCount:10,verifiedProgramMutationCount:0,verifiedScholarshipMutationCount:0},candidateSha256:sha(candidateText),candidateBundleSha256:validation.bundleSha256,operationPlanSha256:validation.operationPlanSha256,sourceEvidence:{manifestSha256:sha(manifestText),safePublicationSha256:sha(safeText),safeApprovalSha256:sha(approvalText)},reconciliation:{destructiveDeletion:false,overwrite:{entityType:"school",id:baseline.school[0].id,slug:schoolSlug,reason:"Replace unverified third-party summary with reviewed official 2026 catalog-derived school profile."},archives:[...baseline.legacyPrograms.map((row:any)=>({entityType:"program",id:row.id,slug:row.slug,reason:"Superseded by reviewed official 2026 route records."})),...baseline.legacyScholarships.map((row:any)=>({entityType:"scholarship",id:row.id,slug:row.slug,reason:"Superseded by independently scoped verified official scholarship records."}))],databaseBaseline:{schoolId:baseline.school[0].id,legacyProgramIds:baseline.legacyPrograms.map((row:any)=>row.id),legacyScholarshipIds:baseline.legacyScholarships.map((row:any)=>row.id),protectedProgramIds:baseline.officialPrograms.map((row:any)=>row.id),protectedScholarshipIds:baseline.officialScholarships.map((row:any)=>row.id)}},sensitiveDataCheck:{result:"pass",scope:"school profile and archive status changes",note:"Public institutional catalog data only; no applicant, account, payment or personal-contact data."},reviewNotes:["No verified program or scholarship is modified.","Legacy rows are status-archived, not physically deleted.","After publication ECNU will have a verified school, 280/280 active verified programs and 9/9 active verified scholarships."]};
const reviewHash=sha(JSON.stringify(reviewBase)),requiredApproval=`批准完成华东师范大学官方学校资料，并归档 12 条旧项目及 10 条旧奖学金（审核哈希 ${reviewHash}）`;await Promise.all([writeFile(paths.candidate,candidateText,"utf8"),writeFile(paths.validation,`${JSON.stringify(validation,null,2)}\n`,"utf8"),writeFile(paths.review,`${JSON.stringify({...reviewBase,reviewHash,requiredApproval},null,2)}\n`,"utf8")]);console.log(JSON.stringify({ok:true,reviewHash,requiredApproval,scope:reviewBase.scope},null,2));
