import { createHash } from "node:crypto";
import { readFile, writeFile } from "node:fs/promises";
import { resolve } from "node:path";
import { createCatalogMigrationValidationReport, type CatalogSeedBundle, type CatalogSeedProgram } from "../src/server/catalog/seed-contract.ts";
import { createPostgresPool } from "../src/server/db/postgres-client.ts";
import { localDatabaseUrl } from "./lib/local-development.ts";

const root=process.cwd(),schoolSlug="donghua-university",prefix="catalog.dhu-cleanup-batch-01";
const paths={full:resolve(root,"seeds/catalog.dhu-complete-batch-01.draft.json"),safeApproval:resolve(root,"seeds/catalog.dhu-safe-new-batch-01.approval.json"),safePublication:resolve(root,"seeds/catalog.dhu-safe-new-batch-01.approved.local.json"),state:resolve(root,".cuac-local/runtime.json"),candidate:resolve(root,`seeds/${prefix}.draft.json`),validation:resolve(root,`seeds/${prefix}.validation.json`),review:resolve(root,`seeds/${prefix}.review.json`)};
const parse=async(path:string)=>JSON.parse(await readFile(path,"utf8")),sha=(value:string|Buffer)=>createHash("sha256").update(value).digest("hex"),writeJson=(path:string,value:unknown)=>writeFile(path,`${JSON.stringify(value,null,2)}\n`,`utf8`);
const [full,safeApproval,safePublication,state]=await Promise.all([paths.full,paths.safeApproval,paths.safePublication,paths.state].map(parse));
if(safeApproval.programSlugs?.length!==119||safeApproval.scholarshipSlugs?.length!==4||safePublication.programs?.length!==119||safePublication.scholarships?.length!==4)throw new Error("DHU safe-new publication changed.");

const officialByKey=new Map(full.programs.map((row:any)=>[`${row.nameEn}|${row.teachingLanguage}`,row]));
const aliases:Record<string,string>={
  "donghua-university-accounting":"Accounting|Chinese",
  "donghua-university-business-administration":"Business Administration|Chinese",
  "donghua-university-digital-media-art":"Digital Media Art|Chinese",
  "donghua-university-environmental-design":"Environmental Design|Chinese",
  "donghua-university-environmental-design-fashion-interior-scf":"Environmental Design (Fashion Interior Design)|English",
  "donghua-university-fashion-and-accessory-design-scf":"Fashion & Accessory Design (Fashion Innovation)|English",
  "donghua-university-fashion-design-and-engineering":"Fashion Design & Engineering|Chinese",
  "donghua-university-fashion-and-apparel-design":"Fashion & Apparel Design|Chinese",
  "donghua-university-finance":"Finance|Chinese",
  "donghua-university-international-economics-and-trade":"International Economy & Trade|Chinese",
  "donghua-university-product-design":"Product Design|Chinese",
  "donghua-university-visual-communication-design":"Visual Communication Design|Chinese",
};
const updatePrograms:CatalogSeedProgram[]=Object.entries(aliases).map(([legacySlug,key])=>{const official=officialByKey.get(key) as CatalogSeedProgram|undefined;if(!official)throw new Error(`Missing official DHU route: ${key}`);return{...official,slug:legacySlug,status:"draft"};});
if(updatePrograms.length!==12||new Set(updatePrograms.map(row=>row.slug)).size!==12)throw new Error("DHU cleanup mapping changed.");

const pool=createPostgresPool({databaseUrl:localDatabaseUrl(state),max:1,applicationName:"cuac:dhu-cleanup-review"});let baseline:any;
try{const school=await pool.query("select id,slug,status,verification_status,source_url from schools where slug=$1",[schoolSlug]);const programs=await pool.query("select id,slug,name_en,status,verification_status,last_verified_at,source_url from programs where school_id=$1 order by slug",[school.rows[0]?.id]);const legacyPrograms=programs.rows.filter((row:any)=>Object.hasOwn(aliases,row.slug));const safePrograms=programs.rows.filter((row:any)=>safeApproval.programSlugs.includes(row.slug));const intakes=await pool.query("select pi.id,p.slug program_slug,pi.intake_term,pi.intake_year,pi.deadline_date,pi.deadline_label,pi.application_round,pi.status from program_intakes pi join programs p on p.id=pi.program_id where p.school_id=$1 order by p.slug,pi.id",[school.rows[0]?.id]);const legacyIntakes=intakes.rows.filter((row:any)=>Object.hasOwn(aliases,row.program_slug));const safeIntakes=intakes.rows.filter((row:any)=>safeApproval.programSlugs.includes(row.program_slug));const scholarships=await pool.query("select id,slug,status,verification_status,last_verified_at from scholarships where school_id=$1 order by slug",[school.rows[0]?.id]);if(school.rows.length!==1||school.rows[0].status!=="active"||school.rows[0].verification_status!=="unverified"||programs.rows.length!==131||legacyPrograms.length!==12||legacyPrograms.some((row:any)=>row.status!=="active"||row.verification_status!=="unverified")||safePrograms.length!==119||safePrograms.some((row:any)=>row.status!=="active"||row.verification_status!=="verified")||intakes.rows.length!==124||legacyIntakes.length!==5||safeIntakes.length!==119||scholarships.rows.length!==4||scholarships.rows.some((row:any)=>row.status!=="active"||row.verification_status!=="verified"))throw new Error("DHU cleanup baseline changed.");baseline={school:school.rows[0],legacyPrograms,legacyIntakes,safeProgramCount:safePrograms.length,safeIntakeCount:safeIntakes.length,scholarships};}finally{await pool.end();}

const existingIntakeSlugs=new Set(baseline.legacyIntakes.map((row:any)=>row.program_slug));
const newIntakes=updatePrograms.filter(program=>!existingIntakeSlugs.has(program.slug)).map(program=>({programSlug:program.slug,intakeTerm:"Fall",intakeYear:2026,deadlineDate:"2026-05-31T00:00:00.000Z",deadlineLabel:"May 31, 2026 (self-funded); April 15, 2026 for entrance-scholarship consideration",applicationRound:"September 2026 undergraduate intake",status:"closed" as const,sourceUrl:program.sourceUrl,sourceLabel:program.sourceLabel,sourceSha256:program.sourceSha256,capturedAt:program.capturedAt,sourceFieldLineage:{deadlineDate:"official 2026 bachelor's program table, self-funded deadline column",applicationRound:"official table heading"}}));
if(newIntakes.length!==7||existingIntakeSlugs.size!==5)throw new Error("DHU legacy intake reconciliation changed.");
const candidate:CatalogSeedBundle={version:1,generatedAt:full.generatedAt,cities:full.cities,schools:full.schools,programs:updatePrograms,programIntakes:newIntakes,scholarships:[]};
const validation=createCatalogMigrationValidationReport(candidate);if(!validation.ok||validation.summary.schools!==1||validation.summary.programs!==12||validation.summary.programIntakes!==7)throw new Error(`Invalid DHU cleanup candidate: ${validation.errors.join(" ")}`);
const candidateText=`${JSON.stringify(candidate,null,2)}\n`;
const reviewBase={version:1,status:"requires_explicit_approval",generatedAt:new Date().toISOString(),scope:{schoolSlug,schoolOverwriteCount:1,programOverwriteCount:12,intakeOverwriteCount:5,intakeInsertCount:7,archiveCount:0,deleteCount:0},candidateSha256:sha(candidateText),candidateBundleSha256:validation.bundleSha256,operationPlanSha256:validation.operationPlanSha256,safePublicationEvidence:{approvalSha256:sha(await readFile(paths.safeApproval)),publicationSha256:sha(await readFile(paths.safePublication)),publishedProgramCount:119,publishedScholarshipCount:4},reconciliation:{destructiveDeletion:false,overwrites:{school:{id:baseline.school.id,slug:schoolSlug},programs:baseline.legacyPrograms.map((row:any)=>({id:row.id,slug:row.slug,officialRouteKey:aliases[row.slug]})),intakes:baseline.legacyIntakes.map((row:any)=>({id:row.id,programSlug:row.program_slug,intakeTerm:row.intake_term,intakeYear:row.intake_year}))},inserts:{intakes:newIntakes.map(row=>({programSlug:row.programSlug,intakeTerm:row.intakeTerm,intakeYear:row.intakeYear}))},archives:[],databaseBaseline:baseline},sourceReview:{result:"pass",note:"Each updated school/program/intake field comes from the same hash-bound Donghua University official evidence used by the already published safe-new batch."},sensitiveDataCheck:{result:"pass",scope:"one school, 12 public program records and 12 public intake records",note:"No applicant, personal contact, passport, account, payment or submitted-document data is read or written."},reviewNotes:["The existing school ID and all 12 legacy program IDs will be preserved through slug-keyed updates.","Five existing intake IDs will be preserved and their 2026 deadline fields updated in place; seven missing 2026 Fall intakes will be inserted.","The 119 verified safe-new programs, their 119 intakes and all four verified scholarships remain byte-for-byte unchanged.","No record is archived or physically deleted."]};
const reviewHash=sha(JSON.stringify(reviewBase)),requiredApproval=`批准完成东华大学官方学校资料与 12 条旧本科项目更新，并更新 5 条、补充 7 条 2026 入学记录（审核哈希 ${reviewHash}），保留原学校及项目 ID`;
await Promise.all([writeJson(paths.candidate,candidate),writeJson(paths.validation,validation),writeJson(paths.review,{...reviewBase,reviewHash,requiredApproval})]);
console.log(JSON.stringify({ok:true,reviewHash,requiredApproval,summary:validation.summary,scope:reviewBase.scope,paths},null,2));
