import { createHash } from "node:crypto";
import { readFile, writeFile } from "node:fs/promises";
import { resolve } from "node:path";
import { CatalogSeedWriter } from "../src/server/catalog/seed-writer.ts";
import { createCatalogMigrationValidationReport, type CatalogSeedBundle } from "../src/server/catalog/seed-contract.ts";
import { assertLocalCatalogPublishTarget, LOCAL_CATALOG_PUBLISH_CONFIRMATION } from "../src/server/catalog/local-publish-safety.ts";
import { createPostgresPool, createTransactionalSqlClient } from "../src/server/db/postgres-client.ts";

const root=process.cwd(),paths={candidate:resolve(root,"seeds/catalog.beihang-scholarships-complete-batch-01.draft.json"),validation:resolve(root,"seeds/catalog.beihang-scholarships-complete-batch-01.validation.json"),review:resolve(root,"seeds/catalog.beihang-scholarships-complete-batch-01.new.review.json"),output:resolve(root,"seeds/catalog.beihang-scholarships-complete-batch-01.approved.local.json"),approval:resolve(root,"seeds/catalog.beihang-scholarships-complete-batch-01.approval.json"),state:resolve(root,".cuac-local/runtime.json")};
const parse=async(path:string)=>JSON.parse(await readFile(path,"utf8")),sha=(value:string)=>createHash("sha256").update(value).digest("hex");
const candidateText=await readFile(paths.candidate,"utf8"),candidate=JSON.parse(candidateText) as CatalogSeedBundle,[validation,review,state]=await Promise.all([parse(paths.validation),parse(paths.review),parse(paths.state)]);
const {reviewHash,...reviewBase}=review;
if(sha(JSON.stringify(reviewBase))===reviewHash)throw new Error("Internal review hash shape unexpectedly includes the publication reference.");
const {publicationReference,...hashedWithHash}=review;const {reviewHash:_discard,...hashedBase}=hashedWithHash;
if(sha(JSON.stringify(hashedBase))!==reviewHash||publicationReference!=="standing-user-default-publication"||review.status!=="standing_user_approval")throw new Error("Beihang standing review is invalid.");
const fresh=createCatalogMigrationValidationReport(candidate);
if(!fresh.ok||!validation.ok||sha(candidateText)!==review.candidateSha256||fresh.bundleSha256!==review.candidateBundleSha256||fresh.bundleSha256!==validation.bundleSha256||fresh.operationPlanSha256!==review.operationPlanSha256||fresh.operationPlanSha256!==validation.operationPlanSha256)throw new Error("Beihang candidate changed after review.");
if(review.scope?.newScholarshipCount!==10||review.scope?.archiveScholarshipAliasCount!==0||review.scope?.scholarshipOverwriteCount!==0||review.reconciliation?.destructiveDeletion!==false||review.sensitiveDataCheck?.result!=="pass")throw new Error("Standing authorization cannot overwrite or archive scholarship data.");
const approvedAt=new Date().toISOString(),scholarships=candidate.scholarships??[],slugs=scholarships.map((row)=>row.slug);
const sourceSchemaSha256=sha(JSON.stringify({cityFields:[...new Set((candidate.cities??[]).flatMap((row)=>Object.keys(row)))].sort(),schoolFields:[...new Set((candidate.schools??[]).flatMap((row)=>Object.keys(row)))].sort(),scholarshipFields:[...new Set(scholarships.flatMap((row)=>Object.keys(row)))].sort()}));
const reviewReference=`standing-user-default-publication-beihang-scholarships-${reviewHash}`;
const publication:CatalogSeedBundle={version:2,generatedAt:approvedAt,handoff:{sourceSystem:"CUAC reviewed official Beihang scholarship pages",cleanedExportName:"catalog.beihang-scholarships-complete-batch-01.draft.json",cleanedExportSha256:fresh.bundleSha256,sourceSchemaSha256,reviewReference,prohibitedDataReviewReference:reviewReference,approvalRecordedAt:approvedAt,sourceReadOnly:true,prohibitedDataConfirmedExcluded:true},cities:candidate.cities??[],schools:candidate.schools??[],programs:[],programIntakes:[],scholarships:scholarships.map((row)=>({...row,status:"active" as const,verificationStatus:"verified" as const,lastVerifiedAt:approvedAt}))};
const report=createCatalogMigrationValidationReport(publication);if(!report.ok||report.summary.scholarships!==10)throw new Error(`Invalid Beihang publication: ${report.errors.join(" ")}`);
const approval={version:1,approvedAt,approvalMode:"standing-product-owner-authorization",reviewReference,approvedReviewSha256:reviewHash,approvedCandidateBundleSha256:fresh.bundleSha256,publicationBundle:"seeds/catalog.beihang-scholarships-complete-batch-01.approved.local.json",publicationBundleSha256:report.bundleSha256,schoolSlug:"beihang-university",scholarshipSlugs:slugs,archivedScholarshipAliases:[],prohibitedDataConfirmedExcluded:true};
async function writeOrVerify(path:string,value:unknown){const body=`${JSON.stringify(value,null,2)}\n`;try{await writeFile(path,body,{encoding:"utf8",flag:"wx"});}catch(error:any){if(error?.code!=="EEXIST")throw error;if(await readFile(path,"utf8")!==body)throw new Error(`Existing artifact differs: ${path}`);}}
await writeOrVerify(paths.output,publication);await writeOrVerify(paths.approval,approval);
const target=assertLocalCatalogPublishTarget(state,publication,LOCAL_CATALOG_PUBLISH_CONFIRMATION,reviewReference),pool=createPostgresPool({databaseUrl:target.databaseUrl,max:1,applicationName:"cuac:beihang-scholarships-new-publish"});
try{const client=createTransactionalSqlClient(pool);const result=await client.transaction(async(tx)=>{
 const identity=await tx.query<{database_name:string;database_user:string}>("select current_database() database_name,current_user database_user",[]);if(identity[0]?.database_name!==target.publicTarget.databaseName||identity[0]?.database_user!==target.publicTarget.databaseUser)throw new Error("Database identity mismatch.");
 const school=await tx.query<{id:string;status:string;verification_status:string}>("select id,status,verification_status from schools where slug='beihang-university'",[]);if(school.length!==1||school[0].id!==review.reconciliation.databaseBaseline.schoolId||school[0].status!=="active"||school[0].verification_status!=="verified")throw new Error("Beihang school changed after review.");
 const programs=await tx.query<{active_count:string;verified_count:string}>("select count(*)::text active_count,count(*) filter(where verification_status='verified')::text verified_count from programs where school_id=$1 and status='active'",[school[0].id]);if(programs[0]?.active_count!=="264"||programs[0]?.verified_count!=="264")throw new Error("Beihang program baseline changed.");
 const stable=await tx.query<{id:string;status:string;verification_status:string}>("select id,status,verification_status from scholarships where slug='official-2026-beihang-high-level-postgraduate-scholarship'",[]),legacy=await tx.query<{id:string;status:string;verification_status:string}>("select id,status,verification_status from scholarships where slug='beihang-university'",[]),before=await tx.query<{slug:string;status:string;verification_status:string;last_verified_at:Date|null}>("select slug,status,verification_status,last_verified_at from scholarships where slug=any($1::text[])",[slugs]);
 if(stable.length!==1||stable[0].id!==review.reconciliation.databaseBaseline.stableScholarshipId||stable[0].status!=="active"||stable[0].verification_status!=="verified"||legacy.length!==1||legacy[0].id!==review.reconciliation.databaseBaseline.legacyScholarshipId||legacy[0].status!=="active"||legacy[0].verification_status!=="unverified")throw new Error("Beihang stable/legacy baseline changed.");
 const preState=before.length===0,postState=before.length===10&&before.every((row)=>row.status==="active"&&row.verification_status==="verified"&&row.last_verified_at?.toISOString()===approvedAt);if(!preState&&!postState)throw new Error("Beihang new scholarship rows no longer match pre-state or this publication.");
 const written=await new CatalogSeedWriter(tx).writeBundle(publication);if(!written.ok)throw new Error(`Catalog write failed: ${written.errors.join(" ")}`);
 const finalRows=await tx.query<{slug:string;verification_status:string;last_verified_at:Date|null;benefit_count:string;material_count:string;step_count:string;action_count:string}>("select slug,verification_status,last_verified_at,jsonb_array_length(benefit_items)::text benefit_count,jsonb_array_length(application_materials)::text material_count,jsonb_array_length(application_steps)::text step_count,jsonb_array_length(action_links)::text action_count from scholarships where slug=any($1::text[]) and status='active' order by slug",[slugs]);if(finalRows.length!==10||finalRows.some((row)=>row.verification_status!=="verified"||row.last_verified_at?.toISOString()!==approvedAt||[row.benefit_count,row.material_count,row.step_count,row.action_count].some((v)=>Number(v)<1)))throw new Error("Beihang post-publication rich-detail check failed.");
 return{written,publishedScholarshipCount:finalRows.length,legacyAliasStatus:"active-unverified-pending-explicit-archive"};
});console.log(JSON.stringify({ok:true,target:target.publicTarget,reviewHash,publicationBundleSha256:report.bundleSha256,approvalPath:paths.approval,outputPath:paths.output,...result},null,2));}finally{await pool.end();}
