import { createHash } from "node:crypto";
import { readFile, writeFile } from "node:fs/promises";
import { resolve } from "node:path";
import { createCatalogMigrationValidationReport, type CatalogSeedBundle, type CatalogSeedScholarship } from "../src/server/catalog/seed-contract.ts";

const root = process.cwd();
const parsedPath = resolve(root, "work/catalog-official/nju-complete-batch-02/parsed-graduate-routes.json");
const priorPath = resolve(root, "seeds/catalog.nju-school-program-batch-01.approved.local.json");
const candidatePath = resolve(root, "seeds/catalog.nju-complete-batch-02.draft.json");
const validationPath = resolve(root, "seeds/catalog.nju-complete-batch-02.validation.json");
const reviewPath = resolve(root, "seeds/catalog.nju-complete-batch-02.review.json");
const sha256 = (value: string) => createHash("sha256").update(value).digest("hex");
const parsedText = await readFile(parsedPath, "utf8");
if (sha256(parsedText) !== "d7f59317f68cfdcddf1b6307f9c915e5467dcdbf9e1953f6b944e9626f1d0773") throw new Error("NJU parsed graduate routes changed after visual review.");
const parsed = JSON.parse(parsedText);
if (JSON.stringify(parsed.counts) !== JSON.stringify({ total: 202, master: 141, doctoral: 61, chinese: 193, english: 9 }) || parsed.duplicateIdentities.length || parsed.suspiciousRows.length) throw new Error(`Unexpected NJU extraction summary: ${JSON.stringify(parsed.counts)}`);
const prior = JSON.parse(await readFile(priorPath, "utf8"));
if (prior.schools?.length !== 1 || prior.schools[0].slug !== "nanjing-university" || prior.programs?.length !== 59) throw new Error("Reviewed NJU dependency bundle is unavailable.");

const manifests = await Promise.all(["work/catalog-official/nju-complete-batch-02/manifest.json", "work/catalog-official/nju-complete-batch-02-en/manifest.json"].map(path => readFile(resolve(root, path), "utf8").then(JSON.parse)));
const expected: Record<string, string> = {
  "nanjing-university-master-admissions-2026": "f2e3347f3f5caa8a2d3f842f93d87dc069ec634200d5c6dabd7780ffe4a19964",
  "nanjing-university-master-catalog-en-pdf-2026": "cfcbe557d5b9916eead81ac946fb85b55681371f12d0d71f55d3f820e576471c",
  "nanjing-university-doctoral-admissions-2026": "9a838dc01e703e7523ccff2385c32630e9f7a0f504574ed3540747153c354c3a",
  "nanjing-university-doctoral-catalog-pdf-2026": "a5d449d3bfa3eac55f20fcc7d5e4d99fdd42a4619ee433f5890c7b5d793fc061",
  "nanjing-university-cgs-high-level-graduate-2026": "8689e7f1ee392ca9721dbe453e6cfbb30d1068a2fe4d3b4a4ce0e21d1f576b49",
  "nanjing-university-cgs-excellence-2026": "06e9aa6b1ab24e8cac8775e80c68000f63f28904b97806b2f0b446dcf8ead08d",
  "nanjing-university-nanjing-government-scholarship-2026": "b119ba3101ec1f4efa4b4540a2cc0815ed2b96d0cf9bf8579182b33a4ed125ac",
};
const evidence = new Map<string, any>();
for (const manifest of manifests) for (const source of manifest.sources ?? []) if (expected[source.id] === source.sha256 && source.status === 200) evidence.set(source.id, source);
const missing = Object.keys(expected).filter(id => !evidence.has(id));
if (missing.length) throw new Error(`Missing locked NJU evidence: ${missing.join(", ")}`);

const slugify = (value: string) => value.normalize("NFKD").replace(/[\u0300-\u036f]/g, "").toLowerCase().replace(/&/g, " and ").replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");
const routeIdentity = (route: any) => [route.degree, route.code, route.teachingLanguage, route.schoolOrDepartment, route.nameEn].join("|");
const programSlug = (route: any) => { const verbose = slugify(["nanjing-university", route.degree, route.code, route.schoolOrDepartment, route.nameEn, route.teachingLanguage].join(" ")); return verbose.length <= 180 ? verbose : `${verbose.slice(0, 163).replace(/-+$/g, "")}-${sha256(routeIdentity(route)).slice(0, 16)}`; };
const publicNote = (value: string) => value.replace(/https?:\/\/\S+/gi, "").replace(/[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}/gi, "").replace(/\+?86[\d\s-]{7,}/g, "").replace(/\s+/g, " ").trim();
const programs = parsed.routes.map((route: any) => {
  const source = evidence.get(route.sourceId)!;
  const duration = Number(route.durationYears);
  const normalizedDuration = Number.isInteger(duration) ? { durationYears: duration } : { durationMonths: Math.round(duration * 12) };
  const note = publicNote(route.requirementsAndTips);
  return {
    slug: programSlug(route), schoolSlug: "nanjing-university", citySlug: "nanjing", nameEn: route.nameEn,
    degreeLevel: route.degree, ...normalizedDuration, fieldCategory: route.schoolOrDepartment, subjectArea: route.schoolOrDepartment,
    teachingLanguage: route.teachingLanguage, cscaRequirement: "No CSCA requirement is published for this graduate route.",
    ...(route.teachingLanguage === "Chinese" ? { hskRequirement: "Natural sciences, engineering and medicine normally require HSK 4 for admission; liberal arts, social sciences and business normally require HSK 5. Confirm route-specific rules with NJU." } : { englishRequirement: "IELTS 6.0, TOEFL 85, TOEFL Essentials 9, Duolingo 100, or another officially listed equivalent; confirm route-specific rules with NJU." }),
    tuitionText: "See the official Nanjing University international student tuition schedule.", displayTuition: "Official tuition schedule",
    scholarshipText: "NJU scholarships are competitive and subject to their published eligibility rules.", applicationUrl: "https://nju.17gz.org/",
    applicationNote: `Program code ${route.code}; ${route.schoolOrDepartment}; published duration ${route.durationText} years.${note ? ` ${note}` : ""}`,
    hasScholarship: true, displayGroup: route.degree.toLowerCase(), displayGroupLabel: route.degree, status: "draft" as const,
    sourceUrl: source.url, sourceLabel: source.label, sourceSha256: source.sha256, capturedAt: source.fetchedAt,
    sourceFieldLineage: { nameEn: `PDF page ${route.sourcePage}, table row ${route.sourceRow}, Major`, degreeLevel: "official PDF title", subjectArea: `PDF page ${route.sourcePage}, table row ${route.sourceRow}, School`, teachingLanguage: `PDF page ${route.sourcePage}, table row ${route.sourceRow}, Language of Instructions`, ...(Number.isInteger(duration) ? { durationYears: `PDF page ${route.sourcePage}, table row ${route.sourceRow}, Study Duration` } : { durationMonths: `PDF page ${route.sourcePage}, table row ${route.sourceRow}, Study Duration; half-year normalized to months` }), applicationNote: `PDF page ${route.sourcePage}, table row ${route.sourceRow}, Code and Notes` },
  };
});
if (new Set(programs.map(row => row.slug)).size !== programs.length) throw new Error("NJU graduate program slugs are not unique.");
const programIntakes = programs.map((program: any) => ({ programSlug: program.slug, intakeTerm: "Fall", intakeYear: 2026, deadlineDate: "2026-05-20T00:00:00.000Z", deadlineLabel: "Application deadline: May 20, 2026", applicationRound: "2026 international graduate intake", status: "closed" as const, sourceUrl: program.sourceUrl, sourceLabel: program.sourceLabel, sourceSha256: program.sourceSha256, capturedAt: program.capturedAt, sourceFieldLineage: { deadlineDate: "official master's/doctoral admissions page, Application Duration; date-only value normalized to ISO UTC" } }));

const item = (label: string, value?: string) => ({ label, ...(value ? { value } : {}) });
const benefit = (label: string, note?: string) => ({ label, included: true, ...(note ? { note } : {}) });
const scholarship = (sourceId: string, data: Partial<CatalogSeedScholarship> & Pick<CatalogSeedScholarship, "slug" | "title" | "fundingLevel" | "coverage" | "applicableDegree" | "amountText">): CatalogSeedScholarship => {
  const source = evidence.get(sourceId)!;
  return { schoolSlug: "nanjing-university", providerLocation: "Nanjing, Jiangsu, China", status: "draft", targetCountries: [], targetRegions: [], sourceUrl: source.url, sourceLabel: source.label, sourceSha256: source.sha256, capturedAt: source.fetchedAt, sourceFieldLineage: { title: "official page title", fundingLevel: "funding section", coverage: "funding section", amountText: "funding section", applicableDegree: "student type or eligibility section", eligibilityItems: "eligibility section", applicationMaterials: "application materials section", applicationSteps: "application procedure section", deadlineDate: "application dates section" }, actionLinks: [{ label: "Official NJU scholarship page", url: source.url, kind: "official-source" }], ...data };
};
const scholarships: CatalogSeedScholarship[] = [
  scholarship("nanjing-university-cgs-high-level-graduate-2026", { slug: "official-2026-nju-cgs-high-level-graduate-program", title: "Nanjing University 2026 Chinese Government Scholarship Type B High-Level Graduate Program", type: "government", typeLabel: "CSC Type B", providerNameEn: "China Scholarship Council / Nanjing University", fundingLevel: "Full", coverage: "Tuition waiver, free on-campus accommodation, monthly stipend and comprehensive medical insurance.", applicableDegree: "Master, Doctoral", applicableProgram: "Eligible full-time NJU graduate programs", amountText: "Tuition waiver; accommodation; RMB 3,000/month for master's or RMB 3,500/month for doctoral students; RMB 800/year medical insurance", deadlineDate: "2026-01-20", deadlineLabel: "NJU application deadline: January 20, 2026", applicationRound: "2026 international graduate intake", benefitItems: [benefit("Tuition waiver"), benefit("On-campus accommodation"), benefit("Monthly stipend", "RMB 3,000 for master's; RMB 3,500 for doctoral students"), benefit("Medical insurance", "RMB 800 per academic year")], eligibilityItems: [item("Citizenship", "Healthy non-Chinese citizen"), item("Degree route", "Eligible master's or doctoral applicant meeting NJU admissions requirements"), item("Concurrent funding", "Applicants holding another 2026-2027 Chinese scholarship are not eligible")], applicationMaterials: [item("Highest degree certificate and transcripts"), item("Two academic recommendation letters"), item("Language proficiency evidence"), item("Personal statement"), item("Physical examination record"), item("Passport and no-criminal-record certificate"), item("Doctoral thesis abstract or architecture/urban planning portfolio", "Where applicable")], applicationSteps: [item("Step 1", "Apply in NJU's international student system by January 20, 2026"), item("Step 2", "Complete school/department review and receive a pre-admission notice if recommended"), item("Step 3", "Submit the CSC Type B application by March 17, 2026 using NJU agency number 10284"), item("Step 4", "Await CSC final review and NJU admission notification")], bodySections: [{ title: "Award duration", body: "The published duration is 2-3 years for master's students and 4 years for doctoral students, subject to annual review." }], summary: "NJU's full CSC Type B route for eligible international master's and doctoral applicants.", sortOrder: 20 }),
  scholarship("nanjing-university-cgs-excellence-2026", { slug: "official-2026-nju-cgs-excellence-program", title: "Nanjing University 2026 Chinese Government Scholarship Excellence Program", type: "government", typeLabel: "CSC Excellence Program", providerNameEn: "China Scholarship Council / Nanjing University", fundingLevel: "Full first-year support", coverage: "High-value first-year support covering tuition, on-campus accommodation, living expenses and comprehensive medical insurance, plus economy round-trip airfare for first-year study and second-year thesis defense travel.", applicableDegree: "Master", applicableProgram: "English-taught International Relations, Information Resources Management, and Sociology excellence routes", amountText: "First-year tuition, accommodation, living expenses and medical insurance; specified economy round-trip airfare", deadlineDate: "2026-03-01", deadlineLabel: "NJU application deadline: March 1, 2026", applicationRound: "2026 CSC Excellence intake", benefitItems: [benefit("First-year tuition"), benefit("First-year on-campus accommodation"), benefit("First-year living expenses"), benefit("First-year medical insurance"), benefit("Economy airfare", "Published travel for first-year study and second-year thesis defense")], eligibilityItems: [item("Age", "45 or younger"), item("Education and experience", "Bachelor's degree or above and at least three years of relevant work experience"), item("Professional profile", "Eligible public-sector, senior management, university/research administration, or international-organization experience"), item("English", "TOEFL 85, IELTS 6.0 or Duolingo 100"), item("Concurrent funding", "No other 2026-2027 Chinese scholarship")], applicationMaterials: [item("Highest degree certificate and undergraduate transcript"), item("Two recommendation letters"), item("English proficiency result"), item("Personal statement and research outputs"), item("Physical examination, passport and no-criminal-record certificate"), item("Employment certificate")], applicationSteps: [item("Step 1", "Apply in the NJU system between January 1 and March 1, 2026"), item("Step 2", "Complete program review and obtain a pre-admission notice"), item("Step 3", "Submit the CSC Type A application by March 31, 2026 using agency number 1563"), item("Step 4", "Await CSC final confirmation")], bodySections: [{ title: "Study model", body: "The two-year 1+1 model places full-time study at NJU in year one and thesis completion in the home country in year two, with return to NJU for the defense." }], summary: "A leadership-focused CSC scholarship attached to three specified English-taught NJU master's routes.", sortOrder: 30 }),
  scholarship("nanjing-university-nanjing-government-scholarship-2026", { slug: "official-2026-nju-nanjing-government-scholarship", title: "Nanjing University 2026 Nanjing Government Scholarship for International Students", type: "government", typeLabel: "Municipal scholarship", providerNameEn: "Nanjing Municipal Government / Nanjing University", fundingLevel: "Fixed annual award", coverage: "One-academic-year award for selected full-time international undergraduate and graduate students at NJU.", applicableDegree: "Undergraduate, Master, Doctoral", applicableProgram: "Full-time NJU degree students, including eligible new and continuing students", amountText: "RMB 10,000 for undergraduate students; RMB 20,000 for graduate students", deadlineDate: "2026-08-28", deadlineLabel: "Application window: August 24-28, 2026", applicationRound: "2026-2027 academic year", benefitItems: [benefit("Undergraduate award", "RMB 10,000"), benefit("Graduate award", "RMB 20,000")], eligibilityItems: [item("Status", "Full-time international undergraduate, master's or doctoral student at NJU"), item("Admissions", "Meet NJU international student admission requirements for new students"), item("Concurrent funding", "No other government or university scholarship in the same period"), item("Continuing students", "Must meet the published academic, conduct and school-recommendation standards")], applicationMaterials: [item("Municipal scholarship application form"), item("2026 NJU admission notice", "New students"), item("Valid HSK result"), item("Scholarship conduct commitment"), item("Transcript, recommendation and supporting achievements", "Continuing students, as applicable")], applicationSteps: [item("Step 1", "Prepare the applicant-category-specific documents"), item("Step 2", "Submit one ordered PDF during August 24-28, 2026 following the official file-naming rules"), item("Step 3", "NJU organizes preliminary review and expert evaluation"), item("Step 4", "Await the published result")], bodySections: [{ title: "Award term", body: "The scholarship is valid for one academic year; the official notice publishes 20 undergraduate and 20 graduate places, subject to adjustment without changing the total budget." }], summary: "Nanjing's municipal award for eligible new and continuing full-time international degree students at NJU.", sortOrder: 40 }),
];

const generatedAt = new Date().toISOString();
const candidate: CatalogSeedBundle = { version: 1, generatedAt, cities: prior.cities.map((row: any) => ({ ...row })), schools: prior.schools.map((row: any) => ({ ...row })), programs, programIntakes, scholarships };
const candidateText = `${JSON.stringify(candidate, null, 2)}\n`;
const validation = createCatalogMigrationValidationReport(JSON.parse(candidateText));
if (!validation.ok) throw new Error(`NJU complete candidate validation failed:\n${validation.errors.join("\n")}`);
const candidateSha256 = sha256(candidateText);
const reviewBase = { version: 1, status: "standing_user_approval", generatedAt, scope: { schoolSlug: "nanjing-university", dependencyCityReplayCount: prior.cities.length, dependencySchoolReplayCount: 1, existingUndergraduateRouteCount: 59, newProgramRouteCount: 202, masterRouteCount: 141, doctoralRouteCount: 61, newProgramIntakeCount: 202, newScholarshipCount: 3, archiveProgramAliasCount: 0, archiveScholarshipAliasCount: 0 }, candidateSha256, evidence: [...evidence.values()].map(source => ({ sourceId: source.id, sourceUrl: source.url, sourceLabel: source.label, sha256: source.sha256, fetchedAt: source.fetchedAt })).sort((a, b) => a.sourceId.localeCompare(b.sourceId)), visualReview: { result: "pass", masterPdfPagesReviewed: 14, doctoralPdfPagesReviewed: 6, note: "All 20 official catalog pages were rendered and visually inspected; codes, schools, majors, teaching language, duration and notes are readable." }, standingAuthorization: { reference: "user-chat-2026-09-13-default-publication", instruction: "发布默认允许", appliesBecause: "The batch adds only new non-conflicting graduate routes, intakes and distinct scholarship records. It archives and deletes nothing." }, reconciliation: { actionAfterReview: "insert_new_verified_nju_graduate_routes_and_three_scholarships", destructiveDeletion: false, existingDependencyRowsReplayedByteEquivalently: true, newProgramSlugConflicts: 0, existingGraduateSemanticConflicts: 0, newScholarshipSlugConflicts: 0 }, unresolvedFields: ["Program-specific tuition is linked to the official NJU schedule because the reviewed catalogs do not publish a row-level tuition value.", "Chinese and English admission thresholds are summarized from the official admissions guides and should be confirmed for exceptional routes."], sensitiveDataCheck: { result: "pass", scope: "candidate bundle only", note: "Only public institutional, program, admissions and scholarship data is included. Applicant data is absent and personal contact details are not republished." }, reviewNotes: ["Program identity includes degree, code, language, school and major.", "The verified 2026 NJU Silk Road scholarship remains untouched."] };
const reviewHash = sha256(JSON.stringify(reviewBase));
await writeFile(candidatePath, candidateText, { flag: "wx" });
await writeFile(validationPath, `${JSON.stringify(validation, null, 2)}\n`, { flag: "wx" });
await writeFile(reviewPath, `${JSON.stringify({ ...reviewBase, reviewHash, publicationReference: "standing-user-default-publication" }, null, 2)}\n`, { flag: "wx" });
console.log(JSON.stringify({ ok: true, counts: reviewBase.scope, candidateSha256, bundleSha256: validation.bundleSha256, reviewHash, candidatePath, validationPath, reviewPath }, null, 2));
