import { createHash } from "node:crypto";
import { readFile, writeFile } from "node:fs/promises";
import { resolve } from "node:path";
import { createCatalogMigrationValidationReport, type CatalogSeedBundle } from "../src/server/catalog/seed-contract.ts";
import { createPostgresPool } from "../src/server/db/postgres-client.ts";
import { localDatabaseUrl } from "./lib/local-development.ts";

const root=process.cwd(),paths={complete:resolve(root,"seeds/catalog.hust-complete-batch-01.draft.json"),completeReview:resolve(root,"seeds/catalog.hust-complete-batch-01.review.json"),base:resolve(root,"seeds/catalog.cscalite-online-20260910.published.json"),candidate:resolve(root,"seeds/catalog.hust-safe-new-batch-01.draft.json"),validation:resolve(root,"seeds/catalog.hust-safe-new-batch-01.validation.json"),review:resolve(root,"seeds/catalog.hust-safe-new-batch-01.review.json"),state:resolve(root,".cuac-local/runtime.json")},sha=(value:string|Buffer)=>createHash("sha256").update(value).digest("hex");
const [completeText,completeReviewText,baseText,stateText]=await Promise.all([readFile(paths.complete,"utf8"),readFile(paths.completeReview,"utf8"),readFile(paths.base,"utf8"),readFile(paths.state,"utf8")]),complete=JSON.parse(completeText) as CatalogSeedBundle,completeReview=JSON.parse(completeReviewText),base=JSON.parse(baseText) as CatalogSeedBundle,state=JSON.parse(stateText),schoolSlug="huazhong-university-of-science-and-technology";
if(complete.programs?.length!==466||complete.programIntakes?.length!==466||complete.scholarships?.length!==7||completeReview.reviewHash!=="814c550cf3aa0bf1809881333711bee700e64818f0779163f97fa5b0451f6ebb")throw new Error("HUST complete candidate/review changed.");
const dependencySchool=(base.schools??[]).find((row)=>row.slug===schoolSlug),dependencyCity=(base.cities??[]).find((row)=>row.slug==="wuhan"),stableSlugs:string[]=completeReview.reconciliation.stableProgramSlugs;
if(!dependencySchool||!dependencyCity||stableSlugs.length!==14)throw new Error("HUST dependency or stable-slug set unavailable.");
const programs=complete.programs.filter((row)=>!stableSlugs.includes(row.slug)),safeSet=new Set(programs.map((row)=>row.slug)),programIntakes=complete.programIntakes!.filter((row)=>safeSet.has(row.programSlug));
if(programs.length!==452||programIntakes.length!==452)throw new Error("HUST safe-new route split changed.");
const candidateRaw:CatalogSeedBundle={version:1,generatedAt:complete.generatedAt,cities:[dependencyCity],schools:[dependencySchool],programs,programIntakes,scholarships:complete.scholarships},candidateText=`${JSON.stringify(candidateRaw,null,2)}\n`,candidate=JSON.parse(candidateText) as CatalogSeedBundle,validation=createCatalogMigrationValidationReport(candidate);if(!validation.ok)throw new Error(`Invalid HUST safe-new candidate: ${validation.errors.join(" ")}`);
const programSlugs=programs.map((row)=>row.slug),scholarshipSlugs=complete.scholarships.map((row)=>row.slug),pool=createPostgresPool({databaseUrl:localDatabaseUrl(state),max:1,applicationName:"cuac:hust-safe-new-review"});let baseline:any;
try{const school=await pool.query("select id,status,verification_status,source_url from schools where slug=$1",[schoolSlug]),city=await pool.query("select id,status,verification_status,source_url from cities where slug='wuhan'"),programRows=await pool.query("select id,slug,status,verification_status,source_url from programs where school_id=$1 order by slug",[school.rows[0]?.id]),scholarships=await pool.query("select id,slug,status,verification_status,source_url from scholarships where school_id=$1 order by slug",[school.rows[0]?.id]),programConflicts=await pool.query("select slug from programs where slug=any($1::text[])",[programSlugs]),scholarshipConflicts=await pool.query("select slug from scholarships where slug=any($1::text[])",[scholarshipSlugs]);baseline={school:school.rows,city:city.rows,programRows:programRows.rows,scholarships:scholarships.rows,programConflicts:programConflicts.rows,scholarshipConflicts:scholarshipConflicts.rows};if(school.rows.length!==1||school.rows[0].status!=="active"||school.rows[0].verification_status!=="unverified"||city.rows.length!==1||programRows.rows.length!==15||programRows.rows.some((row:any)=>row.status!=="active"||row.verification_status!=="unverified")||scholarships.rows.length!==1||scholarships.rows[0].slug!=="official-2026-hust-youth-of-excellence-scholarship"||scholarships.rows[0].verification_status!=="verified"||programConflicts.rows.length!==0||scholarshipConflicts.rows.length!==0)throw new Error(`HUST safe-new baseline changed: ${JSON.stringify(baseline)}`);}finally{await pool.end();}
const reviewBase={version:1,status:"standing_user_approval",generatedAt:candidate.generatedAt,scope:{schoolSlug,dependencyCityReplayCount:1,dependencySchoolReplayCount:1,newProgramRouteCount:452,newProgramIntakeCount:452,newScholarshipCount:7,overwriteCount:0,archiveCount:0},candidateSha256:sha(candidateText),candidateBundleSha256:validation.bundleSha256,operationPlanSha256:validation.operationPlanSha256,completeReviewSha256:sha(completeReviewText),standingAuthorization:{reference:"user-chat-2026-09-13-default-publication",instruction:"发布默认允许",appliesBecause:"The operation inserts 452 new official program routes, their intakes and seven new rich scholarships. It overwrites, archives and deletes nothing; Wuhan and HUST dependencies replay the current imported records."},reconciliation:{destructiveDeletion:false,overwrites:[],archives:[],programSlugConflicts:0,scholarshipSlugConflicts:0,stableProgramOverwritesDeferred:stableSlugs,legacyProgramArchiveDeferred:completeReview.reconciliation.legacyProgramAliasesToArchive,stableVerifiedScholarshipPreserved:{id:baseline.scholarships[0].id,slug:baseline.scholarships[0].slug},databaseBaseline:{schoolId:baseline.school[0].id,cityId:baseline.city[0].id,existingProgramIds:baseline.programRows.map((row:any)=>row.id)}},sourceReview:completeReview.sourceReview??completeReview.visualReview,sensitiveDataCheck:{result:"pass",scope:"publication candidate",note:"Public institutional, program, admissions and scholarship fields only; applicant, account, payment and personal-contact data are excluded."},coverageLimitations:["Fourteen matching unverified program slugs and one legacy program alias remain unchanged for explicit cleanup approval.","The unverified HUST school profile remains unchanged in this safe-new batch.","The existing verified Youth of Excellence scholarship remains unchanged and is not duplicated."]};
const reviewHash=sha(JSON.stringify(reviewBase));await Promise.all([writeFile(paths.candidate,candidateText,"utf8"),writeFile(paths.validation,`${JSON.stringify(validation,null,2)}\n`,"utf8"),writeFile(paths.review,`${JSON.stringify({...reviewBase,reviewHash,publicationReference:"standing-user-default-publication"},null,2)}\n`,"utf8")]);console.log(JSON.stringify({ok:true,reviewHash,scope:reviewBase.scope,paths},null,2));
