import { createHash } from "node:crypto";
import { readFile, writeFile } from "node:fs/promises";
import { resolve } from "node:path";
import { createCatalogMigrationValidationReport, type CatalogSeedBundle, type CatalogSeedProgram, type CatalogSeedScholarship } from "../src/server/catalog/seed-contract.ts";

const root = process.cwd();
const schoolSlug = "nankai-university";
const paths = { parsed: resolve(root, "work/catalog-official/nankai-complete-batch-01/parsed-programs.json"), manifest: resolve(root, "work/catalog-official/nankai-complete-batch-01/manifest.json"), masterManifest: resolve(root, "work/catalog-official/nankai-complete-batch-01-master/manifest.json"), draft: resolve(root, "seeds/catalog.nankai-complete-batch-01.draft.json"), validation: resolve(root, "seeds/catalog.nankai-complete-batch-01.validation.json"), review: resolve(root, "seeds/catalog.nankai-complete-batch-01.review.json") };
const expectedParsedSha256 = "7d40f288e74ab4450646a96dcbd8603cc96c7ae76abd3ce25129c949a31e100c";
const sha = (value: string | Buffer) => createHash("sha256").update(value).digest("hex");
const parsedText = await readFile(paths.parsed, "utf8"); if (sha(parsedText) !== expectedParsedSha256) throw new Error("Parsed Nankai program artifact changed after visual review.");
const parsed = JSON.parse(parsedText); if (JSON.stringify(parsed.counts) !== JSON.stringify({ Undergraduate: 41, Master: 171, Doctoral: 127 }) || parsed.programCount !== 339) throw new Error("Nankai parsed counts mismatch.");
const manifests = [JSON.parse(await readFile(paths.manifest, "utf8")), JSON.parse(await readFile(paths.masterManifest, "utf8"))];
const expected: Record<string, string> = {
  "nankai-silk-road-scholarship-2026": "b9cede0af5d1e4edb44b8282f546c776bb9eff46109d5bc06211c1281e817f22",
  "nankai-undergraduate-admissions-2026": "807f7bf793268f7e60874649e186b1ba99bcd185003e8988e67aa653e09a7ce3",
  "nankai-undergraduate-program-catalog-pdf-2026": "7996b633d39240e02676ca6cfcc795239da3af5419e6f8239a202002291c2852",
  "nankai-master-admissions-2026": "3bf303ec6358f7336a5777aaa9a4958db8fdfa924066a1c8fea85e81f649f9ac",
  "nankai-master-program-catalog-page-2026": "4d05ff47503151fb1ce43113a4c6e384c90aa53c6250c16ea5888e6bfcfab8a1",
  "nankai-master-program-catalog-pdf-2026": "72884af99cee18bd9bb13ff455dd8bca6017903404a0474cbd340290f4ef5d44",
  "nankai-doctoral-admissions-2026": "52abf0b3a574a25674b71ab4fea7fea8991960c88e0b5564647cfafc665f13bb",
  "nankai-doctoral-program-catalog-pdf-2026": "a7b7a5e9e1e25e72d16f8adcf947289ac1c1b95b9a80317cd6706b66250a93b8",
  "nankai-cgs-type-b-scholarship-2026": "399428a0cda9f221742929cf3d5326a7797b50bf474265c867de92816f614dc8",
};
const evidence = new Map<string, any>(); for (const manifest of manifests) for (const row of manifest.sources ?? []) if (expected[row.id] === row.sha256 && row.status === 200) evidence.set(row.id, row);
const missing = Object.keys(expected).filter(id => !evidence.has(id)); if (missing.length) throw new Error(`Missing locked Nankai evidence: ${missing.join(", ")}`);
const slugify = (value: string) => value.toLowerCase().replace(/&/g, " and ").replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");
const used = new Set<string>();
const admissionsByDegree: Record<string, any> = { Undergraduate: evidence.get("nankai-undergraduate-admissions-2026"), Master: evidence.get("nankai-master-admissions-2026"), Doctoral: evidence.get("nankai-doctoral-admissions-2026") };
function programSlug(row: any, index: number) { const base = `${schoolSlug}-${row.degreeLevel.toLowerCase()}-${slugify(row.school)}-${slugify(row.name)}-${slugify(row.teachingLanguage)}-${row.tuitionCnyPerYear}-${String(row.durationYears).replace(".", "-")}`; const result = used.has(base) ? `${base}-${index + 1}` : base; used.add(result); return result; }
const programs: CatalogSeedProgram[] = parsed.programs.map((row: any, index: number) => {
  const source = evidence.get(row.sourceId); const csca = row.degreeLevel === "Undergraduate" ? row.cscaSubjects : undefined;
  const language = row.teachingLanguage;
  const requirement = language.includes("English") ? { englishRequirement: row.degreeLevel === "Undergraduate" ? "Program-specific English standard where applicable; the catalog publishes IELTS/TOEFL or equivalent requirements for selected bilingual routes." : "IELTS 6.0, TOEFL 80 or Duolingo 105; stated exemptions require official evidence." } : { hskRequirement: row.degreeLevel === "Undergraduate" ? "HSK Level 4 score 180 for general admission; several catalog routes publish HSK Level 5 or other program-specific thresholds." : "HSK Level 5 score 180; the College of Chinese Language and Culture and School of Literature require HSK Level 6 score 180 before graduation." };
  return { slug: programSlug(row, index), schoolSlug, citySlug: "tianjin", nameEn: row.name, degreeLevel: row.degreeLevel, durationYears: Math.ceil(row.durationYears), fieldCategory: row.school, subjectArea: row.school, teachingLanguage: language, ...requirement, ...(csca?.length ? { cscaSubjects: csca, cscaRequirement: `2026 undergraduate CSCA subjects: ${csca.join(", ")}.` } : { cscaRequirement: "No CSCA requirement is published for this graduate route." }), tuitionAmount: row.tuitionCnyPerYear, tuitionCurrency: "RMB", tuitionPeriod: "year", tuitionText: `RMB ${Number(row.tuitionCnyPerYear).toLocaleString("en-US")}/year`, displayTuition: `RMB ${Number(row.tuitionCnyPerYear).toLocaleString("en-US")}/year`, scholarshipText: "Nankai's official Chinese Government, Tianjin Government, university and language-teacher scholarship routes are reviewed separately.", applicationUrl: "https://nankai.at0086.cn/StuApplication/Login.aspx", applicationNote: `${row.school}${row.campus ? `; ${row.campus} campus` : ""}; published duration ${row.durationYears} years; ${row.sourceLocator}.`, hasScholarship: true, badgeText: `Official ${row.degreeLevel.toLowerCase()} route`, displaySubjects: csca, displayGroup: row.degreeLevel, displayGroupLabel: `${row.degreeLevel} programs`, status: "draft", sourceUrl: source.url, sourceLabel: source.label, sourceSha256: source.sha256, capturedAt: source.fetchedAt, sourceFieldLineage: { nameEn: `${row.sourceLocator}, English program/major column`, degreeLevel: "official PDF title", fieldCategory: `${row.sourceLocator}, English school column`, teachingLanguage: `${row.sourceLocator}, language column`, durationYears: `${row.sourceLocator}, study length column; 2.5-year route is represented as 3 due to the integer schema and exact source value is retained in applicationNote`, tuitionAmount: `${row.sourceLocator}, tuition fee column`, applicationNote: `${row.sourceLocator}${row.campus ? ", campus column" : ""}`, ...(csca?.length ? { cscaSubjects: `${row.sourceLocator}, CSCA Test Subject column` } : {}) } };
});
if (programs.length !== 339 || new Set(programs.map(row => row.slug)).size !== 339) throw new Error("Nankai program routes/slugs mismatch.");
const info = (label: string, value?: string) => ({ label, ...(value ? { value } : {}) }); const benefit = (label: string) => ({ label, included: true });
function scholarship(sourceId: string, value: Partial<CatalogSeedScholarship> & Pick<CatalogSeedScholarship, "slug" | "title" | "fundingLevel" | "coverage" | "applicableDegree" | "amountText">): CatalogSeedScholarship { const source = evidence.get(sourceId); return { schoolSlug, status: "draft", sourceUrl: source.url, sourceLabel: source.label, sourceSha256: source.sha256, capturedAt: source.fetchedAt, providerLocation: "China", targetCountries: [], targetRegions: [], actionLinks: [{ label: source.label, url: source.url, kind: "official-source" }, { label: "Nankai international student application system", url: "https://nankai.at0086.cn/StuApplication/Login.aspx", kind: "official-application" }], sourceFieldLineage: { title: "official notice title", fundingLevel: "official scholarship coverage section", coverage: "official scholarship coverage section", amountText: "official scholarship coverage section", applicableDegree: "official eligibility/program section", applicableProgram: "official program section", eligibilityItems: "official eligibility section", applicationMaterials: "official application documents section", applicationSteps: "official application procedure section", deadlineDate: "official application deadline section" }, ...value }; }
const commonMaterials = [info("Passport information page"), info("Highest diploma or expected-graduation proof"), info("Academic transcripts"), info("Language qualification certificate"), info("Study plan or personal statement"), info("Recommendation letters required by degree"), info("Foreigner Physical Examination Form"), info("Non-criminal record certificate")];
const scholarships: CatalogSeedScholarship[] = [
  scholarship("nankai-cgs-type-b-scholarship-2026", { slug: "official-2026-nankai-cgs-type-b", title: "Nankai University 2026 Chinese Government Scholarship Type B", nameZh: "南开大学2026年中国政府奖学金B类高校项目", type: "government", typeLabel: "Chinese Government Scholarship Type B", providerName: "中华人民共和国教育部 / 国家留学基金管理委员会", providerNameEn: "Ministry of Education of the PRC / China Scholarship Council", fundingLevel: "Full", coverage: "Tuition waiver, on-campus accommodation or accommodation subsidy, stipend under the applicable CSC standard, and comprehensive medical insurance", applicableDegree: "Master", applicableProgram: "Eligible Nankai 2026 international master's programs", amountText: "Tuition waiver, accommodation support, stipend under the CSC standard and comprehensive medical insurance; the reviewed Nankai page does not restate fixed stipend amounts.", deadlineDate: "2026-03-20", deadlineLabel: "October 20, 2025 - March 20, 2026", applicationRound: "2026 Chinese Government Scholarship Type B", benefitItems: [benefit("Tuition waiver"), benefit("Free on-campus accommodation or accommodation subsidy"), benefit("Stipend under the applicable CSC standard"), benefit("Comprehensive medical insurance")], eligibilityItems: [info("Nationality", "Non-Chinese citizen with a valid passport"), info("Degree route", "Meets the requirements of an eligible Nankai 2026 master's program"), info("Concurrent funding", "May not hold another Chinese-government or Nankai scholarship concurrently")], applicationMaterials: [info("Chinese Government Scholarship application form"), ...commonMaterials, info("Pre-admission document"), info("Two professor or associate-professor recommendations")], applicationSteps: [info("Step 1", "Apply in Nankai's international student system"), info("Step 2", "Apply in the CSC system as Type B using Nankai agency number 10055"), info("Step 3", "Submit all admission and scholarship documents"), info("Step 4", "Attend an online interview if shortlisted and await CSC final approval")], bodySections: [{ title: "Scholarship review", body: "Nankai conducts document and interview review; the final award is subject to China Scholarship Council approval." }], summary: "Nankai's 2026 full Chinese Government Scholarship Type B route for eligible international master's applicants.", sortOrder: 10 }),
  scholarship("nankai-silk-road-scholarship-2026", { slug: "official-2026-nankai-silk-road-scholarship", title: "Nankai University 2026 Chinese Government Scholarship - Silk Road Program", nameZh: "南开大学2026年中国政府奖学金丝绸之路项目", type: "government", typeLabel: "Chinese Government Scholarship - Silk Road Program", providerName: "国家留学基金管理委员会 / 南开大学", providerNameEn: "China Scholarship Council / Nankai University", fundingLevel: "Full", coverage: "Tuition waiver, free on-campus accommodation, monthly living stipend and comprehensive medical insurance", applicableDegree: "Bachelor, Master", applicableProgram: "Business Economics, Business Administration, Finance, International Business, and International Affairs and Public Policy in the published teaching languages", amountText: "Monthly stipend: CNY 2,500 for bachelor's students and CNY 3,000 for master's students, plus tuition, on-campus accommodation and medical insurance.", deadlineDate: "2026-05-18", deadlineLabel: "May 18, 2026", applicationRound: "2026 Silk Road Program", targetCountries: ["Vietnam", "Malaysia", "Thailand", "Myanmar", "Pakistan", "Mongolia", "Indonesia", "Uzbekistan", "Kazakhstan", "Colombia"], benefitItems: [benefit("Tuition waiver"), benefit("Free on-campus accommodation"), benefit("CNY 2,500/month bachelor's stipend"), benefit("CNY 3,000/month master's stipend"), benefit("Comprehensive medical insurance")], eligibilityItems: [info("Nationality and health", "Non-Chinese citizen in good physical and mental health, with no criminal record"), info("Bachelor", "High-school diploma and under 25"), info("Master", "Bachelor's degree and under 35"), info("Chinese route", "HSK Level 5 score 210 or above"), info("English route", "IELTS 6.0, TOEFL 80 or Duolingo 105, with stated exemptions"), info("Concurrent funding", "May not hold another scholarship")], applicationMaterials: commonMaterials, applicationSteps: [info("Step 1", "Apply in Nankai's international student system"), info("Step 2", "Participate in Nankai review and interview"), info("Step 3", "Nominees receive pre-admission and apply in the CSC system as Type B using agency number 10055"), info("Step 4", "CSC makes the final decision and Nankai issues admission documents")], bodySections: [{ title: "Eligible programs", items: ["Business Economics - Bachelor - Chinese", "Business Administration - Bachelor - Chinese", "Finance - Bachelor - Chinese", "International Business - Master - Chinese or English", "International Affairs and Public Policy - Master - English"] }], summary: "Nankai's 2026 Silk Road full scholarship for five specified bachelor's and master's routes and ten published countries.", sortOrder: 20 }),
];
const schoolSource = evidence.get("nankai-undergraduate-admissions-2026");
const candidate: CatalogSeedBundle = { version: 1, generatedAt: manifests[0].generatedAt,
  cities: [{ slug: "tianjin", nameEn: "Tianjin", nameZh: "天津", region: "North China", status: "draft", sourceUrl: schoolSource.url, sourceLabel: schoolSource.label, sourceSha256: schoolSource.sha256, capturedAt: schoolSource.fetchedAt, sourceFieldLineage: { nameEn: "official Nankai campus/contact address", nameZh: "normalized Chinese city name", region: "normalized geographic region from official Tianjin address" } }],
  schools: [{ slug: schoolSlug, nameEn: "Nankai University", nameZh: "南开大学", citySlug: "tianjin", schoolType: "public", region: "Tianjin, North China", applicationLevel: "Undergraduate, Master, Doctoral", languageOfInstruction: "Chinese and English depending on route", languageRequirement: "Chinese-taught routes require HSK and English-taught routes require IELTS, TOEFL, Duolingo or stated equivalent evidence; program-specific undergraduate requirements may be higher.", hskRequirement: "Undergraduate general admission: HSK Level 4 score 180; selected catalog routes require HSK Level 5. Graduate Chinese routes: HSK Level 5 score 180, with HSK Level 6 score 180 for specified literature/language schools before graduation.", englishRequirement: "Graduate English routes: IELTS 6.0, TOEFL 80 or Duolingo 105; undergraduate thresholds are program-specific where applicable.", deadlineSummary: "2026 undergraduate applications: October 20, 2025-June 30, 2026. Graduate applications: October 20, 2025-May 31, 2026. Scholarship deadlines vary by route.", tuitionSummary: "Official 2026 annual tuition by route ranges from RMB 20,000 to RMB 164,000.", applicationFee: "RMB 400 undergraduate; RMB 600 graduate", websiteUrl: "https://www.nankai.edu.cn/", admissionsUrl: "https://ensie.nankai.edu.cn/", cscaRequired: true, cscaRequirement: "2026 international undergraduate applicants must submit CSCA scores in the program-specific subjects published in the official catalog; graduate routes do not publish a CSCA requirement.", cscaSubjects: ["Chinese where specified", "Mathematics", "Physics and/or Chemistry for selected routes"], subjectTags: [...new Set(programs.map(row => row.fieldCategory).filter(Boolean))] as string[], languageTags: [...new Set(programs.map(row => row.teachingLanguage).filter(Boolean))] as string[], tuitionBandLabel: "RMB 20,000-164,000/year", campusHighlights: ["339 official international degree routes", "41 undergraduate, 171 master's and 127 doctoral routes", "Balitai and Jinnan campuses", "Chinese- and English-taught routes", "Independent 2026 scholarship records"], status: "draft", sourceUrl: schoolSource.url, sourceLabel: schoolSource.label, sourceSha256: schoolSource.sha256, capturedAt: schoolSource.fetchedAt, sourceFieldLineage: { nameEn: "official 2026 admission guide title", citySlug: "official campus/contact address", applicationLevel: "three official 2026 degree guides", languageRequirement: "official eligibility sections and program catalogs", deadlineSummary: "official application-date sections", tuitionSummary: "three official program catalogs", applicationFee: "official fee sections", admissionsUrl: "official Nankai international admissions site", cscaRequirement: "official 2026 undergraduate guide and catalog" } }],
  programs,
  programIntakes: programs.map(program => { const source = admissionsByDegree[program.degreeLevel!]; const deadline = program.degreeLevel === "Undergraduate" ? "2026-06-30T00:00:00.000Z" : "2026-05-31T00:00:00.000Z"; return { programSlug: program.slug, intakeTerm: "Fall", intakeYear: 2026, deadlineDate: deadline, deadlineLabel: program.degreeLevel === "Undergraduate" ? "Application deadline: June 30, 2026" : "Application deadline: May 31, 2026", applicationRound: "2026 international degree intake", status: "closed" as const, sourceUrl: source.url, sourceLabel: source.label, sourceSha256: source.sha256, capturedAt: source.fetchedAt, sourceFieldLineage: { deadlineDate: "official 2026 degree guide application-date section; date-only value normalized to ISO UTC" } }; }),
  scholarships,
};
const candidateText = `${JSON.stringify(candidate, null, 2)}\n`; const persisted = JSON.parse(candidateText); const validation = createCatalogMigrationValidationReport(persisted); if (!validation.ok) throw new Error(`Nankai candidate validation failed:\n${validation.errors.join("\n")}`); const candidateSha256 = sha(candidateText);
const oldProgramSlugs = ["nankai-university-accounting","nankai-university-business-administration","nankai-university-chinese-language-and-business","nankai-university-economics","nankai-university-finance","nankai-university-financial-engineering","nankai-university-insurance","nankai-university-international-economics-and-trade","nankai-university-marketing","nankai-university-teaching-chinese-to-speakers-of-other-languages"];
const reviewBase: any = { version: 1, status: "awaiting_user_approval", generatedAt: candidate.generatedAt, scope: { schoolSlug, cityOverwriteCount: 1, schoolOverwriteCount: 1, programRouteCount: 339, undergraduateRouteCount: 41, masterRouteCount: 171, doctoralRouteCount: 127, programIntakeCount: 339, scholarshipCount: 2, newScholarshipCount: 1, stableScholarshipUpdateCount: 1, archiveProgramAliasCount: 10, archiveScholarshipAliasCount: 1 }, candidateSha256, candidateBundleSha256: validation.bundleSha256, operationPlanSha256: validation.operationPlanSha256, evidence: [...evidence.values()].sort((a,b) => a.id.localeCompare(b.id)).map(row => ({ sourceId: row.id, sourceUrl: row.url, sourceLabel: row.label, sha256: row.sha256, fetchedAt: row.fetchedAt, contentType: row.contentType })), visualReview: { result: "pass", undergraduatePdfPagesReviewed: 4, masterPdfPagesReviewed: 12, doctoralPdfPagesReviewed: 7, note: "All 23 official program catalog pages were rendered and visually inspected; school, program, language, tuition, duration, campus and CSCA columns are legible." }, reconciliation: { destructiveDeletion: false, cityOverwrite: { slug: "tianjin", previousSource: "unverified third-party source", replacementSource: "verified Nankai official source" }, schoolOverwrite: { slug: schoolSlug, previousSource: "unverified third-party source", replacementSource: "verified Nankai official source" }, stableScholarshipUpdateSlugs: ["official-2026-nankai-silk-road-scholarship"], legacyProgramAliasesToArchive: oldProgramSlugs, legacyScholarshipAliasesToArchive: ["nankai-university"] }, officialInconsistencies: [{ field: "Chinese Government Scholarship Type B agency number", scholarshipSpecificPage: "10055", graduateOverview: "10056", decision: "Use 10055 from the scholarship-specific 2026 page and disclose the conflict." }, { field: "Chinese Government Scholarship Type B deadline", scholarshipSpecificPage: "March 20, 2026", graduateOverview: "March 10, 2026", decision: "Use March 20 from the scholarship-specific 2026 page and disclose the conflict." }], sensitiveDataCheck: { result: "pass", scope: "candidate bundle only", note: "Only public institutional, program, admissions and scholarship information is included. Applicant records, private files, personal contact details, account data and payment data are absent." }, reviewNotes: ["The 10 legacy programs and one generic scholarship are proposed for archival, not deletion.", "The existing verified Silk Road slug is updated in place with richer fields from the current official notice.", "Program identity includes degree, school, English program name, teaching language, tuition and duration so official academic/professional variants remain distinct.", "This batch cannot use standing default publication because it replaces existing city/school data, updates an existing scholarship and archives legacy aliases."] };
const reviewHash = sha(JSON.stringify(reviewBase)); const review = { ...reviewBase, reviewHash, publicationReference: `product-owner-approved-nankai-complete-batch-01-${reviewHash}` };
await Promise.all([writeFile(paths.draft, candidateText, "utf8"), writeFile(paths.validation, `${JSON.stringify(validation, null, 2)}\n`, "utf8"), writeFile(paths.review, `${JSON.stringify(review, null, 2)}\n`, "utf8")]);
console.log(JSON.stringify({ ok: true, counts: reviewBase.scope, candidateSha256, candidateBundleSha256: validation.bundleSha256, reviewHash, publicationReference: review.publicationReference, paths }, null, 2));
