import { createHash } from "node:crypto";
import { readFile, writeFile } from "node:fs/promises";
import { resolve } from "node:path";
import { createCatalogMigrationValidationReport, type CatalogSeedBundle, type CatalogSeedProgram, type CatalogSeedScholarship } from "../src/server/catalog/seed-contract.ts";

const root = process.cwd();
const manifestPath = resolve(root, "work/catalog-official/2026-09-22T11-29-19-610Z/manifest.json");
const cityPath = resolve(root, "seeds/catalog.qingdao-city-rich-batch-01.draft.json");
const candidatePath = resolve(root, "seeds/catalog.qdu-complete-batch-01.draft.json");
const validationPath = resolve(root, "seeds/catalog.qdu-complete-batch-01.validation.json");
const [manifestText, cityText] = await Promise.all([readFile(manifestPath, "utf8"), readFile(cityPath, "utf8")]);
const manifest = JSON.parse(manifestText), cityBundle = JSON.parse(cityText);
type SourceRecord = { id: string; status: number; url: string; label: string; sha256: string; fetchedAt: string };
const sources = new Map<string, SourceRecord>(((manifest.sources || []) as SourceRecord[]).map(row => [row.id, row]));
const expected = {
  "qdu-international-undergraduate-guide-pdf-2026": "28277e2c56f520c788f90025d18b2dfcf372f889b15c9b4e66910220e221c581",
  "qdu-mbbs-guide-pdf-2026": "ebee719595a3f12a3ad005592f371434f1dd9bb7b9e3f802b72ea3809b62da6c",
  "qdu-chinese-language-guide-pdf-spring-2027": "8d1d53c41f45e9e4a56617b95250f6c743714cd118fceb41a1e85b4ecf1b99b1",
  "qdu-presidential-scholarship-2026": "b13924b429cd35f8a9af09261e2a46b119d5af49f7e89c79ae1af0fc82324a14",
} as const;
for (const [id, digest] of Object.entries(expected)) {
  const source = sources.get(id);
  if (!source || source.status !== 200 || source.sha256 !== digest) throw new Error(`QDU evidence mismatch: ${id}`);
}
const ug = sources.get("qdu-international-undergraduate-guide-pdf-2026");
const mbbsSource = sources.get("qdu-mbbs-guide-pdf-2026");
const languageSource = sources.get("qdu-chinese-language-guide-pdf-spring-2027");
const president = sources.get("qdu-presidential-scholarship-2026");
const schoolSlug = "qingdao-university", citySlug = "qingdao";

const program = (values: Partial<CatalogSeedProgram> & Pick<CatalogSeedProgram, "slug" | "nameEn" | "degreeLevel" | "teachingLanguage" | "sourceUrl" | "sourceLabel" | "sourceSha256" | "capturedAt">): CatalogSeedProgram => ({
  schoolSlug, citySlug, fieldCategory: "Chinese Language", subjectArea: values.nameEn, durationYears: 4,
  applicationUrl: values.sourceUrl, applicationNote: "Apply through Qingdao University's international student application system.",
  hasScholarship: true, status: "draft", sourceFieldLineage: {}, ...values,
});
const programs: CatalogSeedProgram[] = [
  program({ slug: `${schoolSlug}-chinese-language-and-literature`, nameEn: "Chinese Language and Literature", nameZh: "汉语言文学", degreeLevel: "Undergraduate", durationYears: 4, teachingLanguage: "Chinese", cscaSubjects: ["Mathematics"], cscaRequirement: "CSCA Mathematics is required.", hskRequirement: "HSK Level 4 score 210 and HSKK Intermediate score 60.", tuitionAmount: 18000, tuitionCurrency: "CNY", tuitionPeriod: "year", tuitionText: "CNY 18,000/year", scholarshipText: "The official guide identifies the International Chinese Language Teachers Scholarship as available.", sourceUrl: ug.url, sourceLabel: ug.label, sourceSha256: ug.sha256, capturedAt: ug.fetchedAt, sourceFieldLineage: { nameEn: "PDF page 1 official bilingual title", nameZh: "PDF page 1", degreeLevel: "PDF page 1", durationYears: "PDF page 1", teachingLanguage: "PDF page 1", cscaSubjects: "PDF page 1", hskRequirement: "PDF page 1", tuitionAmount: "PDF page 5 fee table" } }),
  program({ slug: `${schoolSlug}-dual-degree-in-chinese-language-and-international-politics`, nameEn: "Dual-degree in Chinese Language and International Politics", nameZh: "汉语言文学+国际政治 双学位本科专业", degreeLevel: "Undergraduate", durationYears: 4, teachingLanguage: "Chinese", cscaSubjects: ["Chinese for Humanities", "Mathematics"], cscaRequirement: "CSCA Chinese for Humanities and Mathematics are required.", hskRequirement: "HSK Level 4 score 180 or above.", tuitionAmount: 27000, tuitionCurrency: "CNY", tuitionPeriod: "year", tuitionText: "CNY 27,000/year", scholarshipText: "The official guide identifies the International Chinese Language Teachers Scholarship as available.", sourceUrl: ug.url, sourceLabel: ug.label, sourceSha256: ug.sha256, capturedAt: ug.fetchedAt, sourceFieldLineage: { nameEn: "PDF page 1 official bilingual title", nameZh: "PDF page 1", degreeLevel: "PDF page 1", durationYears: "PDF page 1", teachingLanguage: "PDF page 1", cscaSubjects: "PDF pages 1-2", hskRequirement: "PDF page 1", tuitionAmount: "PDF page 5 fee table" } }),
  program({ slug: `${schoolSlug}-dual-degree-in-chinese-language-and-business-administration`, nameEn: "Dual-degree in Chinese language & Business Administration", nameZh: "汉语言文学+工商管理 双学位本科专业", degreeLevel: "Undergraduate", durationYears: 4, fieldCategory: "Business Administration", subjectArea: "Business Administration", teachingLanguage: "Chinese", cscaSubjects: ["Chinese for Humanities", "Mathematics"], cscaRequirement: "CSCA Chinese for Humanities and Mathematics are required.", hskRequirement: "HSK Level 4 score 180 or above.", tuitionAmount: 27000, tuitionCurrency: "CNY", tuitionPeriod: "year", tuitionText: "CNY 27,000/year", scholarshipText: "The official guide identifies the International Chinese Language Teachers Scholarship as available.", sourceUrl: ug.url, sourceLabel: ug.label, sourceSha256: ug.sha256, capturedAt: ug.fetchedAt, sourceFieldLineage: { nameEn: "PDF page 1 official bilingual title", nameZh: "PDF page 1", degreeLevel: "PDF page 1", durationYears: "PDF page 1", teachingLanguage: "PDF page 1", cscaSubjects: "PDF pages 1-2", hskRequirement: "PDF page 1", tuitionAmount: "PDF page 5 fee table" } }),
  program({ slug: `${schoolSlug}-mbbs-program-in-english`, nameEn: "MBBS Program (in English)", nameZh: "临床医学本科专业（英文授课）", degreeLevel: "Undergraduate", durationYears: 6, fieldCategory: "Medicine", subjectArea: "Clinical Medicine (MBBS)", teachingLanguage: "English", cscaSubjects: ["Mathematics", "Chemistry"], cscaRequirement: "CSCA Mathematics and Chemistry are required.", englishRequirement: "Strong English ability; non-English-speaking applicants must provide English study records or a standardized English proficiency certificate.", tuitionAmount: 30000, tuitionCurrency: "CNY", tuitionPeriod: "year", tuitionText: "CNY 30,000/year; the guide separately lists an CNY 800 application fee", scholarshipText: "No scholarship entitlement is stated in the MBBS guide.", sourceUrl: mbbsSource.url, sourceLabel: mbbsSource.label, sourceSha256: mbbsSource.sha256, capturedAt: mbbsSource.fetchedAt, sourceFieldLineage: { nameEn: "PDF page 1 official bilingual title", nameZh: "PDF page 1", degreeLevel: "PDF title", durationYears: "PDF page 1", teachingLanguage: "PDF page 1", cscaSubjects: "PDF page 2", englishRequirement: "PDF page 2", tuitionAmount: "PDF page 3 fee table" } }),
  program({ slug: `${schoolSlug}-non-degree-chinese-language-spring-2027`, nameEn: "Chinese Language Program - Spring 2027", nameZh: "2027年春季学期外国留学生语言生项目", degreeLevel: "Non-degree", durationMonths: 5, fieldCategory: "Chinese Language", subjectArea: "Chinese Language Study", teachingLanguage: "Chinese", tuitionAmount: 7000, tuitionCurrency: "CNY", tuitionPeriod: "semester", tuitionText: "CNY 7,000/semester; the guide separately lists a CNY 400 application fee", hasScholarship: false, scholarshipText: undefined, applicationNote: "March-July 2027 semester; dates remain subject to the admission notice.", sourceUrl: languageSource.url, sourceLabel: languageSource.label, sourceSha256: languageSource.sha256, capturedAt: languageSource.fetchedAt, sourceFieldLineage: { nameEn: "PDF official English title", nameZh: "PDF official Chinese title", degreeLevel: "language-program title", durationMonths: "March-July 2027 schedule", teachingLanguage: "class structure", tuitionAmount: "PDF fee section" } }),
];
const intakes = programs.map(p => {
  const isMbbs = p.slug.endsWith("mbbs-program-in-english"), isLanguage = p.degreeLevel === "Non-degree";
  const source = isMbbs ? mbbsSource : isLanguage ? languageSource : ug;
  return { programSlug: p.slug, intakeTerm: isLanguage ? "Spring" : isMbbs ? "Fall" : "Fall", intakeYear: isLanguage ? 2027 : 2026,
    deadlineDate: isLanguage ? "2026-12-11T15:59:59.000Z" : isMbbs ? "2026-09-04T15:59:59.000Z" : "2026-05-31T15:59:59.000Z",
    deadlineLabel: isLanguage ? "Before December 11, 2026" : isMbbs ? "Before September 4, 2026" : "Before May 31, 2026",
    applicationRound: isLanguage ? "Spring 2027 Chinese language program" : isMbbs ? "2026 MBBS admission" : "2026 international undergraduate admission",
    status: (isLanguage ? "open" : "closed") as "open" | "closed", sourceUrl: source.url, sourceLabel: source.label, sourceSha256: source.sha256, capturedAt: source.fetchedAt,
    sourceFieldLineage: { deadlineDate: "official PDF application deadline", intakeYear: "official PDF title and schedule" } };
});

const scholarship: CatalogSeedScholarship = {
  slug: schoolSlug, schoolSlug, title: "Qingdao University 2026 Presidential Scholarship for International Applicants", nameZh: "青岛大学2026年校长奖学金", type: "university", typeLabel: "Qingdao University Presidential Scholarship", providerName: "青岛大学", providerNameEn: "Qingdao University", providerLocation: "Qingdao, Shandong, China", fundingLevel: "Full", coverage: "Tuition, on-campus accommodation, doctoral living allowance and comprehensive medical insurance.", applicableDegree: "Doctoral", applicableProgram: "Eligible Qingdao University doctoral programs; the 2026 page publishes five doctoral quotas.", amountText: "CNY 3,500/month living allowance plus tuition, on-campus accommodation and comprehensive medical insurance.", deadlineDate: "2026-04-20", deadlineLabel: "April 20, 2026", applicationRound: "2026 Presidential Scholarship", targetCountries: [], targetRegions: [], benefitItems: [{ label: "Tuition", included: true }, { label: "On-campus accommodation", included: true }, { label: "Living allowance", included: true, note: "CNY 3,500/month for doctoral recipients" }, { label: "Comprehensive medical insurance", included: true }], eligibilityItems: [{ label: "Citizenship and health", value: "Non-Chinese citizen in good health" }, { label: "Age", value: "Doctoral applicant under 40" }, { label: "Admission requirements", value: "Must satisfy the 2026 international graduate admission requirements" }, { label: "Other funding", value: "May not hold more than one scholarship" }], applicationMaterials: [{ label: "Qingdao University graduate application" }, { label: "Registration-fee payment evidence" }, { label: "Signed Qingdao University international student application form" }], applicationSteps: [{ label: "Step 1", value: "Apply through the university international student system" }, { label: "Step 2", value: "Upload payment evidence after registration review" }, { label: "Step 3", value: "Email the signed application form and payment evidence as instructed" }], actionLinks: [{ label: president.label, url: president.url, kind: "official-source" }], summary: "Closed 2026 full Qingdao University Presidential Scholarship route with five published doctoral quotas.", status: "draft", sourceUrl: president.url, sourceLabel: president.label, sourceSha256: president.sha256, capturedAt: president.fetchedAt, sourceFieldLineage: { title: "official page title", fundingLevel: "coverage section", coverage: "coverage section", applicableDegree: "published doctoral quota and allowance", deadlineDate: "application-time section", eligibilityItems: "eligibility section", applicationMaterials: "application procedure", applicationSteps: "application procedure" },
};

const candidate: CatalogSeedBundle = { version: 1, generatedAt: manifest.generatedAt, cities: [cityBundle.cities[0]], schools: [{ slug: schoolSlug, nameEn: "Qingdao University", nameZh: "青岛大学", citySlug, schoolType: "Public", region: "Qingdao, Shandong, East China", applicationLevel: "Undergraduate, Master, Doctoral and Non-degree", languageOfInstruction: "Chinese and English", languageRequirement: "Program-specific Chinese or English evidence is required.", hskRequirement: "Published specialized undergraduate routes require HSK 4; general Chinese-taught routes with domestic students require HSK 6 score 180.", englishRequirement: "The MBBS route requires evidence of strong English ability; exemptions require proof of English-medium secondary education.", deadlineSummary: "The Spring 2027 Chinese-language program is open until December 11, 2026. Reviewed 2026 undergraduate and scholarship routes are closed.", tuitionSummary: "Reviewed routes range from CNY 7,000/semester for Spring 2027 Chinese language study to CNY 30,000/year for MBBS.", applicationFee: "CNY 400 for general undergraduate and Chinese-language routes; CNY 800 for MBBS", websiteUrl: "https://www.qdu.edu.cn/", admissionsUrl: "https://istudy.qdu.edu.cn/", cscaRequired: true, cscaRequirement: "Degree-route CSCA requirements are program-specific; the reviewed named routes list Mathematics, Chinese for Humanities, and/or Chemistry.", cscaSubjects: ["Chinese for Humanities", "Mathematics", "Chemistry"], subjectTags: ["Chinese Language", "International Politics", "Business Administration", "Medicine"], languageTags: ["Chinese", "English"], campusHighlights: ["Comprehensive public university in Qingdao", "Officially authorized English-medium MBBS route", "Current Spring 2027 Chinese-language intake"], status: "draft", sourceUrl: ug.url, sourceLabel: ug.label, sourceSha256: ug.sha256, capturedAt: ug.fetchedAt, sourceFieldLineage: { nameEn: "official English guide title", nameZh: "official Chinese guide title", citySlug: "official contact address", applicationLevel: "reviewed official guides", languageOfInstruction: "undergraduate and MBBS guides", deadlineSummary: `undergraduate ${ug.sha256}, MBBS ${mbbsSource.sha256}, Spring 2027 language ${languageSource.sha256}`, tuitionSummary: "reviewed official fee tables", applicationFee: "reviewed official fee tables", admissionsUrl: "official guide contact and application pages", cscaRequirement: "reviewed degree guides" } }], programs, programIntakes: intakes, scholarships: [scholarship] };

const candidateText = `${JSON.stringify(candidate, null, 2)}\n`;
const validation = createCatalogMigrationValidationReport(JSON.parse(candidateText));
if (!validation.ok) throw new Error(validation.errors.join("\n"));
const sha = (value: string) => createHash("sha256").update(value).digest("hex");
const validationArtifact = { ...validation, candidateSha256: sha(candidateText), manifestSha256: sha(manifestText), sourceReview: { status: "unreviewed_draft", pdfPagesVisuallyInspected: 12, notes: ["All six undergraduate-guide pages, four MBBS-guide pages and two Spring 2027 language-guide pages were rendered and visually inspected.", "Only explicitly named undergraduate routes are created; the guide's generic reference to all domestic majors is not expanded without a route-specific international catalog.", "The Spring 2027 Chinese-language intake is current and uses its explicit December 11, 2026 deadline.", "The Presidential Scholarship draft keeps the exact legacy slug because the official and legacy titles identify the same award; no publication or database overwrite is authorized."] }, publicationAuthorized: false, databaseWriteAuthorized: false };
await Promise.all([writeFile(candidatePath, candidateText, "utf8"), writeFile(validationPath, `${JSON.stringify(validationArtifact, null, 2)}\n`, "utf8")]);
console.log(JSON.stringify({ ok: true, candidatePath, validationPath, summary: validation.summary, candidateSha256: validationArtifact.candidateSha256, publicationAuthorized: false, databaseWriteAuthorized: false }, null, 2));
