import assert from "node:assert/strict";
import { readFile, writeFile } from "node:fs/promises";
import { resolve } from "node:path";
const root = process.cwd(); const baseUrl = process.argv.find(arg => arg.startsWith("--base-url="))?.slice(11) ?? "http://127.0.0.1:52118"; if (!/^http:\/\/127\.0\.0\.1:\d+$/.test(baseUrl)) throw new Error("Verification is restricted to local CUAC.");
const bundle = JSON.parse(await readFile(resolve(root, "seeds/catalog.nankai-complete-batch-01.approved.local.json"), "utf8")); const approval = JSON.parse(await readFile(resolve(root, "seeds/catalog.nankai-complete-batch-01.approval.json"), "utf8"));
async function all(path: string) { const rows: any[] = []; for (let offset = 0; ; offset += 100) { const response = await fetch(`${baseUrl}${path}${path.includes("?") ? "&" : "?"}limit=100&offset=${offset}`); assert.equal(response.status, 200, `${path} failed at ${offset}`); const page = (await response.json() as any).data; rows.push(...page); if (page.length < 100) break; } return rows; }
const schoolResponse = await fetch(`${baseUrl}/api/v1/catalog/schools/c7ba4d24-a420-42aa-a37f-93bfd978cb18`); assert.equal(schoolResponse.status, 200); const school = (await schoolResponse.json() as any).data; assert.equal(school.slug, "nankai-university"); assert.equal(school.sourceStatus, "verified"); assert.equal(school.programCount, 339); assert.equal(school.scholarshipCount, 2);
const programs = (await all("/api/v1/catalog/programs")).filter(row => row.schoolId === school.id); assert.equal(programs.length, 339); assert.deepEqual(new Set(programs.map(row => row.slug)), new Set(bundle.programs.map((row: any) => row.slug))); assert.equal(programs.filter(row => row.degreeLevel === "Undergraduate").length, 41); assert.equal(programs.filter(row => row.degreeLevel === "Master").length, 171); assert.equal(programs.filter(row => row.degreeLevel === "Doctoral").length, 127); for (const slug of approval.archivedProgramAliases) assert.equal(programs.some(row => row.slug === slug), false);
const samples = [programs.find(row => row.degreeLevel === "Undergraduate" && row.teachingLanguage.includes("English")), programs.find(row => row.degreeLevel === "Master" && row.teachingLanguage === "Chinese"), programs.find(row => row.degreeLevel === "Master" && row.teachingLanguage === "English"), programs.find(row => row.degreeLevel === "Doctoral" && row.teachingLanguage === "Chinese"), programs.find(row => row.degreeLevel === "Doctoral" && row.teachingLanguage === "English")].filter(Boolean); for (const row of samples) { const response = await fetch(`${baseUrl}/api/v1/catalog/programs/${row.id}`); assert.equal(response.status, 200); const detail = (await response.json() as any).data; assert.equal(detail.slug, row.slug); assert.equal(detail.verificationStatus, "verified"); assert.equal(detail.lastVerifiedAt, approval.approvedAt); assert.ok(detail.applicationNote); assert.ok(detail.sourceFieldLineage); }
const scholarships = (await all("/api/v1/catalog/scholarships")).filter(row => row.schoolId === school.id); assert.equal(scholarships.length, 2); assert.deepEqual(new Set(scholarships.map(row => row.slug)), new Set(bundle.scholarships.map((row: any) => row.slug))); for (const row of scholarships) { for (const field of ["benefitItems","eligibilityItems","applicationMaterials","applicationSteps","actionLinks"]) assert.ok(row[field].length > 0); const response = await fetch(`${baseUrl}/api/v1/catalog/scholarships/${row.id}`); assert.equal(response.status, 200); const detail = (await response.json() as any).data; assert.equal(detail.verificationStatus, "verified"); assert.equal(detail.lastVerifiedAt, approval.approvedAt); }
const legacyResponse = await fetch(`${baseUrl}/api/v1/catalog/scholarships/6bb3e871-a671-4098-b47f-f25b0ae27541`); assert.equal(legacyResponse.status, 200); assert.equal((await legacyResponse.json() as any).data, null);
const result = { version: 1, verifiedAt: new Date().toISOString(), baseUrl, publicationBundleSha256: approval.publicationBundleSha256, schoolId: school.id, publicProgramCount: programs.length, publicUndergraduateProgramCount: 41, publicMasterProgramCount: 171, publicDoctoralProgramCount: 127, publicProgramIntakeCount: 339, publicScholarshipCount: scholarships.length, programDetailApiSampleCount: samples.length, archivedProgramAliases: approval.archivedProgramAliases.length, archivedScholarshipAliases: approval.archivedScholarshipAliases.length, listApiChecks: "pass", detailApiChecks: "pass" }; const reportPath = resolve(root, "seeds/catalog.nankai-complete-batch-01.publication-verification.json"); await writeFile(reportPath, `${JSON.stringify(result, null, 2)}\n`, { encoding: "utf8", flag: "wx" }); console.log(JSON.stringify({ ok: true, reportPath, ...result }, null, 2));
