import assert from "node:assert/strict";
import { readFile, writeFile } from "node:fs/promises";
import { resolve } from "node:path";
const root = process.cwd(); const baseUrl = process.argv.find(arg => arg.startsWith("--base-url="))?.slice(11) ?? "http://127.0.0.1:52118"; if (!/^http:\/\/127\.0\.0\.1:\d+$/.test(baseUrl)) throw new Error("Verification is restricted to local CUAC.");
const bundle = JSON.parse(await readFile(resolve(root, "seeds/catalog.tongji-scholarships-batch-02.approved.local.json"), "utf8")); const approval = JSON.parse(await readFile(resolve(root, "seeds/catalog.tongji-scholarships-batch-02.approval.json"), "utf8")); const expected = new Map(bundle.scholarships.map((row: any) => [row.slug, row])); assert.equal(expected.size, 3);
const schoolResponse = await fetch(`${baseUrl}/api/v1/catalog/schools/d01a131b-731a-4fbf-aad7-f9e41a30f01a`); assert.equal(schoolResponse.status, 200); const school = (await schoolResponse.json() as any).data; assert.equal(school.slug, "tongji-university"); assert.equal(school.programCount, 71); assert.equal(school.scholarshipCount, 4);
const listResponse = await fetch(`${baseUrl}/api/v1/catalog/scholarships?limit=100&query=Tongji`); assert.equal(listResponse.status, 200); const rows = (await listResponse.json() as any).data.filter((row: any) => row.schoolId === school.id); assert.equal(rows.length, 4);
for (const [slug, expectedRow] of expected as Map<string, any>) { const row = rows.find((item: any) => item.slug === slug); assert.ok(row, `Missing scholarship ${slug}`); assert.equal(row.sourceStatus, "verified"); assert.equal(row.lastVerifiedAt, approval.approvedAt); for (const field of ["benefitItems","eligibilityItems","applicationMaterials","applicationSteps","actionLinks"]) { assert.equal(row[field].length, expectedRow[field].length); assert.ok(row[field].length > 0); } const response = await fetch(`${baseUrl}/api/v1/catalog/scholarships/${row.id}`); assert.equal(response.status, 200); const detail = (await response.json() as any).data; assert.equal(detail.slug, slug); assert.equal(detail.verificationStatus, "verified"); assert.equal(detail.school?.slug, "tongji-university"); assert.deepEqual(detail.sourceFieldLineage, expectedRow.sourceFieldLineage); }
const result = { version: 1, verifiedAt: new Date().toISOString(), baseUrl, publicationBundleSha256: approval.publicationBundleSha256, schoolId: school.id, publicProgramCount: school.programCount, publicScholarshipCount: rows.length, verifiedNewScholarshipCount: expected.size, listApiChecks: "pass", detailApiChecks: "pass" };
const reportPath = resolve(root, "seeds/catalog.tongji-scholarships-batch-02.publication-verification.json"); await writeFile(reportPath, `${JSON.stringify(result, null, 2)}\n`, { encoding: "utf8", flag: "wx" }); console.log(JSON.stringify({ ok: true, reportPath, ...result }, null, 2));
