import { createHash } from "node:crypto";
import { readFile, writeFile } from "node:fs/promises";
import { resolve } from "node:path";
import { createCatalogMigrationValidationReport, type CatalogSeedBundle } from "../src/server/catalog/seed-contract.ts";
import { createPostgresPool } from "../src/server/db/postgres-client.ts";
import { localDatabaseUrl } from "./lib/local-development.ts";

const root = process.cwd();
const paths = { complete: resolve(root, "seeds/catalog.changan-complete-batch-01.draft.json"), completeReview: resolve(root, "seeds/catalog.changan-complete-batch-01.review.json"), safeApproval: resolve(root, "seeds/catalog.changan-safe-new-batch-01.approval.json"), safePublication: resolve(root, "seeds/catalog.changan-safe-new-batch-01.approved.local.json"), freshManifest: resolve(root, "work/catalog-official/changan-refresh-20260914/manifest.json"), candidate: resolve(root, "seeds/catalog.changan-cleanup.draft.json"), validation: resolve(root, "seeds/catalog.changan-cleanup.validation.json"), review: resolve(root, "seeds/catalog.changan-cleanup.review.json"), state: resolve(root, ".cuac-local/runtime.json") };
const sha = (value: string | Buffer) => createHash("sha256").update(value).digest("hex"), read = async (path: string) => { const text = await readFile(path, "utf8"); return { text, value: JSON.parse(text) }; };
const [completeFile, completeReviewFile, safeApprovalFile, safePublicationFile, freshManifestFile, stateFile] = await Promise.all([paths.complete, paths.completeReview, paths.safeApproval, paths.safePublication, paths.freshManifest, paths.state].map(read));
const complete = completeFile.value as CatalogSeedBundle, completeReview = completeReviewFile.value, safeApproval = safeApprovalFile.value, safePublication = safePublicationFile.value as CatalogSeedBundle, freshManifest = freshManifestFile.value, state = stateFile.value, schoolSlug = "chang-an-university";
if (complete.cities?.length !== 1 || complete.schools?.length !== 1 || complete.schools[0].slug !== schoolSlug || complete.programs?.length !== 215 || complete.programIntakes?.length !== 215 || complete.scholarships?.length !== 6 || safeApproval.programSlugs?.length !== 199 || safeApproval.scholarshipSlugs?.length !== 6 || safePublication.programs?.length !== 199 || freshManifest.sources?.length !== 18 || completeReview.visualReview?.result !== "pass") throw new Error("Chang'an cleanup dependencies changed.");
const stableProgramSlugs: string[] = (completeReview.reconciliation?.overwrites ?? []).filter((row: any) => row.entityType === "program").map((row: any) => row.slug), plannedProgramAliases: string[] = (completeReview.reconciliation?.archives ?? []).filter((row: any) => row.entityType === "program").map((row: any) => row.slug), plannedScholarshipAliases: string[] = (completeReview.reconciliation?.archives ?? []).filter((row: any) => row.entityType === "scholarship").map((row: any) => row.slug);
if (stableProgramSlugs.length !== 16 || plannedProgramAliases.length !== 8 || plannedScholarshipAliases.length !== 1) throw new Error("Chang'an reconciliation plan changed.");
const stableSet = new Set(stableProgramSlugs), stablePrograms = complete.programs.filter((row) => stableSet.has(row.slug)), stableIntakes = complete.programIntakes.filter((row) => stableSet.has(row.programSlug)); if (stablePrograms.length !== 16 || stableIntakes.length !== 16) throw new Error("Chang'an stable program split changed.");
const pool = createPostgresPool({ databaseUrl: localDatabaseUrl(state), max: 1, applicationName: "cuac:changan-cleanup-review" }); let baseline: any;
try {
  const school = await pool.query("select id,slug,status,verification_status from schools where slug=$1", [schoolSlug]), city = await pool.query("select id,slug,status,verification_status from cities where slug='xian'"), safePrograms = await pool.query("select slug,status,verification_status,last_verified_at from programs where slug=any($1::text[]) order by slug", [safeApproval.programSlugs]), safeScholarships = await pool.query("select slug,status,verification_status,last_verified_at from scholarships where slug=any($1::text[]) order by slug", [safeApproval.scholarshipSlugs]), stableProgramsDb = await pool.query("select id,slug,status,verification_status from programs where slug=any($1::text[]) order by slug", [stableProgramSlugs]), programAliases = await pool.query("select id,slug,status,verification_status from programs where slug=any($1::text[]) order by slug", [plannedProgramAliases]), scholarshipAliases = await pool.query("select id,slug,status,verification_status from scholarships where slug=any($1::text[]) order by slug", [plannedScholarshipAliases]), totals = await pool.query("select (select count(*) from programs where school_id=$1 and status='active')::int programs,(select count(*) from scholarships where school_id=$1 and status='active')::int scholarships", [school.rows[0]?.id]);
  baseline = { school: school.rows, city: city.rows, safePrograms: safePrograms.rows, safeScholarships: safeScholarships.rows, stablePrograms: stableProgramsDb.rows, programAliases: programAliases.rows, scholarshipAliases: scholarshipAliases.rows, totals: totals.rows[0] };
  if (school.rows.length !== 1 || school.rows[0].status !== "active" || school.rows[0].verification_status !== "unverified" || city.rows.length !== 1 || city.rows[0].status !== "active") throw new Error("Chang'an school/city baseline changed.");
  if (safePrograms.rows.length !== 199 || safeScholarships.rows.length !== 6 || [...safePrograms.rows, ...safeScholarships.rows].some((row: any) => row.status !== "active" || row.verification_status !== "verified" || row.last_verified_at?.toISOString() !== safeApproval.approvedAt)) throw new Error("Chang'an safe publication changed.");
  if (stableProgramsDb.rows.length !== 16 || programAliases.rows.length !== 8 || scholarshipAliases.rows.length !== 1 || [...stableProgramsDb.rows, ...programAliases.rows, ...scholarshipAliases.rows].some((row: any) => row.status !== "active" || row.verification_status !== "unverified") || totals.rows[0]?.programs !== 223 || totals.rows[0]?.scholarships !== 7) throw new Error("Chang'an legacy baseline changed.");
} finally { await pool.end(); }
const candidate: CatalogSeedBundle = { version: 1, generatedAt: freshManifest.generatedAt, cities: complete.cities, schools: complete.schools, programs: stablePrograms, programIntakes: stableIntakes, scholarships: [] }, candidateText = `${JSON.stringify(candidate, null, 2)}\n`, validation = createCatalogMigrationValidationReport(candidate); if (!validation.ok) throw new Error(`Chang'an cleanup validation failed: ${validation.errors.join(" ")}`);
const reviewBase = { version: 1, status: "requires_explicit_approval", generatedAt: candidate.generatedAt, scope: { schoolSlug, cityOverwriteCount: 1, schoolOverwriteCount: 1, programOverwriteCount: 16, programIntakeUpsertCount: 16, archiveProgramAliasCount: 8, archiveScholarshipAliasCount: 1, verifiedSafeProgramMutationCount: 0, verifiedSafeScholarshipMutationCount: 0 }, candidateSha256: sha(candidateText), candidateBundleSha256: validation.bundleSha256, operationPlanSha256: validation.operationPlanSha256, evidence: { freshManifestSha256: sha(freshManifestFile.text), freshOfficialSourceCount: 18, completeReviewSha256: sha(completeReviewFile.text), safeApprovalSha256: sha(safeApprovalFile.text), safePublicationSha256: sha(safePublicationFile.text) }, reconciliation: { destructiveDeletion: false, overwrite: [{ entityType: "city", id: baseline.city[0].id, slug: "xian" }, { entityType: "school", id: baseline.school[0].id, slug: schoolSlug }, ...baseline.stablePrograms.map((row: any) => ({ entityType: "program", id: row.id, slug: row.slug }))], archives: [...baseline.programAliases.map((row: any) => ({ entityType: "program", id: row.id, slug: row.slug })), ...baseline.scholarshipAliases.map((row: any) => ({ entityType: "scholarship", id: row.id, slug: row.slug }))], protectedSafeProgramSlugs: safeApproval.programSlugs, protectedSafeScholarshipSlugs: safeApproval.scholarshipSlugs, databaseBaseline: { schoolId: baseline.school[0].id, cityId: baseline.city[0].id } }, sourceReview: { result: "pass", note: "All 18 official Chang'an University sources were refreshed byte-for-byte unchanged; the city, school and 16 stable program updates remain bound to the fully reviewed evidence." }, visualReview: completeReview.visualReview, sensitiveDataCheck: { result: "pass", scope: "city, school, 16 stable programs and nine archive status changes", note: "Only public catalog fields and record identifiers are present. Applicant, account, payment, bank, staff-name and personal-contact data are excluded." }, reviewNotes: ["The 199 newly published verified programs and six rich scholarships are protected and will not be rewritten.", "Eight program aliases and one merged scholarship are status-archived, not deleted.", "Sixteen existing stable program URLs are updated in place with official 2026 fields and intakes."] };
const reviewHash = sha(JSON.stringify(reviewBase)), requiredApproval = `批准完成长安大学学校与旧数据清理（审核哈希 ${reviewHash}），覆盖西安城市、长安大学学校及 16 条既有项目，并归档 8 条旧项目别名及 1 条旧奖学金合并概览`;
await Promise.all([writeFile(paths.candidate, candidateText, "utf8"), writeFile(paths.validation, `${JSON.stringify(validation, null, 2)}\n`, "utf8"), writeFile(paths.review, `${JSON.stringify({ ...reviewBase, reviewHash, requiredApproval }, null, 2)}\n`, "utf8")]); console.log(JSON.stringify({ ok: true, reviewHash, requiredApproval, scope: reviewBase.scope, paths }, null, 2));
