import { createHash } from "node:crypto";
import { readFile, writeFile } from "node:fs/promises";
import { resolve } from "node:path";
import { createCatalogMigrationValidationReport, type CatalogSeedBundle, type CatalogSeedProgram, type CatalogSeedScholarship } from "../src/server/catalog/seed-contract.ts";

const root = process.cwd();
const paths = {
  manifest: resolve(root, "work/catalog-official/nuaa-complete-batch-01/manifest.json"),
  parsed: resolve(root, "work/catalog-official/nuaa-complete-batch-01/parsed-programs.json"),
  base: resolve(root, "seeds/catalog.nju-complete-batch-02.approved.local.json"),
  draft: resolve(root, "seeds/catalog.nuaa-complete-batch-01.draft.json"),
  validation: resolve(root, "seeds/catalog.nuaa-complete-batch-01.validation.json"),
};
const sha = (value: string | Buffer) => createHash("sha256").update(value).digest("hex");
const [manifestText, parsedText, baseText] = await Promise.all([readFile(paths.manifest, "utf8"), readFile(paths.parsed, "utf8"), readFile(paths.base, "utf8")]);
const manifest = JSON.parse(manifestText), parsed = JSON.parse(parsedText), base = JSON.parse(baseText) as CatalogSeedBundle;
const expected: Record<string, string> = {
  "nuaa-undergraduate-admissions-2026": "05bebd7b3991fbd2e0297660b2bc0f4efd625a5107e05af3332cb318b1f411bc",
  "nuaa-postgraduate-admissions-2026": "d10e565e0e5e47498e21d20eb966901e906d46f36c39ff1b7e070e9a43262fab",
  "nuaa-csc-university-scholarship-2026": "ce20dae99d4005c92e4bba3ac29e010d2020c7aa0be3cdecdc467bea44b1986c",
  "nuaa-csc-silk-road-scholarship-2026": "18e106b66e66e299272fc9352cfade77be3735059528f728b1d2c3bbaab165d2",
  "nuaa-fly-high-scholarship-2026": "000b66ae0ca7d04acb5013082c39157254fdbbeb80dc48ec4b56a044be64ffba",
};
const evidence = new Map<string, any>();
for (const row of manifest.sources ?? []) if (row.status === 200 && expected[row.id] === row.sha256) evidence.set(row.id, row);
const missing = Object.keys(expected).filter((id) => !evidence.has(id));
if (missing.length || parsed.programCount !== 77 || parsed.duplicateIdentities.length) throw new Error(`NUAA evidence/parser mismatch: ${missing.join(",")}`);
const city = base.cities?.find((row) => row.slug === "nanjing");
if (!city) throw new Error("Current Nanjing city dependency missing.");

const schoolSlug = "nanjing-university-of-aeronautics-and-astronautics";
const slugify = (value: string) => value.toLowerCase().replace(/&/g, " and ").replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");
const used = new Set<string>();
const programs: CatalogSeedProgram[] = parsed.programs.map((row: any, index: number) => {
  const source = evidence.get(row.sourceId), undergraduate = row.degreeLevel === "Undergraduate", business = /International Business|Economics and Management/.test(`${row.nameEn} ${row.collegeEn ?? ""}`);
  const tuition = undergraduate ? (row.nameEn === "International Business" ? 22900 : 23900) : row.degreeLevel === "Master" ? (business ? 30000 : 33600) : (business ? 34000 : 37800);
  let slug = `${schoolSlug}-${row.degreeLevel.toLowerCase()}-${slugify(row.nameEn)}-${slugify(row.collegeEn ?? row.degreeAward ?? `route-${row.sourceRow}`)}-${row.teachingLanguage.toLowerCase()}`;
  if (used.has(slug)) slug = `${slug}-${index + 1}`;
  used.add(slug);
  const cscaSubjects = undergraduate ? (row.nameEn === "International Business" ? ["Mathematics"] : ["Mathematics", "Physics"]) : [];
  return {
    slug, schoolSlug, citySlug: "nanjing", nameEn: row.nameEn, degreeLevel: row.degreeLevel,
    ...(undergraduate ? { durationYears: 4 } : row.degreeLevel === "Master" ? { durationMonths: 30 } : { durationYears: 4 }),
    ...(row.collegeEn ? { fieldCategory: row.collegeEn, subjectArea: row.collegeEn } : { fieldCategory: row.degreeAward, subjectArea: row.degreeAward }),
    teachingLanguage: row.teachingLanguage,
    ...(undergraduate ? { cscaSubjects, cscaRequirement: `CSCA is mandatory; ${cscaSubjects.join(" and ")} must be taken in English.` } : { cscaRequirement: "No CSCA requirement is published for this postgraduate route." }),
    ...(row.teachingLanguage === "Chinese" ? { hskRequirement: "HSK Level 4 or above" } : { englishRequirement: undergraduate ? "IELTS 6.0 or TOEFL 80, or equivalent English proficiency" : "IELTS 6.0 or TOEFL 70, or equivalent English proficiency" }),
    tuitionAmount: tuition, tuitionCurrency: "RMB", tuitionPeriod: "year", tuitionText: `CNY ${tuition.toLocaleString("en-US")}/year`,
    scholarshipText: "Multiple verified 2026 government and NUAA scholarship routes are linked in the scholarship catalog; award decisions are not guaranteed.",
    applicationUrl: "https://nj.at0086.cn/StuApplication/Login.aspx",
    applicationNote: `Official 2026 ${row.degreeLevel.toLowerCase()} route taught in ${row.teachingLanguage}${row.collegeEn ? `; ${row.collegeEn}` : `; degree awarded in ${row.degreeAward}`}.`,
    hasScholarship: true, status: "draft", sourceUrl: source.url, sourceLabel: source.label, sourceSha256: source.sha256, capturedAt: source.fetchedAt,
    sourceFieldLineage: { nameEn: `${row.sourceTable}, row ${row.sourceRow}`, degreeLevel: `${row.sourceTable}, degree checkmark or degree column`, ...(row.collegeEn ? { fieldCategory: `${row.sourceTable}, college column` } : { fieldCategory: `${row.sourceTable}, degree column` }), teachingLanguage: undergraduate ? "2026 undergraduate brochure program and language sections" : "2026 postgraduate guide states the catalog is English-taught", ...(undergraduate ? { cscaSubjects: "2026 undergraduate guide, CSCA section" } : {}), ...(row.teachingLanguage === "Chinese" ? { hskRequirement: "2026 undergraduate guide, language certificate section" } : { englishRequirement: undergraduate ? "2026 undergraduate guide, language certificate section" : "2026 postgraduate guide, eligibility section" }), tuitionAmount: undergraduate ? "2026 undergraduate guide, Tuition & Fees" : "2026 postgraduate guide, Tuition & Fees", applicationUrl: "2026 official application procedure" },
  };
});
if (programs.length !== 77 || used.size !== 77) throw new Error("NUAA program build mismatch.");

const info = (label: string, value?: string) => ({ label, ...(value ? { value } : {}) });
const benefit = (label: string, note?: string) => ({ label, included: true, ...(note ? { note } : {}) });
const commonMaterials = [info("Passport information page"), info("Highest diploma or expected-graduation proof"), info("Academic transcripts"), info("Language proficiency certificate"), info("Study or research plan"), info("Recommendation letters where required"), info("Physical examination record"), info("No-criminal-record certificate")];
function scholarship(sourceId: string, value: Partial<CatalogSeedScholarship> & Pick<CatalogSeedScholarship, "slug" | "title" | "fundingLevel" | "coverage" | "applicableDegree" | "amountText">): CatalogSeedScholarship {
  const source = evidence.get(sourceId);
  return { schoolSlug, status: "draft", sourceUrl: source.url, sourceLabel: source.label, sourceSha256: source.sha256, capturedAt: source.fetchedAt, providerLocation: "China", targetCountries: [], targetRegions: [], actionLinks: [{ label: source.label, url: source.url, kind: "official-source" }, { label: "NUAA online application system", url: "https://nj.at0086.cn/StuApplication/Login.aspx", kind: "official-application" }], sourceFieldLineage: { title: "official notice title or scholarship table label", fundingLevel: "official coverage section", coverage: "official coverage section", amountText: "official coverage or scholarship table", applicableDegree: "official eligibility or admissions section", applicableProgram: "official major/eligibility section", eligibilityItems: "official eligibility section", applicationMaterials: "official application documents", applicationSteps: "official application procedure", ...(value.deadlineDate ? { deadlineDate: "official application time" } : { deadlineLabel: "official admissions/application note" }) }, ...value };
}
const scholarships: CatalogSeedScholarship[] = [
  scholarship("nuaa-csc-university-scholarship-2026", { slug: "official-2026-nuaa-csc-university-program", title: "NUAA 2026 Chinese Government Scholarship - University Program", nameZh: "南京航空航天大学2026年中国政府奖学金高校项目", type: "government", typeLabel: "Chinese Government Scholarship Type B", providerName: "国家留学基金管理委员会 / 南京航空航天大学", providerNameEn: "China Scholarship Council / Nanjing University of Aeronautics and Astronautics", fundingLevel: "Full", coverage: "Tuition waiver, free accommodation, comprehensive medical insurance, and monthly living allowance", applicableDegree: "Master, Doctoral", applicableProgram: "English-taught NUAA postgraduate routes published in the 2026 guide", amountText: "CNY 3,000/month for master's students; CNY 3,500/month for doctoral students, plus tuition, accommodation and medical insurance.", deadlineDate: "2026-03-06", deadlineLabel: "March 6, 2026", applicationRound: "2026 CSC University Program", benefitItems: [benefit("Tuition waiver"), benefit("Accommodation"), benefit("Comprehensive medical insurance"), benefit("Monthly stipend", "CNY 3,000 master; CNY 3,500 doctoral")], eligibilityItems: [info("Nationality", "Non-Chinese citizen in good physical and mental health, with no criminal record"), info("Age", "Master under 35; doctoral under 40"), info("Language", "IELTS 6.0+, TOEFL 70+, or equivalent English-medium proof"), info("Academic profile", "Strong academic, research and innovation ability")], applicationMaterials: [...commonMaterials, info("CSC application form"), info("NUAA supervisor acceptance letter"), info("Research plan", "At least 3,000 words and signed by a potential NUAA supervisor"), info("Self-introduction video")], applicationSteps: [info("Step 1", "Submit CSC Type B application using NUAA agency 10287"), info("Step 2", "Submit matching application in the NUAA portal"), info("Step 3", "Complete preliminary document review"), info("Step 4", "Complete college academic review or interview"), info("Step 5", "Await CSC final approval")], bodySections: [{ title: "Annual review", body: "Performance is reviewed every May; failing review ends scholarship eligibility for the next year." }], summary: "Full 2026 CSC Type B postgraduate award administered through NUAA.", sortOrder: 10 }),
  scholarship("nuaa-csc-silk-road-scholarship-2026", { slug: "official-2026-nuaa-csc-silk-road-program", title: "NUAA 2026 Chinese Government Scholarship - Silk Road Program", nameZh: "南京航空航天大学2026年中国政府奖学金丝绸之路项目", type: "government", typeLabel: "Chinese Government Scholarship Silk Road Type B", providerName: "国家留学基金管理委员会 / 南京航空航天大学", providerNameEn: "China Scholarship Council / Nanjing University of Aeronautics and Astronautics", fundingLevel: "Full", coverage: "Tuition waiver, free accommodation, comprehensive medical insurance, and monthly living allowance", applicableDegree: "Master, Doctoral", applicableProgram: "Aerospace Science and Technology; Mechanical Engineering; Computer Science and Technology; Software Engineering; Transportation Engineering", amountText: "CNY 3,000/month for master's students; CNY 3,500/month for doctoral students, plus tuition, accommodation and medical insurance.", deadlineDate: "2026-05-18", deadlineLabel: "May 18, 2026", applicationRound: "2026 CSC Silk Road Program", targetCountries: ["Pakistan", "Indonesia", "Bangladesh", "Nepal", "Thailand", "Morocco", "Kenya", "Tanzania"], targetRegions: ["Silk Road partner countries listed in the official notice"], benefitItems: [benefit("Tuition waiver"), benefit("Accommodation"), benefit("Comprehensive medical insurance"), benefit("Monthly stipend", "CNY 3,000 master; CNY 3,500 doctoral")], eligibilityItems: [info("Nationality", "Citizen of one of the eight countries published in the notice"), info("Age", "Master under 35; doctoral under 40"), info("Language", "IELTS 6.0+, TOEFL 70+, or equivalent English-medium proof"), info("Academic profile", "Strong academic, research and innovation ability")], applicationMaterials: [...commonMaterials, info("CSC application form"), info("NUAA supervisor acceptance letter"), info("Research plan", "At least 3,000 words and signed by a potential NUAA supervisor"), info("Self-introduction video")], applicationSteps: [info("Step 1", "Submit CSC Type B application using agency 10287"), info("Step 2", "Submit the identical NUAA portal application"), info("Step 3", "Complete preliminary and academic review"), info("Step 4", "Await CSC final approval")], bodySections: [{ title: "Annual review", body: "Performance is reviewed every May; failing review ends scholarship eligibility for the next year." }], summary: "Full 2026 Silk Road postgraduate scholarship for five English-taught disciplines and eight named countries.", sortOrder: 20 }),
  scholarship("nuaa-undergraduate-admissions-2026", { slug: "official-2026-nuaa-csc-bilateral-undergraduate", title: "NUAA 2026 Chinese Government Scholarship Type A - Undergraduate", nameZh: "南京航空航天大学2026年中国政府奖学金A类本科项目", type: "government", typeLabel: "Chinese Government Scholarship Type A", providerName: "国家留学基金管理委员会", providerNameEn: "China Scholarship Council", fundingLevel: "Full", coverage: "Full tuition, on-campus accommodation, comprehensive medical insurance, and living stipend", applicableDegree: "Undergraduate", applicableProgram: "NUAA's six 2026 international undergraduate programs", amountText: "CNY 2,500/month living stipend plus tuition, on-campus accommodation and medical insurance.", deadlineLabel: "Set by the applicant's Chinese embassy or dispatching authority; NUAA undergraduate documents are due by May 30, 2026", applicationRound: "2026 CSC Type A undergraduate", benefitItems: [benefit("Tuition"), benefit("On-campus accommodation"), benefit("Comprehensive medical insurance"), benefit("Living stipend", "CNY 2,500/month")], eligibilityItems: [info("Nationality", "Non-Chinese citizen"), info("Age", "17-25"), info("Education", "Senior-high graduate or above"), info("CSCA", "Mandatory; Mathematics for business, Mathematics and Physics for engineering")], applicationMaterials: commonMaterials, applicationSteps: [info("Step 1", "Contact the Chinese embassy or consulate in the applicant's home country"), info("Step 2", "List NUAA as first choice using agency code 10287"), info("Step 3", "Complete the NUAA admission requirements and CSCA")], summary: "Full undergraduate CSC Type A route published in NUAA's 2026 undergraduate guide.", sortOrder: 30 }),
  scholarship("nuaa-undergraduate-admissions-2026", { slug: "official-2026-nuaa-jiangsu-government-undergraduate", title: "NUAA 2026 Jiangsu Government Scholarship - Undergraduate", nameZh: "南京航空航天大学2026年江苏省政府奖学金本科项目", type: "government", typeLabel: "Jiangsu Government Scholarship", providerName: "江苏省人民政府", providerNameEn: "Jiangsu Provincial Government", fundingLevel: "Full", coverage: "Full tuition, on-campus accommodation, comprehensive medical insurance, and annual living stipend", applicableDegree: "Undergraduate", applicableProgram: "NUAA's six 2026 international undergraduate programs", amountText: "CNY 15,000/year living stipend plus tuition, on-campus accommodation and medical insurance.", deadlineDate: "2026-05-30", deadlineLabel: "May 30, 2026", applicationRound: "2026 undergraduate admissions", benefitItems: [benefit("Tuition"), benefit("On-campus accommodation"), benefit("Comprehensive medical insurance"), benefit("Living stipend", "CNY 15,000/year")], eligibilityItems: [info("Selection", "Based on academics, background, experience and CSCA score"), info("CSCA", "Mandatory for all undergraduate applicants")], applicationMaterials: commonMaterials, applicationSteps: [info("Step 1", "Complete CSCA"), info("Step 2", "Apply through the NUAA portal and select the scholarship route"), info("Step 3", "Monitor the portal for the admission and scholarship result")], summary: "Full Jiangsu provincial award listed for 2026 NUAA undergraduate applicants.", sortOrder: 40 }),
  scholarship("nuaa-postgraduate-admissions-2026", { slug: "official-2026-nuaa-nanjing-municipal-scholarship", title: "NUAA 2026 Nanjing Municipal Scholarship", nameZh: "南京航空航天大学2026年南京市政府奖学金", type: "government", typeLabel: "Nanjing Municipal Scholarship", providerName: "南京市人民政府", providerNameEn: "Nanjing Municipal Government", fundingLevel: "Partial", coverage: "One-time award for the first academic year", applicableDegree: "Undergraduate, Master, Doctoral", applicableProgram: "Published 2026 NUAA international degree programs", amountText: "CNY 10,000 one-time for undergraduate applicants; CNY 20,000 one-time for postgraduate applicants.", deadlineLabel: "Undergraduate May 30, 2026; postgraduate final deadline June 15, 2026", applicationRound: "2026 NUAA degree admissions", benefitItems: [benefit("Undergraduate award", "CNY 10,000 one-time"), benefit("Postgraduate award", "CNY 20,000 one-time")], eligibilityItems: [info("Selection", "Based on background, experience, academics and examination/interview results")], applicationMaterials: commonMaterials, applicationSteps: [info("Step 1", "Apply to the relevant 2026 NUAA degree route"), info("Step 2", "Select the Nanjing scholarship option in the NUAA portal"), info("Step 3", "Await the scholarship result with the admission decision")], bodySections: [{ title: "Renewal", body: "This is a first-year one-time award. From year two, students may compete for the NUAA Academic Scholarship." }], summary: "One-time Nanjing municipal award with degree-specific 2026 amounts.", sortOrder: 50 }),
  scholarship("nuaa-fly-high-scholarship-2026", { slug: "official-2026-nuaa-fly-high-scholarship", title: "2026 NUAA Fly-High Scholarship", nameZh: "南京航空航天大学2026年飞高奖学金", type: "university", typeLabel: "NUAA Fly-High Scholarship", providerName: "南京航空航天大学", providerNameEn: "Nanjing University of Aeronautics and Astronautics", fundingLevel: "Partial", coverage: "First prize waives first-year tuition; second and third prizes provide one-time awards", applicableDegree: "Undergraduate, Master, Doctoral", applicableProgram: "Published 2026 NUAA international degree programs", amountText: "First prize: 100% first-year tuition waiver; second prize: CNY 20,000 one-time; third prize: CNY 10,000 one-time.", deadlineLabel: "Assessed with the relevant 2026 NUAA admission application", applicationRound: "2026 NUAA admissions", benefitItems: [benefit("First prize", "100% first-year tuition waiver"), benefit("Second prize", "CNY 20,000 one-time"), benefit("Third prize", "CNY 10,000 one-time")], eligibilityItems: [info("Selection", "Comprehensive evaluation of academic achievement, professional background and other relevant factors")], applicationMaterials: [info("Relevant NUAA degree-program application and supporting documents")], applicationSteps: [info("Step 1", "Submit the relevant NUAA admission application"), info("Step 2", "Select the Fly-High scholarship where offered"), info("Step 3", "Check the admission letter for the scholarship result")], bodySections: [{ title: "Costs not covered", body: "Accommodation and living costs remain payable unless another award covers them." }, { title: "After the first year", body: "Students may compete for the NUAA Academic Scholarship, a one-time award of up to CNY 20,000, based on academic performance and conduct." }], summary: "NUAA's 2026 first-year merit award with three published prize levels.", sortOrder: 60 }),
];

const undergraduateSource = evidence.get("nuaa-undergraduate-admissions-2026"), postgraduateSource = evidence.get("nuaa-postgraduate-admissions-2026");
const candidate: CatalogSeedBundle = {
  version: 1, generatedAt: manifest.generatedAt, cities: [city],
  schools: [{ slug: schoolSlug, nameEn: "Nanjing University of Aeronautics and Astronautics", nameZh: "南京航空航天大学", citySlug: "nanjing", schoolType: "Public", region: "Nanjing, Jiangsu, East China", applicationLevel: "Undergraduate, Master, Doctoral", languageOfInstruction: "Chinese and English undergraduate; English postgraduate", hskRequirement: "HSK Level 4 or above for Chinese-taught undergraduate routes.", englishRequirement: "Undergraduate: IELTS 6.0 or TOEFL 80; postgraduate: IELTS 6.0 or TOEFL 70; equivalent proof accepted.", deadlineSummary: "Undergraduate: May 30, 2026; postgraduate final deadline: June 15, 2026; scholarship deadlines vary by award.", tuitionSummary: "Undergraduate CNY 22,900-23,900/year; master's CNY 30,000-33,600/year; doctoral CNY 34,000-37,800/year.", applicationFee: "CNY 400, non-refundable", websiteUrl: "https://www.nuaa.edu.cn/", admissionsUrl: "https://cie.nuaa.edu.cn/", cscaRequired: true, cscaRequirement: "All undergraduate applicants must take CSCA; business requires Mathematics, engineering requires Mathematics and Physics, in English.", cscaSubjects: ["Mathematics", "Physics"], subjectTags: ["Aeronautics", "Astronautics", "Mechanical Engineering", "Computer Science", "Artificial Intelligence", "Civil Engineering", "International Business"], languageTags: ["Chinese", "English"], campusHighlights: ["Jiangjun Road campus", "Aeronautics and astronautics", "Engineering and business programs"], status: "draft", sourceUrl: undergraduateSource.url, sourceLabel: undergraduateSource.label, sourceSha256: undergraduateSource.sha256, capturedAt: undergraduateSource.fetchedAt, sourceFieldLineage: { nameEn: "official 2026 brochure identity", nameZh: "official institution identity", citySlug: "official contact address", applicationLevel: "2026 undergraduate and postgraduate program tables", languageOfInstruction: "2026 program guide introductions", hskRequirement: "2026 undergraduate language requirements", englishRequirement: "2026 admissions eligibility", deadlineSummary: "2026 application time sections", tuitionSummary: "2026 Tuition & Fees tables", applicationFee: "2026 application procedure", cscaSubjects: "2026 undergraduate CSCA section" } }],
  programs,
  programIntakes: programs.map((program) => { const undergraduate = program.degreeLevel === "Undergraduate", source = undergraduate ? undergraduateSource : postgraduateSource; return { programSlug: program.slug, intakeTerm: "Fall", intakeYear: 2026, openDate: "2025-11-15T00:00:00.000Z", deadlineDate: undergraduate ? "2026-05-30T00:00:00.000Z" : "2026-06-15T00:00:00.000Z", deadlineLabel: undergraduate ? "May 30, 2026" : "June 15, 2026 final deadline", applicationRound: "2026 international degree admissions", status: "closed" as const, sourceUrl: source.url, sourceLabel: source.label, sourceSha256: source.sha256, capturedAt: source.fetchedAt, sourceFieldLineage: { openDate: "official application time", deadlineDate: "official final application deadline" } }; }),
  scholarships,
};
const candidateText = `${JSON.stringify(candidate, null, 2)}\n`, validation = createCatalogMigrationValidationReport(JSON.parse(candidateText));
if (!validation.ok) throw new Error(`NUAA candidate invalid:\n${validation.errors.join("\n")}`);
await Promise.all([writeFile(paths.draft, candidateText, "utf8"), writeFile(paths.validation, `${JSON.stringify({ ...validation, sourceManifestSha256: sha(manifestText), parsedArtifactSha256: sha(parsedText), extractionCounts: parsed.counts }, null, 2)}\n`, "utf8")]);
console.log(JSON.stringify({ ok: true, summary: validation.summary, bundleSha256: validation.bundleSha256, operationPlanSha256: validation.operationPlanSha256, paths }, null, 2));
