import{createHash}from"node:crypto";import{readFile,writeFile}from"node:fs/promises";import{createCatalogMigrationValidationReport,type CatalogSeedBundle}from"../src/server/catalog/seed-contract.ts";
const sha=(v:string)=>createHash("sha256").update(v).digest("hex"),hmText=await readFile("work/catalog-official/blcu-school-programs-batch-01/manifest.json","utf8"),pmText=await readFile("work/catalog-official/blcu-school-programs-attachments-batch-01/manifest.json","utf8"),hm=JSON.parse(hmText),pm=JSON.parse(pmText),base=JSON.parse(await readFile("seeds/catalog.blcu-graduate-safe-batch-01.approved.local.json","utf8")),pdf=pm.sources.find((x:any)=>x.id==="blcu-graduate-programs-pdf-2026"),req=hm.sources.find((x:any)=>x.id==="blcu-graduate-entry-requirements-current");if(pdf?.sha256!=="9c6ab72ff83e883f151475e74a55f61b0066f7ff58a5175951a582c062a3d237"||req?.sha256!=="ef75e4913a3aa08a07383a529622be9dd19ccc5745cfa0adeb7312667a487695")throw new Error("evidence mismatch");
type R={en:string;zh:string;degree:"Master"|"Doctoral";school:string;years:number;language:"Chinese"|"English";tuition:number;hsk?:string;english?:string};const M="Master" as const,D="Doctoral" as const,C="Chinese" as const,E="English" as const;
const rows:R[]=[
 {en:"Political Science",zh:"政治学",degree:M,school:"School of International Politics and Communication",years:3,language:C,tuition:30000,hsk:"HSK Level 5, 210 or above; each section at least 60"},
 {en:"Principles of Education",zh:"教育学原理",degree:M,school:"School of Teacher Education",years:3,language:C,tuition:30000,hsk:"HSK Level 5, 210 or above; each section at least 60"},
 {en:"Journalism and Communication",zh:"新闻与传播",degree:M,school:"School of International Politics and Communication",years:2,language:C,tuition:30000,hsk:"HSK Level 5, 210 or above; each section at least 60"},
 {en:"Computer Science and Technology",zh:"计算机科学与技术",degree:M,school:"School of Information Science",years:3,language:C,tuition:30000,hsk:"HSK Level 6, 180 or above",english:"TOEFL iBT 90, IELTS 6.0, or GRE 300"},
 {en:"Language Intelligence and Technology",zh:"语言智能与技术",degree:M,school:"School of Information Science",years:3,language:C,tuition:30000,hsk:"HSK Level 6, 200 or above",english:"TOEFL iBT 90, IELTS 6.0, or GRE 300"},
 {en:"Psychology",zh:"心理学",degree:M,school:"School of Psychology and Cognitive Sciences",years:3,language:C,tuition:30000,hsk:"HSK Level 5, 180 or above; each section at least 60"},
 {en:"Language Cognitive Science",zh:"语言认知科学",degree:M,school:"School of Psychology and Cognitive Sciences",years:3,language:C,tuition:30000,hsk:"HSK Level 5, 180 or above"},
 {en:"Language Policy and Planning",zh:"语言政策与语言规划",degree:M,school:"School of Language Sciences and Resources",years:3,language:C,tuition:30000,hsk:"HSK Level 6, 180 or above; writing at least 65"},
 {en:"Language Resource Studies",zh:"语言资源学",degree:M,school:"School of Language Sciences and Resources",years:3,language:C,tuition:30000,hsk:"HSK Level 6, 180 or above"},
 {en:"Language and Brain Science",zh:"语言与人脑科学",degree:M,school:"School of Language Sciences and Resources",years:3,language:C,tuition:30000,hsk:"HSK Level 5, 180 or above"},
 {en:"Finance",zh:"金融",degree:M,school:"Business School",years:2,language:E,tuition:48000,english:"IELTS 6.0 with each section at least 5.5, TOEFL 90, or native English"},
 {en:"International Business",zh:"国际商务",degree:M,school:"Business School",years:2,language:E,tuition:49000,english:"IELTS 6.0 with each section at least 5.5, TOEFL 90, or native English"},
 {en:"International Chinese Language Education",zh:"国际中文教育",degree:D,school:"International Chinese College",years:3,language:C,tuition:48000,hsk:"HSK Level 6, 180 or above"},
 {en:"English Language and Literature",zh:"英语语言文学",degree:D,school:"School of English and Advanced Translation",years:3,language:C,tuition:32500,hsk:"HSK Level 6, 180 or above; each section at least 60",english:"IELTS 6.5, TOEFL 100, or native English"},
 {en:"Literary Theory",zh:"文艺学",degree:D,school:"School of Literature",years:3,language:C,tuition:32500,hsk:"HSK Level 6, 180 or above; each section at least 60"},
 {en:"Chinese Classical Philology",zh:"中国古典文献学",degree:D,school:"School of Literature",years:3,language:C,tuition:32500,hsk:"HSK Level 6, 180 or above; each section at least 60"},
 {en:"Modern and Contemporary Chinese Literature",zh:"中国现当代文学",degree:D,school:"School of Literature",years:3,language:C,tuition:32500,hsk:"HSK Level 6, 180 or above; each section at least 60"},
 {en:"Comparative Literature and World Literature",zh:"比较文学与世界文学",degree:D,school:"School of Literature",years:3,language:C,tuition:32500,hsk:"HSK Level 6, 180 or above; each section at least 60"},
 {en:"Language Intelligence and Technology",zh:"语言智能与技术",degree:D,school:"School of Information Science",years:3,language:C,tuition:32500,hsk:"HSK Level 6, 200 or above",english:"TOEFL iBT 90, IELTS 6.0, or GRE 300"},
 {en:"Psycholinguistics",zh:"心理语言学",degree:D,school:"School of Psychology and Cognitive Sciences",years:3,language:C,tuition:32500,hsk:"HSK Level 6, 180 or above; each section at least 60"},
];if(rows.length!==20)throw new Error("route count");const schoolSlug="beijing-language-and-culture-university",slugify=(v:string)=>v.toLowerCase().replace(/&/g," and ").replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"");
const programs=rows.map(r=>({slug:`${schoolSlug}-${r.degree.toLowerCase()}-${slugify(r.en)}-${r.language.toLowerCase()}-2026`,schoolSlug,citySlug:"beijing",nameEn:r.en,nameZh:r.zh,degreeLevel:r.degree,durationYears:r.years,fieldCategory:r.school,subjectArea:r.school,teachingLanguage:r.language,...(r.hsk?{hskRequirement:r.hsk}:{}),...(r.english?{englishRequirement:r.english}:{}),tuitionAmount:r.tuition,tuitionCurrency:"RMB",tuitionPeriod:"year",tuitionText:`CNY ${r.tuition.toLocaleString("en-US")} per academic year`,applicationUrl:"https://apply.blcu.edu.cn",applicationNote:`Official BLCU 2026 ${r.language.toLowerCase()}-taught ${r.degree.toLowerCase()} route; route-specific interview or examination may apply.`,status:"draft",sourceUrl:pdf.url,sourceLabel:pdf.label,sourceSha256:pdf.sha256,capturedAt:pdf.fetchedAt,sourceFieldLineage:{nameZh:`2026 graduate catalog PDF page ${r.degree===D?2:1}`,nameEn:"editorial English translation of official Chinese title",degreeLevel:"2026 graduate catalog PDF section heading",durationYears:"2026 graduate catalog PDF program group",teachingLanguage:"2026 graduate catalog PDF section heading",tuitionAmount:"2026 graduate catalog PDF program row",...(r.hsk?{hskRequirement:`maintained graduate entry requirement table, ${r.zh}（${r.degree===D?"博士":"硕士"}）`}:{}),applicationUrl:"2026 graduate catalog PDF page 2"}}));
const c:CatalogSeedBundle={version:1,generatedAt:pm.generatedAt,cities:base.cities,schools:base.schools,programs,programIntakes:programs.map(p=>({programSlug:p.slug,intakeTerm:"Fall",intakeYear:2026,deadlineDate:"2026-07-30T00:00:00.000Z",deadlineLabel:"July 30, 2026",applicationRound:"2026 international graduate admissions",status:"closed",sourceUrl:pdf.url,sourceLabel:pdf.label,sourceSha256:pdf.sha256,capturedAt:pdf.fetchedAt,sourceFieldLineage:{deadlineDate:"2026 graduate catalog PDF page 2"}})),scholarships:[]},text=JSON.stringify(c,null,2)+"\n",validation=createCatalogMigrationValidationReport(c);if(!validation.ok)throw new Error(validation.errors.join("\n"));await Promise.all([writeFile("seeds/catalog.blcu-graduate-safe-batch-02.draft.json",text),writeFile("seeds/catalog.blcu-graduate-safe-batch-02.validation.json",JSON.stringify({...validation,candidateSha256:sha(text),pdfManifestSha256:sha(pmText),htmlManifestSha256:sha(hmText)},null,2)+"\n")]);console.log(JSON.stringify({ok:true,summary:validation.summary,bundleSha256:validation.bundleSha256},null,2));
