import { createHash } from "node:crypto";
import { readFile, writeFile } from "node:fs/promises";
import { resolve } from "node:path";
import { CatalogSeedWriter } from "../src/server/catalog/seed-writer.ts";
import { createCatalogMigrationValidationReport, type CatalogSeedBundle } from "../src/server/catalog/seed-contract.ts";
import { assertLocalCatalogPublishTarget, LOCAL_CATALOG_PUBLISH_CONFIRMATION } from "../src/server/catalog/local-publish-safety.ts";
import { createPostgresPool, createTransactionalSqlClient } from "../src/server/db/postgres-client.ts";

const options = new Map(process.argv.slice(2).map(arg => { const at = arg.indexOf("="); if (!arg.startsWith("--") || at < 0) throw new Error(`Option requires a value: ${arg}`); return [arg.slice(2, at), arg.slice(at + 1)]; }));
const required = (name: string) => { const value = options.get(name)?.trim(); if (!value) throw new Error(`Missing --${name}=...`); return value; };
if ([...options.keys()].some(key => !new Set(["review-hash", "review", "approved-at", "confirm"]).has(key))) throw new Error("Unknown publication option.");
const approvedReviewHash = required("review-hash"); const reviewReference = required("review"); const approvedAt = required("approved-at"); const confirmation = required("confirm");
if (!/^[a-f0-9]{64}$/.test(approvedReviewHash) || !/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(?:\.\d{3})?Z$/.test(approvedAt) || Number.isNaN(Date.parse(approvedAt))) throw new Error("Invalid review hash or approval time.");
if (confirmation !== LOCAL_CATALOG_PUBLISH_CONFIRMATION) throw new Error("Incorrect local catalog publication confirmation token.");
const root = process.cwd();
const paths = { candidate: resolve(root, "seeds/catalog.tongji-scholarships-batch-02.draft.json"), validation: resolve(root, "seeds/catalog.tongji-scholarships-batch-02.validation.json"), review: resolve(root, "seeds/catalog.tongji-scholarships-batch-02.review.json"), prior: resolve(root, "seeds/catalog.tongji-school-program-batch-01.approved.local.json"), output: resolve(root, "seeds/catalog.tongji-scholarships-batch-02.approved.local.json"), approval: resolve(root, "seeds/catalog.tongji-scholarships-batch-02.approval.json"), state: resolve(root, ".cuac-local/runtime.json") };
const parse = async (path: string) => JSON.parse(await readFile(path, "utf8"));
const candidateText = await readFile(paths.candidate, "utf8"); const candidate = JSON.parse(candidateText) as CatalogSeedBundle; const validation = await parse(paths.validation); const review = await parse(paths.review); const prior = await parse(paths.prior); const state = await parse(paths.state);
const { reviewHash: storedHash, publicationReference: storedReference, ...reviewBase } = review;
if (storedHash !== approvedReviewHash || createHash("sha256").update(JSON.stringify(reviewBase)).digest("hex") !== approvedReviewHash || storedReference !== reviewReference) throw new Error("Standing-authorized Tongji review hash/reference mismatch.");
const candidateSha256 = createHash("sha256").update(candidateText).digest("hex"); const fresh = createCatalogMigrationValidationReport(candidate);
if (candidateSha256 !== review.candidateSha256 || !fresh.ok || !validation.ok || fresh.bundleSha256 !== validation.bundleSha256 || fresh.operationPlanSha256 !== validation.operationPlanSha256) throw new Error("Tongji candidate or validation changed after review.");
if (review.status !== "standing_user_approval" || review.standingAuthorization?.instruction !== "发布默认允许" || review.sensitiveDataCheck?.result !== "pass" || review.visualReview?.result !== "pass") throw new Error("Tongji review is not eligible for standing-authorized publication.");
if (review.scope?.newScholarshipCount !== 3 || review.scope?.archiveProgramAliasCount !== 0 || review.scope?.archiveScholarshipAliasCount !== 0 || review.reconciliation?.destructiveDeletion !== false) throw new Error("Standing authorization cannot archive, delete or overwrite records.");
if (JSON.stringify(candidate.cities) !== JSON.stringify(prior.cities) || JSON.stringify(candidate.schools) !== JSON.stringify(prior.schools)) throw new Error("Tongji dependency replay is not byte-equivalent.");
const scholarships = candidate.scholarships ?? []; if (scholarships.length !== 3 || scholarships.some(row => row.schoolSlug !== "tongji-university" || row.status !== "draft")) throw new Error("Tongji candidate must contain three draft scholarships.");
const sourceSchemaSha256 = createHash("sha256").update(JSON.stringify({ cityFields: [...new Set((candidate.cities ?? []).flatMap(row => Object.keys(row)))].sort(), schoolFields: [...new Set((candidate.schools ?? []).flatMap(row => Object.keys(row)))].sort(), scholarshipFields: [...new Set(scholarships.flatMap(row => Object.keys(row)))].sort() })).digest("hex");
const publication: CatalogSeedBundle = { version: 2, generatedAt: approvedAt, handoff: { sourceSystem: "CUAC reviewed official Tongji University 2026 scholarship sources", cleanedExportName: "catalog.tongji-scholarships-batch-02.draft.json", cleanedExportSha256: fresh.bundleSha256, sourceSchemaSha256, reviewReference, prohibitedDataReviewReference: reviewReference, approvalRecordedAt: approvedAt, sourceReadOnly: true, prohibitedDataConfirmedExcluded: true }, cities: candidate.cities, schools: candidate.schools, programs: [], programIntakes: [], scholarships: scholarships.map(row => ({ ...row, status: "active" as const, verificationStatus: "verified" as const, lastVerifiedAt: approvedAt })) };
const report = createCatalogMigrationValidationReport(publication); if (!report.ok || report.summary.schools !== 1 || report.summary.scholarships !== 3 || report.summary.programs !== 0) throw new Error(`Invalid Tongji publication: ${report.errors.join(" ")}`);
const approval = { version: 1, approvedAt, approvalMode: "standing-user-default-publication", reviewReference, approvedReviewSha256: approvedReviewHash, approvedCandidateFileSha256: candidateSha256, approvedCandidateBundleSha256: fresh.bundleSha256, publicationBundle: "seeds/catalog.tongji-scholarships-batch-02.approved.local.json", publicationBundleSha256: report.bundleSha256, schoolSlug: "tongji-university", scholarshipSlugs: publication.scholarships!.map(row => row.slug), archivedProgramAliases: [], archivedScholarshipAliases: [], prohibitedDataConfirmedExcluded: true };
async function writeOrVerify(path: string, value: unknown) { const body = `${JSON.stringify(value, null, 2)}\n`; try { await writeFile(path, body, { encoding: "utf8", flag: "wx" }); } catch (error: any) { if (error?.code !== "EEXIST") throw error; if (await readFile(path, "utf8") !== body) throw new Error(`Existing artifact differs: ${path}`); } }
await writeOrVerify(paths.output, publication); await writeOrVerify(paths.approval, approval);
const target = assertLocalCatalogPublishTarget(state, publication, confirmation, reviewReference); const pool = createPostgresPool({ databaseUrl: target.databaseUrl, max: 1, applicationName: "cuac:tongji-scholarships-batch-02" });
try { const client = createTransactionalSqlClient(pool); const result = await client.transaction(async tx => {
  const identity = await tx.query<{ database_name: string; database_user: string }>("select current_database() database_name,current_user database_user", []); if (identity[0]?.database_name !== target.publicTarget.databaseName || identity[0]?.database_user !== target.publicTarget.databaseUser) throw new Error("Database identity mismatch.");
  const school = await tx.query<{ id: string }>("select id from schools where slug=$1 and status='active' and verification_status='verified'", ["tongji-university"]); if (school.length !== 1 || school[0].id !== "d01a131b-731a-4fbf-aad7-f9e41a30f01a") throw new Error("Tongji dependency school mismatch.");
  const baseline = await tx.query<{ programs: string; intakes: string; scholarships: string }>("select (select count(*) from programs where school_id=$1 and status='active')::text programs,(select count(*) from program_intakes pi join programs p on p.id=pi.program_id where p.school_id=$1)::text intakes,(select count(*) from scholarships where school_id=$1 and status='active')::text scholarships", [school[0].id]);
  const slugs = publication.scholarships!.map(row => row.slug); const existing = await tx.query<{ slug: string; status: string; verification_status: string; last_verified_at: Date | null }>("select slug,status,verification_status,last_verified_at from scholarships where slug=any($1::text[])", [slugs]);
  const isPre = baseline[0]?.programs === "71" && baseline[0]?.intakes === "71" && baseline[0]?.scholarships === "1" && existing.length === 0; const isPost = baseline[0]?.programs === "71" && baseline[0]?.intakes === "71" && baseline[0]?.scholarships === "4" && existing.length === 3 && existing.every(row => row.status === "active" && row.verification_status === "verified" && row.last_verified_at?.toISOString() === approvedAt); if (!isPre && !isPost) throw new Error(`Tongji baseline changed: ${JSON.stringify({ baseline: baseline[0], existing })}`);
  const written = await new CatalogSeedWriter(tx).writeBundle(publication); if (!written.ok) throw new Error(`Catalog write failed: ${written.errors.join(" ")}`);
  const final = await tx.query<{ slug: string; body: string; benefits: string; eligibility: string; materials: string; steps: string; actions: string }>("select slug,jsonb_array_length(body_sections)::text body,jsonb_array_length(benefit_items)::text benefits,jsonb_array_length(eligibility_items)::text eligibility,jsonb_array_length(application_materials)::text materials,jsonb_array_length(application_steps)::text steps,jsonb_array_length(action_links)::text actions from scholarships where slug=any($1::text[]) and status='active' and verification_status='verified'", [slugs]); if (final.length !== 3 || final.some(row => [row.body,row.benefits,row.eligibility,row.materials,row.steps,row.actions].some(value => Number(value) < 1))) throw new Error("Tongji rich scholarship post-check failed.");
  const counts = await tx.query<{ programs: string; intakes: string; scholarships: string }>("select (select count(*) from programs where school_id=$1 and status='active')::text programs,(select count(*) from program_intakes pi join programs p on p.id=pi.program_id where p.school_id=$1)::text intakes,(select count(*) from scholarships where school_id=$1 and status='active' and verification_status='verified')::text scholarships", [school[0].id]); if (counts[0]?.programs !== "71" || counts[0]?.intakes !== "71" || counts[0]?.scholarships !== "4") throw new Error(`Tongji post-count mismatch: ${JSON.stringify(counts[0])}`); return { written, schoolId: school[0].id, counts: counts[0], scholarshipSlugs: final.map(row => row.slug) };
}); console.log(JSON.stringify({ ok: true, target: target.publicTarget, approvedReviewSha256: approvedReviewHash, publicationBundleSha256: report.bundleSha256, approvalPath: paths.approval, outputPath: paths.output, ...result }, null, 2)); } finally { await pool.end(); }
