import { createHash } from "node:crypto";
import { readFile, writeFile } from "node:fs/promises";
import { resolve } from "node:path";
import { createCatalogMigrationValidationReport, type CatalogSeedBundle, type CatalogSeedSchool } from "../src/server/catalog/seed-contract.ts";
import { createPostgresPool } from "../src/server/db/postgres-client.ts";
import { localDatabaseUrl } from "./lib/local-development.ts";

const root=process.cwd(),paths={safe:resolve(root,"seeds/catalog.jilin-safe-new-batch-01.approved.local.json"),approval:resolve(root,"seeds/catalog.jilin-safe-new-batch-01.approval.json"),manifest:resolve(root,"work/catalog-official/jilin-complete-batch-01/manifest.json"),candidate:resolve(root,"seeds/catalog.jilin-cleanup.draft.json"),validation:resolve(root,"seeds/catalog.jilin-cleanup.validation.json"),review:resolve(root,"seeds/catalog.jilin-cleanup.review.json"),state:resolve(root,".cuac-local/runtime.json")},sha=(value:string|Buffer)=>createHash("sha256").update(value).digest("hex");
const [safeText,approvalText,manifestText,stateText]=await Promise.all([readFile(paths.safe,"utf8"),readFile(paths.approval,"utf8"),readFile(paths.manifest,"utf8"),readFile(paths.state,"utf8")]),safe=JSON.parse(safeText) as CatalogSeedBundle,approval=JSON.parse(approvalText),manifest=JSON.parse(manifestText),state=JSON.parse(stateText),schoolSlug="jilin-university";
if(approval.programSlugs?.length!==244||approval.scholarshipSlugs?.length!==5||safe.programs?.length!==244||safe.scholarships?.length!==5)throw new Error("Jilin safe publication dependencies changed.");
const source=manifest.sources.find((row:any)=>row.id==="jilin-graduate-admissions-2026");if(!source||source.status!==200||source.sha256!=="3ebbed029297a6af0f56f1ef9624d54d78287ee1bc2aedd0f182562ba4d65100")throw new Error("Jilin official admissions source changed.");
const languages=[...new Set(safe.programs.map((row:any)=>row.teachingLanguage).filter(Boolean))].sort(),subjects=[...new Set(safe.programs.map((row:any)=>row.subjectArea).filter(Boolean))].slice(0,20);
const school:CatalogSeedSchool={slug:schoolSlug,nameEn:"Jilin University",nameZh:"吉林大学",citySlug:"changchun",schoolType:"Public",region:"Changchun, Northeast China",applicationLevel:"Undergraduate, Master, Doctoral",languageOfInstruction:languages.join(", "),hskRequirement:"The reviewed 2026/2027 High-level Graduate scholarship route publishes HSK Level 4 or above for Chinese-medium study.",deadlineSummary:"March 1, 2026 for the reviewed High-level Graduate scholarship route; other routes use their own official deadlines.",tuitionSummary:"CNY 21,000–36,000/year across the reviewed graduate discipline and language bands.",websiteUrl:"https://www.jlu.edu.cn/",admissionsUrl:"https://apply.jlu.edu.cn",cscaRequired:false,cscaRequirement:"No CSCA requirement is published for the reviewed graduate routes; undergraduate requirements must be checked separately.",cscaSubjects:[],subjectTags:subjects,languageTags:languages,status:"draft",sourceUrl:source.url,sourceLabel:source.label,sourceSha256:source.sha256,capturedAt:source.fetchedAt,sourceFieldLineage:{nameEn:"official admissions guide identity",nameZh:"official institution identity",citySlug:"official university identity and Changchun campus context",applicationLevel:"official 2026/2027 admissions materials",languageOfInstruction:"reviewed official program catalog language sections",hskRequirement:"official scholarship eligibility section",deadlineSummary:"official application process",tuitionSummary:"official graduate tuition table",admissionsUrl:"official online application instructions"}};
const candidateRaw:CatalogSeedBundle={version:1,generatedAt:new Date().toISOString(),cities:safe.cities,schools:[school],programs:[],programIntakes:[],scholarships:[]},candidateText=`${JSON.stringify(candidateRaw,null,2)}\n`,candidate=JSON.parse(candidateText) as CatalogSeedBundle,validation=createCatalogMigrationValidationReport(candidate);if(!validation.ok)throw new Error(`Invalid Jilin cleanup candidate: ${validation.errors.join(" ")}`);
const pool=createPostgresPool({databaseUrl:localDatabaseUrl(state),max:1,applicationName:"cuac:jilin-cleanup-review"});let baseline:any;
try{const schoolRows=await pool.query("select id,status,verification_status,source_url from schools where slug=$1",[schoolSlug]),programs=await pool.query("select id,slug,status,verification_status from programs where school_id=$1 and status='active' order by slug",[schoolRows.rows[0]?.id]),scholarships=await pool.query("select id,slug,status,verification_status from scholarships where school_id=$1 and status='active' order by slug",[schoolRows.rows[0]?.id]);const officialPrograms=programs.rows.filter((row:any)=>approval.programSlugs.includes(row.slug)),legacyPrograms=programs.rows.filter((row:any)=>!approval.programSlugs.includes(row.slug)),protectedScholarships=new Set([...approval.scholarshipSlugs,"official-2026-jilin-high-level-postgraduate-scholarship"]),officialScholarships=scholarships.rows.filter((row:any)=>protectedScholarships.has(row.slug)),legacyScholarships=scholarships.rows.filter((row:any)=>!protectedScholarships.has(row.slug));baseline={school:schoolRows.rows,officialPrograms,legacyPrograms,officialScholarships,legacyScholarships};if(schoolRows.rows.length!==1||schoolRows.rows[0].status!=="active"||schoolRows.rows[0].verification_status!=="unverified"||officialPrograms.length!==244||officialPrograms.some((row:any)=>row.verification_status!=="verified")||legacyPrograms.length!==3||legacyPrograms.some((row:any)=>row.verification_status!=="unverified")||officialScholarships.length!==6||officialScholarships.some((row:any)=>row.verification_status!=="verified")||legacyScholarships.length!==1||legacyScholarships[0].verification_status!=="unverified")throw new Error(`Jilin cleanup baseline changed: ${JSON.stringify({school:schoolRows.rows,programs:programs.rows.length,officialPrograms:officialPrograms.length,legacyPrograms:legacyPrograms.length,scholarships:scholarships.rows.length,officialScholarships:officialScholarships.length,legacyScholarships:legacyScholarships.length})}`);}finally{await pool.end();}
const reviewBase={version:1,status:"requires_explicit_approval",generatedAt:candidate.generatedAt,scope:{schoolSlug,schoolOverwriteCount:1,archiveProgramAliasCount:3,archiveScholarshipAliasCount:1,verifiedProgramMutationCount:0,verifiedScholarshipMutationCount:0},candidateSha256:sha(candidateText),candidateBundleSha256:validation.bundleSha256,operationPlanSha256:validation.operationPlanSha256,sourceEvidence:{manifestSha256:sha(manifestText),safePublicationSha256:sha(safeText),safeApprovalSha256:sha(approvalText)},reconciliation:{destructiveDeletion:false,overwrite:{entityType:"school",id:baseline.school[0].id,slug:schoolSlug,reason:"Replace unverified third-party summary with reviewed official admissions and catalog-derived profile."},archives:[...baseline.legacyPrograms.map((row:any)=>({entityType:"program",id:row.id,slug:row.slug,reason:"Superseded by reviewed official 2026/2027 route records."})),...baseline.legacyScholarships.map((row:any)=>({entityType:"scholarship",id:row.id,slug:row.slug,reason:"Superseded by independently scoped verified official scholarship records."}))],databaseBaseline:{schoolId:baseline.school[0].id,legacyProgramIds:baseline.legacyPrograms.map((row:any)=>row.id),legacyScholarshipIds:baseline.legacyScholarships.map((row:any)=>row.id),protectedProgramIds:baseline.officialPrograms.map((row:any)=>row.id),protectedScholarshipIds:baseline.officialScholarships.map((row:any)=>row.id)}},sensitiveDataCheck:{result:"pass",scope:"school profile and archive status changes",note:"Public institutional catalog data only; no applicant, account, payment or personal-contact data."},coverageLimitations:["The 244 verified programs are the official High-level Graduate scholarship catalog subset; the CAPTCHA-protected exhaustive self-funded and undergraduate attachments were not bypassed."],reviewNotes:["No verified program or scholarship is modified.","Legacy rows are status-archived, not physically deleted.","After publication Jilin University will have a verified school, 244/244 active verified programs and 6/6 active verified scholarships."]};
const reviewHash=sha(JSON.stringify(reviewBase)),requiredApproval=`批准完成吉林大学官方学校资料，并归档 3 条旧项目及 1 条旧奖学金（审核哈希 ${reviewHash}）`;await Promise.all([writeFile(paths.candidate,candidateText,"utf8"),writeFile(paths.validation,`${JSON.stringify(validation,null,2)}\n`,"utf8"),writeFile(paths.review,`${JSON.stringify({...reviewBase,reviewHash,requiredApproval},null,2)}\n`,"utf8")]);console.log(JSON.stringify({ok:true,reviewHash,requiredApproval,scope:reviewBase.scope},null,2));
