import { createHash } from "node:crypto";
import { readFile, writeFile } from "node:fs/promises";
import { resolve } from "node:path";
import { CatalogSeedWriter } from "../src/server/catalog/seed-writer.ts";
import { createCatalogMigrationValidationReport, type CatalogSeedBundle } from "../src/server/catalog/seed-contract.ts";
import { assertLocalCatalogPublishTarget, LOCAL_CATALOG_PUBLISH_CONFIRMATION } from "../src/server/catalog/local-publish-safety.ts";
import { createPostgresPool, createTransactionalSqlClient } from "../src/server/db/postgres-client.ts";

const options = new Map(process.argv.slice(2).map((arg) => { const at = arg.indexOf("="); if (!arg.startsWith("--") || at < 0) throw new Error(`Option requires value: ${arg}`); return [arg.slice(2, at), arg.slice(at + 1)]; }));
const required = (name: string) => { const value = options.get(name)?.trim(); if (!value) throw new Error(`Missing --${name}=...`); return value; };
const approvedHash = required("review-hash"), reviewReference = required("review"), approvedAt = required("approved-at"), confirmation = required("confirm");
if (!/^[a-f0-9]{64}$/.test(approvedHash) || Number.isNaN(Date.parse(approvedAt)) || confirmation !== LOCAL_CATALOG_PUBLISH_CONFIRMATION) throw new Error("Invalid UESTC cleanup approval parameters.");
const root = process.cwd(), paths = { candidate: resolve(root, "seeds/catalog.uestc-cleanup.draft.json"), validation: resolve(root, "seeds/catalog.uestc-cleanup.validation.json"), review: resolve(root, "seeds/catalog.uestc-cleanup.review.json"), safeApproval: resolve(root, "seeds/catalog.uestc-safe-programs-batch-01.approval.json"), output: resolve(root, "seeds/catalog.uestc-cleanup.approved.local.json"), approval: resolve(root, "seeds/catalog.uestc-cleanup.approval.json"), state: resolve(root, ".cuac-local/runtime.json") };
const parse = async (path: string) => JSON.parse(await readFile(path, "utf8")), sha = (value: string) => createHash("sha256").update(value).digest("hex");
const candidateText = await readFile(paths.candidate, "utf8"), candidate = JSON.parse(candidateText) as CatalogSeedBundle;
const [validation, review, safeApproval, state] = await Promise.all([parse(paths.validation), parse(paths.review), parse(paths.safeApproval), parse(paths.state)]), { reviewHash, requiredApproval, ...reviewBase } = review;
if (reviewHash !== approvedHash || sha(JSON.stringify(reviewBase)) !== approvedHash || requiredApproval !== reviewReference || review.status !== "requires_explicit_approval" || review.scope?.schoolOverwriteCount !== 1 || review.scope?.programOverwriteCount !== 0 || review.scope?.archiveProgramAliasCount !== 3 || review.scope?.archiveScholarshipAliasCount !== 3 || review.scope?.scholarshipPublicationCount !== 0 || review.reconciliation?.destructiveDeletion !== false || review.sourceReview?.result !== "pass" || review.visualReview?.result !== "pass" || review.sensitiveDataCheck?.result !== "pass") throw new Error("Approved UESTC cleanup review does not match stored operation.");
const fresh = createCatalogMigrationValidationReport(candidate);
if (!fresh.ok || !validation.ok || sha(candidateText) !== review.candidateSha256 || fresh.bundleSha256 !== review.candidateBundleSha256 || fresh.bundleSha256 !== validation.bundleSha256 || fresh.operationPlanSha256 !== review.operationPlanSha256 || fresh.operationPlanSha256 !== validation.operationPlanSha256) throw new Error("UESTC cleanup candidate changed after review.");
const programAliases = review.reconciliation.archives.filter((row: any) => row.entityType === "program").map((row: any) => row.slug), scholarshipAliases = review.reconciliation.archives.filter((row: any) => row.entityType === "scholarship").map((row: any) => row.slug);
const sourceSchemaSha256 = sha(JSON.stringify({ cityFields: [...new Set(candidate.cities!.flatMap(Object.keys))].sort(), schoolFields: [...new Set(candidate.schools!.flatMap(Object.keys))].sort() }));
const publication: CatalogSeedBundle = { version: 2, generatedAt: approvedAt, handoff: { sourceSystem: "CUAC reviewed UESTC 2026 school cleanup", cleanedExportName: "catalog.uestc-cleanup.draft.json", cleanedExportSha256: fresh.bundleSha256, sourceSchemaSha256, reviewReference, prohibitedDataReviewReference: reviewReference, approvalRecordedAt: approvedAt, sourceReadOnly: true, prohibitedDataConfirmedExcluded: true }, cities: candidate.cities, schools: candidate.schools!.map((row) => ({ ...row, status: "active" as const, verificationStatus: "verified" as const, lastVerifiedAt: approvedAt })), programs: [], programIntakes: [], scholarships: [] };
const report = createCatalogMigrationValidationReport(publication);
if (!report.ok || report.summary.schools !== 1 || report.summary.programs !== 0 || report.summary.scholarships !== 0) throw new Error(`Invalid UESTC cleanup publication: ${report.errors.join(" ")}`);
const approval = { version: 1, approvedAt, approvalMode: "explicit-product-owner-approval", reviewReference, approvedReviewSha256: approvedHash, publicationBundle: "seeds/catalog.uestc-cleanup.approved.local.json", publicationBundleSha256: report.bundleSha256, schoolSlug: review.scope.schoolSlug, archivedProgramAliases: programAliases, archivedScholarshipAliases: scholarshipAliases, protectedSafeProgramSlugs: safeApproval.programSlugs, physicalDeletion: false, prohibitedDataConfirmedExcluded: true };
async function writeOrVerify(path: string, value: unknown) { const body = `${JSON.stringify(value, null, 2)}\n`; try { await writeFile(path, body, { encoding: "utf8", flag: "wx" }); } catch (error: any) { if (error?.code !== "EEXIST") throw error; if (await readFile(path, "utf8") !== body) throw new Error(`Existing artifact differs: ${path}`); } }
await writeOrVerify(paths.output, publication); await writeOrVerify(paths.approval, approval);
const target = assertLocalCatalogPublishTarget(state, publication, confirmation, reviewReference), pool = createPostgresPool({ databaseUrl: target.databaseUrl, max: 1, applicationName: "cuac:uestc-cleanup-publish" });
try {
  const client = createTransactionalSqlClient(pool);
  const result = await client.transaction(async (tx) => {
    const school = await tx.query<any>("select id,status,verification_status from schools where slug='university-of-electronic-science-and-technology-of-china'", []), cityBefore = await tx.query<any>("select to_jsonb(c)-'created_at'-'updated_at' snapshot from cities c where slug='chengdu'", []);
    if (school.length !== 1 || school[0].id !== review.reconciliation.databaseBaseline.schoolId || school[0].status !== "active" || school[0].verification_status !== "unverified" || cityBefore.length !== 1 || cityBefore[0].snapshot.id !== review.reconciliation.databaseBaseline.cityId) throw new Error("UESTC cleanup baseline changed.");
    const protectedPrograms = await tx.query<any>("select slug,status,verification_status,last_verified_at from programs where slug=any($1::text[]) order by slug", [safeApproval.programSlugs]);
    const legacyPrograms = await tx.query<any>("select slug,status,verification_status from programs where slug=any($1::text[]) order by slug", [programAliases]), legacyScholarships = await tx.query<any>("select slug,status,verification_status from scholarships where slug=any($1::text[]) order by slug", [scholarshipAliases]);
    if (protectedPrograms.length !== 72 || protectedPrograms.some((row) => row.status !== "active" || row.verification_status !== "verified" || row.last_verified_at?.toISOString() !== safeApproval.approvedAt) || legacyPrograms.length !== 3 || legacyScholarships.length !== 3 || [...legacyPrograms, ...legacyScholarships].some((row) => row.status !== "active" || row.verification_status !== "unverified")) throw new Error("UESTC protected or legacy records changed.");
    const written = await new CatalogSeedWriter(tx).writeBundle(publication, { preserveExistingCitySlugs: ["chengdu"] }); if (!written.ok) throw new Error(`UESTC cleanup write failed: ${written.errors.join(" ")}`);
    await tx.query("update programs set status='archived',updated_at=now() where slug=any($1::text[]) and status='active'", [programAliases]); await tx.query("update scholarships set status='archived',updated_at=now() where slug=any($1::text[]) and status='active'", [scholarshipAliases]);
    const cityAfter = await tx.query<any>("select to_jsonb(c)-'created_at'-'updated_at' snapshot from cities c where slug='chengdu'", []); if (JSON.stringify(cityAfter[0]?.snapshot) !== JSON.stringify(cityBefore[0].snapshot)) throw new Error("Chengdu city dependency changed.");
    const final = await tx.query<any>("select (select count(*) from schools where id=$1 and status='active' and verification_status='verified' and last_verified_at=$4)::int school_verified,(select count(*) from programs where school_id=$1 and status='active')::int programs,(select count(*) from programs where school_id=$1 and status='active' and verification_status='verified')::int verified_programs,(select count(*) from scholarships where school_id=$1 and status='active')::int scholarships,(select count(*) from programs where slug=any($2::text[]) and status='archived')::int archived_programs,(select count(*) from scholarships where slug=any($3::text[]) and status='archived')::int archived_scholarships", [school[0].id, programAliases, scholarshipAliases, approvedAt]);
    const expected = { school_verified: 1, programs: 72, verified_programs: 72, scholarships: 0, archived_programs: 3, archived_scholarships: 3 }; if (Object.entries(expected).some(([key, value]) => final[0]?.[key] !== value)) throw new Error(`UESTC cleanup post-check failed: ${JSON.stringify({ expected, actual: final[0] })}`);
    return { written: written.summary, totals: final[0], schoolId: school[0].id };
  });
  console.log(JSON.stringify({ ok: true, target: target.publicTarget, approvedReviewSha256: approvedHash, publicationBundleSha256: report.bundleSha256, approvalPath: paths.approval, outputPath: paths.output, ...result }, null, 2));
} finally { await pool.end(); }
