import { createHash } from "node:crypto";
import { readFile, writeFile } from "node:fs/promises";
import { resolve } from "node:path";
import { createCatalogMigrationValidationReport, type CatalogSeedBundle } from "../src/server/catalog/seed-contract.ts";
import { createPostgresPool } from "../src/server/db/postgres-client.ts";
import { localDatabaseUrl } from "./lib/local-development.ts";

const root=process.cwd(),schoolSlug="donghua-university",batch="dhu-safe-new-batch-01",prefix=`catalog.${batch}`;
const paths={manifest:resolve(root,"work/catalog-official/dhu-complete-batch-01/manifest.json"),rows:resolve(root,"work/catalog-official/dhu-complete-batch-01/program-rows.json"),fullDraft:resolve(root,"seeds/catalog.dhu-complete-batch-01.draft.json"),fullValidation:resolve(root,"seeds/catalog.dhu-complete-batch-01.validation.json"),state:resolve(root,".cuac-local/runtime.json"),candidate:resolve(root,`seeds/${prefix}.draft.json`),validation:resolve(root,`seeds/${prefix}.validation.json`),review:resolve(root,`seeds/${prefix}.review.json`)};
const parse=async(path:string)=>JSON.parse(await readFile(path,"utf8")),sha=(value:string|Buffer)=>createHash("sha256").update(value).digest("hex"),writeJson=(path:string,value:unknown)=>writeFile(path,`${JSON.stringify(value,null,2)}\n`,`utf8`);
const [manifest,rows,fullDraft,fullValidation,state]=await Promise.all([paths.manifest,paths.rows,paths.fullDraft,paths.fullValidation,paths.state].map(parse));
const freshFull=createCatalogMigrationValidationReport(fullDraft);if(!freshFull.ok||!fullValidation.ok||freshFull.bundleSha256!==fullValidation.bundleSha256||freshFull.operationPlanSha256!==fullValidation.operationPlanSha256||fullDraft.programs?.length!==131||fullDraft.programIntakes?.length!==131||fullDraft.scholarships?.length!==4||rows.length!==131)throw new Error("DHU full candidate changed.");
if(manifest.sources?.length!==10||manifest.sources.some((row:any)=>row.status!==200||row.finalUrl!==row.url||!/^https:\/\/english\.dhu\.edu\.cn\//.test(row.url)||!/^[a-f0-9]{64}$/.test(row.sha256)))throw new Error("DHU official evidence manifest changed.");
for(const source of manifest.sources){const artifact=await readFile(resolve(paths.manifest,"..",source.artifactPath));if(sha(artifact)!==source.sha256)throw new Error(`DHU evidence artifact changed: ${source.id}`);}

const protectedKeys=new Set([
  "Accounting|Chinese","Business Administration|Chinese","Digital Media Art|Chinese","Environmental Design|Chinese",
  "Environmental Design (Fashion Interior Design)|English","Fashion & Accessory Design (Fashion Innovation)|English",
  "Fashion Design & Engineering|Chinese","Fashion & Apparel Design|Chinese","Finance|Chinese",
  "International Economy & Trade|Chinese","Product Design|Chinese","Visual Communication Design|Chinese",
]);
const blocked=(row:any)=>row.degreeLevel==="Undergraduate"&&protectedKeys.has(`${row.nameEn}|${row.teachingLanguage}`);
const blockedPrograms=fullDraft.programs.filter(blocked),safePrograms=fullDraft.programs.filter((row:any)=>!blocked(row));
const safeSlugs=new Set(safePrograms.map((row:any)=>row.slug));
const safeIntakes=fullDraft.programIntakes.filter((row:any)=>safeSlugs.has(row.programSlug));
if(blockedPrograms.length!==12||safePrograms.length!==119||safeIntakes.length!==119)throw new Error(`DHU reconciliation changed: ${blockedPrograms.length}/${safePrograms.length}/${safeIntakes.length}`);

const pool=createPostgresPool({databaseUrl:localDatabaseUrl(state),max:1,applicationName:"cuac:dhu-safe-new-review"});let baseline:any;
try{const school=await pool.query("select id,slug,status,verification_status,source_url from schools where slug=$1",[schoolSlug]);if(school.rows.length!==1||school.rows[0].status!=="active"||school.rows[0].verification_status!=="unverified")throw new Error("DHU school baseline changed.");const programs=await pool.query("select id,slug,name_en,degree_level,teaching_language,status,verification_status,source_url from programs where school_id=$1 order by slug",[school.rows[0].id]);const intakes=await pool.query("select pi.id,p.slug program_slug,pi.intake_year,pi.status from program_intakes pi join programs p on p.id=pi.program_id where p.school_id=$1 order by p.slug",[school.rows[0].id]);const scholarships=await pool.query("select id,slug,status,verification_status from scholarships where school_id=$1 order by slug",[school.rows[0].id]);const candidatePrograms=await pool.query("select slug from programs where slug=any($1::text[])",[safePrograms.map((row:any)=>row.slug)]);const candidateScholarships=await pool.query("select slug from scholarships where slug=any($1::text[])",[fullDraft.scholarships.map((row:any)=>row.slug)]);if(programs.rows.length!==12||programs.rows.some((row:any)=>row.status!=="active"||row.verification_status!=="unverified")||intakes.rows.length!==5||scholarships.rows.length!==0||candidatePrograms.rows.length!==0||candidateScholarships.rows.length!==0)throw new Error("DHU protected or safe-new baseline changed.");baseline={school:school.rows[0],programs:programs.rows,intakes:intakes.rows,scholarships:scholarships.rows};}finally{await pool.end();}

const candidate:CatalogSeedBundle={version:1,generatedAt:fullDraft.generatedAt,cities:fullDraft.cities,schools:fullDraft.schools,programs:safePrograms,programIntakes:safeIntakes,scholarships:fullDraft.scholarships};
const validation=createCatalogMigrationValidationReport(candidate);if(!validation.ok||validation.summary.programs!==119||validation.summary.programIntakes!==119||validation.summary.scholarships!==4)throw new Error(`Invalid DHU safe-new candidate: ${validation.errors.join(" ")}`);
const candidateText=`${JSON.stringify(candidate,null,2)}\n`;
const reviewBase={version:1,status:"standing_user_approval",generatedAt:fullDraft.generatedAt,scope:{schoolSlug,newProgramCount:119,newProgramIntakeCount:119,newScholarshipCount:4,protectedCityCount:1,protectedSchoolCount:1,protectedLegacyProgramCount:12,protectedLegacyIntakeCount:5,overwriteCount:0,archiveCount:0,deleteCount:0},candidateSha256:sha(candidateText),candidateBundleSha256:validation.bundleSha256,operationPlanSha256:validation.operationPlanSha256,manifestSha256:sha(await readFile(paths.manifest)),programRowsSha256:sha(await readFile(paths.rows)),evidence:manifest.sources.map((source:any)=>({sourceId:source.id,sourceUrl:source.url,sourceLabel:source.label,sha256:source.sha256,fetchedAt:source.fetchedAt,contentType:source.contentType,byteLength:source.byteLength})),standingAuthorization:{reference:"user-chat-2026-09-13-default-publication",instruction:"发布默认允许",appliesBecause:"This batch inserts only 119 non-conflicting official program routes, their closed 2026 intakes, and four independently scoped official scholarships. It preserves the existing Shanghai city, Donghua University school, 12 legacy programs and five legacy intakes, with no overwrite, archive or deletion."},reconciliation:{destructiveDeletion:false,overwrites:[],archives:[],blockedOfficialRoutes:blockedPrograms.map((row:any)=>({slug:row.slug,nameEn:row.nameEn,degreeLevel:row.degreeLevel,teachingLanguage:row.teachingLanguage})),databaseBaseline:baseline},sourceReview:{result:"pass",note:"Ten exact Donghua University official sources are hash-bound. The three official program PDFs total six pages; all six pages were rendered and visually inspected, then OCR was reconciled to 131 reviewed program rows: 56 undergraduate, 48 master and 27 doctoral."},coverageReview:{result:"pass",findings:["Twelve official undergraduate rows are withheld because they overlap the 12 protected legacy program records.","The remaining 119 routes are non-conflicting additions with language, campus, tuition, duration, application timing and source lineage.","Four rich scholarships are independently scoped: CGS High-level Postgraduate, Shanghai Government Scholarship Type A, Type B, and CGS China Link.","All September 2026 intakes are marked closed because their May 31 deadline predates this review."]},sensitiveDataCheck:{result:"pass",scope:"119 programs, 119 intakes and four scholarships",note:"Only public institutional catalog, admissions and award facts are included. Personal contact details, applicant records, passport data, account identifiers, bank/payment/remittance information and submitted documents are excluded."},reviewNotes:["The Shanghai city and Donghua University school row remain byte-for-byte unchanged.","The 12 legacy programs and five legacy intakes remain byte-for-byte unchanged.","Updating the protected school and 12 legacy programs requires a separate exact-approval cleanup review."]};
const reviewHash=sha(JSON.stringify(reviewBase)),review={...reviewBase,reviewHash,publicationReference:`standing-authorized-${batch}-${reviewHash}`};
await Promise.all([writeJson(paths.candidate,candidate),writeJson(paths.validation,validation),writeJson(paths.review,review)]);
console.log(JSON.stringify({ok:true,batch,reviewHash,publicationReference:review.publicationReference,summary:validation.summary,blockedOfficialRoutes:blockedPrograms.length,protected:{city:1,school:1,programs:12,intakes:5},paths},null,2));
