import { createHash } from "node:crypto";
import { readFile, writeFile } from "node:fs/promises";
import { resolve } from "node:path";
import { createCatalogMigrationValidationReport, type CatalogSeedBundle } from "../src/server/catalog/seed-contract.ts";
import { createPostgresPool } from "../src/server/db/postgres-client.ts";
import { localDatabaseUrl } from "./lib/local-development.ts";

const root = process.cwd(), batch = "ouc-safe-new-batch-01";
const paths = { complete: resolve(root, "seeds/catalog.ouc-international-batch-01.draft.json"), freshManifest: resolve(root, "work/catalog-official/ouc-refresh-without-two-large-pdfs-20260914/manifest.json"), oldManifest: resolve(root, "work/catalog-official/ouc-complete-batch-01/manifest.json"), completeReview: resolve(root, "seeds/catalog.ouc-international-batch-01.review.json"), candidate: resolve(root, `seeds/catalog.${batch}.draft.json`), validation: resolve(root, `seeds/catalog.${batch}.validation.json`), review: resolve(root, `seeds/catalog.${batch}.review.json`), state: resolve(root, ".cuac-local/runtime.json") };
const sha = (value: string | Buffer) => createHash("sha256").update(value).digest("hex"), parse = async (path: string) => JSON.parse(await readFile(path, "utf8"));
const [complete, freshManifest, oldManifest, completeReview, state] = await Promise.all([parse(paths.complete), parse(paths.freshManifest), parse(paths.oldManifest), parse(paths.completeReview), parse(paths.state)]) as [CatalogSeedBundle, any, any, any, any];
const schoolSlug = "ocean-university-of-china";
if (complete.cities?.length !== 1 || complete.schools?.length !== 1 || complete.schools[0].slug !== schoolSlug || complete.programs?.length !== 10 || complete.programIntakes?.length !== 10 || complete.scholarships?.length !== 3) throw new Error("OUC complete candidate scope changed.");
if (freshManifest.sources?.length !== 15 || freshManifest.sources.some((row: any) => row.status !== 200) || completeReview.visualReview?.result !== "pass" || !String(completeReview.sourceReview?.result).startsWith("pass") || completeReview.sensitiveDataCheck?.result !== "pass") throw new Error("OUC current evidence review is unavailable.");
const oldSources = new Map((oldManifest.sources ?? []).map((row: any) => [row.id, row])); for (const source of freshManifest.sources) { const old: any = oldSources.get(source.id); if (!old || old.sha256 !== source.sha256 || old.finalUrl !== source.finalUrl || old.contentType !== source.contentType) throw new Error(`OUC official source changed: ${source.id}`); }
const candidateProgramSlugs = complete.programs.map((row) => row.slug), candidateScholarshipSlugs = complete.scholarships.map((row) => row.slug);
const pool = createPostgresPool({ databaseUrl: localDatabaseUrl(state), max: 1, applicationName: "cuac:ouc-safe-new-review" }); let baseline: any;
try {
  const school = await pool.query("select id,slug,status,verification_status from schools where slug=$1", [schoolSlug]), city = await pool.query("select id,slug,status,verification_status from cities where slug='qingdao'"), activePrograms = await pool.query("select id,slug,status,verification_status from programs where school_id=$1 and status='active' order by slug", [school.rows[0]?.id]), overlappingPrograms = await pool.query("select id,slug,status,verification_status from programs where slug=any($1::text[]) order by slug", [candidateProgramSlugs]), scholarshipConflicts = await pool.query("select id,slug,status,verification_status from scholarships where slug=any($1::text[]) order by slug", [candidateScholarshipSlugs]), activeScholarships = await pool.query("select id,slug,status,verification_status from scholarships where school_id=$1 and status='active' order by slug", [school.rows[0]?.id]), intakes = await pool.query("select count(*)::int count from program_intakes pi join programs p on p.id=pi.program_id where p.school_id=$1", [school.rows[0]?.id]);
  baseline = { school: school.rows, city: city.rows, activePrograms: activePrograms.rows, overlappingPrograms: overlappingPrograms.rows, scholarshipConflicts: scholarshipConflicts.rows, activeScholarships: activeScholarships.rows, intakeCount: intakes.rows[0]?.count ?? 0 };
  if (school.rows.length !== 1 || school.rows[0].status !== "active" || school.rows[0].verification_status !== "unverified" || city.rows.length !== 1 || city.rows[0].status !== "active") throw new Error("OUC dependency baseline changed.");
  if (activePrograms.rows.length !== 13 || overlappingPrograms.rows.length !== 2 || overlappingPrograms.rows.some((row: any) => row.status !== "active" || row.verification_status !== "unverified")) throw new Error("OUC legacy program baseline changed.");
  if (scholarshipConflicts.rows.length !== 0 || activeScholarships.rows.length !== 1 || activeScholarships.rows[0].status !== "active" || activeScholarships.rows[0].verification_status !== "unverified") throw new Error("OUC scholarship baseline changed.");
} finally { await pool.end(); }
const overlapSlugs = new Set(baseline.overlappingPrograms.map((row: any) => row.slug)), programs = complete.programs.filter((row) => !overlapSlugs.has(row.slug)), safeSlugs = new Set(programs.map((row) => row.slug)), programIntakes = complete.programIntakes.filter((row) => safeSlugs.has(row.programSlug)), scholarships = complete.scholarships;
if (programs.length !== 8 || programIntakes.length !== 8 || scholarships.length !== 3) throw new Error("OUC safe-new split changed.");
const freshHashes = new Set(freshManifest.sources.map((row: any) => row.sha256)); if ([...programs, ...programIntakes, ...scholarships].some((row: any) => !freshHashes.has(row.sourceSha256))) throw new Error("OUC safe-new record lacks freshly confirmed evidence.");
const candidate: CatalogSeedBundle = { version: 1, generatedAt: freshManifest.generatedAt, cities: complete.cities, schools: complete.schools, programs, programIntakes, scholarships }, candidateText = `${JSON.stringify(candidate, null, 2)}\n`, validation = createCatalogMigrationValidationReport(candidate); if (!validation.ok) throw new Error(`OUC safe-new validation failed: ${validation.errors.join(" ")}`);
const reviewBase = { version: 1, status: "standing_user_approval", generatedAt: candidate.generatedAt, scope: { schoolSlug, dependencyCityReplayCount: 1, dependencySchoolReplayCount: 1, newProgramRouteCount: 8, newProgramIntakeCount: 8, newScholarshipCount: 3, overwriteCount: 0, archiveCount: 0 }, candidateSha256: sha(candidateText), candidateBundleSha256: validation.bundleSha256, operationPlanSha256: validation.operationPlanSha256, freshManifestSha256: sha(await readFile(paths.freshManifest, "utf8")), evidence: freshManifest.sources.filter((row: any) => freshHashes.has(row.sha256)).map((row: any) => ({ sourceId: row.id, sourceUrl: row.finalUrl, sourceLabel: row.label, sha256: row.sha256, fetchedAt: row.fetchedAt, contentType: row.contentType })), standingAuthorization: { reference: "user-chat-2026-09-13-default-publication", instruction: "发布默认允许", appliesBecause: "This batch inserts only eight new official program routes, eight intakes and three new rich scholarships. Qingdao city and the OUC school are read-only dependencies; no record is overwritten or archived." }, sourceReview: { result: "pass", note: "Fifteen registered official OUC sources were refreshed on 2026-09-14 and are byte-for-byte unchanged. Every safe-new field is backed by the refreshed set; two unrelated oversized PDFs are not used." }, visualReview: completeReview.visualReview, reconciliation: { destructiveDeletion: false, overwrites: [], archives: [], deferredStableProgramSlugs: baseline.overlappingPrograms.map((row: any) => row.slug), deferredExistingProgramSlugs: baseline.activePrograms.map((row: any) => row.slug), deferredLegacyScholarshipSlugs: baseline.activeScholarships.map((row: any) => row.slug), databaseBaseline: { schoolId: baseline.school[0].id, cityId: baseline.city[0].id, activeProgramCount: baseline.activePrograms.length, activeScholarshipCount: baseline.activeScholarships.length, intakeCount: baseline.intakeCount } }, coverageLimitations: ["Two stable routes, the school profile and shared Qingdao city require explicit overwrite review.", "One erroneous program alias and one merged scholarship require explicit archival; all existing records remain unchanged in this batch."], sensitiveDataCheck: { result: "pass", scope: "safe-new publication candidate", note: "Only public institutional, program, admissions and scholarship-policy fields are included. Applicant, account, payment, bank, staff-name and personal-contact data are excluded." } };
const reviewHash = sha(JSON.stringify(reviewBase)), publicationReference = `standing-authorized-${batch}-${reviewHash}`;
await Promise.all([writeFile(paths.candidate, candidateText, "utf8"), writeFile(paths.validation, `${JSON.stringify(validation, null, 2)}\n`, "utf8"), writeFile(paths.review, `${JSON.stringify({ ...reviewBase, reviewHash, publicationReference }, null, 2)}\n`, "utf8")]);
console.log(JSON.stringify({ ok: true, batch, reviewHash, publicationReference, scope: reviewBase.scope, paths }, null, 2));
