import { createHash } from "node:crypto";
import { readFile, writeFile } from "node:fs/promises";
import { resolve } from "node:path";
import { createCatalogMigrationValidationReport, type CatalogSeedScholarship } from "../src/server/catalog/seed-contract.ts";

const root = process.cwd();
const schoolSlug = "tongji-university";
const prior = JSON.parse(await readFile(resolve(root, "seeds/catalog.tongji-school-program-batch-01.approved.local.json"), "utf8"));
const manifest = JSON.parse(await readFile(resolve(root, "work/catalog-official/tongji-complete-batch-02/manifest.json"), "utf8"));
const paths = {
  draft: resolve(root, "seeds/catalog.tongji-scholarships-batch-02.draft.json"),
  validation: resolve(root, "seeds/catalog.tongji-scholarships-batch-02.validation.json"),
  review: resolve(root, "seeds/catalog.tongji-scholarships-batch-02.review.json"),
};
const expected = new Map<string, string>([
  ["tongji-university-master-chinese-admissions-2026", "29161e5ed6fce6d76f14286595b17e59ffb584cedce6a700f5b8092ea4e0f5c0"],
  ["tongji-university-master-english-admissions-2026", "8f4c36bb35cf01e2bd33478dca5b5a1ed58c3ea644f04f2ea74d7091f9b477f8"],
  ["tongji-university-doctoral-chinese-admissions-2026", "5c09171c1e1bd6a1c1469193aa3e06ccc5dc1eaa9783ffd11fb902d25746e6b9"],
  ["tongji-university-doctoral-english-admissions-2026", "c4f5fee2d256aa821e2dee6e0aba8f4f7ac15d981b3b5621748e762da241d961"],
  ["tongji-university-cgs-high-level-graduate-2026", "5fb70ad9d3b560ade9ec4752169d7a521f737043f2bf28d6f9b9ac5d16b38fe8"],
  ["tongji-university-shanghai-government-scholarship-2026", "754625eed9a067be454383e648b1d196accbcf398ed2485f63886863872071c2"],
  ["tongji-university-international-student-excellence-scholarship-2026", "627c5f42f2fa6d784937f5b90361edee898d400e3b0d5eec789fcded5e93978f"],
]);
const evidence = new Map<string, any>();
for (const [id, sha] of expected) {
  const row = manifest.sources?.find((item: any) => item.id === id);
  if (!row || row.status !== 200 || row.sha256 !== sha || !["text/html", "application/pdf"].includes(row.contentType)) throw new Error(`Tongji evidence is missing or changed: ${id}`);
  evidence.set(id, row);
}
const items = (values: string[]) => values.map(label => ({ label }));
const benefits = (values: string[]) => values.map(label => ({ label, included: true }));
const steps = (values: string[]) => values.map((body, index) => ({ label: `Step ${index + 1}`, body }));
type Input = { sourceId: string; support?: string[]; slug: string; title: string; nameZh: string; type: string; typeLabel: string; fundingLevel: string; providerName: string; providerNameEn: string; coverage: string; applicableDegree: string; applicableProgram: string; amountText: string; eligibility: string[]; materials: string[]; process: string[]; benefitList: string[]; deadlineDate?: string; deadlineLabel: string; applicationRound: string; tags: string[]; unresolved: string[]; sortOrder: number };
function make(input: Input): CatalogSeedScholarship {
  const source = evidence.get(input.sourceId);
  const supporting = (input.support ?? []).map(id => evidence.get(id));
  const summary = `${input.title} is published by Tongji University as a distinct 2026 scholarship route. Eligibility, award coverage and deadlines remain subject to the cited official notice and final award decision.`;
  const record: any = {
    schoolSlug, sourceUrl: source.url, sourceLabel: source.label, sourceSha256: source.sha256, capturedAt: source.fetchedAt, status: "draft",
    slug: input.slug, title: input.title, nameZh: input.nameZh, type: input.type, typeLabel: input.typeLabel, fundingLevel: input.fundingLevel,
    providerName: input.providerName, providerNameEn: input.providerNameEn, providerLocation: "China", coverage: input.coverage,
    applicableDegree: input.applicableDegree, applicableProgram: input.applicableProgram, amountText: input.amountText,
    requirementText: input.eligibility.join("; "), bodySections: [{ title: "Scholarship overview", body: summary }, { title: "Important application notes", items: input.process }],
    benefitItems: benefits(input.benefitList), eligibilityItems: items(input.eligibility), applicationMaterials: items(input.materials), applicationSteps: steps(input.process),
    actionLinks: [{ label: source.label, url: source.url, kind: "official-source" }, ...supporting.map(row => ({ label: row.label, url: row.url, kind: "official-source" })), { label: "Tongji international student application system", url: "https://study-info.tongji.edu.cn/", kind: "official-application" }],
    ...(input.deadlineDate ? { deadlineDate: input.deadlineDate } : {}), deadlineLabel: input.deadlineLabel, applicationRound: input.applicationRound,
    targetCountries: [], targetRegions: [], benefits: input.benefitList, tags: ["2026", ...input.tags], summary, sortOrder: input.sortOrder,
  };
  const evidenceFields = new Set(["sourceUrl", "sourceLabel", "sourceSha256", "capturedAt", "status"]);
  const derivedFields = new Set(["schoolSlug", "slug", "title", "nameZh", "type", "typeLabel", "providerName", "providerNameEn", "providerLocation", "bodySections", "actionLinks", "targetCountries", "targetRegions", "tags", "summary", "sortOrder"]);
  const refs = [source, ...supporting].map(row => `${row.id} ${row.sha256}`).join("; ");
  record.sourceFieldLineage = Object.fromEntries(Object.keys(record).filter(field => !evidenceFields.has(field)).map(field => [field, `${derivedFields.has(field) ? "derived" : "explicit"}: ${refs}`]));
  return record;
}
const graduateMaterials = ["Tongji international student online application form", "Highest diploma or expected-graduation certificate", "Academic transcripts", "Language proficiency evidence for the selected route", "Study or research plan", "Two recommendation letters", "Foreigner Physical Examination Form", "Non-criminal record certificate"];
const scholarships: CatalogSeedScholarship[] = [
  make({ sourceId: "tongji-university-cgs-high-level-graduate-2026", support: ["tongji-university-master-chinese-admissions-2026", "tongji-university-master-english-admissions-2026", "tongji-university-doctoral-chinese-admissions-2026", "tongji-university-doctoral-english-admissions-2026"], slug: "official-2026-tongji-cgs-high-level-graduate-program", title: "Tongji University 2026 Chinese Government Scholarship - High-Level Postgraduate Program", nameZh: "同济大学2026年中国政府奖学金高水平研究生项目", type: "government", typeLabel: "Chinese Government Scholarship Type B", fundingLevel: "Full", providerName: "中华人民共和国教育部 / 国家留学基金管理委员会", providerNameEn: "Ministry of Education of the PRC / China Scholarship Council", coverage: "Tuition waiver, comprehensive medical insurance, on-campus accommodation or monthly accommodation subsidy, and monthly stipend", applicableDegree: "Master, Doctoral", applicableProgram: "Eligible full-time Tongji international graduate programs", amountText: "Monthly stipend: CNY 3,000 for master's students and CNY 3,500 for doctoral students; off-campus accommodation subsidy: CNY 700 or CNY 1,000 per month respectively.", benefitList: ["Tuition waiver", "Comprehensive medical insurance", "On-campus accommodation or CNY 700/month master's and CNY 1,000/month doctoral subsidy", "CNY 3,000/month master's stipend", "CNY 3,500/month doctoral stipend"], eligibility: ["Non-Chinese citizen in good physical and mental health", "Master applicant no older than 35", "Doctoral applicant no older than 40", "Meets the academic and language requirements of the selected Tongji program", "Does not concurrently hold another Chinese Government Scholarship"], materials: [...graduateMaterials, "CSC Type B application using Tongji agency number 10247"], process: ["Apply in Tongji's international student system", "Apply in the CSC system as Type B using agency number 10247", "Submit all graduate admission and scholarship materials", "Await Tongji nomination and CSC final review"], deadlineDate: "2025-12-20", deadlineLabel: "Application period: October 25 to December 20, 2025", applicationRound: "October 25 - December 20, 2025", tags: ["Chinese Government Scholarship", "Master", "Doctoral"], unresolved: ["route quota", "program-specific nomination conditions"], sortOrder: 300 }),
  make({ sourceId: "tongji-university-shanghai-government-scholarship-2026", support: ["tongji-university-master-chinese-admissions-2026", "tongji-university-doctoral-chinese-admissions-2026"], slug: "official-2026-tongji-shanghai-government-scholarship", title: "Tongji University 2026 Shanghai Government Scholarship", nameZh: "同济大学2026年上海市外国留学生政府奖学金", type: "local-government", typeLabel: "Shanghai Government Scholarship", fundingLevel: "Category A full or Category B partial", providerName: "上海市人民政府", providerNameEn: "Shanghai Municipal Government", coverage: "Category A covers tuition, insurance, living stipend and accommodation support; Category B covers tuition and comprehensive medical insurance.", applicableDegree: "Bachelor, Master, Doctoral", applicableProgram: "Eligible Tongji international degree programs", amountText: "Category A stipend: CNY 2,500/month undergraduate, CNY 3,000/month master's, CNY 3,500/month doctoral; accommodation support is CNY 700/month undergraduate or master's and CNY 1,000/month doctoral. Category B covers tuition and insurance.", benefitList: ["Category A tuition waiver", "Category A comprehensive medical insurance", "Category A monthly living stipend", "Category A on-campus accommodation or monthly subsidy", "Category B tuition waiver and comprehensive medical insurance"], eligibility: ["Non-Chinese citizen in good health", "Meets Tongji's degree-level age, academic and language requirements", "Bachelor applicant no older than 25", "Master applicant no older than 35", "Doctoral applicant no older than 40", "Does not concurrently receive another Chinese government scholarship"], materials: graduateMaterials, process: ["Choose an eligible Tongji degree program", "Apply in Tongji's international student system", "Select the Shanghai Government Scholarship route", "Submit admission and scholarship materials by the applicable degree deadline", "Complete annual review if awarded"], deadlineDate: "2026-03-31", deadlineLabel: "Undergraduate deadline: March 31, 2026; master's and doctoral deadline: March 20, 2026", applicationRound: "2026 international degree admissions", tags: ["Shanghai Government Scholarship", "Bachelor", "Master", "Doctoral"], unresolved: ["Category A or B assignment", "route quota"], sortOrder: 310 }),
  make({ sourceId: "tongji-university-international-student-excellence-scholarship-2026", support: ["tongji-university-doctoral-english-admissions-2026", "tongji-university-master-english-admissions-2026"], slug: "official-2026-tongji-international-student-excellence-scholarship", title: "Tongji University 2026 International Student Excellence Scholarship", nameZh: "同济大学2026年国际学生卓越奖学金", type: "university", typeLabel: "Tongji University Scholarship", fundingLevel: "Full", providerName: "同济大学", providerNameEn: "Tongji University", coverage: "Full-time doctoral, high-level exchange and full-time English-taught undergraduate award routes with tuition, insurance, accommodation support and living allowance as published.", applicableDegree: "Bachelor, Doctoral, Exchange", applicableProgram: "Eligible full-time English-taught undergraduate programs, full-time doctoral programs and high-level exchange programs", amountText: "Doctoral: CNY 5,000/month stipend, accommodation or CNY 3,000/month subsidy, plus CNY 12,000 graduation travel grant. English undergraduate: CNY 2,500/month stipend and accommodation or CNY 700/month subsidy. Exchange stipend and housing support vary by level.", benefitList: ["Tuition waiver", "Comprehensive medical insurance", "On-campus accommodation or published monthly subsidy", "Monthly living allowance by route and degree level", "Full-time doctoral CNY 12,000 one-time graduation travel grant"], eligibility: ["Non-Chinese citizen in good health", "Meets the academic requirements for the selected eligible route", "Chinese-taught route normally requires HSK Level 5 score 180", "English-taught route normally requires TOEFL 85 or IELTS 6.5", "Does not concurrently hold a Chinese Government Scholarship"], materials: graduateMaterials, process: ["Confirm that the selected route is eligible for the Excellence Scholarship", "Apply through Tongji's international student system", "Upload the required admission and scholarship materials", "Follow the route-specific deadline published in the application system", "Await Tongji review and final award decision"], deadlineLabel: "General application period: October of the preceding year through May of the enrollment year; exact route deadline varies", applicationRound: "October 2025 - May 2026, route-specific", tags: ["Tongji University Scholarship", "Bachelor", "Doctoral", "Exchange"], unresolved: ["route-specific deadline", "award quota", "eligible-program list by intake"], sortOrder: 320 }),
];
if (scholarships.length !== 3 || new Set(scholarships.map(row => row.slug)).size !== 3) throw new Error("Tongji batch must contain three distinct scholarship routes.");
const candidate = { version: 1, generatedAt: manifest.generatedAt, cities: prior.cities, schools: prior.schools, programs: [], programIntakes: [], scholarships };
const candidateText = `${JSON.stringify(candidate, null, 2)}\n`;
const candidateSha256 = createHash("sha256").update(candidateText).digest("hex");
const validation = createCatalogMigrationValidationReport(candidate);
if (!validation.ok) throw new Error(`Tongji candidate is invalid: ${validation.errors.join(" ")}`);
const reviewBase: any = { version: 1, status: "standing_user_approval", generatedAt: manifest.generatedAt, scope: { schoolSlug, dependencyCityReplayCount: prior.cities.length, dependencySchoolReplayCount: 1, existingProgramCount: 71, existingProgramIntakeCount: 71, existingVerifiedScholarshipCount: 1, newScholarshipCount: 3, archiveProgramAliasCount: 0, archiveScholarshipAliasCount: 0 }, candidateSha256, candidateBundleSha256: validation.bundleSha256, operationPlanSha256: validation.operationPlanSha256, evidence: [...evidence.values()].map(row => ({ sourceId: row.id, sourceUrl: row.url, sourceLabel: row.label, sha256: row.sha256, fetchedAt: row.fetchedAt, contentType: row.contentType })).sort((a, b) => a.sourceId.localeCompare(b.sourceId)), visualReview: { result: "pass", pdfPagesReviewed: 5, note: "All five pages of the official Excellence Scholarship PDF were rendered and visually inspected; route coverage, stipend, language threshold and application period are legible." }, standingAuthorization: { reference: "user-chat-2026-09-13-default-publication", instruction: "发布默认允许", appliesBecause: "The batch adds three new non-conflicting scholarships and archives, deletes or overwrites nothing. Existing Tongji city and school rows are replayed byte-equivalently." }, reconciliation: { destructiveDeletion: false, existingDependencyRowsReplayedByteEquivalently: true, newScholarshipSlugConflicts: 0, archivedAliases: [] }, deferredProgramAcquisition: { status: "blocked_by_official_captcha", affectedAttachments: 4, note: "The four registered official 2026 graduate catalog attachments returned Tongji's CAPTCHA download page. No CAPTCHA bypass or third-party substitute was used." }, records: scholarships.map((row: any) => ({ slug: row.slug, title: row.title, unresolvedFields: row.slug.includes("high-level") ? ["route quota", "program-specific nomination conditions"] : row.slug.includes("shanghai") ? ["Category A or B assignment", "route quota"] : ["route-specific deadline", "award quota", "eligible-program list by intake"] })), sensitiveDataCheck: { result: "pass", scope: "candidate bundle only", note: "Only public institutional scholarship information is included. Applicant data, private files, personal contacts, account data and payment data are absent." } };
const reviewHash = createHash("sha256").update(JSON.stringify(reviewBase)).digest("hex");
const review = { ...reviewBase, reviewHash, publicationReference: `standing-default-publication-tongji-scholarships-${reviewHash}` };
await Promise.all([writeFile(paths.draft, candidateText, "utf8"), writeFile(paths.validation, `${JSON.stringify(validation, null, 2)}\n`, "utf8"), writeFile(paths.review, `${JSON.stringify(review, null, 2)}\n`, "utf8")]);
console.log(JSON.stringify({ ok: true, ...paths, reviewHash, candidateSha256, candidateBundleSha256: validation.bundleSha256, summary: validation.summary }, null, 2));
