import { createHash } from "node:crypto";
import { readFile, writeFile } from "node:fs/promises";
import { resolve } from "node:path";
import { createCatalogMigrationValidationReport, type CatalogSeedBundle, type CatalogSeedScholarship } from "../src/server/catalog/seed-contract.ts";
import { createPostgresPool } from "../src/server/db/postgres-client.ts";
import { localDatabaseUrl } from "./lib/local-development.ts";

const root = process.cwd();
const batch = "pku-scholarships-split-batch-01";
const schoolSlug = "peking-university";
const paths = { dependencies: resolve(root, "seeds/catalog.pku-school-program-batch-01.approved.local.json"), manifest: resolve(root, "work/catalog-official/pku-scholarships-refresh-20260914/manifest.json"), candidate: resolve(root, `seeds/catalog.${batch}.draft.json`), validation: resolve(root, `seeds/catalog.${batch}.validation.json`), review: resolve(root, `seeds/catalog.${batch}.review.json`), state: resolve(root, ".cuac-local/runtime.json") };
const sha = (value: string | Buffer) => createHash("sha256").update(value).digest("hex");
const parse = async (path: string) => JSON.parse(await readFile(path, "utf8"));
const [dependencies, manifest, state] = await Promise.all([parse(paths.dependencies), parse(paths.manifest), parse(paths.state)]) as [CatalogSeedBundle, any, any];
const source = manifest.sources?.[0];
if (dependencies.cities?.length !== 1 || dependencies.schools?.length !== 1 || dependencies.schools[0].slug !== schoolSlug || manifest.sources?.length !== 1 || source.id !== "pku-prospective-graduate-scholarships-2026" || source.status !== 200 || source.sha256 !== "d621e136f140be0f015e1167d85f9f8ba744c6831b6ebcbed2ab4117b797e1c5") throw new Error("PKU scholarship dependencies or evidence changed.");
const item = (label: string, value?: string) => ({ label, ...(value ? { value } : {}) });
const benefit = (label: string) => ({ label, included: true });
const common = {
  schoolSlug, applicableDegree: "Master, Doctoral", applicableProgram: "Eligible 2026 full-time self-funded international graduate programs at Peking University", providerLocation: "Beijing, China", targetCountries: [], targetRegions: [],
  eligibilityItems: [item("Admission", "Meets PKU international graduate admission requirements"), item("Application", "Has submitted a 2026 full-time self-funded international graduate application"), item("Funding", "Does not hold an incompatible scholarship"), item("Study status", "Is not a joint-training-program candidate where that exclusion applies")],
  applicationMaterials: [item("PKU online scholarship application"), item("Official transcripts from prior educational experience"), item("Supporting documents requested in the PKU scholarship system")],
  actionLinks: [{ label: source.label, url: source.finalUrl, kind: "official-source" }],
  status: "draft" as const, sourceUrl: source.finalUrl, sourceLabel: source.label, sourceSha256: source.sha256, capturedAt: source.fetchedAt,
  sourceFieldLineage: { title: "official notice, scholarship section heading", fundingLevel: "official notice, Scope of the Scholarship", coverage: "official notice, Scope of the Scholarship", applicableDegree: "official notice, Scholarship Duration", applicableProgram: "official notice, Eligibility", eligibilityItems: "official notice, Eligibility", benefitItems: "official notice, Scope of the Scholarship", applicationMaterials: "official notice, Application Procedure and notes", applicationSteps: "official notice, Application Procedure", deadlineDate: "official notice, Application Procedure", deadlineLabel: "official notice, Application Procedure", applicationRound: "official notice title and introduction" },
};
const scholarships: CatalogSeedScholarship[] = [
  { ...common, slug: "official-2026-pku-chinese-government-advanced-graduate-scholarship", title: "Peking University 2026 Chinese Government Scholarship for Advanced Graduate Program", nameZh: "北京大学2026年中国政府奖学金高水平研究生项目", type: "government", typeLabel: "Chinese Government Scholarship Type B", providerName: "中华人民共和国教育部 / 国家留学基金管理委员会", providerNameEn: "Ministry of Education of the PRC / China Scholarship Council", fundingLevel: "Full or partial", coverage: "Full or partial tuition waiver, living stipend, housing and medical insurance", amountText: "The official notice publishes full or partial tuition waiver, living stipend, housing and medical insurance; no route-specific amount is stated.", deadlineDate: "2026-03-17", deadlineLabel: "PKU system: March 9, 2026 at 09:00; CSC system: March 17, 2026 at 24:00 Beijing time", applicationRound: "2026 prospective international graduate intake", benefitItems: [benefit("Full or partial tuition waiver"), benefit("Living stipend"), benefit("Housing"), benefit("Medical insurance")], applicationMaterials: [...common.applicationMaterials, item("Completed CSC Type B application form"), item("Certificate for CSC Advanced Graduate Program Application"), item("Attachment 2 scholarship material-list documents"), item("Physical examination statement and no-criminal-record declaration when applicable")], applicationSteps: [item("Step 1", "Submit the PKU online scholarship application by March 9 at 09:00 Beijing time"), item("Step 2", "Submit the CSC Type B application using PKU institution code 10001 by March 17 at 24:00 Beijing time"), item("Step 3", "Upload the required CSC form and supporting materials")], summary: "PKU's 2026 Chinese Government Scholarship Type B route for eligible prospective international master's and doctoral students.", sortOrder: 10 },
  { ...common, slug: "official-2026-pku-university-scholarship", title: "Peking University Scholarship for 2026 Prospective International Graduate Students", nameZh: "北京大学2026年外国留学生研究生新生奖学金", type: "university", typeLabel: "Peking University Scholarship", providerName: "北京大学", providerNameEn: "Peking University", fundingLevel: "Full or partial", coverage: "Full or partial tuition waiver, living stipend and medical insurance", amountText: "The official notice publishes full or partial tuition waiver, living stipend and medical insurance; no fixed amount is stated.", deadlineDate: "2026-03-09", deadlineLabel: "March 9, 2026 at 09:00 Beijing time", applicationRound: "2026 prospective international graduate intake", benefitItems: [benefit("Full or partial tuition waiver"), benefit("Living stipend"), benefit("Medical insurance")], applicationSteps: [item("Step 1", "Submit the 2026 full-time self-funded graduate application"), item("Step 2", "Submit one PKU online scholarship application by March 9 at 09:00 Beijing time"), item("Step 3", "PKU considers the applicant across applicable scholarship categories and makes one final award")], summary: "PKU's university-funded 2026 scholarship for eligible prospective international master's and doctoral students.", sortOrder: 20 },
  { ...common, slug: "official-2026-pku-beijing-government-scholarship", title: "Peking University 2026 Beijing Government Scholarship for Prospective International Graduate Students", nameZh: "北京大学2026年北京市外国留学生奖学金", type: "government", typeLabel: "Beijing Government Scholarship", providerName: "北京市人民政府", providerNameEn: "Beijing Municipal Government", fundingLevel: "Full or partial", coverage: "Full or partial tuition waiver", amountText: "The official notice publishes a full or partial tuition waiver; no fixed amount is stated.", deadlineDate: "2026-03-09", deadlineLabel: "March 9, 2026 at 09:00 Beijing time", applicationRound: "2026 prospective international graduate intake", benefitItems: [benefit("Full or partial tuition waiver")], eligibilityItems: common.eligibilityItems.filter((row) => row.label !== "Study status"), applicationSteps: [item("Step 1", "Submit the 2026 full-time self-funded graduate application"), item("Step 2", "Submit one PKU online scholarship application by March 9 at 09:00 Beijing time"), item("Step 3", "PKU reviews the application for the Beijing Government Scholarship")], summary: "Beijing municipal tuition support administered by PKU for eligible 2026 international graduate applicants.", sortOrder: 30 },
];
if (scholarships.some((row) => !row.benefitItems?.length || !row.eligibilityItems?.length || !row.applicationMaterials?.length || !row.applicationSteps?.length || !row.actionLinks?.length)) throw new Error("PKU split scholarships are incomplete.");
const pool = createPostgresPool({ databaseUrl: localDatabaseUrl(state), max: 1, applicationName: "cuac:pku-scholarships-split-review" });
let baseline: any;
try {
  const school = await pool.query("select id,slug,status,verification_status from schools where slug=$1", [schoolSlug]);
  const conflicts = await pool.query("select id,slug,status,verification_status from scholarships where slug=any($1::text[]) order by slug", [scholarships.map((row) => row.slug)]);
  const active = await pool.query("select id,slug,status,verification_status from scholarships where school_id=$1 and status='active' order by slug", [school.rows[0]?.id]);
  if (school.rows.length !== 1 || school.rows[0].status !== "active" || school.rows[0].verification_status !== "verified" || conflicts.rows.length !== 0 || active.rows.length !== 6) throw new Error("PKU scholarship database baseline changed.");
  baseline = { school: school.rows[0], activeScholarships: active.rows };
} finally { await pool.end(); }
const candidate: CatalogSeedBundle = { version: 1, generatedAt: manifest.generatedAt, cities: dependencies.cities, schools: dependencies.schools, programs: [], programIntakes: [], scholarships };
const candidateText = `${JSON.stringify(candidate, null, 2)}\n`;
const validation = createCatalogMigrationValidationReport(candidate);
if (!validation.ok) throw new Error(`PKU split validation failed: ${validation.errors.join(" ")}`);
const reviewBase = { version: 1, status: "standing_user_approval", generatedAt: candidate.generatedAt, scope: { schoolSlug, dependencyCityReplayCount: 1, dependencySchoolReplayCount: 1, newScholarshipCount: 3, overwriteCount: 0, archiveCount: 0 }, candidateSha256: sha(candidateText), candidateBundleSha256: validation.bundleSha256, operationPlanSha256: validation.operationPlanSha256, manifestSha256: sha(await readFile(paths.manifest, "utf8")), evidence: [{ sourceId: source.id, sourceUrl: source.finalUrl, sourceLabel: source.label, sha256: source.sha256, fetchedAt: source.fetchedAt, contentType: source.contentType }], standingAuthorization: { reference: "user-chat-2026-09-13-default-publication", instruction: "发布默认允许", appliesBecause: "This batch inserts only three new independently modeled official scholarship records; the verified PKU school, programs and all six existing scholarship records are preserved." }, sourceReview: { result: "pass", note: "The registered 2026 PKU scholarship notice was refreshed on 2026-09-14 and is byte-for-byte unchanged. Its three named award sections are represented separately." }, reconciliation: { destructiveDeletion: false, overwrites: [], archives: [], deferredExistingScholarships: baseline.activeScholarships.map((row: any) => row.slug), databaseBaseline: { schoolId: baseline.school.id, activeScholarshipCount: 6 } }, sensitiveDataCheck: { result: "pass", scope: "three PKU scholarship records", note: "Only public scholarship policy fields are present. Footer contact details, applicant data, accounts, payment and bank data are excluded." }, reviewNotes: ["The existing verified combined scholarship overview is preserved pending explicit archival approval.", "The five unrelated or legacy unverified scholarship rows are unchanged.", "PKU requires only one university-system scholarship application; the three award records preserve that shared-process note without merging award identities."] };
const reviewHash = sha(JSON.stringify(reviewBase));
const publicationReference = `standing-authorized-${batch}-${reviewHash}`;
await Promise.all([writeFile(paths.candidate, candidateText, "utf8"), writeFile(paths.validation, `${JSON.stringify(validation, null, 2)}\n`, "utf8"), writeFile(paths.review, `${JSON.stringify({ ...reviewBase, reviewHash, publicationReference }, null, 2)}\n`, "utf8")]);
console.log(JSON.stringify({ ok: true, batch, reviewHash, publicationReference, scope: reviewBase.scope, paths }, null, 2));
