import { createHash } from "node:crypto";
import { readFile, writeFile } from "node:fs/promises";
import { resolve } from "node:path";
import { createCatalogMigrationValidationReport, type CatalogSeedBundle } from "../src/server/catalog/seed-contract.ts";
import { createPostgresPool } from "../src/server/db/postgres-client.ts";
import { localDatabaseUrl } from "./lib/local-development.ts";

const root = process.cwd(), batch = "changan-safe-new-batch-01";
const paths = { complete: resolve(root, "seeds/catalog.changan-complete-batch-01.draft.json"), completeReview: resolve(root, "seeds/catalog.changan-complete-batch-01.review.json"), freshManifest: resolve(root, "work/catalog-official/changan-refresh-20260914/manifest.json"), oldManifest: resolve(root, "work/catalog-official/changan-complete-batch-01/manifest.json"), candidate: resolve(root, `seeds/catalog.${batch}.draft.json`), validation: resolve(root, `seeds/catalog.${batch}.validation.json`), review: resolve(root, `seeds/catalog.${batch}.review.json`), state: resolve(root, ".cuac-local/runtime.json") };
const sha = (value: string | Buffer) => createHash("sha256").update(value).digest("hex"), parse = async (path: string) => JSON.parse(await readFile(path, "utf8"));
const [complete, completeReview, freshManifest, oldManifest, state] = await Promise.all([parse(paths.complete), parse(paths.completeReview), parse(paths.freshManifest), parse(paths.oldManifest), parse(paths.state)]) as [CatalogSeedBundle, any, any, any, any];
const schoolSlug = "chang-an-university";
if (complete.cities?.length !== 1 || complete.schools?.length !== 1 || complete.schools[0].slug !== schoolSlug || complete.programs?.length !== 215 || complete.programIntakes?.length !== 215 || complete.scholarships?.length !== 6 || freshManifest.sources?.length !== 18 || oldManifest.sources?.length !== 18 || completeReview.sourceReview?.result !== "pass" || completeReview.visualReview?.result !== "pass" || completeReview.sensitiveDataCheck?.result !== "pass") throw new Error("Chang'an candidate or review scope changed.");
const oldSources = new Map(oldManifest.sources.map((row: any) => [row.id, row])); for (const source of freshManifest.sources) { const old: any = oldSources.get(source.id); if (!old || old.sha256 !== source.sha256 || old.finalUrl !== source.finalUrl || old.contentType !== source.contentType) throw new Error(`Chang'an source changed: ${source.id}`); }
const allProgramSlugs = complete.programs.map((row) => row.slug), scholarshipSlugs = complete.scholarships.map((row) => row.slug);
const pool = createPostgresPool({ databaseUrl: localDatabaseUrl(state), max: 1, applicationName: "cuac:changan-safe-new-review" }); let baseline: any;
try {
  const school = await pool.query("select id,slug,status,verification_status from schools where slug=$1", [schoolSlug]), city = await pool.query("select id,slug,status,verification_status from cities where slug='xian'"), activePrograms = await pool.query("select id,slug,status,verification_status from programs where school_id=$1 and status='active' order by slug", [school.rows[0]?.id]), conflicts = await pool.query("select id,slug,status,verification_status from programs where slug=any($1::text[]) order by slug", [allProgramSlugs]), scholarshipConflicts = await pool.query("select id,slug,status,verification_status from scholarships where slug=any($1::text[]) order by slug", [scholarshipSlugs]), activeScholarships = await pool.query("select id,slug,status,verification_status from scholarships where school_id=$1 and status='active' order by slug", [school.rows[0]?.id]), intakes = await pool.query("select count(*)::int count from program_intakes pi join programs p on p.id=pi.program_id where p.school_id=$1", [school.rows[0]?.id]);
  baseline = { school: school.rows, city: city.rows, activePrograms: activePrograms.rows, conflicts: conflicts.rows, scholarshipConflicts: scholarshipConflicts.rows, activeScholarships: activeScholarships.rows, intakeCount: intakes.rows[0]?.count ?? 0 };
  if (school.rows.length !== 1 || school.rows[0].status !== "active" || school.rows[0].verification_status !== "unverified" || city.rows.length !== 1 || city.rows[0].status !== "active" || activePrograms.rows.length !== 24 || conflicts.rows.length !== 16 || [...activePrograms.rows, ...conflicts.rows].some((row: any) => row.status !== "active" || row.verification_status !== "unverified")) throw new Error("Chang'an dependency/program baseline changed.");
  if (scholarshipConflicts.rows.length !== 0 || activeScholarships.rows.length !== 1 || activeScholarships.rows[0].verification_status !== "unverified" || baseline.intakeCount !== 0) throw new Error("Chang'an scholarship/intake baseline changed.");
} finally { await pool.end(); }
const conflictSet = new Set(baseline.conflicts.map((row: any) => row.slug)), programs = complete.programs.filter((row) => !conflictSet.has(row.slug)), safeProgramSet = new Set(programs.map((row) => row.slug)), programIntakes = complete.programIntakes.filter((row) => safeProgramSet.has(row.programSlug));
if (programs.length !== 199 || programIntakes.length !== 199 || complete.scholarships.some((row: any) => !row.benefitItems?.length || !row.eligibilityItems?.length || !row.applicationMaterials?.length || !row.applicationSteps?.length || !row.actionLinks?.length)) throw new Error("Chang'an safe split changed or has incomplete scholarship fields.");
const freshHashes = new Set(freshManifest.sources.map((row: any) => row.sha256)); if ([...programs, ...programIntakes, ...complete.scholarships].some((row: any) => !freshHashes.has(row.sourceSha256))) throw new Error("Chang'an safe record lacks freshly confirmed evidence.");
const candidate: CatalogSeedBundle = { version: 1, generatedAt: freshManifest.generatedAt, cities: complete.cities, schools: complete.schools, programs, programIntakes, scholarships: complete.scholarships }, candidateText = `${JSON.stringify(candidate, null, 2)}\n`, validation = createCatalogMigrationValidationReport(candidate); if (!validation.ok) throw new Error(`Chang'an safe-new validation failed: ${validation.errors.join(" ")}`);
const deferredLegacyProgramSlugs = baseline.activePrograms.filter((row: any) => !conflictSet.has(row.slug)).map((row: any) => row.slug);
const reviewBase = { version: 1, status: "standing_user_approval", generatedAt: candidate.generatedAt, scope: { schoolSlug, dependencyCityReplayCount: 1, dependencySchoolReplayCount: 1, newProgramRouteCount: 199, newProgramIntakeCount: 199, newScholarshipCount: 6, overwriteCount: 0, archiveCount: 0 }, candidateSha256: sha(candidateText), candidateBundleSha256: validation.bundleSha256, operationPlanSha256: validation.operationPlanSha256, freshManifestSha256: sha(await readFile(paths.freshManifest, "utf8")), evidence: freshManifest.sources.map((row: any) => ({ sourceId: row.id, sourceUrl: row.finalUrl, sourceLabel: row.label, sha256: row.sha256, fetchedAt: row.fetchedAt, contentType: row.contentType })), standingAuthorization: { reference: "user-chat-2026-09-13-default-publication", instruction: "发布默认允许", appliesBecause: "This batch inserts only 199 new official program routes, 199 intakes and six new rich scholarships. Xi'an city and Chang'an University are read-only dependencies; no record is overwritten or archived." }, sourceReview: { result: "pass", note: "All 18 registered Chang'an University official sources were refreshed on 2026-09-14 and are byte-for-byte unchanged from the fully reviewed evidence set." }, visualReview: completeReview.visualReview, reconciliation: { destructiveDeletion: false, overwrites: [], archives: [], deferredStableProgramSlugs: baseline.conflicts.map((row: any) => row.slug), deferredLegacyProgramSlugs, deferredLegacyScholarshipSlugs: baseline.activeScholarships.map((row: any) => row.slug), databaseBaseline: { schoolId: baseline.school[0].id, cityId: baseline.city[0].id, activeProgramCount: baseline.activePrograms.length, activeScholarshipCount: baseline.activeScholarships.length, intakeCount: baseline.intakeCount } }, coverageLimitations: ["The school profile, shared Xi'an city, 16 stable program updates, eight legacy program aliases and one merged scholarship remain unchanged pending explicit cleanup approval."], sensitiveDataCheck: { result: "pass", scope: "Chang'an safe-new publication candidate", note: "Only public institutional, program, admissions and scholarship-policy fields are included. Applicant, account, payment, bank, staff-name and personal-contact data are excluded." } };
const reviewHash = sha(JSON.stringify(reviewBase)), publicationReference = `standing-authorized-${batch}-${reviewHash}`;
await Promise.all([writeFile(paths.candidate, candidateText, "utf8"), writeFile(paths.validation, `${JSON.stringify(validation, null, 2)}\n`, "utf8"), writeFile(paths.review, `${JSON.stringify({ ...reviewBase, reviewHash, publicationReference }, null, 2)}\n`, "utf8")]); console.log(JSON.stringify({ ok: true, batch, reviewHash, publicationReference, scope: reviewBase.scope, paths }, null, 2));
