import { createHash } from "node:crypto";
import { readFile, writeFile } from "node:fs/promises";
import { resolve } from "node:path";
import { createCatalogMigrationValidationReport, type CatalogSeedBundle, type CatalogSeedProgram, type CatalogSeedProgramIntake } from "../src/server/catalog/seed-contract.ts";
import { createPostgresPool } from "../src/server/db/postgres-client.ts";
import { localDatabaseUrl } from "./lib/local-development.ts";

const root=process.cwd(),schoolSlug="zhejiang-university-of-technology",batch="zjut-school-program-cleanup-batch-01",prefix=`catalog.${batch}`;
const paths={manifest:resolve(root,"work/catalog-official/zjut-complete-batch-01/manifest.json"),parsed:resolve(root,"work/catalog-official/zjut-complete-batch-01/parsed-programs.json"),dependency:resolve(root,"seeds/catalog.zjut-scholarships-safe-new-batch-01.approved.local.json"),state:resolve(root,".cuac-local/runtime.json"),candidate:resolve(root,`seeds/${prefix}.draft.json`),validation:resolve(root,`seeds/${prefix}.validation.json`),review:resolve(root,`seeds/${prefix}.review.json`)};
const parse=async(path:string)=>JSON.parse(await readFile(path,"utf8")),sha=(value:string|Buffer)=>createHash("sha256").update(value).digest("hex"),compact=(value:string)=>value.toLowerCase().replace(/\(english\)\s*$/,"^english").replace(/[^a-z0-9^]+/g,"");
const [manifest,parsed,dependency,state]=await Promise.all([parse(paths.manifest),parse(paths.parsed),parse(paths.dependency),parse(paths.state)]);
const sourceById=new Map(manifest.sources.map((row:any)=>[row.id,row])),undergraduate:any=sourceById.get("zjut-undergraduate-guide-pdf-2026"),graduate:any=sourceById.get("zjut-graduate-guide-pdf-2026");
if(undergraduate?.sha256!=="1b59188e03b8c3f97877f7d4bac0a77ec529ff7fe82af30585ccf072174cba79"||graduate?.sha256!=="e9cef625dc252b38d067fbe28e229acc5cc3b49dec05caff3fa7fba71c6ee5c6")throw new Error("ZJUT cleanup evidence changed.");
const city=dependency.cities?.find((row:any)=>row.slug==="hangzhou");if(!city)throw new Error("Hangzhou dependency missing.");
const school={slug:schoolSlug,nameEn:"Zhejiang University of Technology",nameZh:"浙江工业大学",citySlug:"hangzhou",schoolType:"regular",region:"Hangzhou, Zhejiang, East China",applicationLevel:"Bachelor, Master, Doctoral",languageOfInstruction:"Chinese, English",hskRequirement:"Undergraduate Chinese routes require HSK 4 score 180 or above, with HSK 5 score 180 for Food Science and Engineering, Food Quality and Safety, Computer Science and Technology, and Software Engineering. Graduate Chinese routes require HSK 5 score 180 or above.",deadlineSummary:"2026 international degree applications close May 30, 2026; individual program deadlines may change in the application portal.",tuitionSummary:"Undergraduate CNY 16,200/year (Chinese) or CNY 18,800/year (English); master's CNY 22,600/year (Chinese) or CNY 24,800/year (English); doctoral CNY 25,000/year (Chinese) or CNY 27,800/year (English).",cscaRequired:true,cscaRequirement:"All 2026 undergraduate applicants must submit valid CSCA results using the subject combination and Chinese/English paper published for the selected route.",cscaSubjects:["STEM-Chinese","Humanities-Chinese","Mathematics","Physics","Chemistry"],subjectTags:["Chemical Engineering","Pharmaceutical Science","Environment","Materials","Food Science","Mechanical Engineering","Information Engineering","Computer Science","Civil Engineering","Design and Architecture","Geoinformatics","Management","Economics","Education","Humanities","Law"],languageTags:["Chinese","English"],status:"active" as const,sourceUrl:undergraduate.url,sourceLabel:undergraduate.label,sourceSha256:undergraduate.sha256,capturedAt:undergraduate.fetchedAt,sourceFieldLineage:{nameEn:"undergraduate PDF title",nameZh:"official university identity",citySlug:"official university location",schoolType:"official institutional profile",region:"official university location",applicationLevel:"undergraduate and graduate PDF titles/catalogues",languageOfInstruction:"undergraduate and graduate catalogue teaching-language columns/markers",hskRequirement:"undergraduate PDF pages 2 and 5; graduate PDF page 5",deadlineSummary:"both PDFs pages 3-4, Application Deadline",tuitionSummary:"both PDFs page 4, tuition lines only; account information excluded",cscaRequired:"undergraduate PDF pages 1-3 and 5",cscaRequirement:"undergraduate PDF pages 1-3, CSCA Subjects Required table and notes",cscaSubjects:"undergraduate PDF pages 1-3, CSCA Subjects Required column",subjectTags:"both PDFs pages 1-3, college and program tables",languageTags:"both PDFs pages 1-3, language columns/markers"}};

const aliases=new Map<string,string>([["pharmacy^english","pharmaceuticalscience"],["internationaleconomicsandtradechinabusiness^english","internationaleconomicsandtradespecializedinchinesebusiness"]]);
const routeKey=(row:any)=>`${row.degreeLevel}|${row.teachingLanguage}|${compact(row.nameEn)}`,legacyKey=(row:any)=>{const language=row.teaching_language==="英文授课"?"English":"Chinese",raw=compact(row.name_en),name=aliases.get(raw)??raw.replace(/\^english$/,"");return `Undergraduate|${language}|${name}`;};
const pool=createPostgresPool({databaseUrl:localDatabaseUrl(state),max:1,applicationName:"cuac:zjut-school-program-cleanup-review"});let baseline:any,legacy:any[];
try{const schoolDb=await pool.query("select id,slug,status,verification_status,to_jsonb(s)-'created_at'-'updated_at' snapshot from schools s where slug=$1",[schoolSlug]),rows=await pool.query("select id,slug,name_en,degree_level,teaching_language,status,verification_status from programs where school_id=$1 and verification_status='unverified' and status='active' order by slug",[schoolDb.rows[0]?.id]),intakes=await pool.query("select count(*)::int count from program_intakes pi join programs p on p.id=pi.program_id where p.school_id=$1 and p.slug=any($2::text[])",[schoolDb.rows[0]?.id,rows.rows.map((row:any)=>row.slug)]);if(schoolDb.rows.length!==1||schoolDb.rows[0].verification_status!=="unverified"||rows.rows.length!==23)throw new Error("ZJUT cleanup baseline changed.");const byKey=new Map(parsed.programs.map((row:any)=>[routeKey(row),row]));legacy=rows.rows.map((row:any)=>{const key=legacyKey(row),official=byKey.get(key);if(!official)throw new Error(`Unresolved ZJUT legacy route: ${row.slug}`);return{...row,official};});if(new Set(legacy.map(row=>routeKey(row.official))).size!==23)throw new Error("ZJUT cleanup route mappings are not unique.");baseline={schoolId:schoolDb.rows[0].id,schoolSnapshot:schoolDb.rows[0].snapshot,legacyProgramCount:rows.rows.length,legacyIntakeCount:intakes.rows[0]?.count,activeScholarshipCount:dependency.scholarships?.length??0};}finally{await pool.end();}

const programs:CatalogSeedProgram[]=legacy.map(({slug,official}:any)=>{const row=official,source:any=sourceById.get(row.sourceId),language=row.teachingLanguage==="Chinese"?{hskRequirement:`HSK Level ${row.hskLevel??4}, score 180 or above${row.hskLevel===5?" (program-specific HSK 5 requirement)":""}.`}:{englishRequirement:"IELTS 5.5 or TOEFL 60, or another English qualification accepted by ZJUT."};return{slug,schoolSlug,citySlug:"hangzhou",nameEn:row.nameEn,degreeLevel:"Undergraduate",durationYears:4,fieldCategory:row.collegeEn,subjectArea:row.nameEn,teachingLanguage:row.teachingLanguage,...language,cscaRequirement:`CSCA required: ${row.cscaSubjects.join(", ")}. Applicants use the ${row.teachingLanguage.toLowerCase()} paper corresponding to the teaching language.`,tuitionAmount:row.tuitionAmount,tuitionCurrency:"CNY",tuitionPeriod:"year",tuitionText:`CNY ${Number(row.tuitionAmount).toLocaleString("en-US")}/year`,scholarshipText:"ZJUT publishes separate government and university scholarship routes; eligibility depends on the selected award.",applicationUrl:"https://zjut.at0086.cn/student",applicationNote:"Official 2026 international undergraduate route; application deadline May 30, 2026.",hasScholarship:true,badgeText:"Official 2026 route",displaySubjects:row.cscaSubjects,displayGroup:`zjut-bachelor-${row.teachingLanguage.toLowerCase()}`,displayGroupLabel:`ZJUT Undergraduate routes taught in ${row.teachingLanguage}`,status:"active",sourceUrl:source.url,sourceLabel:source.label,sourceSha256:source.sha256,capturedAt:source.fetchedAt,sourceFieldLineage:{nameEn:row.sourceLocator,degreeLevel:"undergraduate PDF title",durationYears:"undergraduate PDF page 3 notes",fieldCategory:`${row.sourceLocator}, college column`,subjectArea:`${row.sourceLocator}, major column`,teachingLanguage:`${row.sourceLocator}, teaching-language column`,...(row.teachingLanguage==="Chinese"?{hskRequirement:"undergraduate PDF pages 2 and 5"}:{englishRequirement:"undergraduate PDF page 5"}),cscaRequirement:`${row.sourceLocator}, CSCA Subjects Required column`,tuitionAmount:"undergraduate PDF page 4, tuition lines only",applicationUrl:"undergraduate PDF page 6, Application Procedures"}}});
const programIntakes:CatalogSeedProgramIntake[]=programs.map(program=>({programSlug:program.slug,intakeTerm:"Fall",intakeYear:2026,deadlineDate:"2026-05-30T15:59:59.000Z",deadlineLabel:"May 30, 2026; individual program deadlines may change in the application portal",applicationRound:"2026 international undergraduate intake",status:"closed",sourceUrl:program.sourceUrl,sourceLabel:program.sourceLabel,sourceSha256:program.sourceSha256,capturedAt:program.capturedAt,sourceFieldLineage:{intakeTerm:"undergraduate PDF page 3 notes",intakeYear:"undergraduate PDF title",deadlineDate:"undergraduate PDF pages 3-4, Application Deadline",status:"derived: deadline predates review date"}}));
const candidate:CatalogSeedBundle={version:1,generatedAt:manifest.generatedAt,cities:[city],schools:[school],programs,programIntakes,scholarships:[]},candidateText=`${JSON.stringify(candidate,null,2)}\n`,validation=createCatalogMigrationValidationReport(candidate);if(!validation.ok||validation.summary.schools!==1||validation.summary.programs!==23||validation.summary.programIntakes!==23)throw new Error(`Invalid ZJUT cleanup candidate: ${validation.errors.join(" ")}`);
const reviewBase={version:1,status:"requires_explicit_approval",generatedAt:manifest.generatedAt,scope:{schoolSlug,schoolOverwriteCount:1,programOverwriteCount:23,programIntakeUpsertCount:23,archiveCount:0,deleteCount:0},candidateSha256:sha(candidateText),candidateBundleSha256:validation.bundleSha256,operationPlanSha256:validation.operationPlanSha256,manifestSha256:sha(await readFile(paths.manifest)),parsedProgramsSha256:sha(await readFile(paths.parsed)),evidence:[undergraduate,graduate].map(source=>({sourceId:source.id,sourceUrl:source.url,sourceLabel:source.label,sha256:source.sha256,fetchedAt:source.fetchedAt,contentType:source.contentType,byteLength:source.byteLength})),reconciliation:{destructiveDeletion:false,archiveOperations:[],databaseBaseline:baseline,programMappings:legacy.map(({id,slug,name_en,official}:any)=>({id,slug,oldNameEn:name_en,newNameEn:official.nameEn,teachingLanguage:official.teachingLanguage,sourcePage:official.sourcePage}))},sourceReview:{result:"pass",note:"Both official 2026 ZJUT PDFs are hash-bound and all 24 rendered pages were visually reviewed. The 23 legacy undergraduate records each map one-to-one to a current official route."},sensitiveDataCheck:{result:"pass",scope:"one public school profile, 23 public degree routes and their intake records",note:"The candidate excludes all bank/account routing, remittance identifiers, applicant names, passport values, personal contact data and staff contact details."},reviewNotes:["This operation replaces third-party school profile claims with current official 2026 admissions facts and marks the school verified on publication.","All 23 program slugs are preserved, so existing IDs and references remain stable; only their public catalog fields and 2026 intake facts are updated.","No record is archived or deleted. The 80 safe-new verified programs and nine verified scholarships are protected and unchanged."]};const reviewHash=sha(JSON.stringify(reviewBase)),requiredApproval=`批准发布浙江工业大学学校与 23 条旧项目官方更新（审核哈希 ${reviewHash}），保留原项目 ID 且不归档或删除记录`;
await Promise.all([writeFile(paths.candidate,candidateText,"utf8"),writeFile(paths.validation,`${JSON.stringify(validation,null,2)}\n`,"utf8"),writeFile(paths.review,`${JSON.stringify({...reviewBase,reviewHash,requiredApproval},null,2)}\n`,"utf8")]);console.log(JSON.stringify({ok:true,batch,reviewHash,requiredApproval,summary:validation.summary,baseline,paths},null,2));
